CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
    {initial_seq_value} AS TH1_SEQUENCE_NUMBER,
    9010 AS TH1_TRANSACTION_CODE,
    7607 AS TH1_TRANSMIT_BANK_NUMBER ,
    '0001' AS TH1_USER_ASSIGNED_SEQ_NBR ,
    CASE
      WHEN '{env}' IN ('dev','DEV','uat','UAT') THEN 'I7607CVV'
      WHEN '{env}' IN ('prod','PROD') THEN 'I7607CV1'
      ELSE NULL END AS TH1_TRANS_NAME_ID ,
    '' AS TH1_USER_PASSWORD_ID,
    CAST(FORMAT_TIMESTAMP('%j',FILE_CREATE_DT) AS INT64) AS TH1_JULIAN_DATE,
    format_date('%m%d%y', FILE_CREATE_DT) AS TH1_GREGORIAN_DATE,
    'TS2CHK' AS TH1_EQUIPMENT_TYPE,
    '' AS TH1_PRE_PROCESS_FLAG,
    '' AS RESERVED_FIELD_ONE ,
    '' AS RESERVED_FIELD_TWO,
    '' AS TH1_ECCB_TRANSMISSION_FLAG,
    0 AS TH1_VENDOR_ID,
    '' AS FILLER_P1,
    FILE_CREATE_DT,
    CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
    pcb-{env}-landing.domain_payments.CONVCHQ_HEDR
    WHERE FILE_CREATE_DT='{file_create_dt}';