CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
    {initial_seq_value} + ROW_NUMBER() OVER() AS TT1_SEQUENCE_NUMBER ,
    9011 AS TT1_TRANSACTION_CODE ,
    7607 AS TT1_TRANSMIT_BANK_NUMBER ,
    1 AS  TT1_USER_SEQUENCE_NUMBER ,
    CAST((SUM(amount)*100) AS INT64) AS TT1_AMOUNT_OF_DEBITS ,
    0 AS TT1_AMOUNT_OF_CREDITS ,
    0 AS TT1_AMOUNT_OF_PAYMENTS ,
    '' AS FILLER_P1 ,
    '' AS FILLER_P2 ,
    '00001' AS TT1_TOTAL_NBR_OF_BATCHES ,
    ' ' AS FILLER_P3,
    FILE_CREATE_DT,
    CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
    pcb-{env}-landing.domain_payments.CONVCHQ_DETL
    WHERE FILE_CREATE_DT='{file_create_dt}'
    GROUP BY FILE_CREATE_DT;
