/*Temporary Function to get MOD value of a digit */
CREATE TEMP FUNCTION
MOD_NUM(ACC_DIGIT INT64) RETURNS INT64 AS (
CASE WHEN ACC_DIGIT>9 THEN (DIV(ACC_DIGIT, 10) + MOD(ACC_DIGIT, 10))
     ELSE ACC_DIGIT
END
);
/*Temporary Function to get MOD value of 15 digits of account num */
CREATE TEMP FUNCTION
GET_MOD_NUM(ACCOUNT_NUM STRING) RETURNS INT64 AS (
  (
  (SELECT
     CASE WHEN MOD(MOD_AGG_NUM,10) <> 0 THEN (10 - MOD_AGG_NUM)
          ELSE 0
     END
   FROM
  (
    SELECT
    MOD((ACC_DIG1 + ACC_DIG2 + ACC_DIG3 + ACC_DIG4 + ACC_DIG5 + ACC_DIG6 + ACC_DIG7 + ACC_DIG8
    + ACC_DIG9 + ACC_DIG10 + ACC_DIG11 + ACC_DIG12 + ACC_DIG13 + ACC_DIG14 + ACC_DIG15),10) AS MOD_AGG_NUM
    FROM
    (
    SELECT
     MOD_NUM(ACC_DIG1) AS ACC_DIG1,
     ACC_DIG2,
     MOD_NUM(ACC_DIG3) AS ACC_DIG3,
     ACC_DIG4,
     MOD_NUM(ACC_DIG5) AS ACC_DIG5,
     ACC_DIG6,
     MOD_NUM(ACC_DIG7) AS ACC_DIG7,
     ACC_DIG8,
     MOD_NUM(ACC_DIG9) AS ACC_DIG9,
     ACC_DIG10,
     MOD_NUM(ACC_DIG11) AS ACC_DIG11,
     ACC_DIG12,
     MOD_NUM(ACC_DIG13) AS ACC_DIG13,
     ACC_DIG14,
     MOD_NUM(ACC_DIG15) AS ACC_DIG15

     FROM
    (SELECT
          CAST(SUBSTR(ACCOUNT_NUM,1,1) AS INT64) * 2 AS ACC_DIG1,
          CAST(SUBSTR(ACCOUNT_NUM,2,1) AS INT64) AS ACC_DIG2,
          CAST(SUBSTR(ACCOUNT_NUM,3,1) AS INT64) * 2 AS ACC_DIG3,
          CAST(SUBSTR(ACCOUNT_NUM,4,1) AS INT64) AS ACC_DIG4,
          CAST(SUBSTR(ACCOUNT_NUM,5,1) AS INT64) * 2 AS ACC_DIG5,
          CAST(SUBSTR(ACCOUNT_NUM,6,1) AS INT64) AS ACC_DIG6,
          CAST(SUBSTR(ACCOUNT_NUM,7,1) AS INT64) * 2 AS ACC_DIG7,
          CAST(SUBSTR(ACCOUNT_NUM,8,1) AS INT64) AS ACC_DIG8,
          CAST(SUBSTR(ACCOUNT_NUM,9,1) AS INT64) * 2 AS ACC_DIG9,
          CAST(SUBSTR(ACCOUNT_NUM,10,1) AS INT64) AS ACC_DIG10,
          CAST(SUBSTR(ACCOUNT_NUM,11,1) AS INT64) * 2 AS ACC_DIG11,
          CAST(SUBSTR(ACCOUNT_NUM,12,1) AS INT64) AS ACC_DIG12,
          CAST(SUBSTR(ACCOUNT_NUM,13,1) AS INT64) * 2 AS ACC_DIG13,
          CAST(SUBSTR(ACCOUNT_NUM,14,1) AS INT64) AS ACC_DIG14,
          CAST(SUBSTR(ACCOUNT_NUM,15,1) AS INT64) * 2 AS ACC_DIG15)
  )
  )
  )
)
);
/*Temporary Function to decode 16 digit account num from 9 digit source account */
CREATE TEMP FUNCTION
GET_ACCOUNT_NUM (LEN_ACC_NUM INT64,ACC_NUM_DIG1 STRING,ACC_NUM_DIG2 STRING,ACC_NUM_LAST8 STRING,ACC_NUM_LAST7 STRING, ACCOUNT_NUM INT64) RETURNS INT64 AS (
    (
    SELECT
      CASE
        WHEN LEN_ACC_NUM=9 THEN
          CASE
            WHEN ACC_NUM_DIG1 = '1' THEN CAST(CONCAT('518127','10',ACC_NUM_LAST8) AS INT64)
            WHEN ACC_NUM_DIG1 = '2' THEN CAST(CONCAT('518127','1',ACC_NUM_DIG2,ACC_NUM_LAST7,GET_MOD_NUM(CONCAT('518127','1',ACC_NUM_DIG2,ACC_NUM_LAST7))) AS INT64)
            WHEN ACC_NUM_DIG1 = '3' THEN CAST(CONCAT('518116','1',ACC_NUM_DIG2,ACC_NUM_LAST7,GET_MOD_NUM(CONCAT('518116','1',ACC_NUM_DIG2,ACC_NUM_LAST7))) AS INT64)
            WHEN ACC_NUM_DIG1 = '5' THEN CAST(CONCAT('518116','2',ACC_NUM_DIG2,ACC_NUM_LAST7,GET_MOD_NUM(CONCAT('518116','2',ACC_NUM_DIG2,ACC_NUM_LAST7))) AS INT64)
            WHEN ACC_NUM_DIG1 = '4' THEN CAST(CONCAT('522879','0',ACC_NUM_DIG2,ACC_NUM_LAST7,GET_MOD_NUM(CONCAT('522879','0',ACC_NUM_DIG2,ACC_NUM_LAST7))) AS INT64)
            ELSE NULL END
        ELSE ACCOUNT_NUM
      END
    )
);

CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
    {initial_seq_value} + ROW_NUMBER() OVER (ORDER BY SEQ_NUM) AS DF5_SEQUENCE_NUMBER,
    '0104' AS DF5_TRANSACTION_CODE,
    CAST(GET_ACCOUNT_NUM(LENGTH(TRIM(CAST(ACCOUNT_NUM AS STRING))),
    SUBSTR(CAST(ACCOUNT_NUM AS STRING),1,1),
    SUBSTR(CAST(ACCOUNT_NUM AS STRING),2,1),
    SUBSTR(CAST(ACCOUNT_NUM AS STRING),2,8),SUBSTR(CAST(ACCOUNT_NUM AS STRING),3,7),ACCOUNT_NUM) AS STRING) AS DF5_ACCOUNT_NUMBER,
    FORMAT_DATE('%m%d%y', parse_date('%Y%m%d',CAST(process_dt AS string))) AS DF5_TRANSACTION_DATE,
    '' AS FILLER_P1,
    CAST((AMOUNT*100) AS INT64) AS DF5_TRANSACTION_AMOUNT,
    ''  AS DF5_MERCHANT_DESCRIPTION ,
    LPAD(CAST(CHEQUE_NUM AS STRING),5,'0') AS DF5_CHECK_NUMBER,
    '' AS FILLER_P2,
    'D' || substr(SEQ_NUM, 4,10)  AS  DF5_TRACE_ID,
    '' AS  DF5_ALLOW_MER_DESC_ON_CORR,
    CAST(substr(SEQ_NUM, 4,10) AS INT64) AS DF5_REFERENCE_NUMBER,
    '' AS DF5_REJECT_REASON   ,
    '' AS DF5_OVERRIDE_FLAG   ,
    '' AS FILLER_P3 ,
    LPAD(CAST(PROMO_CODE AS STRING),8,'0') AS DF5_SOLICIT_OFFER_ID,
    '' AS DF5_DECLINE_CODE ,
    '' AS DF5_MERCHANT_COUNTRY_CODE,
    '0000' AS DF5_MERCHANT_CLASS_SIC_CODE ,
    '' AS DF5_ELIGABLE_FOR_DISCOUNT_QUAL ,
    '' AS DF5_AUTHORIZATION_CODE ,
    '' AS DF5_MAIL_PHONE_ORDER ,
    '' AS FILER,
    FILE_CREATE_DT,
    CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
    pcb-{env}-landing.domain_payments.CONVCHQ_DETL
WHERE
    FILE_CREATE_DT='{file_create_dt}'
ORDER BY
    DF5_SEQUENCE_NUMBER;