CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
    {initial_seq_value} + ROW_NUMBER() OVER() AS  BT1_SEQUENCE_NUMBER,
    9013 AS BT1_TRANSACTION_CODE,
    7607 AS BT1_TRANSMIT_BANK_NUMBER,
    'DRFT5' AS BH1_BATCH_TYPE_DESCRIPTION,
    CAST(FORMAT_DATE('%j',file_create_dt) AS INT64) AS BH1_JULIAN_DAY,
    1 AS BT1_BATCH_NUMBER,
    'PYC' AS BH1_BATCH_OPERATOR,
    CAST((SUM(amount)*100) AS INT64) AS BT1_NET_AMT_OF_BATCH,
    COUNT(*) AS BT1_NUMBER_OF_DEBITS,
    CAST((SUM(amount)*100) AS INT64) AS BT1_AMOUNT_OF_DEBITS,
    0  AS BT1_NUMBER_OF_CREDITS,
    0  AS BT1_AMOUNT_OF_CREDITS,
    0 AS BT1_NUMBER_OF_PAYMENTS,
    0  AS BT1_AMOUNT_OF_PAYMENTS,
    ''  AS FILLER_P1,
    FILE_CREATE_DT,
    CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
    pcb-{env}-landing.domain_payments.CONVCHQ_DETL
    WHERE FILE_CREATE_DT='{file_create_dt}'
    GROUP BY FILE_CREATE_DT;