CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  {initial_seq_value} + ROW_NUMBER() OVER(ORDER BY DF5_CHECK_NUMBER) AS DF5_SEQUENCE_NUMBER,
  282 AS DF5_TRANSACTION_CODE,
  DF5_ACCOUNT_NUMBER,
  DF5_TRANSACTION_DATE,
  ' ' AS FILLER_1,
  4200 AS DF5_TRANSACTION_AMOUNT,
  RPAD('NSF CHQ#' || SUBSTR(DF5_CHECK_NUMBER, 3, 3) || ' $' || LTRIM(FORMAT('%.2f', DF5_TRANSACTION_AMOUNT)),41,' ') AS DF5_MERCHANT_DESCRIPTION,
  'Y' AS DF5_ALLOW_MER_DESC_ON_CORR,
  ({batch_num_val} + 3) + ROW_NUMBER() OVER(ORDER BY DF5_CHECK_NUMBER) AS DF5_REFERENCE_NUMBER,
  ' ' AS FILLER_2,
  ' ' AS DF5_MERCHANT_COUNTRY_CODE,
  0 AS DF5_MERCHANT_CLASS_SIC_CODE,
  ' ' AS DF5_ELIGABLE_FOR_DISCOUNT_QUAL,
  ' ' AS DF5_AUTHORIZATION_CODE,
  ' ' AS DF5_MAIL_PHONE_ORDER,
  ' ' AS DF5_EXTENSION_IND,
  FILE_CREATE_DT,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  `pcb-{env}-landing.domain_payments.CONVCHQ_CONF_DETL`
WHERE
  FILE_CREATE_DT = '{file_create_dt}'
  AND DF5_DECLINE_CODE IN ('0048',
    '0032',
    '0033',
    '0034',
    '0531',
    '0532',
    '0533',
    '0534',
    '0535',
    '0536',
    '0537',
    '0538',
    '0539',
    '0540');