CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  {initial_seq_value} + ROW_NUMBER() OVER() AS TT1_SEQUENCE_NUMBER,
  '9011' AS TT1_TRANSACTION_CODE,
  '7637' AS TRANSMIT_BANK_NBR,
  {batch_num_val} AS TT1_USER_SEQUENCE_NUMBER,
  BT1_NET_AMT_OF_BATCH AS DF5_TRANSACTION_AMOUNT,
  0 AS TT1_AMOUNT_OF_CREDITS,
  0 AS TT1_AMOUNT_OF_PAYMENTS,
  ' ' AS TT1_RUN_NUMBER,
  ' ' AS TT1_TT1_ASSIGNED_TRANS_NUMBER,
  ' ' AS TT1_NET_AMT_OF_TRANSMIT,
  ' ' AS TT1_NUMBER_OF_REJECTS,
  ' ' AS TT1_AMOUNT_OF_REJECTS,
  ' ' AS TT1_AMT_OUT_OF_BAL_CONDITN,
  '001' AS TOTAL_NBR_OF_BATCHES,
  ' ' AS TT1_ALTERNATE_AMOUNT_DEBIT,
  ' ' AS TT1_ALTERNATE_AMOUNT_CREDIT,
  ' ' AS FILLER,
  FILE_CREATE_DT,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  `pcb-{env}-processing.domain_payments.CC_FEEPOST_TRLR_DBEXT_COLUMN_TF`
WHERE
  FILE_CREATE_DT = '{file_create_dt}';