CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  {initial_seq_value} + ROW_NUMBER() OVER() AS BT1_SEQUENCE_NUMBER,
  '9013' AS BT1_TRANSACTION_CODE,
  '7637' AS TRANSMIT_BANK_NBR,
  'DRFT5' AS BATCH_TYPE_DESCR,
  CAST(FORMAT_TIMESTAMP('%j',CURRENT_DATE()) AS INT64) AS BT1_JULIAN_DATE,
  {batch_num_val} AS BT1_BATCH_DATA,
  HEDR.BH1_BATCH_OPERATOR AS BT1_BATCH_OPERATOR,
  (IFNULL(DETL.BT1_NUMBER_OF_DEBITS,0) * 25) AS BT1_NET_AMT_OF_BATCH,
  IFNULL(DETL.BT1_NUMBER_OF_DEBITS,0) AS BT1_NUMBER_OF_DEBITS,
  (IFNULL(DETL.BT1_NUMBER_OF_DEBITS,0) * 25) AS BT1_AMOUNT_OF_DEBITS,
  0 AS BT1_NUMBER_OF_CREDITS,
  0 AS BT1_AMOUNT_OF_CREDITS,
  0 AS BT1_NUMBER_OF_PAYMENTS,
  0 AS BT1_AMOUNT_OF_PAYMENTS,
  ' ' AS BT1_RUN_NUMBER_ASSIGNED,
  ' ' AS BT1_ASSIGNED_TRANS_NBR,
  ' ' AS BT1_NBR_OF_REJECTS,
  ' ' AS BT1_AMT_OF_REJECTS,
  ' ' AS BT1_NET_AMOUNT_OF_BATCH_2,
  ' ' AS BT1_AMT_OF_DISCOUNT,
  ' ' AS BT1_AMT_OUT_OF_BAL_CONDITN,
  ' ' AS FILLER,
  HEDR.FILE_CREATE_DT,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  `pcb-{env}-processing.domain_payments.CC_FEEPOST_HEDR_DBEXT_COLUMN_TF` HEDR
LEFT JOIN (
  SELECT
    COUNT(*) AS BT1_NUMBER_OF_DEBITS,
    FILE_CREATE_DT
  FROM
    `pcb-{env}-processing.domain_payments.CC_FEEPOST_DETL_DBEXT_COLUMN_TF`
  WHERE
    FILE_CREATE_DT = '{file_create_dt}'
  GROUP BY
    FILE_CREATE_DT) DETL
ON
  HEDR.FILE_CREATE_DT = DETL.FILE_CREATE_DT
AND
  HEDR.FILE_CREATE_DT = '{file_create_dt}';