/*Temporary Function to decode SOURCE ACCOUNT_NUM and generate
ACCOUNT_NUM for target*/
CREATE TEMP FUNCTION
  GET_ACCOUNT_NUM (PCH_BIN INT64, PCH_PIN INT64, PCH_LAST7 STRING) RETURNS STRING AS (
  (
      SELECT
        CONCAT(IFNULL(CAST
         (CASE PCH_BIN
            WHEN 518127
        THEN CASE
             WHEN PCH_PIN > 9 AND PCH_PIN < 20
             THEN PCH_PIN + 10
             ELSE NULL END
        WHEN 518116
        THEN CASE
             WHEN PCH_PIN > 9 AND PCH_PIN < 20 THEN PCH_PIN + 20
             WHEN PCH_PIN > 19 AND PCH_PIN < 25 THEN PCH_PIN + 30
             ELSE NULL END
        WHEN 522879
        THEN CASE
             WHEN PCH_PIN > -1 AND PCH_PIN < 10 THEN PCH_PIN + 40
             ELSE NULL END
        ELSE NULL END
         AS STRING
         ),''),PCH_LAST7)
  )
  );

CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  'PO' AS PERSONAL_CHEQUE_ORDER_INDICATOR
  , '30052'  AS ORDERING_BRANCH_CODE
  , '00' AS ORDERING_SUB_BRANCH_CODE
  , ' '  AS  CUSTOMER_SERVICE_REP_ID
  , ' '   AS  CUSTOMER_SERVICE_REP_NAME
  , '010'  AS MICR_INSTITUTION_NUMBER
  , '30052'  AS MICR_TRANSIT_NUMBER
  , LPAD(GET_ACCOUNT_NUM(CAST(SUBSTR(CKS_ACCOUNT_NUM,1,6) AS INT64),CAST(SUBSTR(CKS_ACCOUNT_NUM,7,2) AS INT64),SUBSTR(CKS_ACCOUNT_NUM,9,7)),18,' ') AS MICR_ACCOUNT_NUMBER
  , 'Y'  AS CHECK_DIGIT_OVERRIDE_FLAG
  , '010'  AS DOMICILE_INSTITUTION_NUMBER
  , '30052'  AS DOMICILE_TRANSIT_NUMBER
  , '00'  AS DOMICILE_SUB_BRANCH_NUMBER
  , ' '  AS  VISUAL_ACCOUNT_NUMBER
  ,  CASE CKS_LANGUAGE_CODE
        WHEN 'ENU'
        THEN 'E'
        ELSE 'F' END AS  LANGUAGE_CODE
  , 'PCM'  AS PRODUCT_TYPE_CODE
  , 'C'  AS SHIP_TO_CODE
  , 'B'  AS BILLING_OVERRIDE_CODE
  , '3270'  AS STYLE_CODE
  , CKS_NUMBER_OF_CHECKS AS QUANTITY
  , CKS_STARTING_CHECK AS STARTING_NUMBER
  , CKS_PRIMARY_NAME AS PERSONALIZATION_NAME_1
  , CKS_SECOND_NAME AS PERSONALIZATION_NAME_2
  , CKS_ADDRESS_LINE1 AS PERSONALIZATION_ADDRESS_1
  , ' '  AS  FILLER_1
  , CASE
      WHEN CKS_ADDRESS_LINE2 IS NULL OR CKS_ADDRESS_LINE2 = ''
      THEN CONCAT(CKS_CITY,' ',CKS_STATE_PROV_CODE)
      ELSE CKS_ADDRESS_LINE2 END
      AS PERSONALIZATION_ADDRESS_2
  , ' '  AS  FILLER_2
  , CASE
      WHEN CKS_ADDRESS_LINE2 IS NULL OR CKS_ADDRESS_LINE2 = ''
      THEN CKS_ADDRESS_LINE2
      ELSE CONCAT(CKS_CITY,' ',CKS_STATE_PROV_CODE) END
      AS PERSONALIZATION_ADDRESS_3
  , ' ' AS  FILLER_3
  , CKS_ZIP_POSTAL_CODE AS PERSONALIZATION_POSTAL_ZIP_CODE
  , '' AS PERSONALIZATION_CONTACT_HOME_TELEPHONE_NUM
  , ' '  AS  REORDER_FLAG
  , '1437917'  AS  AUXILIARY_INFORMATION
  , ' ' AS  AMERICAN_MICR
  , ' '  AS  DOMICILE_NAME_CODE
  , ' ' AS  BULK_NUMBER
  , ' '  AS  SUPPRESS_AUTO_COMP
  , ' '  AS  REASON_CODE
  , ' ' AS  PRIORITY_CODE
  , ' '  AS  PERSONALIZATION_CONTACT_HOME_EMAIL_ADDRESS_email_addr
  , ' ' AS  PERSONALIZATION_CONTACT_WORK_EMAIL_ADDRESS_email_addr2
  , ' '  AS  HOME_EMAIL_ADDRESS_FLAG
  , ' ' AS  PERSONALIZATION_CONTACT_WORK_TELEPHONE_NUMBER
  , ' '  AS  HOME_TELEPHONE_NUMBER_FLAG
  , ' ' AS  TRANSACTION_REGISTER_REQUIRED
  , ' '  AS  WORK_TELEPHONE_NUMBER_FLAG
  , ' '  AS  WORK_EMAIL_ADDRESS_FLAG
  , ' '  AS  FILLER
  , FILE_CREATE_DT
  , CURRENT_DATETIME() AS REC_CREATE_TMS
FROM pcb-{env}-landing.domain_payments.TS2_CHQORDER_DETL
WHERE FILE_CREATE_DT = '{file_create_dt}';
