CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  'HD' AS HEADER_INDICATOR
  , '0010'  AS SOURCE_FI_CODE
  , '00018'  AS  SOURCE_TRANSIT_CODE
  , 'DAVIS + HENDERSON INTERCHEQUES'  AS INTENDED_PARTY
  , {batch_num_val} AS  GENERATION_NUMBER
  , FORMAT_DATE('%d-%m-%Y',PARSE_DATE('%Y%m%d',CAST(CKS_HDR_CREATE_DATE AS STRING))) AS CKS_HDR_CREATE_DATE
  , ' '  AS  FILLER
  , FILE_CREATE_DT
  , CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
    pcb-{env}-landing.domain_payments.TS2_CHQORDER_HEDR
    WHERE FILE_CREATE_DT = '{file_create_dt}';