CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  {initial_seq_value} + ROW_NUMBER() OVER (ORDER BY SEQ_NUM) AS DF5_SEQUENCE_NUMBER,
  '0108' AS DF5_TRANSACTION_CODE,
  ACCOUNT_NUM AS DF5_ACCOUNT_NUMBER,
  FORMAT_DATE('%m%d%y', PARSE_DATE('%Y%m%d',CAST(process_dt AS STRING))) AS DF5_TRANSACTION_DATE,
  ' ' AS FILLER,
  CAST((AMOUNT*100) AS INT64) AS DF5_TRANSACTION_AMOUNT,
  ' ' AS DF5_MERCHANT_NAME,
  ' ' AS DF5_MERCHANT_CITY,
  ' ' AS DF5_MERCHANT_STATE_PROV,
  'Y' AS DF5_ALLOW_MER_DESC_ON_CORR,
  CASE
    WHEN SUBSTR(SEQ_NUM,1,3) = 'APA' THEN '4100'
    ELSE
      CASE
        WHEN CSH_IND = 'CSH' THEN '5100'
        ELSE '3100'
      END
  END || LPAD(CAST({initial_seq_value} + ROW_NUMBER() OVER (ORDER BY SEQ_NUM) AS STRING), 7, '0') AS DF5_REFERENCE_NUMBER,
  ' ' AS FILLER2,
  ' ' AS DF5_MERCHANT_COUNTRY_CODE,
  '0000' AS DF5_MERCHANT_CLASS_SIC_CODE,
  ' ' AS DF5_ELIGABLE_FOR_DISCOUNT_QUAL,
  ' ' AS DF5_AUTHORIZATION_CODE,
  ' ' AS DF5_MAIL_PHONE_ORDER,
  ' ' AS DF5_EXTENSION_IND,
  FILE_CREATE_DT,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  pcb-{env}-landing.domain_payments.PAPER_PYMT_DETL
WHERE
  FILE_CREATE_DT='{file_create_dt}'
AND
  AMOUNT IS NOT NULL;