CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  {initial_seq_value} AS TH1_SEQUENCE_NUMBER,
  '9010' AS TH1_TRANSACTION_CODE,
  '7637' AS TH1_TRANSMIT_BANK_NUMBER,
  {batch_num_val} AS TH1_USER_ASSIGNED_SEQ_NBR,
  'I7637IT1' AS TH1_TRANS_NAME_ID,
  ' ' AS TH1_USER_PASSWORD_ID,
  CAST(FORMAT_TIMESTAMP('%j',CURRENT_DATE()) AS INT64) AS TH1_JULIAN_DATE,
  FORMAT_DATE('%m%d%y', CURRENT_DATE()) AS TH1_GREGORIAN_DATE,
  '7637PC' AS TH1_EQUIPMENT_TYPE,
  ' ' AS TH1_PRE_PROCESS_FLAG,
  ' ' AS TH1_VENDOR_ID_XPANSION,
  ' ' AS TH1_COMMINGLED_FILE_FLAG,
  ' ' AS TH1_CURRENCY_CODE,
  ' ' AS TH1_CONFIRMATION_NUMBER,
  ' ' AS FILLER,
  ' ' AS TH1_RUN_NUMBER_ASSIGNED,
  ' ' AS TH1_TRANS_NUMBER_ASSIGNED,
  ' ' AS TH1_TYPE_ENTRY_DESCR,
  ' ' AS TH1_SOFTWARE_VER_REL_NBR,
  ' ' AS TH1_ECCB_TRANSMISSION_FLAG,
  '000' AS TH1_VENDOR_ID,
  ' ' AS TH1_STRACS_TRANS_ID,
  ' ' AS TH1_STRACS_BATCH_NBR,
  ' ' AS TH1_STRACS_TRANS_DATE,
  ' ' AS TH1_STRACS_TRANS_TIME,
  ' ' AS FILLER2,
  'N' AS TH1_256_BYTE_TRANSMISSION,
  FILE_CREATE_DT,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  pcb-{env}-landing.domain_payments.PAPER_PYMT_HEDR
WHERE
  FILE_CREATE_DT='{file_create_dt}';
