CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  {initial_seq_value} + ROW_NUMBER() OVER() BT1_SEQUENCE_NUMBER,
  '9013' AS BT1_TRANSACTION_CODE,
  '7637' AS BT1_TRANSMIT_BANK_NUMBER,
  'DRFT5' AS BT1_BATCH_TYPE_DESCRIPTION,
  CAST(FORMAT_DATE('%j',CURRENT_DATE()) AS INT64) AS BT1_JULIAN_DAY,
  '0001' AS BT1_BATCH_DATA,
  'PYP' AS BT1_BATCH_OPERATOR,
  COALESCE((SUM(DF5_TRANSACTION_AMOUNT)),0) BT1_NET_AMT_OF_BATCH,
  0 AS BT1_NUMBER_OF_DEBITS,
  0 AS BT1_AMOUNT_OF_DEBITS,
  0 AS BT1_NUMBER_OF_CREDITS,
  0 AS BT1_AMOUNT_OF_CREDITS,
  COALESCE((COUNT(*)),0) AS BT1_NUMBER_OF_PAYMENTS,
  COALESCE((SUM(DF5_TRANSACTION_AMOUNT)),0) AS BT1_AMOUNT_OF_PAYMENTS,
  ' ' AS BT1_RUN_NUMBER_ASSIGNED,
  ' ' AS BT1_ASSIGNED_TRANS_NBR,
  ' ' AS BT1_NBR_OF_REJECTS,
  ' ' AS BT1_AMT_OF_REJECTS,
  ' ' AS BT1_NET_AMOUNT_OF_BATCH_2,
  ' ' AS BT1_AMT_OF_DISCOUNT,
  ' ' AS BT1_AMT_OUT_OF_BAL_CONDITN,
  ' ' AS FILLER,
  CAST('{file_create_dt}' AS DATE) AS FILE_CREATE_DT,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  pcb-{env}-processing.domain_payments.TSYS_PPYMT_DETL_DBEXT_COLUMN_TF
WHERE
  FILE_CREATE_DT='{file_create_dt}';