CREATE OR REPLACE TABLE pcb-{env}-processing.domain_payments.{output_table_name}_COLUMN_TF
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  {initial_seq_value} + ROW_NUMBER() OVER() AS BH1_SEQUENCE_NUMBER,
  '9012' AS BH1_TRANSACTION_CODE,
  '7637' AS BH1_ASSIGN_TRANS_BANK_NBR,
  'DRFT5' AS BH1_BATCH_TYPE_DESCR,
  FORMAT_TIMESTAMP('%j', CURRENT_DATE()) AS BH1_JULIAN_DAY,
  '0001' AS BH1_BATCH_NUMBER,
  'PYP' AS BH1_BATCH_OPERATOR,
  'PCP' AS BH1_BATCH_ITEMS_LOCATION,
  1 AS BH1_BEGINNING_REF_NUMBER,
  FORMAT_DATE('%m%d%y', CURRENT_DATE()) AS BH1_DATE_FOR_INDIV_ITEMS,
  ' ' AS BH1_ALTERNATE_AMT_FLAG,
  ' ' AS BH1_MERCHANT_HDR_REQUIRED,
  ' ' AS FILLER,
  FILE_CREATE_DT,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  pcb-{env}-landing.domain_payments.PAPER_PYMT_HEDR
WHERE
  FILE_CREATE_DT='{file_create_dt}';
