WITH
  BILLER_DETAIL_TABLE AS (
  SELECT
    REC_TYPE,
    BILLER_ID,
    BILLER_NAME,
    BILLER_PROVINCE,
    BILLER_CITY,
    BILLER_STATUS
  FROM
    pcb-{env}-processing.domain_payments.BILL_REFRESH_STAGING_DET),
  BILLER_TRAILER_TABLE AS (
  SELECT
    CAST(BILLER_REC_COUNT AS INT64) AS BILLER_REC_COUNT
  FROM
    pcb-{env}-processing.domain_payments.BILL_REFRESH_STAGING_TRL),
  DETAIL_COUNT_TABLE AS (
  SELECT
    COUNT(*) AS DETAIL_COUNT
  FROM
    BILLER_DETAIL_TABLE),
  ERROR_CHECKS AS (
  SELECT
    CASE
      WHEN SAFE_CAST(BILLER_ID AS INT64) IS NULL THEN CONCAT('BillerID ', BILLER_ID, ' is not a valid number')
      WHEN LENGTH(BILLER_NAME) > 100 THEN  CONCAT('BillerName ', BILLER_NAME, ' length exceeds 100 characters')
      WHEN LENGTH(BILLER_PROVINCE) > 2 THEN  CONCAT('Biller Province ', BILLER_PROVINCE, ' length exceeds 2 characters')
      WHEN LENGTH(BILLER_CITY) > 100 THEN  CONCAT('Biller City ', BILLER_CITY, ' length exceeds 100 characters')
      WHEN BILLER_STATUS NOT IN ('I', 'A') THEN CONCAT('Biller Status ', BILLER_STATUS, ' is not I or A')
  END
    AS ERROR_MESSAGE
  FROM
    BILLER_DETAIL_TABLE
  UNION ALL
  SELECT
    CASE
      WHEN ( SELECT DETAIL_COUNT FROM DETAIL_COUNT_TABLE) <> ( SELECT BILLER_REC_COUNT FROM BILLER_TRAILER_TABLE)
      THEN CONCAT('Number of rows in detail does not match with the number in trailer')
  END
    AS ERROR_MESSAGE )
SELECT
  ERROR_MESSAGE
FROM
  ERROR_CHECKS
WHERE
  ERROR_MESSAGE IS NOT NULL;