WITH
  cust_base AS(
  SELECT
    DISTINCT CAST(a.CIFP_ACCOUNT_ID6 AS INTEGER) AS MAST_ACCOUNT_ID,
    CAST(c.ACCOUNT_UID AS INTEGER) AS ACCOUNT_ID,
    CAST(c.CUSTOMER_UID AS INTEGER) AS CUSTOMER_ID,
    CASE
      WHEN UPPER(CIFP_TSYS_PRODUCT_CODE) = 'MW' THEN 'MW-PCH' -- WORLD
      WHEN UPPER(CIFP_TSYS_PRODUCT_CODE) = 'MC'
    AND UPPER(CIFP_CLIENT_PRODUCT_CODE) IN ('PCS',
      'PCI',
      'PCR') THEN CONCAT(CIFP_TSYS_PRODUCT_CODE,'-',CIFP_CLIENT_PRODUCT_CODE) -- SILVER
  END
    AS PRODUCT_TYPE
  FROM
    `pcb-{env}-landing.domain_account_management.CIF_CARD_CURR` a
  INNER JOIN
    `pcb-{env}-landing.domain_account_management.CIF_ACCOUNT_CURR` b
  ON
    a.CIFP_ACCOUNT_ID6 = b.CIFP_ACCOUNT_ID5
  INNER JOIN
    `pcb-{env}-landing.domain_account_management.ACCOUNT_CUSTOMER` c
  ON
    a.CIFP_CUSTOMER_ID_2 = CAST(c.ACCOUNT_CUSTOMER_NO AS INTEGER)
  WHERE
    ((UPPER(CIFP_TSYS_PRODUCT_CODE) = 'MC'
        AND UPPER(CIFP_CLIENT_PRODUCT_CODE) IN ('PCS',
          'PCI',
          'PCR'))
      OR (UPPER(CIFP_TSYS_PRODUCT_CODE) = 'MW'))
    AND CIFP_CUSTOMER_TYPE = 0 -- customer role is primary
    AND CIFP_DATE_CLOSE IS NULL /* Filters to pick only active cards */
    AND (UPPER(a.CIFP_RELATIONSHIP_STAT) = 'A'
      OR a.CIFP_RELATIONSHIP_STAT IS NULL
      OR a.CIFP_RELATIONSHIP_STAT = '')
    AND (AM00_STATC_CLOSED IS NULL
      OR AM00_STATC_CLOSED = '')
    AND (AM00_STATC_CREDIT_REVOKED IS NULL
      OR AM00_STATC_CREDIT_REVOKED = '')
    AND (AM00_STATC_CHARGEOFF IS NULL
      OR AM00_STATC_CHARGEOFF = '')
    AND (AM00_STATC_SECURITY_FRAUD IS NULL
      OR AM00_STATC_SECURITY_FRAUD = '')
    AND COALESCE(UPPER(AM00_STATC_WATCH),'') NOT IN ('SF')
    AND UPPER(CIFP_FIRST_NAME) != 'FRAUD'
    AND UPPER(CIFP_LAST_NAME) NOT LIKE 'RESTITUTION%'
    AND UPPER(CIFP_FIRST_NAME) NOT LIKE '%TEST%'
    AND UPPER(CIFP_LAST_NAME) NOT LIKE '%TEST%'
  QUALIFY
    ROW_NUMBER() OVER (PARTITION BY MAST_ACCOUNT_ID, CUSTOMER_ID ORDER BY MAST_ACCOUNT_ID, CUSTOMER_ID) =1 ),
  transactions AS(
  SELECT
    CAST(MAST_ACCOUNT_ID AS INTEGER) AS MAST_ACCOUNT_ID,
    SUM(AT31_AMT_TRANSACTION) AS TOTAL_SPEND
  FROM
    `pcb-{env}-landing.domain_account_management.AT31`
  WHERE
    FILE_CREATE_DT BETWEEN DATETIME_SUB(CURRENT_DATE()-1, INTERVAL 12 month)
    AND CURRENT_DATE()-1
    AND AT31_DATE_TRANSACTION BETWEEN DATETIME_SUB(CURRENT_DATE()-1, INTERVAL 12 month)
    AND CURRENT_DATE()-1
    AND UPPER(AT31_DEBIT_CREDIT_INDICATOR) IN ('D') -- ONLY INCLUDE PURCHASES
    AND AT31_TERMS_BALANCE_CODE = 1 -- FILTERS TO ONLY GET VALID DEBIT/CREDIT PCMC TRANSACTIONS
    AND UPPER(AT31_TRNS_ACCT_FUNC) NOT IN ('PFC',
      'CFC',
      'FCA',
      'FDA',
      'FCV',
      'FDV',
      'CCF',
      'CPF',
      'WCF',
      'WPF') -- FILTER TO EXCLUDE INTEREST
  GROUP BY
    MAST_ACCOUNT_ID ),
  offer_detail AS(
  SELECT
    OFFER_ID,
    OFFER_PRIORITY
  FROM
    `pcb-{env}-landing.domain_account_management.REF_CUSTOMER_OFFER_DETAIL`
  WHERE
    OFFER_TYPE='Product Upgrade'
  QUALIFY
    ROW_NUMBER() OVER (ORDER BY OFFER_ID DESC, OFFER_CREATED_DT DESC) =1 ),
  velvet_upgrades AS (
  SELECT
    DISTINCT CUSTOMER_UID
  FROM
    `pcb-{env}-curated.domain_account_management.CME_VELVET_UPGRADES` a
  JOIN
    `pcb-{env}-landing.domain_customer_management.CUSTOMER_IDENTIFIER` b
  ON
    a.PCF_CUST_ID=b.CUSTOMER_IDENTIFIER_NO
    AND UPPER(b.TYPE) = 'PCF-CUSTOMER-ID'
  WHERE
    CURRENT_DATE() BETWEEN a.OFFER_START_DATE
    AND a.OFFER_END_DATE)
SELECT
  * EXCEPT(VELVET_CUSTOMER_UID)
FROM (
  SELECT
    offer_detail.OFFER_ID AS OFFER_ID,
    offer_detail.OFFER_PRIORITY AS OFFER_PRIORITY,
    CURRENT_DATE('America/Toronto') AS OFFER_CREATED_DT,
    cust_base.ACCOUNT_ID AS ACCOUNT_ID,
    cust_base.CUSTOMER_ID AS CUSTOMER_ID,
    cust_base.PRODUCT_TYPE AS CURRENT_VALUE,
    CASE
      WHEN TOTAL_SPEND>=25000 THEN 'MX-PCE'
      WHEN UPPER(PRODUCT_TYPE) IN ('MC-PCS',
      'MC-PCI',
      'MC-PCR')
    AND TOTAL_SPEND>=15000 THEN 'MW-PCH'
  END
    AS ELIGIBLE_VALUE,
    velvet_upgrades.CUSTOMER_UID AS VELVET_CUSTOMER_UID,
    DATETIME_TRUNC(CURRENT_DATETIME('America/Toronto'),SECOND) AS REC_LOAD_TIMESTAMP
  FROM
    cust_base
  JOIN
    transactions
  ON
    cust_base.MAST_ACCOUNT_ID = transactions.MAST_ACCOUNT_ID
  LEFT JOIN
    velvet_upgrades
  ON
    cust_base.CUSTOMER_ID = velvet_upgrades.CUSTOMER_UID
  CROSS JOIN
    offer_detail )
WHERE
  ELIGIBLE_VALUE IS NOT NULL
  AND VELVET_CUSTOMER_UID IS NULL;