INSERT INTO pcb-{env}-landing.domain_tax_slips.RL3_TAX_SLIP (
    Annee,
    NoReleve,
    NoRelevePDF,
    NoReleveDerniereTrans,
    BeneficiaireType,
    BeneficiaireNo,
    PersonneNAS,
    PersonneNomFamille,
    PersonnePrenom,
    PersonneInitiale,
    RaisonSocialeAutreNoId,
    RaisonSocialeNom1,
    RaisonSocialeNom2,
    AdresseLigne1,
    AdresseLigne2,
    AdresseVille,
    AdresseProvince,
    AdresseCodePostal,
    A1_DividendeDetermine,
    A2_DividendeOrdinaire,
    B_DividendeImposable,
    C_CreditImpotDividende,
    D_InteretSourceCdn,
    E_AutreRevenuCdn,
    F_RevenuBrutEtranger,
    G_ImpotEtranger,
    H_RedevanceCdn,
    I_DividendeGainCapital,
    J_RevenuAccumuleRente,
    K_InteretBilletsLies,
    DeviseEtrangere,
    CodeRensCompl,
    DonneeRensCompl,
    StmtId,
    RptTcd,
    SbmtRefId,
    CreateDate
)

WITH sbmt_ref_id_processed AS (
  SELECT DISTINCT SbmtRefId FROM pcb-{env}-landing.domain_tax_slips.RL3_TAX_SLIP
)

SELECT 
    CAST(RL3_TAX_SLIP.Annee AS INTEGER) AS Annee,
    CAST(RL3_TAX_SLIP.NoReleve AS STRING) AS NoReleve,
    CAST(RL3_TAX_SLIP.NoRelevePDF AS STRING) AS NoRelevePDF,
    CAST(RL3_TAX_SLIP.NoReleveDerniereTrans AS STRING) AS NoReleveDerniereTrans,
    CAST(RL3_TAX_SLIP.BeneficiaireType AS INTEGER) AS BeneficiaireType,
    CAST(RL3_TAX_SLIP.BeneficiaireNo AS STRING) AS BeneficiaireNo,
    CAST(RL3_TAX_SLIP.PersonneNAS AS STRING) AS PersonneNAS,
    CAST(RL3_TAX_SLIP.PersonneNomFamille AS STRING) AS PersonneNomFamille,
    CAST(RL3_TAX_SLIP.PersonnePrenom AS STRING) AS PersonnePrenom,
    CAST(RL3_TAX_SLIP.PersonneInitiale AS STRING) AS PersonneInitiale,
    CAST(RL3_TAX_SLIP.RaisonSocialeAutreNoId AS STRING) AS RaisonSocialeAutreNoId,
    CAST(RL3_TAX_SLIP.RaisonSocialeNom1 AS STRING) AS RaisonSocialeNom1,
    CAST(RL3_TAX_SLIP.RaisonSocialeNom2 AS STRING) AS RaisonSocialeNom2,
    CAST(RL3_TAX_SLIP.AdresseLigne1 AS STRING) AS AdresseLigne1,
    CAST(RL3_TAX_SLIP.AdresseLigne2 AS STRING) AS AdresseLigne2,
    CAST(RL3_TAX_SLIP.AdresseVille AS STRING) AS AdresseVille,
    CAST(RL3_TAX_SLIP.AdresseProvince AS STRING) AS AdresseProvince,
    CAST(RL3_TAX_SLIP.AdresseCodePostal AS STRING) AS AdresseCodePostal,
    CAST(RL3_TAX_SLIP.A1_DividendeDetermine AS STRING) AS A1_DividendeDetermine,
    CAST(RL3_TAX_SLIP.A2_DividendeOrdinaire AS STRING) AS A2_DividendeOrdinaire,
    CAST(RL3_TAX_SLIP.B_DividendeImposable AS STRING) AS B_DividendeImposable,
    CAST(RL3_TAX_SLIP.C_CreditImpotDividende AS STRING) AS C_CreditImpotDividende,
    CAST(RL3_TAX_SLIP.D_InteretSourceCdn AS STRING) AS D_InteretSourceCdn,
    CAST(RL3_TAX_SLIP.E_AutreRevenuCdn AS STRING) AS E_AutreRevenuCdn,
    CAST(RL3_TAX_SLIP.F_RevenuBrutEtranger AS STRING) AS F_RevenuBrutEtranger,
    CAST(RL3_TAX_SLIP.G_ImpotEtranger AS STRING) AS G_ImpotEtranger,
    CAST(RL3_TAX_SLIP.H_RedevanceCdn AS STRING) AS H_RedevanceCdn,
    CAST(RL3_TAX_SLIP.I_DividendeGainCapital AS STRING) AS I_DividendeGainCapital,
    CAST(RL3_TAX_SLIP.J_RevenuAccumuleRente AS STRING) AS J_RevenuAccumuleRente,
    CAST(RL3_TAX_SLIP.K_InteretBilletsLies AS STRING) AS K_InteretBilletsLies,
    CAST(RL3_TAX_SLIP.DeviseEtrangere AS STRING) AS DeviseEtrangere,
    CAST(RL3_TAX_SLIP.CodeRensCompl AS STRING) AS CodeRensCompl,
    CAST(RL3_TAX_SLIP.DonneeRensCompl AS STRING) AS DonneeRensCompl,
    CAST(RL3_TAX_SLIP.StmtId AS INTEGER) AS StmtId,
    CAST(RL3_TAX_SLIP.RptTcd AS STRING) AS RptTcd,
    CAST(RL3_TAX_SLIP.SbmtRefId AS STRING) AS SbmtRefId,
    CAST(RL3_TAX_SLIP.CreateDate AS DATETIME) AS CreateDate
FROM pcb-{env}-processing.domain_tax_slips.RL3_TAX_SLIP
LEFT JOIN sbmt_ref_id_processed PROCESSED
ON RL3_TAX_SLIP.SbmtRefId = PROCESSED.SbmtRefId
WHERE PROCESSED.SbmtRefId IS NULL
ORDER BY NoReleve
