INSERT INTO pcb-{env}-landing.domain_tax_slips.T5_TAX_TRAILER
 SELECT
     bn,
     l1_nm,
     l2_nm,
     l3_nm,
     addr_l1_txt,
     addr_l2_txt,
     cty_nm,
     prov_cd,
     cntry_cd,
     pstl_cd,
     cntc_nm,
     cntc_area_cd,
     cntc_phn_nbr,
     cntc_extn_nbr,
     filr_fi_br_nbr,
     tx_yr,
     slp_cnt,
     rpt_tcd,
     fileramendmentnote,
     FORMAT("%.2f", CAST(tot_cdn_int_amt AS FLOAT64)) as tot_cdn_int_amt,
     tot_actl_dvnd_amt,
     tot_actl_elg_dvamt,
     tot_tx_elg_dvamt,
     tot_enhn_dvtc_amt,
     tot_tx_dvnd_amt,
     tot_dvnd_tx_cr_amt,
     totr_cdn_incamt,
     tot_fgn_incamt,
     tot_fgn_tx_pay_amt,
     tot_cdn_royl_amt,
     tot_cgain_dvnd_amt,
     tot_acr_annty_amt,
     tot_rsrc_alwnc_amt,
     (SELECT sbmt_ref_id FROM `pcb-{env}-landing.domain_tax_slips.T5_TAX_RAW_HEADER`) AS sbmt_ref_id,
     current_datetime('America/Toronto') AS create_date
 FROM pcb-{env}-landing.domain_tax_slips.T5_TAX_RAW_TRAILER;