[global]
cert = /etc/pip/truststore
index-url = https://pypi-reader:phOsi09bIMObrijUbi3ivl2riyUD@repo.prod.pcfcloud.io/artifactory/api/pypi/pypi-composer-releases/simple

[search]
index = https://pypi-reader:phOsi09bIMObrijUbi3ivl2riyUD@repo.prod.pcfcloud.io/artifactory/api/pypi/pypi-composer-releases/simple
