[global]
cert = /etc/pip/truststore
index-url = https://pypi-reader:wefrOD7kizich8cophedrlmutrUs01BAcri@repo.nonprod.pcfcloud.io/artifactory/api/pypi/pypi-composer-releases/simple

[search]
index = https://pypi-reader:wefrOD7kizich8cophedrlmutrUs01BAcri@repo.nonprod.pcfcloud.io/artifactory/api/pypi/pypi-composer-releases/simple
