CREATE OR REPLACE TABLE pcb-{env}-processing.domain_customer_acquisition.APP_ABB_ACC_RE_IDV
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
APP_ABB.APA_APP_NUM,
LTTR_OVRD_DETAIL_XTO.TS2_ACCOUNT_ID as ACCOUNT_NUMBER
FROM
`pcb-{env}-processing.domain_customer_acquisition.APP_ABB_RE_IDV` AS APP_ABB
INNER JOIN
`pcb-{env}-curated.domain_customer_acquisition.LTTR_OVRD_DETAIL_XTO` LTTR_OVRD_DETAIL_XTO
  ON LTTR_OVRD_DETAIL_XTO.APP_NUM=APP_ABB.APA_APP_NUM
  AND LTTR_OVRD_DETAIL_XTO.TS2_ACCOUNT_ID is not null
  AND LTTR_OVRD_DETAIL_XTO.TS2_ACCOUNT_ID<>0
INNER JOIN
  `pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR` CIF
  ON CAST(LTTR_OVRD_DETAIL_XTO.TS2_ACCOUNT_ID AS INT64) = CAST(CIF.CIFP_ACCOUNT_ID5 AS INT64)
WHERE
  CIF.CIFP_CLOSED_MAINT_DATE IS NULL;  -- Ensure account is not closed