CREATE OR REPLACE TABLE pcb-{env}-processing.domain_customer_acquisition.APP_ABB_RE_IDV
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT DISP_APP_DATA.APA_APP_NUM
FROM
---- Identify Approved apps --------
(SELECT DISTINCT
   ADM_STD_DISP_APP_DATA_V.APA_APP_NUM,
   MAX(ADM_STD_DISP_APP_DATA_V.EXECUTION_ID ) as MAX_EXECUTION_ID
from
   `pcb-{env}-curated.domain_customer_acquisition.ADM_STD_DISP_APP_DATA` ADM_STD_DISP_APP_DATA_V
where
   ADM_STD_DISP_APP_DATA_V.APA_STATUS = 'NEWACCOUNT'
   and ADM_STD_DISP_APP_DATA_V.APA_QUEUE_ID = 'APPROVE'
   and (ADM_STD_DISP_APP_DATA_V.APA_TEST_ACCOUNT_FLAG IS NULL OR ADM_STD_DISP_APP_DATA_V.APA_TEST_ACCOUNT_FLAG = "" )
   and ADM_STD_DISP_APP_DATA_V.FILE_CREATE_DT < COALESCE(PARSE_DATE('%Y-%m-%d', NULLIF('{lookback_date}', '')), DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH))
group by
   ADM_STD_DISP_APP_DATA_V.APA_APP_NUM) DISP_APP_DATA
  INNER JOIN
  ------ Identify promo code used to submit the apps ----------
  ( SELECT DISTINCT
   APA_APP_NUM, EXECUTION_ID
FROM
  `pcb-{env}-curated.domain_customer_acquisition.ADM_STD_DISP_BAL_TRNS_INFO` ADM_STD_DISP_BAL_TRNS_INFO
  WHERE
  ADM_STD_DISP_BAL_TRNS_INFO.DTC_BXR_SOURCE_1='00011535'
  AND ADM_STD_DISP_BAL_TRNS_INFO.FILE_CREATE_DT < COALESCE(PARSE_DATE('%Y-%m-%d', NULLIF('{lookback_date}', '')), DATE_SUB(CURRENT_DATE(), INTERVAL 6 MONTH))
  ) BAL_TRNS_INFO
 ON DISP_APP_DATA.APA_APP_NUM=BAL_TRNS_INFO.APA_APP_NUM
   AND DISP_APP_DATA.MAX_EXECUTION_ID=BAL_TRNS_INFO.EXECUTION_ID;
