CREATE OR REPLACE TABLE pcb-{env}-processing.domain_customer_acquisition.MAP_ACC_NUM_RE_IDV
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT ACCOUNT.MAST_ACCOUNT_ID as ACCOUNT_NUMBER,
ACCOUNT_CUSTOMER.ACCOUNT_UID as ACCOUNT_UID,
ACCOUNT_CUSTOMER.CUSTOMER_UID
FROM
`pcb-{env}-curated.domain_account_management.ACCOUNT` ACCOUNT
inner join
`pcb-{env}-curated.domain_account_management.ACCOUNT_CUSTOMER` ACCOUNT_CUSTOMER
ON ACCOUNT.ACCOUNT_UID=ACCOUNT_CUSTOMER.ACCOUNT_UID
AND ACCOUNT_CUSTOMER.ACCOUNT_CUSTOMER_ROLE_UID=1
AND ACCOUNT.PRODUCT_UID  = 7 -- PCMA ABB - REIDV only
AND ACCOUNT_CUSTOMER.ACTIVE_IND='Y'
AND ACCOUNT_CUSTOMER.CUSTOMER_UID != 9647425 -- Ignore dummy customer id which is used for tsys purged customers;
