INSERT INTO `pcb-{env}-landing.domain_customer_acquisition.RE_IDV_REQUIRED_CUSTOMER` (
  CUSTOMER_UID,
  RE_IDV_STATUS,
  INGESTION_TIMESTAMP,
  SOURCE,
  EMAIL_SENT_COUNTER
)
SELECT DISTINCT
MAP_ACC_NUM.CUSTOMER_UID AS CUSTOMER_UID,
'NEW' AS RE_IDV_STATUS,
CURRENT_TIMESTAMP() AS INGESTION_TIMESTAMP,
'INTERNAL' AS SOURCE,
0 AS EMAIL_SENT_COUNTER
FROM `pcb-{env}-processing.domain_customer_acquisition.APP_ABB_ACC_RE_IDV` AS APP_ABB_ACC
INNER JOIN
`pcb-{env}-processing.domain_customer_acquisition.MAP_ACC_NUM_RE_IDV` AS MAP_ACC_NUM
ON APP_ABB_ACC.ACCOUNT_NUMBER = CAST(MAP_ACC_NUM.ACCOUNT_NUMBER AS INTEGER)
LEFT JOIN
`pcb-{env}-landing.domain_customer_acquisition.RE_IDV_REQUIRED_CUSTOMER` RE_IDV_ACC
ON RE_IDV_ACC.CUSTOMER_UID = MAP_ACC_NUM.CUSTOMER_UID
WHERE RE_IDV_ACC.CUSTOMER_UID IS NULL; -- Remove accounts, for which reidv is already triggered.