CREATE TABLE IF NOT EXISTS `pcb-{DEPLOY_ENV}-curated.domain_aml.AML_ABB_CUST` (
            CUSTOMER_NUMBER STRING,
            ACCOUNT_NUMBER STRING,
            ABB_IND STRING DEFAULT 'Y',
            REC_CREATE_TMS TIMESTAMP)
            PARTITION BY DATETIME_TRUNC(REC_CREATE_TMS, YEAR);