CREATE OR REPLACE TABLE `pcb-{DEPLOY_ENV}-processing.domain_aml.APP_ABB_ACC` AS
SELECT
  APP_ABB.APA_APP_NUM,
  LTTR_OVRD_DETAIL_XTO.TS2_ACCOUNT_ID as ACCOUNT_NUMBER
FROM
  `pcb-{DEPLOY_ENV}-processing.domain_aml.APP_ABB` APP_ABB
  INNER JOIN `pcb-{DEPLOY_ENV}-curated.domain_customer_acquisition.LTTR_OVRD_DETAIL_XTO` LTTR_OVRD_DETAIL_XTO
    ON LTTR_OVRD_DETAIL_XTO.APP_NUM = APP_ABB.APA_APP_NUM
    AND LTTR_OVRD_DETAIL_XTO.TS2_ACCOUNT_ID IS NOT NULL
    AND LTTR_OVRD_DETAIL_XTO.TS2_ACCOUNT_ID <> 0;