CREATE OR REPLACE TABLE `pcb-{DEPLOY_ENV}-processing.domain_aml.STG_ABB_CUST` AS
SELECT
    q2.ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
    q1.CUSTOMER_IDENTIFIER_NO AS CUSTOMER_NUMBER,
    q1.CUSTOMER_UID
FROM
    (
        SELECT
            ACCOUNT.MAST_ACCOUNT_ID AS ACCOUNT_NUMBER,
            ACCOUNT_CUSTOMER.ACTIVE_IND,
            ACCOUNT_CUSTOMER.ACCOUNT_CUSTOMER_ROLE_UID,
            CUSTOMER_IDENTIFIER.CUSTOMER_IDENTIFIER_NO,
            CUSTOMER_IDENTIFIER.CUSTOMER_UID
        FROM
            `pcb-{DEPLOY_ENV}-curated.domain_account_management.ACCOUNT` ACCOUNT
            INNER JOIN `pcb-{DEPLOY_ENV}-curated.domain_account_management.ACCOUNT_CUSTOMER` ACCOUNT_CUSTOMER
                ON ACCOUNT.ACCOUNT_UID = ACCOUNT_CUSTOMER.ACCOUNT_UID
            INNER JOIN `pcb-{DEPLOY_ENV}-curated.domain_customer_management.CUSTOMER_IDENTIFIER` CUSTOMER_IDENTIFIER
                ON ACCOUNT_CUSTOMER.CUSTOMER_UID = CUSTOMER_IDENTIFIER.CUSTOMER_UID
        WHERE 
            ACCOUNT_CUSTOMER.ACCOUNT_CUSTOMER_ROLE_UID = 1
            AND CUSTOMER_IDENTIFIER.TYPE = 'PCF-CUSTOMER-ID'
            AND CUSTOMER_IDENTIFIER.DISABLED_IND = 'N'
            AND ACCOUNT_CUSTOMER.ACTIVE_IND = 'Y'
            AND ACCOUNT.PRODUCT_UID IN (7, 8, 9, 10)
    )q1
    INNER JOIN `pcb-{DEPLOY_ENV}-processing.domain_aml.APP_ABB_ACC` q2
        ON q2.ACCOUNT_NUMBER = CAST(q1.ACCOUNT_NUMBER AS INT64)