INSERT INTO `pcb-{env}-processing.domain_customer_acquisition.PRE_PURGE_REPORT` (
  IS_TERMINUS,
  APP_SOURCE,
  APP_TYPE,
  PURGE_LIST_DATE,
  PURGE_IND,
  PURGE_COUNT,
  SUM_CUR_BALANCE,
  MAX_DECLINE_DATE,
  MAX_CREDIT_REVOKE_DATE,
  MAX_LAST_FINANCIAL_ACTIVITY_DATE,
  MAX_CLOSURE_CRVK_DATE,
  REPORT_DATE
)
SELECT
  IS_TERMINUS,
  APP_SOURCE,
  APP_TYPE,
  PURGE_LIST_DATE,
  CASE
    WHEN IS_TERMINUS = 'N' THEN 1
    ELSE PURGE_IND
  END AS PURGE_IND,
  COUNT(APP_NUMBER) AS PURGE_COUNT,
  SUM(CURRENT_BALANCE) AS SUM_CUR_BALANCE,
  MAX(DECLINE_DATE) AS MAX_DECLINE_DATE,
  MAX(CREDIT_REVOKE_DATE) AS MAX_CREDIT_REVOKE_DATE,
  MAX(LAST_FINANCIAL_ACTIVITY_DATE) AS MAX_LAST_FINANCIAL_ACTIVITY_DATE,
  MAX(LEAST(ACCOUNT_CLOSE_DATE, CREDIT_REVOKE_DATE)) AS MAX_CLOSURE_CRVK_DATE,
  CURRENT_DATETIME() AS REPORT_DATE
FROM
  `pcb-{env}-landing.domain_customer_acquisition.PURGELIST_EXPERIAN`
WHERE
  IS_TERMINUS = '{is_terminus}'
  AND PURGE_LIST_DATE = (
    SELECT
      MAX(PURGE_LIST_DATE) AS LAST_PURGE_DATE
    FROM
      `pcb-{env}-landing.domain_customer_acquisition.PURGELIST_EXPERIAN`
    WHERE
      IS_TERMINUS = '{is_terminus}'
      AND PURGE_IND = {purge_ind}
  )
GROUP BY
  APP_TYPE, PURGE_LIST_DATE, APP_SOURCE, IS_TERMINUS, PURGE_IND;
