CREATE OR REPLACE TABLE pcb-{env}-processing.domain_customer_acquisition.PRE_PURGE_REPORT (
  IS_TERMINUS STRING,
  APP_SOURCE STRING,
  APP_TYPE STRING,
  PURGE_LIST_DATE DATE,
  PURGE_IND INTEGER,
  PURGE_COUNT INTEGER,
  SUM_CUR_BALANCE FLOAT64,
  MAX_DECLINE_DATE DATE,
  MAX_CREDIT_REVOKE_DATE DATE,
  MAX_LAST_FINANCIAL_ACTIVITY_DATE DATE,
  MAX_CLOSURE_CRVK_DATE DATE,
  REPORT_DATE DATETIME
)
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
);