INSERT INTO `pcb-{env}-processing.domain_customer_acquisition.PRE_PURGE_REPORT` (
  IS_TERMINUS,
  APP_SOURCE,
  APP_TYPE,
  PURGE_LIST_DATE,
  PURGE_IND,
  PURGE_COUNT,
  SUM_CUR_BALANCE,
  MAX_DECLINE_DATE,
  MAX_CREDIT_REVOKE_DATE,
  MAX_LAST_FINANCIAL_ACTIVITY_DATE,
  MAX_CLOSURE_CRVK_DATE,
  REPORT_DATE
)
SELECT
  'N' AS IS_TERMINUS,
  APP_SOURCE,
  APP_TYPE,
  PARSE_DATE('%Y%m%d', CAST(PURGE_LIST_DATE AS STRING)) AS PURGE_LIST_DATE,
  PURGE_IND,
  COUNT({app_id_column}) AS PURGE_COUNT,
  SUM( CAST(CURRENT_BALANCE AS FLOAT64)) AS SUM_CUR_BALANCE,
  MAX(PARSE_DATE('%Y%m%d', CAST(DECLINE_DATE AS STRING))) AS MAX_DECLINE_DATE,
  MAX(PARSE_DATE('%Y%m%d', CAST(CREDIT_REVOKE_DATE AS STRING))) AS MAX_DECLINE_DATE,
  MAX(PARSE_DATE('%Y%m%d', CAST(LAST_FINANCIAL_ACTIVITY_DATE AS STRING))) AS MAX_DECLINE_DATE,
  MAX(LEAST(
  PARSE_DATE('%Y%m%d', CAST(ACCOUNT_CLOSE_DATE AS STRING)),
  PARSE_DATE('%Y%m%d', CAST(CREDIT_REVOKE_DATE AS STRING))
  )
  ) AS MAX_CLOSURE_CRVK_DATE,
  CURRENT_DATETIME() AS REPORT_DATE
FROM
  pcb-{env}-processing.domain_customer_acquisition.{src_table}
  GROUP BY
    APP_TYPE, PURGE_LIST_DATE, APP_SOURCE, IS_TERMINUS, PURGE_IND;