SELECT * EXCEPT (ROW_RANK)
FROM (
	WITH AT31_DAT AS (
			SELECT CASE
					WHEN AT31_DEBIT_CREDIT_INDICATOR = 'C'
						THEN - AT31_AMT_TRANSACTION
					ELSE AT31_AMT_TRANSACTION
					END AS AT31_AMT_TRANSACTION
				,AT31_DEBIT_CREDIT_INDICATOR
				,FILE_CREATE_DT
				,MAST_ACCOUNT_ID
				,AT31_TERMS_BALANCE_CODE
				,AT31_TRNS_ACCT_FUNC
			FROM pcb-{env}-landing.domain_account_management.AT31
			WHERE FILE_CREATE_DT BETWEEN DATE_SUB(DATE_TRUNC(CURRENT_DATE (), MONTH), INTERVAL 12 MONTH)
					AND DATE_SUB(DATE_TRUNC(CURRENT_DATE (), MONTH), INTERVAL 1 DAY)
				AND SUBSTR(AT31_ACCOUNT_NUMB, 1, 6) IN (
					'518127'
					,'522879'
					,'518116'
					,'516179'
					)
			)
		,AT31_AGG_TRANS AS (
			SELECT COALESCE(SUM(CASE
							WHEN AT31_DEBIT_CREDIT_INDICATOR = 'C'
								AND AT31_TERMS_BALANCE_CODE != 0
								THEN - ABS(AT31_AMT_TRANSACTION)
							WHEN AT31_DEBIT_CREDIT_INDICATOR = 'D'
								AND AT31_TERMS_BALANCE_CODE = 0
								THEN - ABS(AT31_AMT_TRANSACTION)
							ELSE ABS(AT31_AMT_TRANSACTION)
							END), 0) AS AMT_INT
				,MAST_ACCOUNT_ID
				,FILE_CREATE_DT
			FROM AT31_DAT
			WHERE AT31_TRNS_ACCT_FUNC IN (
					'PFC'
					,'CFC'
					,'FCA'
					,'FDA'
					,'FCV'
					,'FDV'
					,'CCF'
					,'CPF'
					,'WCF'
					,'WPF'
					)
			GROUP BY MAST_ACCOUNT_ID
				,FILE_CREATE_DT
			)
		,INTREST_12M AS (
			SELECT SUM(AMT_INT) AS INTREST_12M
				,MAST_ACCOUNT_ID
			FROM AT31_AGG_TRANS
			GROUP BY MAST_ACCOUNT_ID
			),
			AM00 AS (
			SELECT CASE WHEN AM00_DAILY.AM00_DATE_ACCOUNT_OPEN = 0
						THEN  DATE(1900,01,01) ELSE DATE_ADD(
    DATE(CAST(SUBSTR(CAST(AM00_DAILY.AM00_DATE_ACCOUNT_OPEN AS STRING), 1, 4) AS INT64),1,1),
    INTERVAL CAST(SUBSTR(CAST(AM00_DAILY.AM00_DATE_ACCOUNT_OPEN AS STRING), 5, 3) AS INT64) - 1 DAY) END AS ACCOUNT_OPEN_DATE,* FROM pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM00_REC AM00_DAILY
			),
      AM33_CASH_ADV AS (
        SELECT MAST_ACCOUNT_ID,SUM(AM33_AMT_DEBITS_CTD) AS AMT_DEBITS_CTD  FROM pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM33_REC
		WHERE  AM33_CLASS_CODE = 'CA'
		GROUP BY MAST_ACCOUNT_ID
      )
	SELECT CAST(AM00.MAST_ACCOUNT_ID AS NUMERIC) AS ID
		,AB.Description AS BALANCE_CATEG
		,IFNULL(AM02.AM02_BALANCE_CURRENT,0) AS BALANCE
		,IFNULL(AM33_CASH_ADV.AMT_DEBITS_CTD,0) AS CASH_BALANCE
		,CL.Description AS CREDIT_LIMIT_CATEG
		,CAST(AM00.AM00_LIMIT_CREDIT AS NUMERIC) AS CREDIT_LIMIT
		,AC.CIFP_PURCHASE_APR AS RATE_PURCHASE_APR
		,AC.CIFP_CASH_APR AS RATE_CASH_APR
		, AM00.ACCOUNT_OPEN_DATE
		,IFNULL(AM02.AM02_OUT_MIN_PAYMENT_DUE,0) AS MINIMUM_PAYMENT
		,CASE
		    WHEN AM00.MAST_ACCOUNT_SUFFIX <>0
		        THEN 'Transfers'
            WHEN DB.Description IS NOT NULL and AM02.AM02_BALANCE_CURRENT <=0
                THEN DB.Description
            WHEN DS.Decription IS NOT NULL
                THEN DS.Decription
            ELSE '180+ days'
            END AS DAYS_DELINQUENT_ID_CATEG
        ,CAST(AM04.AM04_CONS_DAYS_PASTDUE AS NUMERIC) AS DAYS_DELINQUENT_ID
		,CS.Description AS CREDIT_SCORE_ID_CATEG
		,CAST(AM00.AM00_CREDIT_SCORE_CUR AS NUMERIC) AS CREDIT_SCORE_ID
		,AR.Description AS AGE_CATEG
		,DATE_DIFF(CURRENT_DATE (), AM00.ACCOUNT_OPEN_DATE, month) AS AGE_MONTHS
		,CA.CIFP_STATE AS PROVINCE_ID
		,CA.CIFP_CUSTOMER_ID_2 AS CUSTOMER_ID
		,CASE
			WHEN ACT.Prd_Cd IS NOT NULL
				THEN UPPER(ACT.Description)
			ELSE 'SILVER'
			END AS CARD_TYPE
		,CASE
			WHEN AM00.AM00_SECURITIZATION_POOL_ID1 IN ('00000A')
				THEN 1
			ELSE 0
			END AS SECURITIZED
		,IFNULL(INTR.INTREST_12M,0) AS CUM_INTR_12M
		,IFNULL(AM33_PURCHASE.AM33_AMT_FCHG_OUT,0) AS `PURCHASE_INTEREST_OUTSTANDING`
		,IFNULL(AM33_CASH.AM33_AMT_FCHG_OUT,0) AS `CASH_INTEREST_OUTSTANDING`
		,CASE
			WHEN INTR.INTREST_12M >= 50
				THEN 'REVOLVER'
			ELSE 'TRANSACTOR'
			END AS ACCOUNT_TYPE
        ,AM00.MAST_ACCOUNT_SUFFIX AS ACCOUNT_SUFFIX
        ,AM00.AM00_STATC_CHARGEOFF AS STATC_CHARGEOFF
        ,AM00.AM00_STATC_SECURITY_FRAUD AS STATC_SECURITY_FRAUD
        ,AM00.AM00_STATC_CLOSED AS STATC_CLOSED
        ,AM00.AM00_BANKRUPTCY_TYPE AS BANKRUPTCY_TYPE
        ,AM00.AM00_STATF_DECLINED_REISSUE AS STATF_DECLINED_REISSUE
        ,AM00.AM00_STATC_CREDIT_REVOKED AS STATC_CREDIT_REVOKED
		,ROW_NUMBER() OVER (
			PARTITION BY am00.MAST_ACCOUNT_ID,am00.MAST_ACCOUNT_SUFFIX
			) AS ROW_RANK
	FROM  AM00
  left join
    pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM02_REC AM02
  on am00.MAST_ACCOUNT_ID = am02.MAST_ACCOUNT_ID and am00.MAST_ACCOUNT_SUFFIX = am02.AM00_APPLICATION_SUFFIX
	left join pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM04_PD AM04 ON  am00.MAST_ACCOUNT_ID = AM04.MAST_ACCOUNT_ID and
  am00.MAST_ACCOUNT_SUFFIX=AM04.AM00_APPLICATION_SUFFIX
	LEFT JOIN pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM33_REC AM33_PURCHASE ON AM00.MAST_ACCOUNT_ID = AM33_PURCHASE.MAST_ACCOUNT_ID
  AND AM00.MAST_ACCOUNT_SUFFIX=AM33_PURCHASE.AM00_APPLICATION_SUFFIX
		AND AM33_PURCHASE.AM33_CLASS_CODE = 'PR'
		AND AM33_PURCHASE.AM33_TRANSACTION_CATEGORY = 1000
	LEFT JOIN pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM33_REC AM33_CASH ON AM00.MAST_ACCOUNT_ID = AM33_CASH.MAST_ACCOUNT_ID
  AND AM00.MAST_ACCOUNT_SUFFIX=AM33_CASH.AM00_APPLICATION_SUFFIX
		AND AM33_CASH.AM33_CLASS_CODE = 'CA'
		AND AM33_CASH.AM33_TRANSACTION_CATEGORY IN (
			0002
			,0003
			,0004
			,0005
			)
    LEFT JOIN AM33_CASH_ADV ON AM00.MAST_ACCOUNT_ID = AM33_CASH_ADV.MAST_ACCOUNT_ID
    LEFT JOIN pcb-{env}-curated.domain_account_management.CIF_CARD_CURR CA ON SAFE_CAST(AM00.MAST_ACCOUNT_ID AS NUMERIC) = CA.CIFP_ACCOUNT_ID6
    LEFT JOIN pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR AC ON AC.CIFP_ACCOUNT_ID5 = SAFE_CAST(AM00.MAST_ACCOUNT_ID AS NUMERIC)
	LEFT JOIN INTREST_12M INTR ON SAFE_CAST(AM00.MAST_ACCOUNT_ID AS NUMERIC) = INTR.MAST_ACCOUNT_ID
	LEFT JOIN pcb-{env}-landing.domain_treasury.ALM_AGE_OF_PORTFOLIO_REF AR ON DATE_DIFF(CURRENT_DATE (), AM00.ACCOUNT_OPEN_DATE, month) BETWEEN AR.Min_Range
			AND AR.Max_Range
	LEFT JOIN pcb-{env}-landing.domain_treasury.ALM_CARD_TYPE_REF ACT ON AM00.CLIENT_PRODUCT_CODE = ACT.Prd_Cd
	LEFT JOIN pcb-{env}-landing.domain_treasury.ALM_CREDIT_SCORE_REF CS ON IFNULL(AM00.AM00_CREDIT_SCORE_CUR, 0) BETWEEN CS.Min_Range
			AND CS.Max_Range
	LEFT JOIN pcb-{env}-landing.domain_treasury.ALM_ACCOUNT_BALANCE_REF AB ON IFNULL(AM02.AM02_BALANCE_CURRENT, 0) BETWEEN AB.Min_Range
			AND AB.Max_Range
	LEFT JOIN pcb-{env}-landing.domain_treasury.ALM_CREDIT_LIMIT_REF CL ON IFNULL(AM00.AM00_LIMIT_CREDIT, 0) BETWEEN CL.Min_Range
			AND CL.Max_Range
	LEFT JOIN pcb-{env}-landing.domain_treasury.ALM_DAYS_DELQ_AM02_BAL_CUR_REF DB ON IFNULL(AM02.AM02_BALANCE_CURRENT, 0) BETWEEN DB.Min_Range
			AND DB.Max_Range
	LEFT JOIN pcb-{env}-landing.domain_treasury.ALM_DAYS_DELQ_AM00_STATC_CUR_REF DS ON IFNULL(CAST(AM04.AM04_CONS_DAYS_PASTDUE AS STRING), '') = DS.am00_statc_current_past_due
	WHERE  (am00.AM00_STATC_CHARGEOFF is null or am00.AM00_STATC_CHARGEOFF = '') and (AM00.MAST_ACCOUNT_SUFFIX=0 or AM02.AM02_BALANCE_CURRENT<>0)
		AND AM00.CLIENT_PRODUCT_CODE IN (
			'PCP'
			,'PCS'
			,'PCR'
			,'PCE'
			,'PCH'
			,'PCI'
			,'PFE'
			)
		-- AND (
		-- 	CA.CIFP_RELATIONSHIP_STAT IS NULL
		-- 	OR CA.CIFP_RELATIONSHIP_STAT = ''
		-- 	OR CA.CIFP_RELATIONSHIP_STAT = 'A'
		-- 	)
		-- AND CA.CIFP_CUSTOMER_TYPE = 0
	)
WHERE ROW_RANK = 1
