--Extract data for  Demand deposits--

SELECT
  * EXCEPT(ROW_RANK)
FROM (
  SELECT
    CAST(AM00.MAST_ACCOUNT_ID AS NUMERIC) AS ID,
    IFNULL(AM02.AM02_BALANCE_CURRENT,0) AS PRINCIPAL,
    0 AS EARN_RATE,
    CASE
      WHEN AM00.AM00_LIMIT_CREDIT > 0 THEN '19'
      ELSE '0'
  END
    AS OVERDRAFT_INTEREST_RATE,
    CAST(AM00.AM00_LIMIT_CREDIT AS NUMERIC) AS OVERDRAFT_LIMIT,
    CASE AM00.CLIENT_PRODUCT_CODE
      WHEN 'PDI' THEN 'Deposit Account'
      ELSE AM00.CLIENT_PRODUCT_CODE
  END
    AS PRODUCT_TYPE,
    DATE_ADD(
    DATE(CAST(SUBSTR(CAST(AM00.AM00_DATE_ACCOUNT_OPEN AS STRING), 1, 4) AS INT64),1,1),
    INTERVAL CAST(SUBSTR(CAST(AM00.AM00_DATE_ACCOUNT_OPEN AS STRING), 5, 3) AS INT64) - 1 DAY) AS ACCOUNT_OPEN_DATE,
    CA.CIFP_CUSTOMER_ID_2 AS CUSTOMER_ID,
    AM00.MAST_ACCOUNT_SUFFIX AS ACCOUNT_SUFFIX,
    AM00_STATC_CHARGEOFF AS STATC_CHARGEOFF,
    AM00_STATC_SECURITY_FRAUD AS STATC_SECURITY_FRAUD,
    AM00_STATC_CLOSED AS STATC_CLOSED,
    AM00_BANKRUPTCY_TYPE AS BANKRUPTCY_TYPE,
    AM00_STATF_DECLINED_REISSUE AS STATF_DECLINED_REISSUE,
    AM00_STATC_CREDIT_REVOKED AS STATC_CREDIT_REVOKED,
    ROW_NUMBER() OVER(PARTITION BY am00.MAST_ACCOUNT_ID,am00.MAST_ACCOUNT_SUFFIX ) AS ROW_RANK
  FROM
    pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM00_REC AM00
  left join
    pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM02_REC AM02
  on am00.MAST_ACCOUNT_ID = am02.MAST_ACCOUNT_ID AND AM00.MAST_ACCOUNT_SUFFIX = AM02.AM00_APPLICATION_SUFFIX
  left JOIN
    pcb-{env}-curated.domain_account_management.CIF_CARD_CURR CA
  ON
    SAFE_CAST(AM00.MAST_ACCOUNT_ID AS NUMERIC)=CA.CIFP_ACCOUNT_ID6
  WHERE
    (am00.AM00_STATC_CHARGEOFF is null or am00.AM00_STATC_CHARGEOFF = '')
    and (AM00.MAST_ACCOUNT_SUFFIX=0 or AM02.AM02_BALANCE_CURRENT<>0)
    AND AM00.CLIENT_PRODUCT_CODE IN ('PDI','PDG')
    -- AND (CA.CIFP_RELATIONSHIP_STAT IS NULL
    --   OR CA.CIFP_RELATIONSHIP_STAT = ''
    --   OR CA.CIFP_RELATIONSHIP_STAT = 'A' )
    -- AND CA.CIFP_CUSTOMER_TYPE=0
    )
WHERE
  ROW_RANK=1