CREATE OR REPLACE TABLE `pcb-{env}-curated.cots_alm_tbsm.CREDIT_CARD_RECV_TRANS_TEST_STG` AS
SELECT * 
    EXCEPT (ROW_RANK)
FROM 
 ( SELECT
    TR13.CIFP_ACCOUNT_ID5 AS ID,
    TR13.BALANCE,
    TR13.CIFP_CUR_CASH_ADV_CTD AS CASH_BALANCE,
    TR13.CREDIT_LIMIT,
    TR13.CIFP_PURCHASE_APR AS RATE_PURCHASE_APR,
    TR13.CIFP_CASH_APR AS RATE_CASH_APR,
    DATE (TR13.CIFP_DATE_OPEN) AS ACCOUNT_OPEN_DATE,
    TR13.CIFP_MINIMUM_PAY_DUE AS MINIMUM_PAYMENT,
    TR13.DAYS_DELINQUENT_ID,
    TR13.CREDIT_SCORE_ID,
    TR13.AGE,
    TR13.CIFP_STATE AS PROVINCE_ID,
    TR13.CIFP_CUSTOMER_ID_2 AS CUSTOMER_ID,
    TR13.CARD_TYPE,
    TR13.SECURITIZED,
    TR13.CUM_INTR_12M,
    TR13.PURCHASE_INTEREST_OUTSTANDING,
    TR13.CASH_INTEREST_OUTSTANDING,
    TR13.ACCOUNT_TYPE,
    ROW_NUMBER() OVER (PARTITION BY CIFP_ACCOUNT_ID6 ORDER BY REC_LOAD_TIMESTAMP DESC) AS ROW_RANK
   FROM 
    pcb-{env}-processing.cots_alm_tbsm.ASSET_CC_RECV_TRANS_13 TR13
 )
WHERE 
    ROW_RANK = 1