CREATE OR REPLACE VIEW `pcb-{env}-processing.cots_alm_tbsm.AT31_DAT` AS
SELECT
    CASE
    WHEN AT31_DEBIT_CREDIT_INDICATOR = {at31_debit_credit_indicator_val_1} 
    THEN -AT31_AMT_TRANSACTION
    ELSE AT31_AMT_TRANSACTION
    END AS AT31_AMT_TRANSACTION,
    AT31_DEBIT_CREDIT_INDICATOR,
    FILE_CREATE_DT,
    MAST_ACCOUNT_ID,
    AT31_TERMS_BALANCE_CODE,
    AT31_TRNS_ACCT_FUNC
FROM 
    pcb-{env}-landing.domain_account_management.AT31
WHERE
    FILE_CREATE_DT BETWEEN DATE_SUB(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 12 MONTH)
    AND DATE_SUB(DATE_TRUNC(CURRENT_DATE(), MONTH), INTERVAL 1 DAY)
    AND SUBSTR(AT31_ACCOUNT_NUMB, 1, 6) IN ({at31_account_numb_val})