CREATE OR REPLACE VIEW `pcb-{env}-processing.cots_alm_tbsm.ASSET_CC_RECV_TRANS_6` AS
SELECT 
    TR5.*,
    AM33_PURCHASE.AM33_AMT_FCHG_OUT AS `PURCHASE_INTEREST_OUTSTANDING`,
    AM33_CASH.AM33_AMT_FCHG_OUT AS `CASH_INTEREST_OUTSTANDING`
FROM 
    pcb-{env}-processing.cots_alm_tbsm.ASSET_CC_RECV_TRANS_5 TR5
LEFT JOIN 
    pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM33_REC AM33_PURCHASE
ON 
    TR5.CIFP_ACCOUNT_ID5 = SAFE_CAST(AM33_PURCHASE.MAST_ACCOUNT_ID AS NUMERIC)
    AND AM33_PURCHASE.AM33_CLASS_CODE = {am33_purchase_class_code_val}
    AND AM33_PURCHASE.AM33_TRANSACTION_CATEGORY = {am33_purchase_transaction_category_val}
    AND TR5.MAST_ACCOUNT_ID = AM33_PURCHASE.MAST_ACCOUNT_ID
LEFT JOIN
    pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM33_REC AM33_CASH 
ON 
    TR5.CIFP_ACCOUNT_ID5 = SAFE_CAST(AM33_CASH.MAST_ACCOUNT_ID AS NUMERIC)
    AND AM33_CASH.AM33_CLASS_CODE = {am33_cash_class_code_val}
    AND AM33_CASH.AM33_TRANSACTION_CATEGORY IN ({am33_cash_transaction_category_val})
    AND TR5.MAST_ACCOUNT_ID = AM33_CASH.MAST_ACCOUNT_ID