CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_account_management.{output_table_name}
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) ) AS
WITH
  sa14_record AS (
  SELECT
    SA14_CLIENT_NUM AS client_num,
    SA14_ACCT_ID AS ACCT_ID,
    SA14_SEQ_NUM AS SEQ_NUM,
    sa14.*
  FROM
    `pcb-{env}-landing.domain_account_management.SA14` sa14
  WHERE
    sa14.FILE_CREATE_DT='{file_create_dt}'
    AND sa14.FILE_NAME='{file_name}')
SELECT
  (((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((LPAD(CAST (sa14_record .CLIENT_NUM AS STRING ), 4, '0') || LPAD(CAST (sa14_record .ACCT_ID AS STRING ), 12, '0')) || sa14_record .sa14_RECORD_ID) || LPAD(CAST (sa14_record .SA14_SEQ_NUM AS STRING ), 5, '0')) || ' ') || LPAD(IFNULL (sa14_record .SA14_KEY_STMT_FORM, ' ' ), 4, ' ')) || LPAD(IFNULL (sa14_record .SA14_KEY_INSRT_GRP, ' ' ), 3, ' ')) || ' ') || LPAD(IFNULL (sa14_record .SA14_STMT_MSG1, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_STMT_MSG2, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_STMT_MSG3, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_TRIAD_STMT_MSG1, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_TRIAD_STMT_MSG2, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_TRIAD_STMT_MSG3, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_STMT_MSG_FX, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRICING_STMT_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PD_OL_MSG_STAT, ' ' ), 2, ' ')) || LPAD(CAST (sa14_record .SA14_PD_MSG_STAT AS STRING ), 2, '0')) || LPAD(CAST (sa14_record .SA14_OL_MSG_STAT AS STRING ), 2, '0')) || LPAD(IFNULL (sa14_record .SA14_FIRST_USE_THIS_CYCLE, ' '), 1, ' ')) || LPAD(IFNULL (sa14_record .SA14_NEXT_AUTOPAY_MSG_STAT, ' '), 1, ' ')) || LPAD(CAST (sa14_record .SA14_AUTOPAY_DAY AS STRING ), 2, '0')) || LPAD(IFNULL (sa14_record .SA14_PSE_SPLIT_STMT_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PSE_STATE_LEGAL_FLAG, ' '), 1, ' ')) || LPAD(' ', 4, ' ')) || LPAD(IFNULL (sa14_record .SA14_PSE_OL_OPT_STMT_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PSE_PD_OPT_STMT_MSG, ' ' ), 5, ' ')) ||
                                                                                              IF
                                                                                                ((sa14_record .SA14_INSUR_AMT < 0), (LPAD(REPLACE (CAST ((sa14_record .SA14_INSUR_AMT * -1) AS STRING ), '.', ''), 13, '0') || '-'), (LPAD(REPLACE (CAST (sa14_record .SA14_INSUR_AMT AS STRING ), '.', ''), 13, '0') || '+'))) || LPAD(IFNULL (sa14_record .SA14_AUTOP_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_AUTO_PAY_DATE, ' ' ), 8, ' ')) || LPAD(IFNULL (sa14_record .SA14_NEXT_AUTOP_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRE_PAY_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_REG_INSUR_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_RET_INSUR_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_SKIP_A_PAY_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_AMF_MSG1, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_AMF_MSG2, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_AMF_MSG3, ' ' ), 5, ' ')) ||
                                                                        IF
                                                                          ((sa14_record .SA14_NEXT_AUTOP_AMT < 0), (LPAD(REPLACE (CAST ((sa14_record .SA14_NEXT_AUTOP_AMT * -100) AS STRING ), '.', ''), 13, '0') || '-'), (LPAD(REPLACE (CAST (sa14_record .SA14_NEXT_AUTOP_AMT * 100 AS STRING ), '.', ''), 13, '0') || '+'))) || LPAD(' ', 13, ' ')) || LPAD(IFNULL (sa14_record .SA14_VARI_MSG1, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_VARI_MSG2, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_VARI_MSG3, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_VARI_MSG4, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_VARI_MSG5, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_IAFEE_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_XFR_TRAN_MSG, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_AUTO_PAY_DAILY, ' '), 1, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_LINE, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_DELQ, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_OVLM, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_AUTH, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_REIS, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_PROD, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_PRIC, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_USR1, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_USR2, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_PRB_STMT_MSG_USR3, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_1, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_2, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_3, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_4, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_5, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_6, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_7, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_8, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_9, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_10, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_11, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_12, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_13, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_14, ' ' ), 5, ' ')) || LPAD(IFNULL (sa14_record .SA14_ESC_MSG_15, ' ' ), 5, ' ')) || LPAD(' ', 300, ' ')) AS RECORD,
  sa14_record.ACCT_ID,
  sa14_record.sa14_SEQ_NUM AS SEQ_NUM,
  sa14_record.file_create_dt,
  sa14_record.SA14_RECORD_ID AS RECORD_ID,
  SUBSTR(sa14_record.PARENT_CARD_NUM,11) AS PARENT_NUM,
  2 AS RECORD_SEQ
FROM
  sa14_record