CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_account_management.{output_table_name}
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) ) AS
WITH
  SA60_record AS (
  SELECT
    FILE_CREATE_DT,
    SA60_CLIENT_NUM AS CLIENT_NUM,
    SA60_ACCT_ID AS ACCT_ID,
    SA60_ACCOUNT_NUMB,
    SA60_RECORD_ID,
    SA60_ACCOUNT_NUMB_ORIG,
    SA60_AMT_TRANS * 100 AS SA60_AMT_TRANS,
    SA60_DEB_CRED_IND,
    SA60_CLASS_CODE,
    SA60_DATE_POST,
    SA60_DATE_TRANS,
    SA60_CONVERSION_DATE,
    SA60_CONVERSION_RATE,
    SA60_CONVERSION_AMT,
    SA60_CONV_MARKUP_RATE,
    SA60_MERCH_CAT_CODE,
    SA60_MERCH_DBA_COUNTRY,
    SA60_MERCHANT_DBA_NAME,
    SA60_MERCHANT_DBA_CITY,
    SA60_MERCHANT_DBA_STATE,
    SA60_TRANS_CATEGORY,
    SA60_TRANS_CODE,
    SA60_MERCH_CURR_ALPHA,
    SA60_MERCHANT_ID,
    SA60_ACC_METHOD_TYPE_CD_CURR,
    SA60_PAYMENT_TRANS_INDICATOR,
    SA60_CLIENT_NUM,
    SA60_ACCT_ID,
    SA60_KEY_STMT_FORM,
    SA60_KEY_INSRT_GRP,
    SA60_SEQ_NUM,
    PARENT_CARD_NUM,
    SA60_CUST_TYPE
  FROM
    `pcb-{env}-landing.domain_account_management.SA60` SA60
  WHERE
    sa60.FILE_CREATE_DT='{file_create_dt}'
    AND sa60.FILE_NAME='{file_name}'
    AND ( SA60.SA60_TRANS_SUM_INDICATOR IS NULL
      OR SA60.SA60_TRANS_SUM_INDICATOR = 'Y' ) )
SELECT
  ((((((((((((((((((((((((((((( LPAD(CAST(SA60_record.CLIENT_NUM AS STRING), 4, '0') || LPAD(CAST(SA60_record.ACCT_ID AS STRING), 12, '0')) || SA60_record.sa60_RECORD_ID) || LPAD(CAST(SA60_record.SA60_SEQ_NUM AS STRING), 5, '0')) || ' ') || LPAD(IFNULL(SA60_record.SA60_KEY_STMT_FORM, ' '), 4, ' ')) || LPAD(IFNULL(SA60_record.SA60_KEY_INSRT_GRP, ' '), 3, ' ')) || ' ') || LPAD(IFNULL(SA60_record.SA60_ACCOUNT_NUMB, ' '), 19, ' ')) || LPAD(IFNULL(SA60_record.SA60_ACCOUNT_NUMB_ORIG, ' '), 19, ' ')) ||
                                        IF
                                          ((SA60_record.SA60_AMT_TRANS < 0), (LPAD(REPLACE(CAST((SA60_record.SA60_AMT_TRANS * -1) AS STRING), '.', ''), 13, '0') || '-'), (LPAD(REPLACE(CAST(SA60_record.SA60_AMT_TRANS AS STRING), '.', ''), 13, '0') || '+'))) || IFNULL(SA60_record.SA60_DEB_CRED_IND, ' ')) || LPAD(IFNULL(SA60_record.SA60_CLASS_CODE, ' '), 2, ' ')) || LPAD(IFNULL(SA60_record.SA60_DATE_POST, ' '), 8, ' ')) || LPAD(IFNULL(SA60_record.SA60_DATE_TRANS, ' '), 8, ' ')) ||
                              IF
                                ((SA60_record.SA60_CONVERSION_RATE < 0), (LPAD(REPLACE(CAST((SA60_record.SA60_CONVERSION_RATE * -1000000000) AS STRING), '.', ''), 17, '0') || '-'), (LPAD(REPLACE(CAST(SA60_record.SA60_CONVERSION_RATE * 1000000000 AS STRING), '.', ''), 17, '0') || '+'))) || LPAD(IFNULL(SA60_record.SA60_CONVERSION_AMT, ' '), 16, ' ')) || LPAD(CAST(SA60_record.SA60_MERCH_CAT_CODE AS STRING), 4, '0')) || LPAD(IFNULL(SA60_record.SA60_MERCH_DBA_COUNTRY, ' '), 3, ' ')) || RPAD(IFNULL(SA60_record.SA60_MERCHANT_DBA_NAME, ' '), 25, ' ')) || RPAD(IFNULL(SA60_record.SA60_MERCHANT_DBA_CITY, ' '), 13, ' ')) || RPAD(IFNULL(SA60_record.SA60_MERCHANT_DBA_STATE, ' '), 3, ' ')) || LPAD(CAST(SA60_record.SA60_TRANS_CATEGORY AS STRING), 4, '0')) || LPAD(CAST(SA60_record.SA60_TRANS_CODE AS STRING), 4, '0')) || LPAD(IFNULL(SA60_record.SA60_MERCH_CURR_ALPHA, ' '), 3, ' ')) || LPAD(IFNULL(SA60_record.SA60_MERCHANT_ID, ' '), 15, ' ')) || LPAD(IFNULL(SA60_record.SA60_ACC_METHOD_TYPE_CD_CURR, ' '), 1, ' ')) ||
      IF
        ((SA60_record.SA60_CONV_MARKUP_RATE < 0), (LPAD(REPLACE(CAST((SA60_record.SA60_CONV_MARKUP_RATE * -1000000000) AS STRING), '.', ''), 17, '0') || '-'), (LPAD(REPLACE(CAST(SA60_record.SA60_CONV_MARKUP_RATE * 1000000000 AS STRING), '.', ''), 17, '0') || '+'))) || IFNULL(CAST(SA60_record.SA60_PAYMENT_TRANS_INDICATOR AS STRING),'0')) || LPAD(' ', 17, ' ')) AS record,
  SA60_record.ACCT_ID,
  SA60_record.SA60_SEQ_NUM AS SEQ_NUM,
  SA60_record.file_create_dt,
  SA60_record.SA60_RECORD_ID AS RECORD_ID,
  SUBSTR(sa60_record.PARENT_CARD_NUM,11) AS PARENT_NUM,
  9 AS RECORD_SEQ,
  SA60_PAYMENT_TRANS_INDICATOR,
  SA60_CUST_TYPE,
  SA60_ACCOUNT_NUMB
FROM
  SA60_record