CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_account_management.{output_table_name} AS (
  WITH
    CREDIT_CARE_ENRLL AS (
    SELECT
      DATE_REGISTERED,
      ACCOUNT_ID
    FROM
      `pcb-{env}-landing.domain_account_management.CC_USER_REGISTERATION` ),
    PCF_CUST_DATA AS (
    SELECT
    DISTINCT PCF_CARD.CARD_NUM AS CARD_NUM
    FROM
    `pcb-{env}-landing.domain_loyalty.PCF_CUST` PCF_CUST,
    `pcb-{env}-curated.domain_loyalty.PCF_CARD` PCF_CARD
    WHERE
    PCF_CUST.PCF_CUST_ID = PCF_CARD.PCF_CUST_ID
    AND PCF_CUST.PCPLUS_OPTIN_DATE IS NOT NULL ),
    CONSTANTS AS (
    SELECT
      MAX(CASE
          WHEN field_name = 'SA88_STMT_CAT_1' THEN constant_value
      END
        ) AS SA88_STMT_CAT_1,
      MAX(CASE
          WHEN field_name = 'SA88_STMT_CAT_2' THEN constant_value
      END
        ) AS SA88_STMT_CAT_2,
      MAX(CASE
          WHEN field_name = 'SA88_STMT_CAT_6' THEN constant_value
      END
        ) AS SA88_STMT_CAT_6,
      MAX(CASE
          WHEN field_name = 'SA88_CRED_AVAIL' THEN constant_value
      END
        ) AS SA88_CRED_AVAIL,
      MAX(CASE
          WHEN field_name = 'SA88_REPRICE_DATE' THEN constant_value
      END
        ) AS SA88_REPRICE_DATE
    FROM
      `pcb-{env}-landing.domain_account_management.STMT_VI70_CONSTANT_REF`
    WHERE
      interface_id = 'VI70' )
  SELECT
    SA10_CLIENT_NUM AS SA88_CLIENT_NUM,
    sa10.SA10_ACCT_ID AS SA88_ACCT_ID,
    SA10.FILE_CREATE_DT,
    'SA88' AS SA88_RECORD_ID,
    12 AS SA88_SEQ_NUM,
    SA10_KEY_STMT_FORM AS KEY_STMT_FORM,
    SA10_KEY_INSRT_GRP AS KEY_INSRT_GRP,
    IFNULL(SA88_PURCHASE_AMT.AMT_CTD, 0) + SA10.SA10_MISC_DEBITS AS SA88_PURCHASES,
    IFNULL(SA88_CASH_ADV_AMT.AMT_CTD, 0) AS SA88_CASH_ADVANCES,
    IFNULL(SA88_CONV_CHEQUES_AMT.AMT_CTD, 0) AS SA88_CONV_CHEQUES,
    IFNULL(SA88_PROM_PURCHASES_AMT.AMT_CTD, 0) AS SA88_PROM_PURCHASES,
    IFNULL(SA88_FEE_AMT.AMT_CTD, 0) AS SA88_FEES,
    IFNULL(SA88_OTHER_CHARGES_AMT.AMT_CTD, 0) AS SA88_OTHER_CHARGES,
    IFNULL(PC_PTS.PC_POINTS, 0) AS SA88_PC_POINTS,
    0 AS SA88_PC_BONUS_POINTS,
    IFNULL((PC_PTS.PC_BONUS_POINTS + IFNULL(PC_PTS.PC_POINTS,0)),0) AS SA88_PC_TOTAL_POINTS,
    CAST(ROUND(0, 2) AS NUMERIC) AS SA88_POINTS_BALANCE,
    NULL AS SA88_SALUTATION,
    NULL AS SA88_GENDER,
    (CASE
      WHEN PCF_CUST_DATA.CARD_NUM IS NOT NULL THEN 'Y'
      ELSE 'N'
    END
    ) AS SA88_LYLTY_PLUS_CODE,
    (CASE
      WHEN CREDIT_CARE_ENRLL.DATE_REGISTERED IS NOT NULL AND CREDIT_CARE_ENRLL.ACCOUNT_ID=SA10.SA10_ACCT_ID THEN 'Y'
      ELSE 'N'
  END
    ) AS SA88_CREDIT_CARE_ENRLL,
  CAST(ROUND(0, 2) AS NUMERIC) AS SA88_SPEND_BUCKET,
  NULL AS SA88_NOTIFICATION_AREA,
  NULL AS SA88_INSERTS,
  SUBSTR( sa20.SA20_NAME_1, CAST(sa20.SA20_POS_FIRST_NAME AS INT64), CAST(( sa20.SA20_POS_MIDDLE_NAME - sa20.SA20_POS_FIRST_NAME ) AS INT64) ) AS SA88_FIRST_NAME,
  SUBSTR( sa20.SA20_NAME_1, CAST(sa20.SA20_POS_MIDDLE_NAME AS INT64), CAST(( GREATEST(sa20.SA20_POS_LAST_NAME - sa20.SA20_POS_MIDDLE_NAME , 0))AS INT64) ) AS SA88_MIDDLE_INIT,
  SUBSTR ( sa20.SA20_NAME_1, CAST(sa20.SA20_POS_LAST_NAME AS INT64), CAST(( GREATEST(LENGTH(sa20.SA20_NAME_1) - sa20.SA20_POS_LAST_NAME + 1, 0) )AS INT64) ) AS SA88_LAST_NAME,
  CASE
    WHEN SA10.SA10_CLIENT_PROD_CODE = CONSTANTS.SA88_CRED_AVAIL THEN SA10_MONEY_AVAILABLE
    ELSE SA10_CRED_AVAIL
END
  AS SA88_CRED_AVAIL,
  sa20.SA20_JUNK_MAIL_FLAG AS SA88_DNS_CODE,
  (
    CASE
      WHEN IFNULL(SA59_CUST_TYPE_2.AUTH_USER_CODE, 0) >= 1 THEN 'Y'
      ELSE 'N'
  END
    ) AS SA88_AUTH_USER_CODE,
  IFNULL(SA60_TTL_AMT_TRANS.TTL_AMT_TRANS, 0) AS SA88_IN_STORE_PURCHASE_AMT,
  (
    CASE
      WHEN SUBSTR (SA10_CUST_DATA_80, 1, 1) = 'E' THEN 'E'
      ELSE NULL
  END
    ) AS SA88_PAYMENT_METHOD,
  FORMAT_DATE( '%m%d%Y', DATE_SUB( PARSE_DATE('%m%d%Y', SA10_STMT_START_DATE), INTERVAL 1 DAY ) ) AS SA88_PREV_STMT_DATE,
  (
    CASE
      WHEN ( IFNULL(SA88_SUB_TOTAL_IND.COUNT_ACCT_NUM, 0) > 1 OR IFNULL(SA59_CUST_TYPE_2.AUTH_USER_CODE, 0) >= 1 ) THEN 'Y'
      ELSE 'N'
  END
    ) AS SA88_SUB_TOTAL_IND,
  (
    CASE
      WHEN LENGTH(SA10_STC_CHARGEOFF) > 0 THEN 'Y'
      ELSE 'N'
  END
    ) || '~' || (
    CASE
      WHEN LENGTH(SA10_STC_SEC_FRAUD) > 0 THEN 'Y'
      ELSE 'N'
  END
    ) AS SA88_PRSNT_CRTRIA,
  'DST' AS SA88_SOURCE,
  FORMAT_DATE('%m%d%Y', DATE_ADD(PARSE_DATE('%m%d%Y', SA10_CLOSING_DATE), INTERVAL SAFE_CAST(CONSTANTS.SA88_REPRICE_DATE AS INT64) MONTH)) AS SA88_REPRICE_DATE,
  (
    CASE
      WHEN IFNULL(sa20.SA20_COUNTRY_CODE, 'CAN') IN ('CA', 'CAN') THEN ''
      ELSE sa20.SA20_COUNTRY_NAME
  END
    ) AS SA88_COUNTRY_NAME,
  (
    CASE
      WHEN sa20.SA20_COUNTRY_CODE IN ('CA', 'CAN') THEN 'CAN'
      WHEN sa20.SA20_COUNTRY_CODE IN ('US',
      'USA') THEN 'USA'
      ELSE 'INT'
  END
    ) AS SA88_COUNTRY_CODE,
  (
    CASE
      WHEN sa10.SA10_LANG_CODE_BEG_CY <> 'FRC' AND ( sa85.SA85_RPAY_FAIL_FLAG = '' OR sa85.SA85_RPAY_FAIL_FLAG IS NULL ) THEN 1
      WHEN sa10.SA10_LANG_CODE_BEG_CY = 'FRC'
    AND ( sa85.SA85_RPAY_FAIL_FLAG = ''
      OR sa85.SA85_RPAY_FAIL_FLAG IS NULL ) THEN 2
      WHEN sa10.SA10_LANG_CODE_BEG_CY <> 'FRC' AND ( sa85.SA85_RPAY_FAIL_FLAG <> '' OR sa85.SA85_RPAY_FAIL_FLAG IS NOT NULL ) AND sa85.SA85_RPAY_FAIL_FLAG <> 'Z' THEN 3
      WHEN sa10.SA10_LANG_CODE_BEG_CY = 'FRC'
    AND ( sa85.SA85_RPAY_FAIL_FLAG <> ''
      OR sa85.SA85_RPAY_FAIL_FLAG IS NOT NULL )
    AND sa85.SA85_RPAY_FAIL_FLAG <> 'Z' THEN 4
      WHEN sa10.SA10_BAL_CUR = sa10.SA10_STMT_MINPAY OR IFNULL(sa85.SA85_RPAY_FAIL_FLAG, 'X') = 'Z' THEN 5
  END
    ) AS SA88_TTP_IND,
  (CASE
	WHEN SA10_EBPP_STMT_IND = 'N'
      AND( (SA10_ARCHIVAL_ONLY = CONSTANTS.SA88_STMT_CAT_2
           AND ((SA10_CUST_DATA_12 IS NULL OR SA10_CUST_DATA_12 = '')
                OR SA10_CUST_DATA_12=CONSTANTS.SA88_STMT_CAT_1))
      OR (SA10_ARCHIVAL_ONLY = CONSTANTS.SA88_STMT_CAT_6
           AND (SUBSTR(sa10.SA10_CUST_DATA_80, 8, 1)='2'
           AND (SA10_CUST_DATA_12 = '0' OR SA10_CUST_DATA_12 IS NULL OR SA10_CUST_DATA_12 = ''))))
    THEN 'H'
    WHEN SA10_ARCHIVAL_ONLY = CONSTANTS.SA88_STMT_CAT_6
      AND (SA10_EBPP_STMT_IND='Y'
            AND SA10_CUST_DATA_12 <> '0'
            AND SA10_CUST_DATA_12 IS NOT NULL
            AND SA10_CUST_DATA_12 <> ''
            AND (SA10_STC_SEC_FRAUD IS NULL OR SA10_STC_SEC_FRAUD = '')
            AND (SA10_STC_CHARGEOFF IS NULL OR SA10_STC_CHARGEOFF = '')
            AND SA10_BANKRUPTCY_TYPE = 0)
      OR (SA10_EBPP_STMT_IND = 'N'
            AND SUBSTR(sa10.SA10_CUST_DATA_80, 8, 1) = '2'
            AND SA10_CUST_DATA_12 <> '0'
            AND SA10_CUST_DATA_12 <> ''
            AND SA10_CUST_DATA_12 IS NOT NULL)
    THEN 'A'
    WHEN SA10_ARCHIVAL_ONLY = CONSTANTS.SA88_STMT_CAT_2
      AND SA10_EBPP_STMT_IND = 'N'
      AND SA10_CUST_DATA_12 <> '0'
      AND SA10_CUST_DATA_12 IS NOT NULL
      AND SA10_CUST_DATA_12 <> ''
    THEN 'A'
    WHEN SA10_EBPP_STMT_IND = 'Y'
      AND(
       ( SA10_ARCHIVAL_ONLY = CONSTANTS.SA88_STMT_CAT_6
         AND(
              ((SA10_STC_SEC_FRAUD IS NULL OR SA10_STC_SEC_FRAUD = '')
                AND (SA10_STC_CHARGEOFF IS NULL OR SA10_STC_CHARGEOFF = '')
                AND SA10_BANKRUPTCY_TYPE = 0
                AND SA10_BAL_CUR <> 0
              )
              OR SUBSTR(sa10.SA10_CUST_DATA_80, 8, 1) = '2'
            )
         )
       OR SA10_ARCHIVAL_ONLY = CONSTANTS.SA88_STMT_CAT_2
      )
    THEN 'E'
    WHEN SA10_ARCHIVAL_ONLY = CONSTANTS.SA88_STMT_CAT_6
    THEN 'D'
    ELSE ' '
  END
    ) AS SA88_STMT_CAT,
  SUBSTR(sa10.SA10_CUST_DATA_80, 1, 1) AS SA88_CDF_80_1,
  SUBSTR(sa10.SA10_CUST_DATA_80, 2, 1) AS SA88_CDF_80_2,
  SUBSTR(sa10.SA10_CUST_DATA_80, 3, 1) AS SA88_CDF_80_3,
  SUBSTR(sa10.SA10_CUST_DATA_80, 4, 1) AS SA88_CDF_80_4,
  SUBSTR(sa10.SA10_CUST_DATA_80, 5, 1) AS SA88_CDF_80_5,
  SUBSTR(sa10.SA10_CUST_DATA_80, 6, 1) AS SA88_CDF_80_6,
  SUBSTR(sa10.SA10_CUST_DATA_80, 7, 1) AS SA88_CDF_80_7,
  SUBSTR(sa10.SA10_CUST_DATA_80, 8, 1) AS SA88_CDF_80_8,
  IFNULL(SA88_TOTAL_DEPOSITS.TTL_DEPOSITS, 0) AS SA88_TOTAL_DEPOSITS,
  IFNULL(SA88_TOTAL_WITHDRAWALS.TTL_WITHDRAWALS, 0) AS SA88_TOTAL_WITHDRAWALS,
  SA10.PARENT_CARD_NUM AS PARENT_CARD_NUM
FROM
  `pcb-{env}-landing.domain_account_management.SA10` SA10
LEFT JOIN
  `pcb-{env}-landing.domain_account_management.SA30` sa30
ON
  SA10.SA10_ACCT_ID = sa30.SA30_acct_id
  AND SA10.PARENT_CARD_NUM = sa30.PARENT_CARD_NUM
  AND SA10.FILE_CREATE_DT = sa30.FILE_CREATE_DT
  AND SA10.FILE_NAME = sa30.FILE_NAME
LEFT JOIN
  `pcb-{env}-landing.domain_account_management.SA20` sa20
ON
  sa10.SA10_acct_id = sa20.SA20_acct_id
  AND sa10.PARENT_CARD_NUM = sa20.PARENT_CARD_NUM
  AND SA10.FILE_CREATE_DT = sa20.FILE_CREATE_DT
  AND SA10.FILE_NAME = sa20.FILE_NAME
LEFT JOIN
  `pcb-{env}-landing.domain_account_management.SA85` sa85
ON
  sa10.SA10_acct_id = sa85.SA85_acct_id
  AND sa10.PARENT_CARD_NUM = sa85.PARENT_CARD_NUM
  AND SA10.FILE_CREATE_DT = sa85.FILE_CREATE_DT
  AND SA10.FILE_NAME = sa85.FILE_NAME
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_SUB_TOTAL_IND_DBEXT AS SA88_SUB_TOTAL_IND
ON
  sa10.SA10_acct_id = SA88_SUB_TOTAL_IND.SA59_acct_id
  AND sa10.PARENT_CARD_NUM = SA88_SUB_TOTAL_IND.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA60_TTL_AMT_TRANS_DBEXT AS SA60_TTL_AMT_TRANS
ON
  SA10.SA10_ACCT_ID = SA60_TTL_AMT_TRANS.SA60_ACCT_ID
  AND sa10.PARENT_CARD_NUM = SA60_TTL_AMT_TRANS.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA59_CUST_TYPE_2_DBEXT AS SA59_CUST_TYPE_2
ON
  SA10.SA10_ACCT_ID = SA59_CUST_TYPE_2.SA59_ACCT_ID
  AND sa10.PARENT_CARD_NUM = SA59_CUST_TYPE_2.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA59_NUMB_DBEXT AS SA59_NUMB
ON
  SA10.sa10_ACCT_ID = SA59_NUMB.ACCT_ID
  AND sa10.PARENT_CARD_NUM = SA59_NUMB.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_PURCHASE_AMT_DBEXT AS SA88_PURCHASE_AMT
ON
  SA10.SA10_ACCT_ID = SA88_PURCHASE_AMT.ACCOUNT_ID
  AND SA10.PARENT_CARD_NUM = SA88_PURCHASE_AMT.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_CASH_ADV_AMT_DBEXT AS SA88_CASH_ADV_AMT
ON
  SA10.SA10_ACCT_ID = SA88_CASH_ADV_AMT.ACCOUNT_ID
  AND SA10.PARENT_CARD_NUM = SA88_CASH_ADV_AMT.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_CONV_CHEQUES_AMT_DBEXT AS SA88_CONV_CHEQUES_AMT
ON
  SA10.SA10_ACCT_ID = SA88_CONV_CHEQUES_AMT.ACCOUNT_ID
  AND SA10.PARENT_CARD_NUM = SA88_CONV_CHEQUES_AMT.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_PROM_PURCHASES_AMT_DBEXT AS SA88_PROM_PURCHASES_AMT
ON
  SA10.SA10_ACCT_ID = SA88_PROM_PURCHASES_AMT.ACCOUNT_ID
  AND SA10.PARENT_CARD_NUM = SA88_PROM_PURCHASES_AMT.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_FEE_AMT_DBEXT AS SA88_FEE_AMT
ON
  SA10.SA10_ACCT_ID = SA88_FEE_AMT.ACCOUNT_ID
  AND SA10.PARENT_CARD_NUM = SA88_FEE_AMT.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_OTHER_CHARGES_AMT_DBEXT AS SA88_OTHER_CHARGES_AMT
ON
  SA10.SA10_ACCT_ID = SA88_OTHER_CHARGES_AMT.ACCOUNT_ID
  AND SA10.PARENT_CARD_NUM = SA88_OTHER_CHARGES_AMT.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.PC_PTS_DBEXT AS PC_PTS
ON
  SA10.SA10_ACCT_ID = PC_PTS.SA60_ACCT_ID
  AND SA10.PARENT_CARD_NUM = PC_PTS.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_TOTAL_DEPOSITS_DBEXT AS SA88_TOTAL_DEPOSITS
ON
  SA10.SA10_ACCT_ID = SA88_TOTAL_DEPOSITS.SA60_ACCT_ID
  AND SA10.PARENT_CARD_NUM = SA88_TOTAL_DEPOSITS.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.SA88_TOTAL_WITHDRAWALS_DBEXT AS SA88_TOTAL_WITHDRAWALS
ON
  SA10.SA10_ACCT_ID = SA88_TOTAL_WITHDRAWALS.SA60_ACCT_ID
  AND SA10.PARENT_CARD_NUM = SA88_TOTAL_WITHDRAWALS.PARENT_CARD_NUM
LEFT JOIN
  pcb-{env}-processing.domain_account_management.BILLING_CYCLE_DBEXT AS BILLING_CYCLE
ON
  SA10.SA10_ACCT_ID = BILLING_CYCLE.SA10_ACCT_ID
  AND SA10.PARENT_CARD_NUM = BILLING_CYCLE.PARENT_CARD_NUM
LEFT JOIN
  CREDIT_CARE_ENRLL
ON
  SA10.SA10_ACCT_ID = CREDIT_CARE_ENRLL.ACCOUNT_ID
LEFT JOIN
 PCF_CUST_DATA
ON
  SA10.PARENT_CARD_NUM = PCF_CUST_DATA.CARD_NUM
CROSS JOIN
  CONSTANTS
WHERE
  sa10.SA10_CLIENT_PROD_CODE <> 'PDG'
  AND sa10.file_create_dt='{file_create_dt}'
  AND SA10.FILE_NAME = '{file_name}')