CREATE TABLE IF NOT EXISTS
  `pcb-{env}-landing.domain_account_management.STMT_IDX_REJECTS` (
    ACCOUNT_NUMBER STRING,
    STATEMENT_DATE STRING,
    CYCLE_DATE STRING,
    REJECT_REASON STRING,
    REC_LOAD_TIMESTAMP DATETIME,
    SOURCE_FILENAME STRING
  );

INSERT INTO
  `pcb-{env}-landing.domain_account_management.STMT_IDX_REJECTS`
SELECT
  DISTINCT
  IDX.ACCOUNT_NUMBER,
  IDX.STATEMENT_DATE,
  IDX.CYCLE_DATE,
  'Card not available in CIF_CARD_XREF' AS REJECT_REASON,
  IDX.REC_LOAD_TIMESTAMP,
  SOURCE_FILENAME
FROM
  `pcb-{env}-landing.domain_account_management.STMT_IDX_RAW_DATA` IDX
LEFT JOIN
  `pcb-{env}-curated.domain_account_management.CIF_CARD_XREF` XREF
ON
  IDX.ACCOUNT_NUMBER = XREF.CIFP_ACCOUNT_NUM
  AND IDX.SOURCE_FILENAME='{file_name}'
WHERE
  XREF.CIFP_ACCOUNT_NUM IS NULL