CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_account_management.STMT_AVAIL_DATA_BODY
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) ) AS
SELECT
  DISTINCT
  " " AS CYCLE_INDICATOR,
  DB.CYCLE_DATE AS END_DATE,
  XREF.CIFP_ACCOUNT_ID6 AS ACCOUNT_ID,
  CRAWFORD_AFF_FILE_NAME,
  " " AS PAYMENT_DUE_AMOUNT,
  " " AS PAYMENT_DUE_DATE,
  " " AS CURRENT_BALANCE,
  " " AS DEBIT_CREDIT_INDICATOR,
  RPAD(SUBSTR(CONCAT(COALESCE(TRIM(DB.FIRST_NAME), ''), ' ', COALESCE(TRIM(DB.LAST_NAME), '')), 1, 36), 36, ' ') AS CUSTOMER_NAME,
  'STMT00' AS DOCUMENT_TYPE,
  CONCAT( "        |", CAST(DB.CYCLE_DATE AS STRING), "|", LPAD(CAST(COALESCE(XREF.CIFP_ACCOUNT_ID6, 0) AS STRING), 12, '0'), "|", "             |", "        |", "             |", " |", RPAD(SUBSTR(CONCAT(COALESCE(TRIM(DB.FIRST_NAME), ''), ' ', COALESCE(TRIM(DB.LAST_NAME), '')), 1, 36), 36, ' '), "|", 'STMT00' ) AS RECORD
FROM
  pcb-{env}-processing.domain_account_management.STMT_IDX_DATA_EXT AS DB
INNER JOIN
  pcb-{env}-landing.domain_account_management.CIF_CARD_XREF AS XREF
ON
  DB.ACCOUNT_NUMBER = XREF.CIFP_ACCOUNT_NUM
