CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_account_management.STMT_AVAIL_DATA_HEDR
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
SELECT
  PARSE_DATE('%Y%m%d',SUBSTR(FILE_IDENTIFIER,1,8)) AS FILE_CREATE_DATE,
  CONCAT("HEADER|", FILE_IDENTIFIER, "|", CAST(RECORD_COUNT AS STRING)) AS RECORD
FROM
(
SELECT
  COUNT(*) AS RECORD_COUNT,
  SUBSTR(CRAWFORD_AFF_FILE_NAME, 1, 9) AS FILE_IDENTIFIER
FROM
  `pcb-{env}-processing.domain_account_management.STMT_AVAIL_DATA_BODY`
GROUP BY
  2
)
