CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_account_management.STMT_IDX_DATA_EXT
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) ) AS
SELECT
  DISTINCT
  IDX.ACCOUNT_NUMBER,
  IDX.STATEMENT_DATE,
  IDX.CYCLE_DATE,
  IDX.FIRST_NAME,
  IDX.LAST_NAME,
  CRAWFORD_AFF_FILE_NAME,
  IDX.REC_LOAD_TIMESTAMP,
  SOURCE_FILENAME
FROM
  `pcb-{env}-landing.domain_account_management.STMT_IDX_RAW_DATA` IDX
LEFT JOIN
  `pcb-{env}-curated.domain_account_management.CIF_CARD_XREF` XREF
ON
  IDX.ACCOUNT_NUMBER = XREF.CIFP_ACCOUNT_NUM
  AND IDX.SOURCE_FILENAME='{file_name}'
WHERE
  XREF.CIFP_ACCOUNT_NUM IS NOT NULL