WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_AIRLINE_DATA_EXT`
  WHERE
    at41_extra_type IN (3) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) as AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_AD1_PASSENGER_NAME,
  AT41_AD1_DEPARTURE_DATE,
  AT41_AD1_TRAVEL_AGENCY_CODE,
  AT41_AD1_TRAVEL_AGENCY_NAME,
  AT41_AD1_TICKET_NUMBER,
  AT41_AD1_CARRIER_CODE_1,
  AT41_AD1_SVC_CLASS_CODE_1,
  AT41_AD1_STOP_OVER_CODE_1,
  AT41_AD1_DEST_AIRPORT_CODE_1,
  AT41_AD1_FARE_BASIS_CODE_1,
  AT41_AD1_ORIG_AIRPORT_CODE_1,
  AT41_AD1_CARRIER_CODE_2,
  AT41_AD1_SVC_CLASS_CODE_2,
  AT41_AD1_STOP_OVER_CODE_2,
  AT41_AD1_DEST_AIRPORT_CODE_2,
  AT41_AD1_FARE_BASIS_CODE_2,
  AT41_AD1_ORIG_AIRPORT_CODE_2,
  AT41_AD1_CARRIER_CODE_3,
  AT41_AD1_SVC_CLASS_CODE_3,
  AT41_AD1_STOP_OVER_CODE_3,
  AT41_AD1_DEST_AIRPORT_CODE_3,
  AT41_AD1_FARE_BASIS_CODE_3,
  AT41_AD1_ORIG_AIRPORT_CODE_3,
  AT41_AD1_CARRIER_CODE_4,
  AT41_AD1_SVC_CLASS_CODE_4,
  AT41_AD1_STOP_OVER_CODE_4,
  AT41_AD1_DEST_AIRPORT_CODE_4,
  AT41_AD1_FARE_BASIS_CODE_4,
  AT41_AD1_ORIG_AIRPORT_CODE_4,
  AT41_AD1_RESTRICTED_TICKET_IND,
  AT41_ISSUING_CARRIER,
  AT41_AD1_CRED_REASON_IND,
  AT41_AD1_TICK_CHANGE_IND,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)