WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_COMMON_INFO_EXT`
  WHERE
    at41_extra_type IN (1) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) AS AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_COMMON_CNCY_MARKUP_AMT,
  AT41_COMMON_ISSUER_FEE_AMT,
  AT41_COMMON_ISA_AMT_FOR_LCA,
  AT41_COMMON_X_BORDER,
  AT41_COMMON_X_BORDER_FEE_IND,
  AT41_COMMON_INTRCHG_FEE_AMT,
  AT41_COMMON_SAFE_CAT,
  AT41_FRGN_FEE_TYPE,
  AT41_MERCH_TERMINAL_ID,
  AT41_COMMON_PROG_PART_IND,
  AT41_VIRTUAL_CARD_NUMBER,
  AT41_SURCHARGE_AMT,
  AT41_SURCHARGE_AMT_CDHLDR_CUR,
  AT41_SURCHARGE_DC_IND,
  AT41_PROMO_ID,
  AT41_COMMON_VCN_ASSURANCE_LVL,
  AT41_COMMON_VCN_REQUESTOR_ID,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)