WITH AT00 AS (
  SELECT 
    MAST_ACCOUNT_ID, 
    AT00_CLIENT_NUM, 
    AT00_APPLICATION_NUM, 
    AT00_APPLICATION_SUFFIX 
  FROM 
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT`
), 
AT21 AS (
  SELECT 
    MAST_ACCOUNT_ID, 
    AT00_APPLICATION_SUFFIX, 
    AT21_CDATE_STMT_BEG 
  FROM 
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT`
), 
AT31 AS (
  SELECT 
    * 
  FROM 
    `pcb-{env}-processing.domain_account_management.accttx_AT31_REC_EXT`
) 
SELECT 
  MAST_ACCOUNT_ID, 
  MAST_REC_TYPE, 
  AT00_CLIENT_NUM, 
  AT00_APPLICATION_NUM, 
  AT00_APPLICATION_SUFFIX, 
  AT21_CDATE_STMT_BEG, 
  AT31.* EXCEPT (MAST_ACCOUNT_ID, MAST_REC_TYPE, AT00_APPLICATION_SUFFIX) 
FROM 
  AT31 
  INNER JOIN AT21 USING (MAST_ACCOUNT_ID, AT00_APPLICATION_SUFFIX) 
  INNER JOIN AT00 USING (MAST_ACCOUNT_ID, AT00_APPLICATION_SUFFIX)
