WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_REAGE_EXT`
  WHERE
    at41_extra_type IN (2) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) AS AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_PASTDUE_SNAPSHOT_1,
  AT41_PASTDUE_SNAPSHOT_2,
  AT41_PASTDUE_SNAPSHOT_3,
  AT41_PASTDUE_SNAPSHOT_4,
  AT41_PASTDUE_SNAPSHOT_5,
  AT41_PASTDUE_SNAPSHOT_6,
  AT41_PASTDUE_SNAPSHOT_7,
  AT41_PASTDUE_SNAPSHOT_8,
  AT41_PASTDUE_SNAPSHOT_9,
  AT41_PASTDUE_SNAPSHOT_10,
  AT41_PASTDUE_SNAPSHOT_11,
  AT41_PASTDUE_SNAPSHOT_12,
  PARSE_NUMERIC(AT41_REAGE_RECENCY) AS AT41_REAGE_RECENCY,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)