WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_AWARD_INFO_EXT`
  WHERE
    at41_extra_type IN (15,
      16,
      17) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) AS AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_AWARD_OPT_ID_1,
  AT41_AWARD_SEGMENT_ID_1,
  AT41_AWARD_ELEMENT_ID_1,
  AT41_AWARD_EARNED_AMT_1,
  AT41_AWARD_OPT_ID_2,
  AT41_AWARD_SEGMENT_ID_2,
  AT41_AWARD_ELEMENT_ID_2,
  AT41_AWARD_EARNED_AMT_2,
  AT41_AWARD_OPT_ID_3,
  AT41_AWARD_SEGMENT_ID_3,
  AT41_AWARD_ELEMENT_ID_3,
  AT41_AWARD_EARNED_AMT_3,
  AT41_AWARD_OPT_ID_4,
  AT41_AWARD_SEGMENT_ID_4,
  AT41_AWARD_ELEMENT_ID_4,
  AT41_AWARD_EARNED_AMT_4,
  AT41_AWARD_OPT_ID_5,
  AT41_AWARD_SEGMENT_ID_5,
  AT41_AWARD_ELEMENT_ID_5,
  AT41_AWARD_EARNED_AMT_5,
  AT41_AWARD_OPT_ID_6,
  AT41_AWARD_SEGMENT_ID_6,
  AT41_AWARD_ELEMENT_ID_6,
  AT41_AWARD_EARNED_AMT_6,
  AT41_AWARD_OPT_ID_7,
  AT41_AWARD_SEGMENT_ID_7,
  AT41_AWARD_ELEMENT_ID_7,
  AT41_AWARD_EARNED_AMT_7,
  AT41_AWARD_OPT_ID_8,
  AT41_AWARD_SEGMENT_ID_8,
  AT41_AWARD_ELEMENT_ID_8,
  AT41_AWARD_EARNED_AMT_8,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)