WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_MC_RENTAL_EXT`
  WHERE
    at41_extra_type IN (8) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) AS AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_MCR_RENTAL_AGREEMENT_NBR,
  AT41_MCR_ICA_ACQUIRER,
  AT41_MCR_RATE_DAILY,
  AT41_MCR_PROGRAM_CODE,
  AT41_MCR_BILLING_ADJ_IND,
  AT41_MCR_AMT_ADJUSTMENT,
  AT41_MCR_RENTER_NAME,
  AT41_MCR_CITY,
  AT41_MCR_STATE_CTRY_CODE,
  AT41_MCR_DATE_RENTAL_RETURN,
  AT41_MCR_RATE_PER_MILE,
  AT41_MCR_TOTAL_MILES,
  AT41_MCR_MAX_FREE_MILES,
  AT41_MCR_RETURN_LOCATION_ID,
  AT41_MCR_RENT_CLASS,
  AT41_MCR_PHONE_CUST_SERVICE,
  AT41_MCR_INSURANCE_INDICATOR,
  AT41_MCR_AMT_INSURANCE,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)