WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_OUTSTAND_DIST_EXT`
  WHERE
    at41_extra_type IN (20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      70,
      71,
      72,
      73,
      74,
      76,
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88,
      89) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) AS AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_CATEGORY_APPLIED_1,
  AT41_OUTSTANDING_TYPE_1,
  AT41_AMOUNT_DIST_1,
  AT41_CATEGORY_APPLIED_2,
  AT41_OUTSTANDING_TYPE_2,
  AT41_AMOUNT_DIST_2,
  AT41_CATEGORY_APPLIED_3,
  AT41_OUTSTANDING_TYPE_3,
  AT41_AMOUNT_DIST_3,
  AT41_CATEGORY_APPLIED_4,
  AT41_OUTSTANDING_TYPE_4,
  AT41_AMOUNT_DIST_4,
  AT41_CATEGORY_APPLIED_5,
  AT41_OUTSTANDING_TYPE_5,
  AT41_AMOUNT_DIST_5,
  AT41_CATEGORY_APPLIED_6,
  AT41_OUTSTANDING_TYPE_6,
  AT41_AMOUNT_DIST_6,
  AT41_CATEGORY_APPLIED_7,
  AT41_OUTSTANDING_TYPE_7,
  AT41_AMOUNT_DIST_7,
  AT41_CATEGORY_APPLIED_8,
  AT41_OUTSTANDING_TYPE_8,
  AT41_AMOUNT_DIST_8,
  AT41_MINDUE_SNAPSHOT,
  IFNULL(AT41_STMT_MIN_PAYMENT_APPLIED, 0) AS AT41_STMT_MIN_PAYMENT_APPLIED,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)