WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_MC_LODGE_EXT`
  WHERE
    at41_extra_type IN (7) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) AS AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_MCL_FOLIO_NBR,
  AT41_MCL_ICA_ACQUIRER,
  AT41_MCL_RATE_DAILY,
  AT41_MCL_PROGRAM_CODE,
  AT41_MCL_BILLING_ADJ_IND,
  AT41_MCL_AMT_ADJUSTMENT,
  AT41_MCL_PHONE_CUST_SERVICE,
  SAFE.PARSE_DATETIME('%Y%j' ,LPAD(CAST(AT41_MCL_DATE_ARRIVAL AS STRING), 7, '0')) AS AT41_MCL_DATE_ARRIVAL,
  SAFE.PARSE_DATETIME('%Y%j' ,LPAD(CAST(AT41_MCL_DATE_DEPARTURE AS STRING), 7, '0')) AS AT41_MCL_DATE_DEPARTURE,
  AT41_MCL_AMT_ROOM_TAX,
  AT41_MCL_PHONE_PROPERTY,
  AT41_MCL_OTHER_SERVICE_CODE,
  AT41_MCL_AMT_OTHER_SERVICE,
  AT41_MCL_AMT_FOOD_CHGS,
  AT41_MCL_AMT_BAR_CHGS,
  AT41_MCL_AMT_PHONE_CHGS,
  AT41_MCL_AMT_GIFT_SHOP_CHGS,
  AT41_MCL_AMT_LAUNDRY_CHGS,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)