WITH
  AT00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_CLIENT_NUM,
    AT00_APPLICATION_NUM,
    AT00_APPLICATION_SUFFIX
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT00_REC_EXT` ),
  AT21 AS (
  SELECT
    MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX,
    AT21_CDATE_STMT_BEG
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT21_REC_EXT` ),
  AT41 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.accttx_AT41_EUROPAY_EXT`
  WHERE
    at41_extra_type IN (58) )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AT00.AT00_CLIENT_NUM,
  AT00.AT00_APPLICATION_NUM,
  AT00_APPLICATION_SUFFIX,
  AT21.AT21_CDATE_STMT_BEG,
  CAST(AT31_DATE_POST AS DATETIME) AS AT31_DATE_POST,
  AT31_TIME_POST,
  AT41_SEGMENT_LENGTH,
  AT41_EXTRA_TYPE,
  AT41_ACCT_TRAN_EXTRA_DATA,
  AT41_EUROPAY_PROC_CODE,
  NULL AS AT41_EUROPAY_AMT_TRAN,
  AT41_EUROPAY_POS_DATA_CODE,
  AT41_EUROPAY_ACQ_INST_ID,
  AT41_EUROPAY_FORWD_INST_ID,
  NULL AS AT41_EUROPAY_AMOUNT_FEE,
  NULL AS AT41_EUROPAY_CONV_RATE_FEE,
  NULL AS AT41_EUROPAY_CNCY_CODE_TRAN,
  AT41_EUROPAY_REC_INST_ID,
  CAST(NULL AS STRING) AS AT41_EUROPAY_TRAN_TYPE,
  AT41_EUROPAY_CARD_SEQ_NUM,
  IF(AT41_EUROPAY_TRAN_TIME=0, NULL, FORMAT('%s:%s:%s',
    SUBSTR(LPAD(CAST(AT41_EUROPAY_TRAN_TIME AS STRING), 6, '0'), 1, 2),
    SUBSTR(LPAD(CAST(AT41_EUROPAY_TRAN_TIME AS STRING), 6, '0'), 3, 2),
    SUBSTR(LPAD(CAST(AT41_EUROPAY_TRAN_TIME AS STRING), 6, '0'), 5, 2)))
  AS AT41_EUROPAY_TRAN_TIME,
  NULL AS AT41_EUROPAY_SYS_TRACE_AUD_NUM,
  AT41_EUROPAY_TRAN_TRACE_ID,
  NULL AS AT41_EUROPAY_AMT_CARDHLDR,
  NULL AS AT41_EUROPAY_AMT_EURO,
  CAST(NULL AS STRING) AS AT41_EUROPAY_EURO_CNCY_CODE,
  CAST(NULL AS STRING) AS AT41_EUROPAY_TRAN_FEE_RULE,
  AT41_EUROPAY_FNCT_CODE,
  AT41_NEW_EUROPAY_CONV_RATE_REC,
  AT41_EUROPAY_BUS_ACTIVITY_FLD,
  AT41_MC_AUTH_ECSI,
  AT41_MC_RETRIEVAL_REF_NUM,
  AT41_MC_ADDR_VERI_RESP_CODE,
  AT41_MC_UCAF_STATUS_DATA,
  AT41_MC_ASSIGN_ID,
  AT41_MC_PROG_REG_ID,
  AT41_MC_PMT_TRANS_INIT,
  AT41_TRANSIT_TYPE_IND,
  AT41_TRANSPORT_MODE_IND,
  AT41_MC_MERCHANT_ID,
  AT41_MC_IND_SALES_ORG_ID,
  AT41_MC_REASON_CODE,
  AT41_MC_PMT_FACILITATOR_ID,
  AT41_MC_SUB_MERCHANT_ID,
  FILE_CREATE_DT
FROM
  AT41
INNER JOIN
  AT21
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)
INNER JOIN
  AT00
USING
  (MAST_ACCOUNT_ID,
    AT00_APPLICATION_SUFFIX)