SELECT
  SA59.*,
  SA10_BILLING_CYCLE AS SA59_BILLING_CYCLE,
  SA60.SA59_DEVICE_TYPE AS SA59_DEVICE_TYPE,
  'N' AS SA59_PROC_IND,
  '0' AS SA59_PAYMENT_TRANSSUM_IND,
  CAST(NULL AS NUMERIC) AS SA59_SUB_TOTAL
FROM
  `pcb-{env}-processing.domain_account_management.SA59{file_type}_DBEXT_COLUMN_TF` AS SA59
INNER JOIN (
  SELECT
    MAX(SA60_ACC_METHOD_TYPE_CD_CURR) AS SA59_DEVICE_TYPE,
    SA60_ACCOUNT_NUMB_ORIG
  FROM
    `pcb-{env}-processing.domain_account_management.SA60{file_type}_DBEXT_COLUMN_TF`
  GROUP BY
    SA60_ACCOUNT_NUMB_ORIG )AS SA60
ON
  SA59.SA59_ACCOUNT_NUMB = SA60.SA60_ACCOUNT_NUMB_ORIG
INNER JOIN pcb-{env}-processing.domain_account_management.SA10{file_type}_DBEXT_COLUMN_TF AS SA10
ON SA59.PARENT_CARD_NUM = SA10.PARENT_CARD_NUM