CREATE TABLE `pcb-{env}-landing.domain_account_management.SA00`
AS
SELECT
  CAST(CLIENT_NUM AS INTEGER) AS SA00_CLIENT_NUM,
  CAST(ACCT_ID  AS INTEGER) AS SA00_ACCT_ID,
  RECORD_ID AS SA00_RECORD_ID,
  CAST(SEQ_NUM AS INTEGER) AS SA00_SEQ_NUM,
  KEY_STMT_FORM AS SA00_KEY_STMT_FORM,
  KEY_INSRT_GRP AS SA00_KEY_INSRT_GRP,
  CAST(PROCESS_DATE AS STRING) AS SA00_PROCESS_DATE,
  RUN_DATE AS SA00_RUN_DATE,
  RUN_TIME AS SA00_RUN_TIME,
  RUN_DAY_OF_WEEK AS SA00_RUN_DAY_OF_WEEK,
  CLIENT_NAME AS SA00_CLIENT_NAME,
  CAST(FILE_SEQ_NBR AS INTEGER) AS SA00_FILE_SEQ_NBR,
  CURRENT_DATE('America/Toronto') AS FILE_CREATE_DT,
  '' AS FILE_NAME,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP
FROM `pcb-{env}-landing.domain_account_management.STMT_DAILY`
LIMIT 0;

INSERT INTO `pcb-{env}-landing.domain_account_management.SA00`
SELECT
  CAST(CLIENT_NUM AS INTEGER) AS SA00_CLIENT_NUM,
  CAST(ACCT_ID  AS INTEGER) AS SA00_ACCT_ID,
  RECORD_ID AS SA00_RECORD_ID,
  CAST(SEQ_NUM AS INTEGER) AS SA00_SEQ_NUM,
  KEY_STMT_FORM AS SA00_KEY_STMT_FORM,
  KEY_INSRT_GRP AS SA00_KEY_INSRT_GRP,
  CAST(PROCESS_DATE AS STRING) AS SA00_PROCESS_DATE,
  RUN_DATE AS SA00_RUN_DATE,
  RUN_TIME AS SA00_RUN_TIME,
  RUN_DAY_OF_WEEK AS SA00_RUN_DAY_OF_WEEK,
  CLIENT_NAME AS SA00_CLIENT_NAME,
  CAST(FILE_SEQ_NBR AS INTEGER) AS SA00_FILE_SEQ_NBR,
  CURRENT_DATE('America/Toronto') AS FILE_CREATE_DT,
  '' AS FILE_NAME,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP
FROM `pcb-{env}-landing.domain_account_management.STMT_DAILY`
where RECORD_ID = 'SA00'