SELECT
  sa59.SA59_CLIENT_NUM,
  sa59.SA59_ACCT_ID,
  sa59.SA59_RECORD_ID,
  sa59.SA59_SEQ_NUM,
  sa59.SA59_KEY_STMT_FORM,
  sa59.SA59_KEY_INSRT_GRP,
  sa59.SA59_ACCOUNT_NUMB,
  sa59.SA59_NAME_PRINT,
  sa59.SA59_CUST_TYPE,
  sa59.SA59_CUST_ID,
  NULL AS SA59_POS_FIRST_NAME,
  NULL AS SA59_POS_MIDDLE_NAME,
  NULL AS SA59_POS_LAST_NAME,
  NULL AS SA59_POS_SUFFIX,
  CAST(NULL AS STRING) AS SA59_NAME_PRINT_LEGAL,
  NULL AS SA59_POS_FIRST_NAME_LEGAL,
  NULL AS SA59_POS_MIDDLE_NAME_LEGAL,
  NULL AS SA59_POS_LAST_NAME_LEGAL,
  NULL AS SA59_POS_SUFFIX_LEGAL,
  sa59.PARENT_CARD_NUM,
  sa59.FILE_CREATE_DT,
  sa59.FILE_NAME,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  sa59.SA10_BILLING_CYCLE,
  sa59.SA59_DEVICE_TYPE,
  'Y' AS SA59_PROC_IND,
  '0' AS SA59_PAYMENT_TRANSSUM_IND,
  SA60_SUB_TOT.SA60_AMT_TRANS AS SA59_SUB_TOTAL
FROM `pcb-{env}-processing.domain_account_management.SA59_CALC_MID{file_type}` sa59
LEFT JOIN
(
SELECT SUM(CASE SA60_DEB_CRED_IND
        WHEN 'C' THEN SA60_AMT_TRANS * -1
        WHEN 'D' THEN SA60_AMT_TRANS
        ELSE 0
    END
      ) AS SA60_AMT_TRANS, PARENT_CARD_NUM, SA60_ACCOUNT_NUMB
FROM `pcb-{env}-processing.domain_account_management.SA60_MID{file_type}`
WHERE IFNULL(SA60_PAYMENT_TRANS_INDICATOR,0) <> 1
GROUP BY PARENT_CARD_NUM, SA60_ACCOUNT_NUMB
) SA60_SUB_TOT
ON sa59.PARENT_CARD_NUM = SA60_SUB_TOT.PARENT_CARD_NUM
AND sa59.SA59_ACCOUNT_NUMB = SA60_SUB_TOT.SA60_ACCOUNT_NUMB
WHERE sa59.SA59_PROC_IND  = 'Y'
AND IFNULL(sa59.SA59_PAYMENT_TRANSSUM_IND,'0') <> '1'