WITH SA60 AS
  (SELECT
    SA60.*,
    CASE
      WHEN SA60_TRANS_CODE IN ( SELECT DISTINCT(TRANS_CODE) FROM pcb-{env}-landing.domain_account_management.STMT_HO50_PYMTTRANS_LOOKUP) THEN 1
      ELSE 0
  END
    AS SA60_PAYMENT_TRANS_INDICATOR,
    CASE
      WHEN SA60_TRANS_CODE IN (403, 404) THEN 'N'
      ELSE CAST(NULL AS STRING)
  END
    AS SA60_TRANS_SUM_INDICATOR,
    SA59_CUST_ID AS SA60_CUST_ID,
    SA59_CUST_TYPE AS SA60_CUST_TYPE,
    'N' AS SA60_PROC_IND
  FROM
    `pcb-{env}-processing.domain_account_management.SA60{file_type}_DBEXT_COLUMN_TF` AS SA60
  INNER JOIN
    `pcb-{env}-processing.domain_account_management.SA59{file_type}_DBEXT_COLUMN_TF` AS SA59
  ON
    SA59.SA59_ACCOUNT_NUMB = SA60.SA60_ACCOUNT_NUMB_ORIG
  AND SA59.PARENT_CARD_NUM = SA60.PARENT_CARD_NUM),
  SA60_RANKED AS
  (
    SELECT *, RANK() OVER (PARTITION BY SA60_CUST_ID, SA60_CUST_TYPE, PARENT_CARD_NUM, SA60_ACCT_ID ORDER BY SA60_SEQ_NUM DESC) AS RNK
    from SA60
  ),
  SA60_NEW_ACCT_NUM AS
  (
    SELECT SA60_CUST_ID, SA60_CUST_TYPE, PARENT_CARD_NUM, SA60_ACCT_ID, SA60_ACCOUNT_NUMB FROM SA60_RANKED
    WHERE RNK = 1
  )
  SELECT
    SA60.*
    REPLACE(IF(IFNULL( SA60_PAYMENT_TRANS_INDICATOR, 0) != 1, SA60_NEW_ACCT_NUM.SA60_ACCOUNT_NUMB, SA60.SA60_ACCOUNT_NUMB) AS SA60_ACCOUNT_NUMB)
  FROM
    SA60,
    SA60_NEW_ACCT_NUM
  WHERE SA60.SA60_CUST_ID=SA60_NEW_ACCT_NUM.SA60_CUST_ID
  AND SA60.SA60_CUST_TYPE=SA60_NEW_ACCT_NUM.SA60_CUST_TYPE
  AND SA60.PARENT_CARD_NUM=SA60_NEW_ACCT_NUM.PARENT_CARD_NUM
  AND SA60.SA60_ACCT_ID=SA60_NEW_ACCT_NUM.SA60_ACCT_ID