SELECT
SA59_CLIENT_NUM,
SA59_ACCT_ID,
SA59_RECORD_ID,
0 AS SA59_SEQ_NUM,
SA59_KEY_STMT_FORM,
SA59_KEY_INSRT_GRP,
SA1059.PARENT_CARD_NUM AS SA59_ACCOUNT_NUMB,
CAST(NULL AS STRING) AS SA59_NAME_PRINT,
'0' AS SA59_CUST_TYPE,
NULL AS SA59_CUST_ID,
NULL AS SA59_POS_FIRST_NAME,
NULL AS SA59_POS_MIDDLE_NAME,
NULL AS SA59_POS_LAST_NAME,
NULL AS SA59_POS_SUFFIX,
CAST(NULL AS STRING) AS SA59_NAME_PRINT_LEGAL,
NULL AS SA59_POS_FIRST_NAME_LEGAL,
NULL AS SA59_POS_MIDDLE_NAME_LEGAL,
NULL AS SA59_POS_LAST_NAME_LEGAL,
NULL AS SA59_POS_SUFFIX_LEGAL,
SA1059.PARENT_CARD_NUM,
SA1059.FILE_CREATE_DT,
SA1059.FILE_NAME,
CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
CYCLE_NO,
CAST(NULL AS STRING) AS SA59_DEVICE_TYPE,
  'Y' AS SA59_PROC_IND,
  '1' AS SA59_PAYMENT_TRANSSUM_IND,
  AMT_TRAN_SUM AS SA59_SUB_TOTAL
FROM (
  SELECT
    SA60_ACCT_ID AS SA60_ACCT_ID,
    FILE_CREATE_DT,
    PARENT_CARD_NUM AS PARENT_CARD_NUM,
    SUM(CASE SA60_DEB_CRED_IND
        WHEN 'C' THEN SA60_AMT_TRANS * -1
        WHEN 'D' THEN SA60_AMT_TRANS
        ELSE 0
    END
      ) AS AMT_TRAN_SUM
  FROM
    `pcb-{env}-processing.domain_account_management.SA60_DAILY{file_type}`
  WHERE
    SA60_PAYMENT_TRANS_INDICATOR = 1
  GROUP BY
    SA60_ACCT_ID,
    FILE_CREATE_DT,
    PARENT_CARD_NUM ) AS AMT_SUM
INNER JOIN (
  SELECT
    sa59.SA59_CLIENT_NUM AS SA59_CLIENT_NUM,
    sa59.SA59_ACCT_ID AS SA59_ACCT_ID,
    sa59.SA59_RECORD_ID AS SA59_RECORD_ID,
    sa59.SA59_KEY_STMT_FORM AS SA59_KEY_STMT_FORM,
    sa59.SA59_KEY_INSRT_GRP AS SA59_KEY_INSRT_GRP,
    sa59.FILE_CREATE_DT AS FILE_CREATE_DT,
    sa59.PARENT_CARD_NUM AS PARENT_CARD_NUM,
    sa10.SA10_BILLING_CYCLE AS CYCLE_NO,
    sa10.FILE_NAME AS FILE_NAME
  FROM
    `pcb-{env}-processing.domain_account_management.SA59_DAILY{file_type}` sa59
  LEFT JOIN
    `pcb-{env}-processing.domain_account_management.SA10{file_type}_DBEXT` sa10
  ON
    sa10.PARENT_CARD_NUM = sa59.PARENT_CARD_NUM
  --WHERE
  --  sa10.SA10_ACCT_ID = 394360
  GROUP BY
    sa59.SA59_CLIENT_NUM,
    sa59.SA59_RECORD_ID,
    sa59.SA59_KEY_STMT_FORM,
    sa59.SA59_KEY_INSRT_GRP,
    sa59.SA59_ACCT_ID,
    sa59.FILE_CREATE_DT,
    sa59.PARENT_CARD_NUM,
    sa10.SA10_BILLING_CYCLE,
    sa10.FILE_NAME ) AS SA1059
ON
  AMT_SUM.PARENT_CARD_NUM = SA1059.PARENT_CARD_NUM
  AND AMT_SUM.FILE_CREATE_DT = SA1059.FILE_CREATE_DT