SELECT
  sa59.SA59_CLIENT_NUM,
  sa59.SA59_ACCT_ID,
  sa59.SA59_RECORD_ID,
  sa59.SA59_SEQ_NUM,
  sa59.SA59_KEY_STMT_FORM,
  sa59.SA59_KEY_INSRT_GRP,
  IF
    (SA60_ACCOUNT_NUMB_ORIG = '' OR SA60_ACCOUNT_NUMB_ORIG IS NULL, sa59.SA59_ACCOUNT_NUMB, SA60_ACCOUNT_NUMB_ORIG) AS SA59_ACCOUNT_NUMB,
  sa59.SA59_NAME_PRINT,
  sa59.SA59_CUST_TYPE,
  sa59.SA59_CUST_ID,
  NULL AS SA59_POS_FIRST_NAME,
  NULL AS SA59_POS_MIDDLE_NAME,
  NULL AS SA59_POS_LAST_NAME,
  NULL AS SA59_POS_SUFFIX,
  CAST(NULL AS STRING) AS SA59_NAME_PRINT_LEGAL,
  NULL AS SA59_POS_FIRST_NAME_LEGAL,
  NULL AS SA59_POS_MIDDLE_NAME_LEGAL,
  NULL AS SA59_POS_LAST_NAME_LEGAL,
  NULL AS SA59_POS_SUFFIX_LEGAL,
  sa59.PARENT_CARD_NUM,
  sa59.FILE_CREATE_DT,
  sa59.FILE_NAME,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  sa59.SA10_BILLING_CYCLE,
  sa59.SA59_DEVICE_TYPE,
  'Y' AS SA59_PROC_IND,
  '0' AS SA59_PAYMENT_TRANSSUM_IND,
  CAST(NULL AS NUMERIC) AS SA59_SUB_TOTAL
FROM (
  SELECT
    SA59_CLIENT_NUM,
    SA59_RECORD_ID,
    SA59.SA59_SEQ_NUM,
    SA59_KEY_STMT_FORM,
    SA59_KEY_INSRT_GRP,
    SA59_ACCT_ID,
    SA59_ACCOUNT_NUMB,
    SA59_NAME_PRINT,
    SA59_CUST_TYPE,
    SA59_CUST_ID,
    SA59.PARENT_CARD_NUM,
    SA59.FILE_NAME,
    SA59_DEVICE_TYPE,
    SA59.FILE_CREATE_DT AS FILE_CREATE_DT,
    SA10_BILLING_CYCLE,
    RANK() OVER (PARTITION BY SA59_CUST_ID, SA59_CUST_TYPE, SA59_DEVICE_TYPE, SA59.PARENT_CARD_NUM ORDER BY SA59_SEQ_NUM DESC) rnk
  FROM
    `pcb-{env}-processing.domain_account_management.SA59_DAILY{file_type}` AS SA59
  JOIN
    `pcb-{env}-processing.domain_account_management.SA10{file_type}_DBEXT_COLUMN_TF` AS SA10
  ON
    SA59.PARENT_CARD_NUM = SA10.PARENT_CARD_NUM
  WHERE
    IFNULL( SA59_PAYMENT_TRANSSUM_IND,'0') <> '1' ) sa59
LEFT JOIN (
  SELECT
    SA60_ACCOUNT_NUMB_ORIG,
    SA60_CUST_TYPE,
    SA60_CUST_ID,
    SA60_ACC_METHOD_TYPE_CD_CURR,
    PARENT_CARD_NUM,
    SA60_ACCT_ID,
    FILE_NAME
  FROM (
    SELECT
      SA60_ACCOUNT_NUMB_ORIG,
      SA60_CUST_TYPE,
      SA60_CUST_ID,
      SA60_ACC_METHOD_TYPE_CD_CURR,
      PARENT_CARD_NUM,
      SA60_ACCT_ID,
      FILE_NAME,
      RANK() OVER (PARTITION BY SA60_CUST_TYPE, SA60_CUST_ID, SA60_ACC_METHOD_TYPE_CD_CURR, PARENT_CARD_NUM ORDER BY SA60_SEQ_NUM DESC ) rnk
    FROM
      `pcb-{env}-processing.domain_account_management.SA60_DAILY{file_type}` AS SA60
    WHERE
      SA60.SA60_TRANSFER_FLAG = ''
      AND IFNULL(SA60.SA60_PAYMENT_TRANS_INDICATOR,0) <> 1)
  WHERE
    rnk =1) sa60
ON
  sa59.SA59_CUST_ID = sa60.SA60_CUST_ID
  AND sa59.SA59_CUST_TYPE = sa60.SA60_CUST_TYPE
  AND IFNULL(sa59.SA59_DEVICE_TYPE,'X') = IFNULL(sa60.SA60_ACC_METHOD_TYPE_CD_CURR, 'X')
  AND sa59_ACCT_ID = sa60_ACCT_ID
  AND sa59.PARENT_CARD_NUM = sa60.PARENT_CARD_NUM
  AND sa59.FILE_NAME = sa60.FILE_NAME
WHERE
  rnk = 1