WITH
  SA6059 AS (
  SELECT
    SA60.*,
    SA59_ACCOUNT_NUMB
  FROM
    pcb-{env}-processing.domain_account_management.SA60_DAILY{file_type} AS sa60
  LEFT JOIN
    pcb-{env}-processing.domain_account_management.SA59_CALC_MID{file_type} AS sa59
  ON
    sa60.SA60_CUST_ID = sa59.SA59_CUST_ID
    AND sa60.SA60_CUST_TYPE = sa59.SA59_CUST_TYPE
    AND sa60.PARENT_CARD_NUM = sa59.PARENT_CARD_NUM
    AND SA59_PROC_IND = 'Y'
    AND IFNULL( SA60_PAYMENT_TRANS_INDICATOR, 0) != 1
    AND IFNULL( SA59_PAYMENT_TRANSSUM_IND, '0') != '1'
    AND IFNULL( SA60_ACC_METHOD_TYPE_CD_CURR,'X') = IFNULL( SA59_DEVICE_TYPE,'X') )
SELECT
  SA6059.*
  EXCEPT(SA59_ACCOUNT_NUMB)
  REPLACE(
    IF(SA59_ACCOUNT_NUMB IS NOT NULL, SA59_ACCOUNT_NUMB, SA60_ACCOUNT_NUMB) AS SA60_ACCOUNT_NUMB,
    IF(SA59_ACCOUNT_NUMB IS NOT NULL, 'Y', SA60_PROC_IND) AS SA60_PROC_IND
  )
FROM
  SA6059