MERGE pcb-{env}-landing.domain_dispute.TCS_DISPOSITION_RPT T
USING pcb-{env}-processing.domain_dispute.TCS_DISPOSITION_RPT_IDL S
      ON  T.FILE_HDR_DT = (CAST(S.REC_CREATE_TMS AS DATE)-1)
      AND T.INTERACTIONID = S.INTERACTIONID
      AND T.TSYSACCOUNTID = S.TSYSACCOUNTID
      AND T.CPC = S.CPC
      AND T.TPC = S.TPC
WHEN NOT MATCHED THEN INSERT (
    INTERACTIONID,
    INTCREATEDATETIME,
    INTCOMPLETIONDATETIME,
    CREATEOPERATOR,
    PRIMARYACTIVITY,
    SECONDARYACTIVITY,
    TSYSACCOUNTID,
    CPC,
    TPC,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    REC_CHNG_ID,
    BATCH_RUN_LOG_UID,
    FILE_HDR_DT)
VALUES(S.INTERACTIONID,
    CAST(S.INTCREATEDATETIME AS DATETIME),
    CAST(S.INTCOMPLETIONDATETIME AS DATETIME),
    S.CREATEOPERATOR,
    S.PRIMARYACTIVITY,
    S.SECONDARYACTIVITY,
    S.TSYSACCOUNTID,
    S.CPC,
    S.TPC,
    CAST(S.REC_CREATE_TMS AS DATETIME),
    CAST(S.REC_CHNG_TMS AS DATETIME),
    'IDL-' || S.REC_CHNG_ID,
    CAST(S.BATCH_RUN_LOG_UID as int64),
    DATE(S.REC_CREATE_TMS)-1)
 ;