CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_dispute.TCS_DISPUTE_DTL_ETHOCA_STGNG AS
WITH
  MAXDISP AS
(
  SELECT
    MAX(FILE_HDR_DT) AS MAX_FILE_HDR_DT
  FROM
    pcb-{env}-curated.domain_dispute.TCS_DISPUTE_DTL
)

SELECT
  NULLIF(AT31.AT31_ACCOUNT_NUMB_ORIG,'') AS CARD_NUMBER,
  NULLIF(AT31.AT31_REFERENCE_NUM,'') AS REFERENCE,
  DISP.TYTRANSACTIONLIST_ID AS TRANSACTION_ID,
  AT31.AT31_DATE_SETTLEMENT AS SETTLED_DATE_TIME,
  "MC" AS CARD_SCHEME,
  DISP.TXTRANSACTIONDATE AS AUTHORISATION_DATE_TIME,
  NULLIF(DISP.TYMERCHANTNAME,'') AS MERCHANT_NAME,
  NULLIF(DISP.MERCHANT_CITY,'') AS MERCHANT_CITY,
  NULLIF(DISP.MERCHANT_STATE,'') AS MERCHANT_STATE_PROVINCE_REGION,
  NULLIF(DISP.MERCHANT_COUNTRY,'') AS MERCHANT_COUNTRY,
  DISP.TYDISPUTEAMOUNT AS AMOUNT,
  AT31.AT31_CURRENCY_CODE AS CURRENCY,
  DISP.CHARGEBACKAMOUNT AS CB_AMOUNT,
  AT31.AT31_CURRENCY_CODE AS CB_CURRENCY,
  NULLIF(DISP.AUTH_CODE,'') AS AUTH_CODE,
  NULLIF(AT31.AT31_MERCHANT_ID,'') AS MID,
  NULLIF(DISP.CHARGEBACKREASONCODECHOSEN,'') AS CB_REASON_CODE,
  CAST(NULL AS STRING) AS ACQUIRER_ID,
  NULLIF(DISP.POS_ENTRY_MODE,'') AS POS_CODE,
  AT31.AT31_MERCHANT_CATEGORY_CODE AS MCC,
  "A" AS AUTH_DECISION,
  DISP.ARN

FROM (
  SELECT
    FILE_HDR_DT,
    TYTRANSACTIONLIST_ID,
    TXTRANSACTIONDATE,
    TYMERCHANTNAME,
    MERCHANT_CITY,
    MERCHANT_STATE,
    MERCHANT_COUNTRY,
    TYDISPUTEAMOUNT,
    CHARGEBACKAMOUNT,
    AUTH_CODE,
    CHARGEBACKREASONCODECHOSEN,
    POS_ENTRY_MODE,
    ARN,
    FRAUDINDICATOR,
    TXTRANSACTIONAMOUNT,
    ROW_NUMBER() OVER (PARTITION BY TDD.ARN ORDER BY TDD.FILE_HDR_DT ASC) CNT
  FROM
    pcb-{env}-curated.domain_dispute.TCS_DISPUTE_DTL TDD
  WHERE
    FILE_HDR_DT > DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY)
    AND FILE_HDR_DT <= IFNULL(DATE(<<<FROM_DATE_VAL>>>),(
      SELECT
        MAX_FILE_HDR_DT
      FROM
        MAXDISP))) DISP
JOIN (
  SELECT
    ATR.*,
    RANK() OVER (PARTITION BY ATR.AT31_REFERENCE_NUM ORDER BY ATR.AT31_DATE_POST ASC) AT31_RANK
  FROM
    pcb-{env}-curated.domain_account_management.AT31 ATR
  WHERE
    ATR.FILE_CREATE_DT > DATE_SUB(CURRENT_DATE(), INTERVAL 150 DAY)) AT31
ON
  AT31.AT31_REFERENCE_NUM = CAST(DISP.ARN AS STRING)
  AND AT31.AT00_APPLICATION_SUFFIX = 0
  AND AT31.AT31_RANK = 1
  AND DISP.CNT = 1
WHERE
  DISP.FRAUDINDICATOR <> 'Y'
  AND DISP.TXTRANSACTIONAMOUNT >= 1
  AND DISP.TXTRANSACTIONAMOUNT <= 10000
  AND DISP.FILE_HDR_DT = IFNULL(DATE(<<<FROM_DATE_VAL>>>),(
    SELECT
      MAX_FILE_HDR_DT
    FROM
      MAXDISP))
