MERGE pcb-{env}-landing.domain_dispute.TCS_DISPUTE_CLAIM T
USING pcb-{env}-processing.domain_dispute.TCS_DISPUTE_CLAIM_IDL S
      ON  T.FILE_HDR_DT = (CAST(S.REC_CREATE_TMS AS DATE)-1)
     AND T.PZINSKEY = S.PZINSKEY
     AND T.INTERACTIONID = S.INTERACTIONID
     AND T.WORKTYPEID = S.WORKTYPEID
     AND T.WTSTATUS = S.WTSTATUS
WHEN NOT MATCHED THEN INSERT (
    PZINSKEY,
    INTERACTIONID,
    WORKTYPEID,
    INTENTTASKNAME,
    WTSTATUS,
    WORKTYPENAME,
    PARENTWORKTYPE,
    RESOLVEDUSERID,
    ACCOUNTNUMBER,
    NET_FRAUD_AMOUNT,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    REC_CHNG_ID,
    BATCH_RUN_LOG_UID,
    FILE_HDR_DT)
VALUES(S.PZINSKEY,
    S.INTERACTIONID,
    S.WORKTYPEID,
    S.INTENTTASKNAME,
    S.WTSTATUS,
    S.WORKTYPENAME,
    S.PARENTWORKTYPE,
    S.RESOLVEDUSERID,
    S.ACCOUNTNUMBER,
    NULL, --S.NET_FRAUD_AMOUNT,
    CAST(S.REC_CREATE_TMS AS DATETIME),
    CAST(S.REC_CHNG_TMS AS DATETIME),
    'IDL-' || S.REC_CHNG_ID,
    CAST(S.BATCH_RUN_LOG_UID as int64),
    DATE(S.REC_CREATE_TMS)-1)
 ;
