MERGE pcb-{env}-landing.domain_dispute.TCS_ALERTS T
USING pcb-{env}-processing.domain_dispute.TCS_ALERTS_IDL S
      ON  T.FILE_HDR_DT = (CAST(S.REC_CREATE_TMS AS DATE)-1)
      AND T.PZINSKEY = S.PZINSKEY
      AND T.TYALERTS_ID = CAST(S.TYALERTS_ID AS INT64)
      AND T.WORKTYPEID = S.WORKTYPEID
      AND T.ALERTNAME = S.ALERTNAME
WHEN NOT MATCHED THEN INSERT (
    PZINSKEY,
    TYALERTS_ID,
    WORKTYPEID,
    ALERTNAME,
    WTCREATEDATETIME,
    CHRONICCATEGORY,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    REC_CHNG_ID,
    BATCH_RUN_LOG_UID,
    FILE_HDR_DT)
VALUES(S.PZINSKEY,
    CAST(S.TYALERTS_ID AS INT64),
    S.WORKTYPEID,
    S.ALERTNAME,
    CAST(S.WTCREATEDATETIME AS DATETIME),
    S.CHRONICCATEGORY,
    CAST(S.REC_CREATE_TMS AS DATETIME),
    CAST(S.REC_CHNG_TMS AS DATETIME),
    'IDL-' || S.REC_CHNG_ID,
    CAST(S.BATCH_RUN_LOG_UID as int64),
    DATE(S.REC_CREATE_TMS)-1)
 ;
