BEGIN
--TCS ALERTS Table insert query--
INSERT INTO pcb-{env}-landing.domain_dispute.TCS_ALERTS
SELECT
  PZINSKEY,
  CAST(TYALERTS_ID AS INT64),
  WORKTYPEID,
  ALERTNAME,
  CAST(WTCREATEDATETIME AS DATETIME),
  CHRONICCATEGORY,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_ALERTS_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

-- TCS FRAUD DETAILS Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_FRAUD_DTL
SELECT
  PZINSKEY,
  INTERACTIONID,
  WORKTYPEID,
  INTENTTASKNAME,
  WTSTATUS,
  WORKTYPENAME,
  PARENTWORKTYPE,
  RESOLVEDUSERIDR,
  ACCOUNTNUMBE,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_FRAUD_DTL_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

-- TCS DISPUTE CLAIM Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_DISPUTE_CLAIM
SELECT
  PZINSKEY,
  INTERACTIONID,
  WORKTYPEID,
  INTENTTASKNAME,
  WTSTATUS,
  WORKTYPENAME,
  PARENTWORKTYPE,
  RESOLVEDUSERID,
  ACCOUNTNUMBER,
  NET_FRAUD_AMOUNT,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_DISPUTE_CLAIM_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

-- TCS FRAUD MONITORING Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_FRAUD_MONITORING
SELECT
  PZINSKEY,
  PXINDEXCOUNT,
  PXINDEXCOUNT_TB,
  PYID,
  TYQUEUEID,
  TYFRAUDACTIONDESC,
  TYQUEUEACTION,
  CAST(PYRESOLVEDDATETIME AS DATETIME),
  TYPHONETYPE,
  TYPHONE_NUMBER,
  TYREASON,
  TYOUTBOUNDCALLSTATUS,
  CAST(
    TYCHCONTACTEDDATETIME AS DATETIME
  ),
  TYACCOUNTSTATUS,
  STATUS_CD_TYSTATUS,
  TYREASONCODE,
  RSN_CD_TYSTATUS,
  CAST(PXCOMMITDATETIME AS DATETIME),
  TYCARDGUARDACTION,
  CORRESPOND_ID,
  LETTER_DESC,
  LETTER_STS,
  FRAUD_INV_ACK,
  FRAUD_INV_RESOLUTION,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_FRAUD_MONITORING_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

--TCS DISPUTE DTL Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_DISPUTE_DTL
SELECT
  PZINSKEY,
  TYTRANSACTIONLIST_ID,
  PXINDEXCOUNT,
  PXINDEXCOUNT_TB,
  WORKTYPEID,
  PARENTWORKTYPE,
  CAST(TXTRANSACTIONDATE AS DATETIME),
  TXTRANSACTIONAMOUNT,
  TYMERCHANTNAME,
  ARN,
  MCC,
  CAST(
    ORIGN_PXCREATEDATETIME AS DATETIME
  ),
  TYDISPUTEAMOUNT,
  TYDISPUTEREASON,
  TYDISPUTEREASONDESC,
  TYDISPUTEACTIONDESC,
  CAST(
    RTRVL_RQ_PXCREATEDATETIME AS DATETIME
  ),
  CHARGEBACKAMOUNT,
  CHARGEBACKREASONCODECHOSEN,
  CHARGEBACKREASONCODEDESCPRIPTION,
  REPRESENTMENTREASONCODE,
  REPRESENTMENTRCDESCRIPTION,
  REPRESENTMENTAMOUNT,
  TYGLDESCRIPTION,
  TYGLKEYCODE,
  TYMERCHANTISSUEDCREDITAMOUNT,
  TYWRITEOFFAMOUNT,
  FRAUDINDICATOR,
  CAST(
    TYCENTRALPROCESSINGDATE AS DATETIME
  ),
  MERCHANTDBANAME,
  CAST(TYFCBAFINALITYDATE AS DATETIME),
  CAST(
    TYFIRSTDFARECEIVEDDATE AS DATETIME
  ),
  CAST(
    TYADDITIONALDFARECEIVEDDATE AS DATETIME
  ),
  CAST(TYRRFULFILLMENTDATE AS DATETIME),
  CAST(
    TYRRNONFULFILLMENTDATE AS DATETIME
  ),
  CAST(CHARGEBACKDATE AS DATETIME),
  CAST(REPRESENTMENTDATE AS DATETIME),
  CARDHOLDERLIABLEAMOUNT,
  CAST(PYRESOLVEDTIMESTAMP AS DATETIME),
  WTSTATUS,
  CAST(
    MRCH_CR_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  CAST(TYCHDOCATTACHDATE AS DATETIME),
  CAST(TYFINALRESLETTERDATE AS DATETIME),
  DISPUTESTAGE,
  TYLASTINDEXEDBY,
  CAST(TYLASTINDEXEDDATE AS DATETIME),
  TYCHARGEBACKREFNUMBER,
  ARBITRATIONCHARGEBACKAMOUNT,
  CAST(
    ARBITRATIONCHARGEBACKDATE AS DATETIME
  ),
  CAST(
    PREARBORDISPRESINITIATIONDATE AS DATETIME
  ),
  PREARBACCEPTANCEAMOUNT,
  CAST(
    PRE_ARB_CR_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  AMOUNTOUTSTANDINGPREARBRES,
  CAST(
    PRE_ARB_DB_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  CAST(
    CASEFILINGACKNLDGMTDATE AS DATETIME
  ),
  ACQUIRERLIABLEAMOUNT,
  CAST(
    ARB_CR_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  ISSUERLIABLEAMOUNT,
  CAST(
    ARB_DB_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  TYPRECOMPLIANCEAMOUNT,
  CAST(
    PRE_CMPLNC_CR_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  PRE_CMPLNC_DB_ISSUERLIABLEAMOUNT,
  CAST(
    PRE_CMPLNC_DB_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  TYCOMPLIANCEAMOUNT,
  CAST(
    CMPLNC_CR_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  CMPLNC_DB_ISSUERLIABLEAMOUNT,
  CAST(
    CMPLNC_DB_PYRESOLVEDTIMESTAMP AS DATETIME
  ),
  INV_REBIL_CARDHOLDER_LIAB_AMOUT,
  CAST(
    INV_REBILL_PYRESOLVED_TIMESTAMP AS DATETIME
  ),
  INV_CREATE_OPERATOR,
  LOCOFFRAUD_TYMERCHANTCOUNTRY,
  MF_ACCOUNTBALANCE,
  MERCHANT_CITY,
  MERCHANT_STATE,
  MERCHANT_COUNTRY,
  AUTH_CODE,
  POS_ENTRY_MODE,
  RESOLUTION_AMOUNT,
  ATT_CHRGBACK_RSN_CODE,
  TRANSACTION_ID,
  BANKNET_REF_NUMBER,
  FRAUD_REASON,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_DISPUTE_DTL_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

--TCS DISPUTES LTR Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_DISPUTES_LTR
SELECT
  PZINSKEY,
  PZINSKEY_TB,
  TYOPERATIONNAME,
  CAST(
    LTR_SENT_PXCREATEDATETIME AS DATETIME
  ),
  PXCREATEOPERATOR,
  TYLETTERID,
  PYDESCRIPTION,
  DOC_TYSTATUS,
  PYTOPARTY,
  CAST(TYRECEIVEDDATE AS DATETIME),
  PYFROMPARTY,
  TYPARENTID,
  PYID,
  ADDRTYPE,
  ADDRESSLINE1,
  ADDRESSLINE2,
  ADDRESSLINE3,
  ADDRESSLINE4,
  CITY,
  STATE,
  PROVINCE,
  POSTALCODE,
  ZIPCODE,
  COUNTRY,
  NO_OF_PAGES,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_DISPUTES_LTR_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

--TCS DISPUTE FRAUD COMMON Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_DISPUTE_FRAUD_COMMON
SELECT
  PZINSKEY,
  PXINDEXCOUNT,
  TYNOTESLIST_ID,
  TYACCOUNTLIST_ID,
  INTERACTIONTYPE,
  INTERACTIONID,
  INTENTTASKNAME,
  INTSTATUS,
  WTSTATUS,
  INTOPNAME,
  CLIENTCUSTOMERID,
  INTCARDNUM,
  CAST(INTCREATEDATETIME AS DATETIME),
  CAST(
    INTCOMPLETIONDATETIME AS DATETIME
  ),
  ERRORSTATUS,
  URGENCYWORK,
  WORKTYPENAME,
  PARENTWORKTYPE,
  RESOLVEDUSERID,
  ACCOUNTNUMBER,
  CAST(WTCREATEDATETIME AS DATETIME),
  CAST(WTUPDATEDATETIME AS DATETIME),
  CAST(WTCOMPLETIONDATETIME AS DATETIME),
  CREATEOPERATOR,
  WTUPDTOPID,
  SLADEADLINE,
  SLAGOAL,
  INTCUSTID,
  RESOLVEDUSERWORKGROUP,
  NOTES,
  NOTESLISTID,
  CURRENTINTNOTES,
  WTCUSTID,
  DURATION,
  TSYSACCOUNTID,
  CLIENTID,
  WTAPPLICATION,
  CTIVERIFICATION,
  PRODUCTNAME,
  CPC,
  TPC,
  PYLABEL,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_DISPUTE_FRAUD_COMMON_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

--TCS FRAUD REPORTING Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_FRAUD_REPORTING
SELECT
  PZINSKEY,
  PXINDEXCOUNT,
  PYID,
  CAST(
    SAFE_RPTD_PXCREATEDATETIME AS DATETIME
  ),
  TYREASON,
  PYSTATUSWORK,
  FRAUDTYPE,
  CHARGEBACKAMOUNT,
  CAST(
    FRAUD_PXCREATEDATETIME AS DATETIME
  ),
  DISPUTEAMOUNT,
  ZRPT_MERCHANTDBANAME,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_FRAUD_REPORTING_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

--TCS LOST STOLEN Table insert query--

INSERT INTO pcb-{env}-landing.domain_dispute.TCS_LOST_STOLEN
SELECT
  PZINSKEY,
  TYSELECTEDACCOUNTLIST_ID,
  WORKTYPEID,
  REASONDESCRIPTION,
  REASONCODE,
  RELATIONSHIPTYPE,
  OLDCARDNUMBER,
  NEWCARDNUMBER,
  CARDHOLDERNAME,
  CARDTYPE,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_LOST_STOLEN_STGNG
WHERE
 REC_CHNG_ID =  "<<file_name>>";

END;
