MERGE pcb-{env}-landing.domain_dispute.TCS_WORK_BASKET T
USING pcb-{env}-processing.domain_dispute.TCS_WORK_BASKET_IDL S
      ON  T.FILE_HDR_DT = (CAST(S.REC_CREATE_TMS AS DATE)-1)
      AND T.PXREFOBJECTINSNAME = S.PXREFOBJECTINSNAME
      AND T.PYSTATUSWORK = S.PYSTATUSWORK
WHEN NOT MATCHED THEN INSERT (
    SLACATEGORY,
    PXASSIGNEDOPERATORID,
    PXCREATEDATETIME,
    PXDEADLINETIME,
    PXGOALTIME,
    PYLABEL,
    PXREFOBJECTINSNAME,
    PYSTATUSWORK,
    PXSKILLNAME,
    PXSKILLRATING,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    REC_CHNG_ID,
    BATCH_RUN_LOG_UID,
    FILE_HDR_DT)
VALUES(S.SLACATEGORY,
    S.PXASSIGNEDOPERATORID,
    CAST(S.PXCREATEDATETIME AS DATETIME),
    CAST(S.PXDEADLINETIME AS DATETIME),
    CAST(S.PXGOALTIME AS DATETIME),
    S.PYLABEL,
    S.PXREFOBJECTINSNAME,
    S.PYSTATUSWORK,
    S.PXSKILLNAME,
    S.PXSKILLRATING,
    CAST(S.REC_CREATE_TMS AS DATETIME),
    CAST(S.REC_CHNG_TMS AS DATETIME),
    'IDL-' || S.REC_CHNG_ID,
    CAST(S.BATCH_RUN_LOG_UID as int64),
    DATE(S.REC_CREATE_TMS)-1)
 ;