MERGE pcb-{env}-landing.domain_dispute.TCS_FRAUD_REPORTING T
USING pcb-{env}-processing.domain_dispute.TCS_FRUAD_REPORTING_IDL S
      ON  T.FILE_HDR_DT = (CAST(S.REC_CREATE_TMS AS DATE)-1)
     AND T.PZINSKEY = S.PZINSKEY
     AND T.PYID = S.PYID
     AND T.DISPUTEAMOUNT = S.DISPUTEAMOUNT
     AND T.PYSTATUSWORK = S.PYSTATUSWORK
WHEN NOT MATCHED THEN INSERT (
    PZINSKEY,
    PXINDEXCOUNT,
    PYID,
    SAFE_RPTD_PXCREATEDATETIME,
    TYREASON,
    PYSTATUSWORK,
    FRAUDTYPE,
    CHARGEBACKAMOUNT,
    FRAUD_PXCREATEDATETIME,
    DISPUTEAMOUNT,
    ZRPT_MERCHANTDBANAME,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    REC_CHNG_ID,
    BATCH_RUN_LOG_UID,
    FILE_HDR_DT)
VALUES(
    S.PZINSKEY,
    CAST(S.PXINDEXCOUNT AS INT64),
    S.PYID,
    CAST(S.SAFE_RPTD_PXCREATEDATETIME AS DATETIME),
    S.TYREASON,
    S.PYSTATUSWORK,
    S.FRAUDTYPE,
    S.CHARGEBACKAMOUNT,
    CAST(S.FRAUD_PXCREATEDATETIME AS DATETIME),
    S.DISPUTEAMOUNT,
    S.ZRPT_MERCHANTDBANAME,
    CAST(S.REC_CREATE_TMS AS DATETIME),
    CAST(S.REC_CHNG_TMS AS DATETIME),
    'IDL-' || S.REC_CHNG_ID,
    CAST(S.BATCH_RUN_LOG_UID as int64),
    DATE(S.REC_CREATE_TMS)-1)
 ;