MERGE pcb-{env}-landing.domain_dispute.TCS_LOST_STOLEN T
USING pcb-{env}-processing.domain_dispute.TCS_LOST_STOLEN_IDL S
      ON  T.FILE_HDR_DT = (CAST(S.REC_CREATE_TMS AS DATE)-1)
      AND T.WORKTYPEID = S.WORKTYPEID
      AND T.OLDCARDNUMBER = S.OLDCARDNUMBER
      AND T.CARDHOLDERNAME = S.CARDHOLDERNAME
WHEN NOT MATCHED THEN INSERT (
    PZINSKEY,
    TYSELECTEDACCOUNTLIST_ID,
    WORKTYPEID,
    REASONDESCRIPTION,
    REASONCODE,
    RELATIONSHIPTYPE,
    OLDCARDNUMBER,
    NEWCARDNUMBER,
    CARDHOLDERNAME,
    CARDTYPE,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    REC_CHNG_ID,
    BATCH_RUN_LOG_UID,
    FILE_HDR_DT)
VALUES(S.PZINSKEY,
    S.TYSELECTEDACCOUNTLIST_ID,
    S.WORKTYPEID,
    S.REASONDESCRIPTION,
    S.REASONCODE,
    S.RELATIONSHIPTYPE,
    S.OLDCARDNUMBER,
    S.NEWCARDNUMBER,
    S.CARDHOLDERNAME,
    S.CARDTYPE,
    CAST(S.REC_CREATE_TMS AS DATETIME),
    CAST(S.REC_CHNG_TMS AS DATETIME),
    'IDL-' || S.REC_CHNG_ID,
    CAST(S.BATCH_RUN_LOG_UID as int64),
    DATE(S.REC_CREATE_TMS)-1)
 ;