--TCS WORK BASKET Table insert query--
INSERT INTO pcb-{env}-landing.domain_dispute.TCS_WORK_BASKET
SELECT
  SLACATEGORY,
  PXASSIGNEDOPERATORID,
  CAST(PXCREATEDATETIME AS DATETIME),
  CAST(PXDEADLINETIME AS DATETIME),
  CAST(PXGOALTIME AS DATETIME),
  PYLABEL,
  PXREFOBJECTINSNAME,
  PYSTATUSWORK,
  PXSKILLNAME,
  PXSKILLRATING,
  CAST(REC_CREATE_TMS AS DATETIME),
  CAST(REC_CHNG_TMS AS DATETIME),
  REC_CHNG_ID,
  BATCH_RUN_LOG_UID,
  FILE_HDR_DT
FROM
  pcb-{env}-processing.domain_dispute.TCS_WORK_BASKET_STGNG
WHERE
  REC_CHNG_ID =  "<<file_name>>";
