WITH MA00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    MA00_CLIENT_NUM,
    MA00_APPLICATION_NUM,
    MA00_APPLICATION_SUFFIX
  FROM
    pcb-{env}-processing.domain_account_management.TSYS_ACCT_MISC_MA00_REC_EXT
),
MA03 AS (
  SELECT
    *
  FROM
     `pcb-{env}-processing.domain_account_management.TSYS_ACCT_MISC_MA03_REC_EXT`
)
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  MA03_SEGMENT_LENGTH,
  MA00.MA00_CLIENT_NUM,
  MA00.MA00_APPLICATION_NUM,
  MA00_APPLICATION_SUFFIX,
  MA03_OPTION_SET,
  IF(
    MA03_ENROLLMENT_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA03_ENROLLMENT_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA03_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA03_ENROLLMENT_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA03_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA03_ENROLLMENT_DATE,
  IF(
    MA03_PROGRAM_START_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA03_PROGRAM_START_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA03_PROGRAM_START_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA03_PROGRAM_START_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA03_PROGRAM_START_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA03_PROGRAM_START_DATE,
  IF(
    MA03_PROGRAM_STOP_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA03_PROGRAM_STOP_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA03_PROGRAM_STOP_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA03_PROGRAM_STOP_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA03_PROGRAM_STOP_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA03_PROGRAM_STOP_DATE,
  MA03_QUAL_VOL_CTD,
  MA03_QUAL_VOL_PTD,
  MA03_EARNED_CTD,
  MA03_EARNED_PTD,
  MA03_POST_TO_ACCT_CTD,
  MA03_POST_TO_ACCT_PTD,
  IF(
    MA03_LAST_EARNED_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA03_LAST_EARNED_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA03_LAST_EARNED_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA03_LAST_EARNED_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA03_LAST_EARNED_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA03_LAST_EARNED_DATE,
  IF(
    MA03_LAST_POST_TO_ACCT_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA03_LAST_POST_TO_ACCT_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA03_LAST_POST_TO_ACCT_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA03_LAST_POST_TO_ACCT_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA03_LAST_POST_TO_ACCT_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA03_LAST_POST_TO_ACCT_DATE,
  MA03_NBR_QUAL_TRANS_CTD,
  MA03_NBR_QUAL_TRANS_PTD,
  MA03_ACCOUNT_REWARDS_QUALIFIER_1,
  MA03_ACCOUNT_REWARDS_QUALIFIER_2,
  FILE_CREATE_DT,
FROM
  MA03
  INNER JOIN
  MA00
  USING
  ( MAST_ACCOUNT_ID,
    MA00_APPLICATION_SUFFIX)