WITH
  MA00 AS (
  SELECT
    MAST_ACCOUNT_ID,
    MA00_CLIENT_NUM,
    MA00_APPLICATION_NUM,
    MA00_APPLICATION_SUFFIX
  FROM
    pcb-{env}-processing.domain_account_management.TSYS_ACCT_MISC_MA00_REC_EXT ),
  MA01 AS (
  SELECT
    *
  FROM
    `pcb-{env}-processing.domain_account_management.TSYS_ACCT_MISC_MA01_REC_EXT` )
SELECT
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  MA01_SEGMENT_LENGTH,
  MA00.MA00_CLIENT_NUM,
  MA00.MA00_APPLICATION_NUM,
  MA00_APPLICATION_SUFFIX,
  MA01_CUSTOMER_ID,
  MA01_ENHANCEMENT_ID,
  MA01_PLAN_ID,
 IF(
    MA01_DATE_LAST_BILL IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_DATE_LAST_BILL AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_DATE_LAST_BILL AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_DATE_LAST_BILL AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_DATE_LAST_BILL AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_DATE_LAST_BILL,
  MA01_AMOUNT_LAST_BILL,
  MA01_AMOUNT_BILL_CTD,
  MA01_ACCT_BILL_LTD,
  IF(
    MA01_DATE_CANCELLATION IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_DATE_CANCELLATION AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_DATE_CANCELLATION AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_DATE_CANCELLATION AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_DATE_CANCELLATION AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_DATE_CANCELLATION,
  MA01_CANCELLATION_REASON,
  MA01_STATUS,
  MA01_INTRO_PRICE_CYC_COUNTER,
  MA01_NUM_CYC_TO_NEXT_BILL,
  MA01_ADJUSTMENT_AMT_CTD,
  MA01_ADJUSTMENT_AMT_LTD,
  MA01_MEMO_REBATE_IND,
  MA01_LAST_REBATE_AMT,
  IF(
    MA01_LAST_REBATE_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_LAST_REBATE_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_LAST_REBATE_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_LAST_REBATE_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_LAST_REBATE_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_LAST_REBATE_DATE,
  MA01_LAST_TAX1_AMT,
  MA01_LAST_TAX2_AMT,
  IF(
    MA01_LAST_TAX_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_LAST_TAX_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_LAST_TAX_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_LAST_TAX_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_LAST_TAX_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_LAST_TAX_DATE,
  IF(
    MA01_CONFIRM_ENROLLMENT_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_CONFIRM_ENROLLMENT_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_CONFIRM_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_CONFIRM_ENROLLMENT_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_CONFIRM_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_CONFIRM_ENROLLMENT_DATE,
  MA01_ENROLLMENT_CHANNEL,
  MA01_CANCELLATION_CHANNEL,
  MA01_OFFER_CODE,
  IF(
    MA01_OFFER_START_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_OFFER_START_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_OFFER_START_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_OFFER_START_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_OFFER_START_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_OFFER_START_DATE,
  IF(
    MA01_OFFER_STOP_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_OFFER_STOP_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_OFFER_STOP_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_OFFER_STOP_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_OFFER_STOP_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_OFFER_STOP_DATE,
  MA01_VENDOR_CHANNEL,
  IF(
    MA01_CANCELLATION_NOTIFY_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_CANCELLATION_NOTIFY_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_CANCELLATION_NOTIFY_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_CANCELLATION_NOTIFY_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_CANCELLATION_NOTIFY_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_CANCELLATION_NOTIFY_DATE,
  IF(
    MA01_ENROLLMENT_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_ENROLLMENT_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_ENROLLMENT_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_ENROLLMENT_DATE,
  IF(
    MA01_RE_ENROLLMENT_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_RE_ENROLLMENT_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_RE_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_RE_ENROLLMENT_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_RE_ENROLLMENT_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_RE_ENROLLMENT_DATE,
  MA01_EXTERNAL_MONTHS_REMAIN,
  MA01_CANCEL_LAG_NUM_OF_MONTHS,
  MA01_ENROLL_CONFIRMATION_NBR,
  MA01_CANCEL_CONFIRMATION_NBR,
  MA01_OPERATOR_ENTRY_ID,
  MA01_OFFER_OVERRIDE_NBR_CYCLES,
  IF(
    MA01_LAST_ADJUSTMENT_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_LAST_ADJUSTMENT_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_LAST_ADJUSTMENT_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_LAST_ADJUSTMENT_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_LAST_ADJUSTMENT_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_LAST_ADJUSTMENT_DATE,
  MA01_ENROLLMENT_PROVINCE_CODE,
  IF(
    MA01_GENERAL_MAINT_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_GENERAL_MAINT_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_GENERAL_MAINT_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_GENERAL_MAINT_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_GENERAL_MAINT_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_GENERAL_MAINT_DATE,
  IF(
    MA01_CUST_DATE_OF_BIRTH IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_CUST_DATE_OF_BIRTH AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_CUST_DATE_OF_BIRTH AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_CUST_DATE_OF_BIRTH AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_CUST_DATE_OF_BIRTH AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_CUST_DATE_OF_BIRTH,
  IF(
    MA01_INACTIVE_DATE IS NOT NULL
    AND CAST(SUBSTR(CAST(MA01_INACTIVE_DATE AS STRING), 1, 4) AS INT64) > 0
    AND CAST(SUBSTR(CAST(MA01_INACTIVE_DATE AS STRING), 5, 3) AS INT64) BETWEEN 1 AND 366,
    DATETIME(DATE_ADD(
      DATE(CONCAT(CAST(SUBSTR(CAST(MA01_INACTIVE_DATE AS STRING), 1, 4) AS STRING), '-01-01')),
      INTERVAL CAST(SUBSTR(CAST(MA01_INACTIVE_DATE AS STRING), 5, 3) AS INT64) - 1 DAY
    )),
    NULL
  ) AS MA01_INACTIVE_DATE,
  MA01_OFFER_OVERRIDE_AMT,
  FILE_CREATE_DT
FROM
  MA01
INNER JOIN
  MA00
USING
  ( MAST_ACCOUNT_ID,
    MA00_APPLICATION_SUFFIX)