dag_id: aml_transaction_eve_feed
dag_name: aml_transaction_eve_feed
dag_owner: team-defenders-alerts
feed_name: eve
idl_cutoff_date: 2007-01-01
bqtable_eve_transaction_feed: pcb-{env}-curated.cots_aml_verafin.TRANSACTION_EVE_FEED
staging_bucket: pcb-{env}-staging-extract
bq_to_gcs_folder: aml/transaction
destination_bq_dataset: cots_aml_verafin
bq_table_name: TRANSACTION_EVE_FEED
staging_folder: aml/pcb_verafin_veratran
source_headers_file_path: aml_processing/csv_headers_files/eve_transaction_headers.csv.gz
destination_headers_file_path: aml/transaction/eve_feed/eve_transaction_headers.csv.gz
bqtable_product_transaction: pcb-{env}-curated.domain_account_management.PRODUCT_TRANSACTION_VW
bqtable_customer: pcb-{env}-curated.domain_customer_management.CUSTOMER
outbound_bucket: verafin-outbound-pcb{env_suffix}
outbound_folder: pcb_verafin_aml
filename_prefix: pcb_verafin_veratran_save
filename_extension: "{file_env}"
transaction_history_table: pcb-{env}-curated.cots_aml_verafin.TRANSACTION_FEED_HISTORICAL_RECORDS_TABLE
tbl_curated_transaction_feed_schema: aml_processing/transaction/TRANSACTION_FEED_SCHEMA.json
sql_eve_create_table_path: aml_processing/transaction/eve/queries/create_eve_transaction_table.sql
sql_eve_insert_table_path: aml_processing/transaction/eve/queries/load_eve_feed_table.sql
sql_feed_history_table_path: aml_processing/transaction/eve/queries/feed_history_table.sql
sql_bq_data_check_query_path: aml_processing/transaction/eve/queries/bq_data_check_query.sql