CREATE TABLE IF NOT EXISTS `pcb-{env}-landing.domain_customer_contact_centre.CALL_CONVERSATION_STATE`
(
    CONVERSATION_ID STRING,
    CUSTOMER_ID STRING,
    ACCOUNT_ID STRING,
    CARD_ID STRING,
    APPLICATION_NAME STRING,
    DNIS STRING,
    ANI STRING,
    CALL_START_TIMESTAMP TIMESTAMP,
    CALL_END_TIMESTAMP TIMESTAMP,
    SELECTED_LANGUAGE STRING,
    PAYLOAD STRING,
    VERSION STRING,
    INGESTION_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    METADATA STRUCT<
        STREAM_NAME STRING,
        TOPIC_PARTITION INT64,
        PARTITION_OFFSET INT64,
        STREAM_OFFSET INT64,
        OFFSET_DIFF INT64,
        ENVIRONMENT STRING,
        TOPIC_VERSION INT64
    >
);
