CREATE OR REPLACE TABLE
  `{staging_table_id}`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
) AS
SELECT
FILE_UUID,
RECORD_NUM,
GEN_CLIENT_NUM,
GEN_REQUEST_TYPE,
ISSUE_TYPE,
GEN_PHOTO_IND,
GEN_CRV_IND,
GEN_MC_VISA_IND,
GEN_ACCT_NBR_ON_CARD,
GEN_ACCT_IDENTIFIER,
GEN_NUM_CARDS_IN_MLR,
GEN_DELIVERY_CODE,
GEN_LANGUAGE_CODE,
GEN_REGION_CODE,
GEN_CREDIT_LIMIT,
GEN_CARDHOLDER_NAME,
GEN_ADDRESS_LINE2,
GEN_ADDRESS_LINE3,
GEN_ADDRESS_LINE4,
GEN_ADDRESS_LINE5,
GEN_MLR_MSG_LINE1,
GEN_MLR_MSG_LINE2,
GEN_MLR_MSG_LINE3,
GEN_MLR_MSG_LINE4,
GEN_MLR_MSG_LINE5,
GEN_MLR_MSG_LINE6,
GEN_RTN_ADD_LINE1,
GEN_RTN_ADD_LINE2,
GEN_EMBOSS_LINE1,
GEN_EMBOSS_LINE2,
GEN_EMBOSS_LINE3,
GEN_EMBOSS_LINE4,
GEN_DEBOSS_LINE1,
GEN_COERCIVITY,
GEN_ENC_TRACK1,
GEN_ENC_TRACK2,
GEN_MAILER_FORM_NBR,
GEN_INSERT_ID,
GEN_ENV_FORM_NBR,
GEN_PLASTIC_FORM_NBR,
GEN_CMID,
GEN_PROMO_SOLICIT_CODE,
GEN_CUSTOMER_ID,
GEN_PAN_SEQ_NBR,
GEN_DISCLOSURE_GRP,
GEN_ALTERNATE_DISCLOSURE_GRP,
GEN_CUST_TYPE,
GEN_CONTACTLESS_IND,
GEN_CPC,
CH1_START_CODE,
SAFE_CAST(CH1_CHIP_DATA_LEN AS INT64) AS CH1_CHIP_DATA_LEN,
TO_BASE64(FROM_HEX(CH1_APPLICATION_ID)) AS CH1_APPLICATION_ID,
SAFE_CAST(CH1_APPLICATION_LEN AS INT64) AS CH1_APPLICATION_LEN,
TO_BASE64(FROM_HEX(CH1_KEK_HD_ID)) AS CH1_KEK_HD_ID,
SAFE_CAST(CH1_TLV_DATA_LEN AS INT64) AS CH1_TLV_DATA_LEN,
TO_BASE64(FROM_HEX(CH1_TLV_DATA_PLUS_BYTES)) AS CH1_TLV_DATA_PLUS_BYTES,
CASE
    WHEN ENCRYPTED_UDK IS NOT NULL THEN TO_BASE64(FROM_HEX(ENCRYPTED_UDK))
    ELSE NULL END AS ENCRYPTED_UDK,
CASE
    WHEN KDI IS NOT NULL THEN TO_BASE64(FROM_HEX(KDI))
    ELSE NULL END AS KDI,
CASE
    WHEN IV_CVC_TRACK1 IS NOT NULL THEN TO_BASE64(FROM_HEX(IV_CVC_TRACK1))
    ELSE NULL END AS IV_CVC_TRACK1,
CASE
    WHEN IV_CVC_TRACK2 IS NOT NULL THEN TO_BASE64(FROM_HEX(IV_CVC_TRACK2))
    ELSE NULL END AS IV_CVC_TRACK2,
CASE
    WHEN PAY_PASS_TRACK1_DATA IS NOT NULL THEN TO_BASE64(FROM_HEX(PAY_PASS_TRACK1_DATA))
    ELSE NULL END AS PAY_PASS_TRACK1_DATA,
CASE
    WHEN PAY_PASS_TRACK2_DATA IS NOT NULL THEN TO_BASE64(FROM_HEX(PAY_PASS_TRACK2_DATA))
    ELSE NULL END AS PAY_PASS_TRACK2_DATA,
CASE
    WHEN TRACK2_EQUIVALENT IS NOT NULL THEN TO_BASE64(FROM_HEX(TRACK2_EQUIVALENT))
    ELSE NULL END AS TRACK2_EQUIVALENT,
CASE
    WHEN PIN_BLOCK IS NOT NULL THEN TO_BASE64(FROM_HEX(PIN_BLOCK))
    ELSE NULL END AS PIN_BLOCK,
NULL AS INSTANT_ISSUANCE_ORCHESTRATION_ID,
NULL AS EMBOSSING_REQUEST_FLOW

FROM `pcb-{env}-curated.domain_card_management.{curated_table}`
WHERE FILE_UUID = '{uuid_filter}'
;


EXPORT DATA
  OPTIONS (
    uri = '{output_uri_landing}',
    format = 'PARQUET',
    overwrite = true
    )
AS
(SELECT
        SAFE_CAST(FILE_UUID AS STRING) AS FILE_UUID,
        SAFE_CAST(RECORD_NUM AS STRING) AS RECORD_NUM,
        SAFE_CAST(GEN_CLIENT_NUM AS INT64) AS GEN_CLIENT_NUM,
        SAFE_CAST(GEN_REQUEST_TYPE AS STRING) AS GEN_REQUEST_TYPE,
        SAFE_CAST(ISSUE_TYPE AS STRING) AS ISSUE_TYPE,
        SAFE_CAST(GEN_PHOTO_IND AS STRING) AS GEN_PHOTO_IND,
        SAFE_CAST(GEN_CRV_IND AS STRING) AS GEN_CRV_IND,
        SAFE_CAST(GEN_MC_VISA_IND AS STRING) AS GEN_MC_VISA_IND,
        SAFE_CAST(GEN_ACCT_NBR_ON_CARD AS STRING) AS GEN_ACCT_NBR_ON_CARD,
        SAFE_CAST(GEN_ACCT_IDENTIFIER AS STRING) AS GEN_ACCT_IDENTIFIER,
        SAFE_CAST(GEN_NUM_CARDS_IN_MLR AS INT64) AS GEN_NUM_CARDS_IN_MLR,
        SAFE_CAST(GEN_DELIVERY_CODE AS STRING) AS GEN_DELIVERY_CODE,
        SAFE_CAST(GEN_LANGUAGE_CODE AS STRING) AS GEN_LANGUAGE_CODE,
        SAFE_CAST(GEN_REGION_CODE AS STRING) AS GEN_REGION_CODE,
        SAFE_CAST(GEN_CREDIT_LIMIT AS STRING) AS GEN_CREDIT_LIMIT,
        SAFE_CAST(GEN_CARDHOLDER_NAME AS STRING) AS GEN_CARDHOLDER_NAME,
        SAFE_CAST(GEN_ADDRESS_LINE2 AS STRING) AS GEN_ADDRESS_LINE2,
        SAFE_CAST(GEN_ADDRESS_LINE3 AS STRING) AS GEN_ADDRESS_LINE3,
        SAFE_CAST(GEN_ADDRESS_LINE4 AS STRING) AS GEN_ADDRESS_LINE4,
        SAFE_CAST(GEN_ADDRESS_LINE5 AS STRING) AS GEN_ADDRESS_LINE5,
        SAFE_CAST(GEN_MLR_MSG_LINE1 AS STRING) AS GEN_MLR_MSG_LINE1,
        SAFE_CAST(GEN_MLR_MSG_LINE2 AS STRING) AS GEN_MLR_MSG_LINE2,
        SAFE_CAST(GEN_MLR_MSG_LINE3 AS STRING) AS GEN_MLR_MSG_LINE3,
        SAFE_CAST(GEN_MLR_MSG_LINE4 AS STRING) AS GEN_MLR_MSG_LINE4,
        SAFE_CAST(GEN_MLR_MSG_LINE5 AS STRING) AS GEN_MLR_MSG_LINE5,
        SAFE_CAST(GEN_MLR_MSG_LINE6 AS STRING) AS GEN_MLR_MSG_LINE6,
        SAFE_CAST(GEN_RTN_ADD_LINE1 AS STRING) AS GEN_RTN_ADD_LINE1,
        SAFE_CAST(GEN_RTN_ADD_LINE2 AS STRING) AS GEN_RTN_ADD_LINE2,
        SAFE_CAST(GEN_EMBOSS_LINE1 AS STRING) AS GEN_EMBOSS_LINE1,
        SAFE_CAST(GEN_EMBOSS_LINE2 AS STRING) AS GEN_EMBOSS_LINE2,
        SAFE_CAST(GEN_EMBOSS_LINE3 AS STRING) AS GEN_EMBOSS_LINE3,
        SAFE_CAST(GEN_EMBOSS_LINE4 AS STRING) AS GEN_EMBOSS_LINE4,
        SAFE_CAST(GEN_DEBOSS_LINE1 AS STRING) AS GEN_DEBOSS_LINE1,
        SAFE_CAST(GEN_COERCIVITY AS STRING) AS GEN_COERCIVITY,
        SAFE_CAST(GEN_ENC_TRACK1 AS STRING) AS GEN_ENC_TRACK1,
        SAFE_CAST(GEN_ENC_TRACK2 AS STRING) AS GEN_ENC_TRACK2,
        SAFE_CAST(GEN_MAILER_FORM_NBR AS STRING) AS GEN_MAILER_FORM_NBR,
        SAFE_CAST(GEN_INSERT_ID AS STRING) AS GEN_INSERT_ID,
        SAFE_CAST(GEN_ENV_FORM_NBR AS STRING) AS GEN_ENV_FORM_NBR,
        SAFE_CAST(GEN_PLASTIC_FORM_NBR AS STRING) AS GEN_PLASTIC_FORM_NBR,
        SAFE_CAST(GEN_CMID AS STRING) AS GEN_CMID,
        SAFE_CAST(GEN_PROMO_SOLICIT_CODE AS STRING) AS GEN_PROMO_SOLICIT_CODE,
        SAFE_CAST(GEN_CUSTOMER_ID AS INT64) AS GEN_CUSTOMER_ID,
        SAFE_CAST(GEN_PAN_SEQ_NBR AS INT64) AS GEN_PAN_SEQ_NBR,
        SAFE_CAST(GEN_DISCLOSURE_GRP AS STRING) AS GEN_DISCLOSURE_GRP,
        SAFE_CAST(GEN_ALTERNATE_DISCLOSURE_GRP AS STRING) AS GEN_ALTERNATE_DISCLOSURE_GRP,
        SAFE_CAST(GEN_CUST_TYPE AS STRING) AS GEN_CUST_TYPE,
        SAFE_CAST(GEN_CONTACTLESS_IND AS STRING) AS GEN_CONTACTLESS_IND,
        SAFE_CAST(GEN_CPC AS STRING) AS GEN_CPC,
        SAFE_CAST(CH1_START_CODE AS STRING) AS CH1_START_CODE,
        SAFE_CAST(CH1_CHIP_DATA_LEN AS INT64) AS CH1_CHIP_DATA_LEN,
        SAFE_CAST(CH1_APPLICATION_ID AS STRING) AS CH1_APPLICATION_ID,
        SAFE_CAST(CH1_APPLICATION_LEN AS INT64) AS CH1_APPLICATION_LEN,
        SAFE_CAST(CH1_KEK_HD_ID AS STRING) AS CH1_KEK_HD_ID,
        SAFE_CAST(CH1_TLV_DATA_LEN AS INT64) AS CH1_TLV_DATA_LEN,
        SAFE_CAST(CH1_TLV_DATA_PLUS_BYTES AS STRING) AS CH1_TLV_DATA_PLUS_BYTES,
        SAFE_CAST(ENCRYPTED_UDK AS STRING) AS ENCRYPTED_UDK,
        SAFE_CAST(KDI AS STRING) AS KDI,
        SAFE_CAST(IV_CVC_TRACK1 AS STRING) AS IV_CVC_TRACK1,
        SAFE_CAST(IV_CVC_TRACK2 AS STRING) AS IV_CVC_TRACK2,
        SAFE_CAST(PAY_PASS_TRACK1_DATA AS STRING) AS PAY_PASS_TRACK1_DATA,
        SAFE_CAST(PAY_PASS_TRACK2_DATA AS STRING) AS PAY_PASS_TRACK2_DATA,
        SAFE_CAST(TRACK2_EQUIVALENT AS STRING) AS TRACK2_EQUIVALENT,
        SAFE_CAST(PIN_BLOCK AS STRING) AS PIN_BLOCK
FROM `{staging_table_id}`);