-- Monthly Loyalty Subscription Usage LifeTime Data Sync.
CREATE OR REPLACE TABLE
  `{staging_table_id}`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 14 DAY)
) AS
SELECT
  loyalty_subscription_usage.PCF_CUSTOMER_ID,
  loyalty_subscription_usage.CARD_BIN,
  loyalty_subscription_usage.LOYALTY_PARTNER,
  loyalty_subscription_usage.SUBSCRIPTION_TYPE,
  loyalty_subscription_usage.USAGE_COUNT,
  SAFE_CAST(0 AS INTEGER) AS POINTS_EARNED,
  SAFE_CAST(0 AS INTEGER) AS MONETARY_VALUE,
  CURRENT_DATETIME() AS CREATE_DT,
  'INITIAL_LOAD' AS CREATE_USER_ID,
  CURRENT_DATETIME() AS UPDATE_DT,
  'MONTHLY_LOAD' AS UPDATE_USER_ID
FROM `pcb-{env}-landing.domain_loyalty.LOYALTY_SUBSCRIPTION_USAGE` loyalty_subscription_usage
WHERE loyalty_subscription_usage.TX_YEAR = EXTRACT(YEAR FROM DATE_SUB(CURRENT_DATE(), INTERVAL 2 MONTH))
AND loyalty_subscription_usage.TX_MONTH = EXTRACT(MONTH FROM DATE_SUB(CURRENT_DATE(), INTERVAL 2 MONTH));

-- Load staging table into landing zone table.
MERGE `pcb-{env}-landing.domain_loyalty.LOYALTY_SUBSCRIPTION_USAGE_LIFETIME` T
USING `{staging_table_id}` S
ON T.PCF_CUSTOMER_ID = S.PCF_CUSTOMER_ID
AND T.CARD_BIN = S.CARD_BIN
AND T.LOYALTY_PARTNER = S.LOYALTY_PARTNER
AND T.SUBSCRIPTION_TYPE = S.SUBSCRIPTION_TYPE
WHEN MATCHED THEN
  UPDATE SET
  T.USAGE_COUNT = S.USAGE_COUNT + T.USAGE_COUNT,
  T.POINTS_EARNED = S.POINTS_EARNED + T.POINTS_EARNED,
  T.MONETARY_VALUE = S.MONETARY_VALUE + T.MONETARY_VALUE,
  T.UPDATE_DT = S.UPDATE_DT,
  T.UPDATE_USER_ID = S.UPDATE_USER_ID
WHEN NOT MATCHED THEN
  INSERT (
    PCF_CUSTOMER_ID,
    CARD_BIN,
    LOYALTY_PARTNER,
    SUBSCRIPTION_TYPE,
    USAGE_COUNT,
    POINTS_EARNED,
    MONETARY_VALUE,
    CREATE_DT,
    CREATE_USER_ID,
    UPDATE_DT,
    UPDATE_USER_ID
  )
  VALUES (
    S.PCF_CUSTOMER_ID,
    S.CARD_BIN,
    S.LOYALTY_PARTNER,
    S.SUBSCRIPTION_TYPE,
    S.USAGE_COUNT,
    S.POINTS_EARNED,
    S.MONETARY_VALUE,
    S.CREATE_DT,
    S.CREATE_USER_ID,
    S.UPDATE_DT,
    S.UPDATE_USER_ID
  );