-- Monthly Loyalty Points Earned LifeTime Data Sync.
CREATE OR REPLACE TABLE
  `{staging_table_id}`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 14 DAY)
) AS
SELECT
  loyalty_points_earned.PCF_CUSTOMER_ID,
  loyalty_points_earned.CARD_BIN,
  loyalty_points_earned.LOYALTY_PARTNER,
  loyalty_points_earned.EARNING_CATEGORY,
  loyalty_points_earned.TRANSACTION_TYPE,
  loyalty_points_earned.PURCHASE_METHOD,
  loyalty_points_earned.POINTS_EARNED,
  CURRENT_DATETIME() AS CREATE_DT,
  'INITIAL_LOAD' AS CREATE_USER_ID,
  CURRENT_DATETIME() AS UPDATE_DT,
  'MONTHLY_LOAD' AS UPDATE_USER_ID
FROM `pcb-{env}-landing.domain_loyalty.LOYALTY_POINTS_EARNED` loyalty_points_earned
WHERE loyalty_points_earned.TX_YEAR = EXTRACT(YEAR FROM DATE_SUB(CURRENT_DATE(), INTERVAL 2 MONTH))
AND loyalty_points_earned.TX_MONTH = EXTRACT(MONTH FROM DATE_SUB(CURRENT_DATE(), INTERVAL 2 MONTH));

-- Load staging table into landing zone table.
MERGE `pcb-{env}-landing.domain_loyalty.LOYALTY_POINTS_EARNED_LIFETIME` T
USING `{staging_table_id}` S
ON T.PCF_CUSTOMER_ID = S.PCF_CUSTOMER_ID
AND T.CARD_BIN = S.CARD_BIN
AND T.LOYALTY_PARTNER = S.LOYALTY_PARTNER
AND T.EARNING_CATEGORY = S.EARNING_CATEGORY
AND T.TRANSACTION_TYPE = S.TRANSACTION_TYPE
AND T.PURCHASE_METHOD = S.PURCHASE_METHOD
WHEN MATCHED THEN
  UPDATE SET
  T.POINTS_EARNED = S.POINTS_EARNED + T.POINTS_EARNED,
  T.UPDATE_DT = S.UPDATE_DT,
  T.UPDATE_USER_ID = S.UPDATE_USER_ID
WHEN NOT MATCHED THEN
  INSERT (
    PCF_CUSTOMER_ID,
    CARD_BIN,
    LOYALTY_PARTNER,
    EARNING_CATEGORY,
    TRANSACTION_TYPE,
    PURCHASE_METHOD,
    POINTS_EARNED,
    CREATE_DT,
    CREATE_USER_ID,
    UPDATE_DT,
    UPDATE_USER_ID
  )
  VALUES (
    S.PCF_CUSTOMER_ID,
    S.CARD_BIN,
    S.LOYALTY_PARTNER,
    S.EARNING_CATEGORY,
    S.TRANSACTION_TYPE,
    S.PURCHASE_METHOD,
    S.POINTS_EARNED,
    S.CREATE_DT,
    S.CREATE_USER_ID,
    S.UPDATE_DT,
    S.UPDATE_USER_ID
  );