-- Index4 T0040: Insert CIF Snapshot into Landing Table
-- This query creates a snapshot of Customer Information File (CIF) data by joining
-- card and account information from the curated zone.
--
-- Data Flow:
--   pcb-prod-curated.domain_account_management.CIF_CARD_CURR (card/customer data)
--     + pcb-prod-curated.domain_account_management.CIF_ACCOUNT_CURR (account data)
--     → THIS QUERY joins and consolidates
--     → pcb-{env}-landing.domain_scoring.SCORING_PREP_CIF_SNAPSHOT (108 fields)
--
-- Business Purpose:
--   CIF snapshot provides point-in-time customer and account information:
--   - Customer demographics (name, address, phone, DOB)
--   - Account status and flags (closed, charge-off, fraud, bankruptcy)
--   - Credit information (limits, balances, scores, APRs)
--   - Relationship data (primary/authorized user status)
--   - Risk indicators (VIP, test accounts, collection scenarios)
--
-- Parameters:
--   {report_year} - Report year (e.g., 2024)
--   {report_month} - Report month (e.g., 04)
--   {job_id} - Airflow job ID for audit tracking
--   {env} - Environment (dev, staging, prod)
INSERT INTO
  `pcb-{env}-landing.domain_scoring.SCORING_PREP_CIF_SNAPSHOT` (
    REPORT_DATE,
    YYYY,
    MM,
    DD,
    MAST_ACCOUNT_ID,
    CIFP_CLIENT_PRODUCT_CODE,
    CIFP_VIP,
    CIFP_CYCLE_NUM,
    CIFP_DT_LAST_STATEMENT,
    CIFP_DATE_OPEN,
    CIFP_CREDIT_LIMIT,
    CIFP_CRVK_DATE,
    CIFP_CLOSED_MAINT_DATE,
    CIFP_CRVK_MAINT_DATE,
    CIFP_FIRST_USE_DATE,
    CIFP_DATE_CHARGE_OFF,
    CIFP_CURRENT_BALANCE,
    CIFP_PREV_STAT_BAL,
    CIFP_MINIMUM_PAY_DUE,
    CIFP_AMT_ACT_CRG_OFF,
    CIFP_SCE0_CB_SCORE,
    CIFP_SCE0_DATE_CB_SCORE,
    CIFP_ACQUISITION_CODE,
    CIFP_PASTDUE_AT_CYCLE,
    CIFP_DATE_PAYMENT_DUE,
    CIFP_ACTUAL_DAYS_PASTDUE,
    CIFP_SPID_TYPE5,
    CIFP_TEST_DIGIT_TYPE5,
    AM00_STATF_CHGOFF_LAG,
    AM00_STATF_POTENTIAL_PURGE,
    AM00_STATF_CREDIT_COUNSELING,
    CIFP_SECONDARY_CHGOFF_DATE,
    CIFP_COLL_SCENARIO_ID,
    CIFP_COLLECTION_AGENCY,
    AM00_BANKRUPTCY_TYPE,
    AM00_STATC_CLOSED,
    AM00_STATC_CHARGEOFF,
    AM00_STATC_CREDIT_REVOKED,
    AM00_STATC_CURRENT_PAST_DUE,
    AM00_STATC_SECURITY_FRAUD,
    AM00_STATF_INACTIVE,
    CIFP_TRIAD_SCORE_ALIGNED,
    CIFP_AVAIL_AMT_TO_BUY,
    CIFP_DT_SEC_FRAUD_STAT,
    CIFP_DATE_FRAUD,
    AM00_STATF_FRAUD,
    CIFP_DATE_EXPIRED,
    APPLICATION_ID,
    CIFP_DT_LAST_LIMIT_CHG,
    CIFP_AMT_PAY_CTD,
    AM00_STATC_DISPUTE,
    AM00_TYPEC_VIP,
    AM00_STATF_DECLINED_REISSUE,
    AM00_STATC_APPLICATION,
    AM00_STATC_FIXED_PAYMENT,
    AM00_STATC_RETURN_MAIL,
    REC_LOAD_DT_TM_STAMP,
    AM00_STATC_WATCH,
    CIFP_CUSTOM_DATA_81,
    CIFP_SCE0_CB_SCORE_FIRST,
    CIFP_SEC_POOL_ID1,
    CIFP_WAIVE_FCHG_FLAG,
    CIFP_DT_LAST_DSCL_GRP_CHG,
    CIFP_DISCLOSURE_GROUP,
    CIFP_ALT_DISCLOSURE_GRP,
    CIFP_PURCHASE_APR,
    CIFP_CASH_APR,
    CIFP_CUSTOM_DATA_11,
    CIFP_CUSTOM_DATA_22,
    CIFP_CUSTOM_DATA_41,
    CIFP_RELATIONSHIP_STAT,
    CIFP_TRANS_FROM_ACCT_NO,
    CIFP_TRANS_TO_ACCT_NO,
    CIFP_DATE_TRANSFER,
    CIFP_ACCOUNT_NUM,
    CIFP_ADDRESS_LINE1,
    CIFP_CITY,
    CIFP_STATE,
    CIFP_ZIP_CODE,
    CIFP_COUNTRY_CODE,
    CIFP_HOME_PHONE_NUM,
    CIFP_BUS_PHONE_NUM,
    CIFP_PHONE_ALT1,
    CIFP_DATE_OF_BIRTH,
    CIFP_PREFIX,
    CIFP_FIRST_NAME,
    CIFP_MIDDLE_INITIAL,
    CIFP_LAST_NAME,
    CIFP_SUFFIX,
    CIFP_CRV_STATUS,
    CIFP_CRV_DATE,
    CIFP_SECURITY_FRAUD,
    CIFP_STATC_WATCH,
    CIFP_STATC_WATCH_DT_MAINT,
    CIFP_CUSTOMER_TYPE,
    CIFP_LANGUAGE_CODE,
    CIFP_EMAIL_ADDRESS_LINE1,
    CIFP_PRIM_CARD_ID,
    CIFP_NUM_CUST_CARDS_OUT_PRIM,
    CIFP_CM00_EMPLOYEE,
    CIFP_SPID_TYPE6,
    CIFP_TEST_DIGIT_TYPE6,
    CIFP_CUSTOMER_ID_1,
    CIFP_CUSTOMER_ID_2,
    CIFP_PCF_CUST_ID,
    REC_LOAD_TIMESTAMP,
    JOB_ID
  ) 
WITH -- Step 1: Extract card/customer data from CIF_CARD_CURR
  card_curr_data AS (
    SELECT DISTINCT
      FILE_CREATE_DT,
      EXTRACT(YEAR FROM FILE_CREATE_DT) AS yyyy,
      EXTRACT(MONTH FROM FILE_CREATE_DT) AS mm,
      EXTRACT(DAY FROM FILE_CREATE_DT) AS dd,
      CIFP_RELATIONSHIP_STAT AS cifp_relationship_stat,
      CIFP_TRANS_FROM_ACCT_NO AS cifp_trans_from_acct_no,
      CIFP_DATE_TRANSFER AS cifp_date_transfer,
      CIFP_ACCOUNT_ID6 AS mast_account_id,
      CIFP_ACCOUNT_NUM AS cifp_account_num,
      CIFP_ADDRESS_LINE1 AS cifp_address_line1,
      CIFP_CITY AS cifp_city,
      CIFP_STATE AS cifp_state,
      CIFP_ZIP_CODE AS cifp_zip_code,
      CIFP_COUNTRY_CODE AS cifp_country_code,
      CIFP_HOME_PHONE_NUM AS cifp_home_phone_num,
      CIFP_BUS_PHONE_NUM AS cifp_bus_phone_num,
      CIFP_PHONE_ALT1 AS cifp_phone_alt1,
      DATE(CIFP_DATE_OF_BIRTH) AS cifp_date_of_birth,
      CIFP_PREFIX AS cifp_prefix,
      CIFP_FIRST_NAME AS cifp_first_name,
      CIFP_MIDDLE_INITIAL AS cifp_middle_initial,
      CIFP_LAST_NAME AS cifp_last_name,
      CIFP_SUFFIX AS cifp_suffix,
      CIFP_CRV_STATUS AS cifp_crv_status,
      DATE(CIFP_CRV_DATE) AS cifp_crv_date,
      CIFP_SECURITY_FRAUD AS cifp_security_fraud,
      CIFP_STATC_WATCH AS cifp_statc_watch,
      DATE(CIFP_STATC_WATCH_DT_MAINT) AS cifp_statc_watch_dt_maint,
      CIFP_CUSTOMER_TYPE AS cifp_customer_type,
      CIFP_LANGUAGE_CODE AS cifp_language_code,
      CIFP_EMAIL_ADDRESS_LINE1 AS cifp_email_address_line1,
      CIFP_PRIM_CARD_ID AS cifp_prim_card_id,
      CIFP_NUM_CUST_CARDS_OUT_PRIM AS cifp_num_cust_cards_out_prim,
      CIFP_CM00_EMPLOYEE AS cifp_cm00_employee,
      CIFP_SPID_TYPE6 AS cifp_spid_type6,
      CIFP_TEST_DIGIT_TYPE6 AS cifp_test_digit_type6,
      CIFP_TRANS_TO_ACCT_NO AS cifp_trans_to_acct_no,
      CIFP_CUSTOMER_ID_1 AS cifp_customer_id_1,
      CIFP_CUSTOMER_ID_2 AS cifp_customer_id_2,
      CIFP_PCF_CUST_ID AS cifp_pcf_cust_id
    FROM
      `pcb-{env}-curated.domain_account_management.CIF_CARD_CURR`
    WHERE
      CIFP_CUSTOMER_TYPE = 0 -- Primary customers only
      AND (
        CIFP_RELATIONSHIP_STAT IN ('', ' ', 'A')
        OR CIFP_RELATIONSHIP_STAT IS NULL
      ) -- Active relationships
    ORDER BY
      CIFP_ACCOUNT_ID6 ASC,
      FILE_CREATE_DT DESC
  ),
  -- Step 2: Extract account data from CIF_ACCOUNT_CURR
  account_curr_data AS (
    SELECT DISTINCT
      FILE_CREATE_DT,
      EXTRACT(YEAR FROM FILE_CREATE_DT) AS yyyy,
      EXTRACT(MONTH FROM FILE_CREATE_DT) AS mm,
      EXTRACT(DAY FROM FILE_CREATE_DT) AS dd,
      CIFP_ACCOUNT_ID5 AS mast_account_id,
      CIFP_CLIENT_PRODUCT_CODE AS cifp_client_product_code,
      CIFP_VIP AS cifp_vip,
      CIFP_CYCLE_NUM AS cifp_cycle_num,
      DATE(CIFP_DT_LAST_STATEMENT) AS cifp_dt_last_statement,
      DATE(CIFP_DATE_OPEN) AS cifp_date_open,
      CIFP_CREDIT_LIMIT AS cifp_credit_limit,
      DATE(CIFP_CLOSED_MAINT_DATE) AS cifp_closed_maint_date,
      DATE(CIFP_CRVK_MAINT_DATE) AS cifp_crvk_maint_date,
      DATE(CIFP_FIRST_USE_DATE) AS cifp_first_use_date,
      DATE(CIFP_DATE_CHARGE_OFF) AS cifp_date_charge_off,
      CIFP_CURRENT_BALANCE AS cifp_current_balance,
      CIFP_PREV_STAT_BAL AS cifp_prev_stat_bal,
      CIFP_MINIMUM_PAY_DUE AS cifp_minimum_pay_due,
      CIFP_AMT_ACT_CRG_OFF AS cifp_amt_act_crg_off,
      CIFP_SCE0_CB_SCORE AS cifp_sce0_cb_score,
      DATE(CIFP_SCE0_DATE_CB_SCORE) AS cifp_sce0_date_cb_score,
      CIFP_ACQUISITION_CODE AS cifp_acquisition_code,
      CIFP_PASTDUE_AT_CYCLE AS cifp_pastdue_at_cycle,
      CIFP_DATE_PAYMENT_DUE AS cifp_date_payment_due,
      CIFP_ACTUAL_DAYS_PASTDUE AS cifp_actual_days_pastdue,
      CIFP_SPID_TYPE5 AS cifp_spid_type5,
      CIFP_TEST_DIGIT_TYPE5 AS cifp_test_digit_type5,
      CIFP_SECONDARY_CHGOFF_DATE AS cifp_secondary_chgoff_date,
      CIFP_COLL_SCENARIO_ID AS cifp_coll_scenario_id,
      CIFP_COLLECTION_AGENCY AS cifp_collection_agency,
      AM00_BANKRUPTCY_TYPE AS am00_bankruptcy_type,
      AM00_STATC_CLOSED AS am00_statc_closed,
      AM00_STATC_CHARGEOFF AS am00_statc_chargeoff,
      AM00_STATC_CREDIT_REVOKED AS am00_statc_credit_revoked,
      AM00_STATC_CURRENT_PAST_DUE AS am00_statc_current_past_due,
      AM00_STATC_SECURITY_FRAUD AS am00_statc_security_fraud,
      AM00_STATF_INACTIVE AS am00_statf_inactive,
      DATE(CIFP_CRVK_DATE) AS cifp_crvk_date,
      AM00_STATF_CHGOFF_LAG AS am00_statf_chgoff_lag,
      AM00_STATF_POTENTIAL_PURGE AS am00_statf_potential_purge,
      AM00_STATF_CREDIT_COUNSELING AS am00_statf_credit_counseling,
      CIFP_TRIAD_SCORE_ALIGNED AS cifp_triad_score_aligned,
      CIFP_AVAIL_AMT_TO_BUY AS cifp_avail_amt_to_buy,
      DATE(CIFP_DT_SEC_FRAUD_STAT) AS cifp_dt_sec_fraud_stat,
      DATE(CIFP_DATE_FRAUD) AS cifp_date_fraud,
      AM00_STATF_FRAUD AS am00_statf_fraud,
      DATE(CIFP_DATE_EXPIRED) AS cifp_date_expired,
      CAST(NULL AS STRING) AS application_id,
      CIFP_CUSTOM_DATA_81 AS cifp_custom_data_81,
      DATE(CIFP_DT_LAST_LIMIT_CHG) AS cifp_dt_last_limit_chg,
      CIFP_AMT_PAY_CTD AS cifp_amt_pay_ctd,
      AM00_STATC_DISPUTE AS am00_statc_dispute,
      AM00_TYPEC_VIP AS am00_typec_vip,
      AM00_STATF_DECLINED_REISSUE AS am00_statf_declined_reissue,
      AM00_STATC_APPLICATION AS am00_statc_application,
      AM00_STATC_FIXED_PAYMENT AS am00_statc_fixed_payment,
      AM00_STATC_RETURN_MAIL AS am00_statc_return_mail,
      DATE(REC_LOAD_TIMESTAMP) AS rec_load_timestamp_source,
      AM00_STATC_WATCH AS am00_statc_watch,
      CIFP_SCE0_CB_SCORE_FIRST AS cifp_sce0_cb_score_first,
      CIFP_SEC_POOL_ID1 AS cifp_sec_pool_id1,
      CIFP_WAIVE_FCHG_FLAG AS cifp_waive_fchg_flag,
      DATE(CIFP_DT_LAST_DSCL_GRP_CHG) AS cifp_dt_last_dscl_grp_chg,
      CIFP_DISCLOSURE_GROUP AS cifp_disclosure_group,
      CIFP_ALT_DISCLOSURE_GRP AS cifp_alt_disclosure_grp,
      CIFP_PURCHASE_APR AS cifp_purchase_apr,
      CIFP_CASH_APR AS cifp_cash_apr,
      CIFP_CUSTOM_DATA_11 AS cifp_custom_data_11,
      CIFP_CUSTOM_DATA_22 AS cifp_custom_data_22,
      CIFP_CUSTOM_DATA_41 AS cifp_custom_data_41
    FROM
      `pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR`
  ),
  -- Step 3: Join card and account data
  cif_snapshot AS (
    SELECT DISTINCT
      a.*,
      b.*
    EXCEPT
      (yyyy, mm, dd, mast_account_id)
    FROM
      account_curr_data a
      LEFT JOIN card_curr_data b ON a.mast_account_id = b.mast_account_id
  ) -- Final SELECT: All 104 CIF fields + metadata + audit
SELECT DISTINCT
  -- Metadata fields
  CONCAT('{report_year}', LPAD('{report_month}', 2, '0'), '01') AS REPORT_DATE,
  -- All CIF fields (cast to STRING) - 104 fields
  CAST(yyyy AS STRING) AS yyyy,
  CAST(mm AS STRING) AS mm,
  CAST(dd AS STRING) AS dd,
  CAST(mast_account_id AS STRING) AS mast_account_id,
  CAST(cifp_client_product_code AS STRING) AS cifp_client_product_code,
  CAST(cifp_vip AS STRING) AS cifp_vip,
  CAST(cifp_cycle_num AS STRING) AS cifp_cycle_num,
  CAST(cifp_dt_last_statement AS STRING) AS cifp_dt_last_statement,
  CAST(cifp_date_open AS STRING) AS cifp_date_open,
  CAST(cifp_credit_limit AS STRING) AS cifp_credit_limit,
  CAST(cifp_closed_maint_date AS STRING) AS cifp_closed_maint_date,
  CAST(cifp_crvk_maint_date AS STRING) AS cifp_crvk_maint_date,
  CAST(cifp_first_use_date AS STRING) AS cifp_first_use_date,
  CAST(cifp_date_charge_off AS STRING) AS cifp_date_charge_off,
  CAST(cifp_current_balance AS STRING) AS cifp_current_balance,
  CAST(cifp_prev_stat_bal AS STRING) AS cifp_prev_stat_bal,
  CAST(cifp_minimum_pay_due AS STRING) AS cifp_minimum_pay_due,
  CAST(cifp_amt_act_crg_off AS STRING) AS cifp_amt_act_crg_off,
  CAST(cifp_sce0_cb_score AS STRING) AS cifp_sce0_cb_score,
  CAST(cifp_sce0_date_cb_score AS STRING) AS cifp_sce0_date_cb_score,
  CAST(cifp_acquisition_code AS STRING) AS cifp_acquisition_code,
  CAST(cifp_pastdue_at_cycle AS STRING) AS cifp_pastdue_at_cycle,
  CAST(cifp_date_payment_due AS STRING) AS cifp_date_payment_due,
  CAST(cifp_actual_days_pastdue AS STRING) AS cifp_actual_days_pastdue,
  CAST(cifp_spid_type5 AS STRING) AS cifp_spid_type5,
  CAST(cifp_test_digit_type5 AS STRING) AS cifp_test_digit_type5,
  CAST(cifp_secondary_chgoff_date AS STRING) AS cifp_secondary_chgoff_date,
  CAST(cifp_coll_scenario_id AS STRING) AS cifp_coll_scenario_id,
  CAST(cifp_collection_agency AS STRING) AS cifp_collection_agency,
  CAST(am00_bankruptcy_type AS STRING) AS am00_bankruptcy_type,
  CAST(am00_statc_closed AS STRING) AS am00_statc_closed,
  CAST(am00_statc_chargeoff AS STRING) AS am00_statc_chargeoff,
  CAST(am00_statc_credit_revoked AS STRING) AS am00_statc_credit_revoked,
  CAST(am00_statc_current_past_due AS STRING) AS am00_statc_current_past_due,
  CAST(am00_statc_security_fraud AS STRING) AS am00_statc_security_fraud,
  CAST(am00_statf_inactive AS STRING) AS am00_statf_inactive,
  CAST(cifp_crvk_date AS STRING) AS cifp_crvk_date,
  CAST(am00_statf_chgoff_lag AS STRING) AS am00_statf_chgoff_lag,
  CAST(am00_statf_potential_purge AS STRING) AS am00_statf_potential_purge,
  CAST(am00_statf_credit_counseling AS STRING) AS am00_statf_credit_counseling,
  CAST(cifp_triad_score_aligned AS STRING) AS cifp_triad_score_aligned,
  CAST(cifp_avail_amt_to_buy AS STRING) AS cifp_avail_amt_to_buy,
  CAST(cifp_dt_sec_fraud_stat AS STRING) AS cifp_dt_sec_fraud_stat,
  CAST(cifp_date_fraud AS STRING) AS cifp_date_fraud,
  CAST(am00_statf_fraud AS STRING) AS am00_statf_fraud,
  CAST(cifp_date_expired AS STRING) AS cifp_date_expired,
  CAST(application_id AS STRING) AS APPLICATION_ID,
  CAST(cifp_custom_data_81 AS STRING) AS cifp_custom_data_81,
  CAST(cifp_dt_last_limit_chg AS STRING) AS cifp_dt_last_limit_chg,
  CAST(cifp_amt_pay_ctd AS STRING) AS cifp_amt_pay_ctd,
  CAST(am00_statc_dispute AS STRING) AS am00_statc_dispute,
  CAST(am00_typec_vip AS STRING) AS am00_typec_vip,
  CAST(am00_statf_declined_reissue AS STRING) AS am00_statf_declined_reissue,
  CAST(am00_statc_application AS STRING) AS am00_statc_application,
  CAST(am00_statc_fixed_payment AS STRING) AS am00_statc_fixed_payment,
  CAST(am00_statc_return_mail AS STRING) AS am00_statc_return_mail,
  CAST(rec_load_timestamp_source AS STRING) AS rec_load_timestamp_source,
  CAST(am00_statc_watch AS STRING) AS am00_statc_watch,
  CAST(cifp_sce0_cb_score_first AS STRING) AS cifp_sce0_cb_score_first,
  CAST(cifp_sec_pool_id1 AS STRING) AS cifp_sec_pool_id1,
  CAST(cifp_waive_fchg_flag AS STRING) AS cifp_waive_fchg_flag,
  CAST(cifp_dt_last_dscl_grp_chg AS STRING) AS cifp_dt_last_dscl_grp_chg,
  CAST(cifp_disclosure_group AS STRING) AS cifp_disclosure_group,
  CAST(cifp_alt_disclosure_grp AS STRING) AS cifp_alt_disclosure_grp,
  CAST(cifp_purchase_apr AS STRING) AS cifp_purchase_apr,
  CAST(cifp_cash_apr AS STRING) AS cifp_cash_apr,
  CAST(cifp_custom_data_11 AS STRING) AS cifp_custom_data_11,
  CAST(cifp_custom_data_22 AS STRING) AS cifp_custom_data_22,
  CAST(cifp_custom_data_41 AS STRING) AS cifp_custom_data_41,
  CAST(cifp_relationship_stat AS STRING) AS cifp_relationship_stat,
  CAST(cifp_trans_from_acct_no AS STRING) AS cifp_trans_from_acct_no,
  CAST(cifp_date_transfer AS STRING) AS cifp_date_transfer,
  CAST(cifp_account_num AS STRING) AS cifp_account_num,
  CAST(cifp_address_line1 AS STRING) AS cifp_address_line1,
  CAST(cifp_city AS STRING) AS cifp_city,
  CAST(cifp_state AS STRING) AS cifp_state,
  CAST(cifp_zip_code AS STRING) AS cifp_zip_code,
  CAST(cifp_country_code AS STRING) AS cifp_country_code,
  CAST(cifp_home_phone_num AS STRING) AS cifp_home_phone_num,
  CAST(cifp_bus_phone_num AS STRING) AS cifp_bus_phone_num,
  CAST(cifp_phone_alt1 AS STRING) AS cifp_phone_alt1,
  CAST(cifp_date_of_birth AS STRING) AS cifp_date_of_birth,
  CAST(cifp_prefix AS STRING) AS cifp_prefix,
  CAST(cifp_first_name AS STRING) AS cifp_first_name,
  CAST(cifp_middle_initial AS STRING) AS cifp_middle_initial,
  CAST(cifp_last_name AS STRING) AS cifp_last_name,
  CAST(cifp_suffix AS STRING) AS cifp_suffix,
  CAST(cifp_crv_status AS STRING) AS cifp_crv_status,
  CAST(cifp_crv_date AS STRING) AS cifp_crv_date,
  CAST(cifp_security_fraud AS STRING) AS cifp_security_fraud,
  CAST(cifp_statc_watch AS STRING) AS cifp_statc_watch,
  CAST(cifp_statc_watch_dt_maint AS STRING) AS cifp_statc_watch_dt_maint,
  CAST(cifp_customer_type AS STRING) AS cifp_customer_type,
  CAST(cifp_language_code AS STRING) AS cifp_language_code,
  CAST(cifp_email_address_line1 AS STRING) AS cifp_email_address_line1,
  CAST(cifp_prim_card_id AS STRING) AS cifp_prim_card_id,
  CAST(cifp_num_cust_cards_out_prim AS STRING) AS cifp_num_cust_cards_out_prim,
  CAST(cifp_cm00_employee AS STRING) AS cifp_cm00_employee,
  CAST(cifp_spid_type6 AS STRING) AS cifp_spid_type6,
  CAST(cifp_test_digit_type6 AS STRING) AS cifp_test_digit_type6,
  CAST(cifp_trans_to_acct_no AS STRING) AS cifp_trans_to_acct_no,
  CAST(cifp_customer_id_1 AS STRING) AS cifp_customer_id_1,
  CAST(cifp_customer_id_2 AS STRING) AS cifp_customer_id_2,
  CAST(cifp_pcf_cust_id AS STRING) AS cifp_pcf_cust_id,
  -- Audit fields
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM
  cif_snapshot;