EXPORT DATA
  OPTIONS (
    uri = '{output_uri_processing}',
    format = 'CSV',
    field_delimiter = '|',
    overwrite = true
  )
AS
(
WITH LATEST_TIMESTAMP_FILE AS (
  SELECT
    MAX(REC_LOAD_TIMESTAMP) AS LATEST_TIMESTAMP
  FROM
    `pcb-{env}-landing.domain_loyalty.ESSO_FUEL_TRANSACTIONS`
)
SELECT DISTINCT
  'H'AS RECORD_TYPE,
  SUBSTR(LOWER(H.SOURCE_FILENAME), STRPOS(LOWER(H.SOURCE_FILENAME), 'fdc_pcl_essogaspcpts'), 29),
  FORMAT_TIMESTAMP('%Y%m%d_%H%M%S', CURRENT_TIMESTAMP()),
  CAST(null AS STRING),
  CAST(null AS STRING),
  CAST(null AS STRING)
FROM
  `pcb-{env}-landing.domain_loyalty.ESSO_FUEL_TRANSACTIONS` H
JOIN
  LATEST_TIMESTAMP_FILE LT
ON
  H.REC_LOAD_TIMESTAMP = LT.LATEST_TIMESTAMP

UNION ALL

SELECT
  'T' AS RECORD_TYPE,
  LPAD(CAST(COUNT(*) AS STRING), 10, '0'),
  LPAD(CAST(FLOOR(SUM(CAST(T.LITERS_PURCHASED AS NUMERIC))) AS STRING), 15, '0')
    ||
  CASE
    WHEN
      SUM(CAST(T.LITERS_PURCHASED AS NUMERIC)) = FLOOR(SUM(CAST(T.LITERS_PURCHASED AS NUMERIC)))
    THEN
      '.0'
    ELSE
      '.' || SUBSTR(CAST(ROUND(SUM(CAST(T.LITERS_PURCHASED AS NUMERIC)), 1) AS STRING),STRPOS(CAST(ROUND(SUM(CAST(T.LITERS_PURCHASED AS NUMERIC)), 1) AS STRING),'.') + 1, 1)
  END,
  FORMAT_TIMESTAMP('%Y%m%d_%H%M%S', TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 MINUTE)),
  LPAD(CAST(FLOOR(SUM(CAST(T.TRANSACTION_AMOUNT AS NUMERIC))) AS STRING), 15, '0')
    ||
  CASE
    WHEN
      SUM(CAST(T.TRANSACTION_AMOUNT AS NUMERIC)) = FLOOR(SUM(CAST(T.TRANSACTION_AMOUNT AS NUMERIC)))
    THEN
      '.0'
    ELSE
    '.' || SUBSTR(CAST(ROUND(SUM(CAST(T.TRANSACTION_AMOUNT AS NUMERIC)), 2) AS STRING),STRPOS(CAST(ROUND(SUM(CAST(T.TRANSACTION_AMOUNT AS NUMERIC)), 2) AS STRING),'.') + 1, 2)
  END,
  CAST(null AS STRING)
FROM
  `pcb-{env}-landing.domain_loyalty.ESSO_FUEL_TRANSACTIONS` T
JOIN
  LATEST_TIMESTAMP_FILE LT
ON
  T.REC_LOAD_TIMESTAMP = LT.LATEST_TIMESTAMP
GROUP BY
  T.SOURCE_FILENAME,
  T.REC_LOAD_TIMESTAMP

ORDER BY RECORD_TYPE ASC
);




