WITH ALL_ACCOUNT_INFO AS (
  SELECT
    CIFP_ACCOUNT_ID5 AS MAST_ACCOUNT_ID,
    SAFE_CAST(CIFP_CUSTOM_DATA_81 AS INT64) AS APA_APP_NUM,
    CIFP_DATE_OPEN AS CIFP_DATE_OPEN,
    CIFP_DATE_CLOSE AS ACCOUNT_CLOSE_DATE,
    CIFP_CRVK_DATE AS ACCOUNT_REVOKE_DATE,
    CIFP_DTE_LST_FINANCIAL_ACT AS LAST_FINANACIAL_ACT_DATE,
    CIFP_CURRENT_BALANCE,
    CASE WHEN (
      (
        CIFP_DATE_CLOSE IS NOT NULL
        AND CIFP_DATE_CLOSE < PARSE_DATE("%Y%m%d", "{cutoff_date}")
      )
      OR (
        CIFP_CRVK_DATE IS NOT NULL
        AND CIFP_CRVK_DATE < PARSE_DATE("%Y%m%d", "{cutoff_date}")
      )
    )
    AND (
      CIFP_DTE_LST_FINANCIAL_ACT IS NULL
      OR CIFP_DTE_LST_FINANCIAL_ACT < PARSE_DATE("%Y%m%d", "{cutoff_date}")
    )
    AND CIFP_CURRENT_BALANCE = 0 THEN 0 ELSE 1 END AS ACTIVE_IND
  FROM
    `pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR`
  WHERE
    CIFP_ACCOUNT_ID5 IS NOT NULL
),
ADM_ACCOUNTS AS (
  SELECT
    TS2_ACCOUNT_ID
  FROM
    `pcb-{env}-curated.domain_customer_acquisition.LTTR_OVRD_DETAIL_XTO`
),
ONLY_ADM_ACCOUNTS AS (
  SELECT
    *
  FROM
    ALL_ACCOUNT_INFO
  WHERE
    MAST_ACCOUNT_ID IN (
      SELECT
        TS2_ACCOUNT_ID
      FROM
        ADM_ACCOUNTS
    )
),
LRJ_DATASET AS (
  SELECT
    *
  FROM
    (
      SELECT
        APP_NUM,
        TYPE,
        CORRESPONDENCE_ID,
        PARSE_DATE('%m%d%Y', REQUESTED_DT) AS REQUESTED_DT,
        1 AS DECLINE_IND,
        ROW_NUMBER() OVER(
          PARTITION BY APP_NUM
          ORDER BY
            PARSE_DATE('%m%d%Y', REQUESTED_DT) DESC
        ) AS ROW_NUM
      FROM
        `pcb-{env}-curated.domain_customer_acquisition.LTTR_OVRD_DETAIL_LTO`
      WHERE
        TYPE = 'LRJ'
        AND STATUS_SW IN ('S', 'E')
    ) TBL
  WHERE
    TBL.ROW_NUM = 1
),
ADM_LRJ_COMBINED AS (
  SELECT
    *,
    COALESCE(
      ONLY_ADM_ACCOUNTS.APA_APP_NUM, LRJ_DATASET.APP_NUM
    ) APP_NUMBER
  FROM
    ONLY_ADM_ACCOUNTS FULL
    JOIN LRJ_DATASET ON ONLY_ADM_ACCOUNTS.APA_APP_NUM = LRJ_DATASET.APP_NUM
),
PURGEABLE_DATASET AS (
  SELECT
    SAFE_CAST(APP_NUMBER AS INT64) AS APP_NUMBER,
    CASE WHEN ACTIVE_IND IS NULL
    AND (
      REQUESTED_DT IS NOT NULL
      AND REQUESTED_DT < PARSE_DATE("%Y%m%d", "{cutoff_date}")
    ) THEN 'APP DECLINED > 5 YEARS' WHEN ACTIVE_IND = 0 THEN 'ACCOUNT CLOSED > 5 YEARS AND 0 BALANCE' ELSE NULL END APP_TYPE,
    SAFE_CAST(MAST_ACCOUNT_ID AS INT64),
    '' AS IMAGE_ID,
    CIFP_CURRENT_BALANCE AS CURRENT_BALANCE,
    "ADM" AS APP_SOURCE,
    0 AS PURGE_IND,
    DATE(ACCOUNT_CLOSE_DATE) AS ACCOUNT_CLOSE_DATE,
    DATE(ACCOUNT_REVOKE_DATE) AS CREDIT_REVOKE_DATE,
    REQUESTED_DT AS DECLINED_DATE,
    DATE(LAST_FINANACIAL_ACT_DATE) AS LAST_FINANACIAL_ACT_DATE,
    CURRENT_DATE() AS PURGE_LIST_DATE,
    CURRENT_DATETIME() AS CREATE_TS,
    '{purge_cycle}' AS PURGE_CYCLE,
    'Y' AS IS_TERMINUS
  FROM
    ADM_LRJ_COMBINED
)
SELECT
  *
FROM
  PURGEABLE_DATASET
WHERE
  APP_TYPE IS NOT NULL
  AND APP_NUMBER NOT IN (
    SELECT DISTINCT APP_NUMBER FROM `pcb-{env}-landing.domain_customer_acquisition.PURGELIST_ADM` where IS_TERMINUS = 'Y' and PURGE_IND = 1
  )

