WITH
  ALL_ACCOUNT_INFO AS (
    SELECT DISTINCT
      /*TSYS ACCOUNT ID*/ CIFP_ACCOUNT_ID5 AS MAST_ACCOUNT_ID,
      /*TSYS APP NUMBER*/ SAFE_CAST (CIFP_CUSTOM_DATA_81 AS INT64) AS APA_APP_NUM,
      /*ACCOUNT OPEN DATE*/ CIFP_DATE_OPEN,
      /*ACCOUNT CLOSE DATE*/ CIFP_DATE_CLOSE,
      /*ACCOUNT CRVK DATE*/ CIFP_CRVK_DATE,
      /*ACCOUNT LAST FINANCIAL ACT*/ CIFP_DTE_LST_FINANCIAL_ACT,
      CIFP_CURRENT_BALANCE,
      /*CARD NUMBER*/ CIFP_ACCOUNT_NUM,
      /*PREVIOUS CARD NUMBER*/ CIFP_TRANS_FROM_ACCT_NO,
      CIFP_FIRST_NAME,
      CIFP_LAST_NAME,
      CIFP_DATE_OF_BIRTH AS CIFP_DATE_OF_BIRTH,
      CASE
        WHEN (
          (
            CIFP_DATE_CLOSE IS NOT NULL
            AND CIFP_DATE_CLOSE<PARSE_DATE ("%Y%m%d", "{cutoff_date}")
          )
          OR (
            CIFP_CRVK_DATE IS NOT NULL
            AND CIFP_CRVK_DATE<PARSE_DATE ("%Y%m%d", "{cutoff_date}")
          )
        )
        AND (
          CIFP_DTE_LST_FINANCIAL_ACT IS NULL
          OR CIFP_DTE_LST_FINANCIAL_ACT<PARSE_DATE ("%Y%m%d", "{cutoff_date}")
        )
        AND CIFP_CURRENT_BALANCE=0 THEN 0
        ELSE 1
      END AS ACTIVE_IND
    FROM
      pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR A
      LEFT JOIN pcb-{env}-curated.domain_account_management.CIF_CARD_CURR B ON A.CIFP_ACCOUNT_ID5=B.CIFP_ACCOUNT_ID6
    WHERE
      CIFP_CUSTOMER_TYPE=0 /*PRIMARY USER ONLY*/
      AND A.CIFP_ACCOUNT_ID5 IS NOT NULL
  ),
  ADM_ACCOUNTS AS (
     SELECT DISTINCT
          TS2_ACCOUNT_ID
        FROM
          pcb-{env}-curated.domain_customer_acquisition.LTTR_OVRD_DETAIL_XTO
  ),
  ALL_ACCOUNT_INFO2 AS (
    SELECT * FROM ALL_ACCOUNT_INFO WHERE MAST_ACCOUNT_ID NOT IN (SELECT TS2_ACCOUNT_ID FROM ADM_ACCOUNTS)
  ),
  EAPS_DATA AS (
    SELECT
      A.APPLICATION_ID,
      APP_AJUDICATION_CODE,
      APP_APPL_ACTION_STATUS,
      A.APP_APRV_LOAN_NUMBER AS CARD_NUMBER,
      PRI_FIRST_NAME AS FIRST_NAME,
      PRI_LAST_NAME AS LAST_NAME,
      PRI_BIRTH_DATE AS DOB,
      APP_DATE_ADJUDICATED AS ADJ_DATE,
      APP_SETUP_DATE AS SETUP_DATE
    FROM
      pcb-{env}-curated.domain_customer_acquisition.EAPS_1 A
      LEFT JOIN pcb-{env}-curated.domain_customer_acquisition.EAPS_2 B ON A.APPLICATION_ID=B.APPLICATION_ID
  ),
  EAPS_CARD_NUM_JOIN AS (
    SELECT DISTINCT
      A.APPLICATION_ID,
      B.MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID_CARD_CURR,
      C.MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID_CARD_PREV,
      A.CARD_NUMBER,
      B.CIFP_ACCOUNT_NUM AS CARD_NUM_CURR,
      C.CIFP_TRANS_FROM_ACCT_NO AS CARD_NUM_PREV
    FROM
      EAPS_DATA A
      LEFT JOIN ALL_ACCOUNT_INFO2 B ON A.CARD_NUMBER=B.CIFP_ACCOUNT_NUM
      LEFT JOIN ALL_ACCOUNT_INFO2 C ON A.CARD_NUMBER=C.CIFP_TRANS_FROM_ACCT_NO
    WHERE
      A.CARD_NUMBER IS NOT NULL
  ),
  EAPS_NAME_DOB_JOIN AS (
    SELECT DISTINCT
      A.APPLICATION_ID,
      B.MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID_NAME_DOB,
      A.FIRST_NAME,
      B.CIFP_FIRST_NAME,
      A.LAST_NAME,
      B.CIFP_LAST_NAME,
      A.DOB,
      B.CIFP_DATE_OF_BIRTH,
      A.SETUP_DATE,
      B.CIFP_DATE_OPEN
    FROM
      EAPS_DATA A
      INNER JOIN ALL_ACCOUNT_INFO2 B ON TRIM(A.FIRST_NAME)=B.CIFP_FIRST_NAME
      AND TRIM(A.LAST_NAME)=B.CIFP_LAST_NAME
      AND A.DOB=B.CIFP_DATE_OF_BIRTH
      AND DATE_DIFF (
       B.CIFP_DATE_OPEN,A.SETUP_DATE,
       DAY
      ) BETWEEN 0 AND 2
    WHERE
      A.FIRST_NAME IS NOT NULL
      AND A.LAST_NAME IS NOT NULL
      AND A.DOB IS NOT NULL
      AND A.SETUP_DATE IS NOT NULL
      AND B.APA_APP_NUM IS NULL
  ),
  EAPS_JOINED AS (
    SELECT DISTINCT
      A.*,
      COALESCE(
        C.MAST_ACCOUNT_ID_CARD_CURR,
        C.MAST_ACCOUNT_ID_CARD_PREV,
        D.MAST_ACCOUNT_ID_NAME_DOB
      ) AS MAST_ACCOUNT_ID,
      CASE
        WHEN C.MAST_ACCOUNT_ID_CARD_CURR IS NOT NULL THEN 'CARD NUM CURR'
        WHEN C.MAST_ACCOUNT_ID_CARD_PREV IS NOT NULL THEN 'CARD NUM PREV'
        WHEN D.MAST_ACCOUNT_ID_NAME_DOB IS NOT NULL THEN 'NAME/DOB'
        ELSE 'NOT FOUND'
      END AS JOIN_TYPE
    FROM
      EAPS_DATA A
      LEFT JOIN EAPS_CARD_NUM_JOIN C ON A.APPLICATION_ID=C.APPLICATION_ID
      LEFT JOIN EAPS_NAME_DOB_JOIN D ON A.APPLICATION_ID=D.APPLICATION_ID
  ),
  EAPS_TS2_JOINED AS (
    SELECT DISTINCT
      A.*  EXCEPT (MAST_ACCOUNT_ID),
      B.ACTIVE_IND,
      A.JOIN_TYPE,
      B.MAST_ACCOUNT_ID,
      APA_APP_NUM,
      CIFP_DATE_CLOSE,
      CIFP_CRVK_DATE,
      CIFP_DTE_LST_FINANCIAL_ACT,
      CIFP_CURRENT_BALANCE
    FROM
      EAPS_JOINED A
      LEFT JOIN ALL_ACCOUNT_INFO2 B ON A.MAST_ACCOUNT_ID=B.MAST_ACCOUNT_ID
  ),
  PRE_PURGE_LIST_EAPS AS (
    SELECT
      APPLICATION_ID,
      CASE
        WHEN ACTIVE_IND=1 THEN ''
        WHEN ACTIVE_IND=0 THEN 'ACCOUNT CLOSED > 5 YEARS AND 0 BALANCE'
        WHEN ACTIVE_IND IS NULL
        AND APP_AJUDICATION_CODE='A' THEN 'ACCOUNT CLOSED > 5 YEARS AND 0 BALANCE'
        ELSE 'APP DECLINED > 5 YEARS'
      END AS APP_TYPE,
      SAFE_CAST(MAST_ACCOUNT_ID AS INT64) AS MAST_ACCOUNT_ID,
      ''  AS IMAGE_ID,
      CIFP_CURRENT_BALANCE AS CURRENT_BALANCE,
      "EAPS" AS APP_SOURCE,
      /*IF ACTIVE NO PURGE, THE REST PURGE*/
      CASE
        WHEN ACTIVE_IND=1 THEN 1
        ELSE 0
      END AS PURGE_IND,
      DATE(CIFP_DATE_CLOSE) AS ACCOUNT_CLOSE_DATE,
      DATE(CIFP_CRVK_DATE) AS CREDIT_REVOKE_DATE,
      CASE
        WHEN APP_AJUDICATION_CODE!='A'
        AND ACTIVE_IND IS NULL THEN DATE(ADJ_DATE)
      END AS DECLINE_DATE,
      DATE(CIFP_DTE_LST_FINANCIAL_ACT) AS LAST_FINANCIAL_ACTIVITY_DATE,
      CURRENT_DATE() AS PURGE_LIST_DATE,
      CURRENT_DATETIME() AS CREATE_TS,
      '{purge_cycle}' AS PURGE_CYCLE,
      'Y' AS IS_TERMINUS
    FROM
      EAPS_TS2_JOINED
  ),
  FINAL_PURGE_LIST_EAPPS AS (
    SELECT * FROM PRE_PURGE_LIST_EAPS
    WHERE APPLICATION_ID NOT IN (SELECT APPLICATION_ID FROM PRE_PURGE_LIST_EAPS WHERE PURGE_IND=1)
  )

  SELECT * FROM FINAL_PURGE_LIST_EAPPS WHERE
  APPLICATION_ID NOT IN (SELECT DISTINCT APPLICATION_ID FROM `pcb-{env}-landing.domain_customer_acquisition.PURGELIST_EAPPS`
                            where IS_TERMINUS = 'Y' and PURGE_IND = 1)