WITH ALL_ACCOUNT_INFO AS (
  SELECT
    DISTINCT CIFP_ACCOUNT_ID5 AS MAST_ACCOUNT_ID,
    SAFE_CAST(CIFP_CUSTOM_DATA_81 AS INT64) AS APP_NUMBER,
    CIFP_DATE_OPEN,
    CIFP_DATE_CLOSE AS ACCOUNT_CLOSE_DATE,
    CIFP_CRVK_DATE AS CIFP_CRVK_DATE,
    CIFP_DTE_LST_FINANCIAL_ACT AS LST_FINANCIAL_ACT_DATE,
    CIFP_CURRENT_BALANCE AS CURRENT_BALANCE,
    CIFP_ACCOUNT_NUM,
    CIFP_TRANS_FROM_ACCT_NO,
    CIFP_FIRST_NAME,
    CIFP_LAST_NAME,
    CIFP_DATE_OF_BIRTH,
    CASE WHEN (
      (
        CIFP_DATE_CLOSE IS NOT NULL
        AND CIFP_DATE_CLOSE < PARSE_DATE("%Y%m%d", "{cutoff_date}")
      )
      OR (
        CIFP_CRVK_DATE IS NOT NULL
        AND CIFP_CRVK_DATE < PARSE_DATE("%Y%m%d", "{cutoff_date}")
      )
    )
    AND (
      CIFP_DTE_LST_FINANCIAL_ACT IS NULL
      OR CIFP_DTE_LST_FINANCIAL_ACT < PARSE_DATE("%Y%m%d", "{cutoff_date}")
    )
    AND CIFP_CURRENT_BALANCE = 0 THEN 0 ELSE 1 END AS ACTIVE_IND
  FROM
    `pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR` A
    LEFT JOIN `pcb-{env}-curated.domain_account_management.CIF_CARD_CURR` B ON A.CIFP_ACCOUNT_ID5 = B.CIFP_ACCOUNT_ID6
  WHERE
    CIFP_CUSTOMER_TYPE = 0
    AND A.CIFP_ACCOUNT_ID5 IS NOT NULL
),
ADM_ACCOUNTS AS (
  SELECT
    TS2_ACCOUNT_ID
  FROM
    `pcb-{env}-curated.domain_customer_acquisition.LTTR_OVRD_DETAIL_XTO`
),
EXPERIAN_ALL_ACCOUNTS AS (
  SELECT
    *
  FROM
    ALL_ACCOUNT_INFO
  WHERE
    MAST_ACCOUNT_ID NOT IN (
      SELECT
        TS2_ACCOUNT_ID
      FROM
        ADM_ACCOUNTS
    )
),
EXPERIAN_BASE_DATA AS (
  SELECT
    APP_STATUS,
    APP_NUMBER,
    P_PI_FIRST_NAME AS FIRST_NAME,
    P_PI_LAST_NAME AS LAST_NAME,
    P_PI_DOB AS DOB,
    MCCARD_NUMBER_FDR AS CARD_NUMBER,
    APP_MODIFIED_DATE,
    IMAGE_ID
  FROM
    `pcb-{env}-curated.domain_customer_acquisition.EXPERIAN_BASE`
),
EXPERIAN_APP_NUM_JOIN AS (
  SELECT DISTINCT
    EBD.APP_NUMBER,
    EAA.MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID_APP_NUM
  FROM
    EXPERIAN_BASE_DATA EBD
    JOIN EXPERIAN_ALL_ACCOUNTS EAA ON EBD.APP_NUMBER = EAA.APP_NUMBER
    AND EBD.APP_NUMBER IS NOT NULL
),
EXPERIAN_CARD_NUM_FIRST_JOIN AS (
  SELECT
    DISTINCT A.APP_NUMBER,
    B.MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID_CARD_CURR,
    A.CARD_NUMBER AS CARD_NUMBER,
    B.CIFP_ACCOUNT_NUM AS CARD_NUM_CURR
  FROM
    EXPERIAN_BASE_DATA A
    LEFT JOIN EXPERIAN_ALL_ACCOUNTS B ON
      A.CARD_NUMBER = B.CIFP_ACCOUNT_NUM
  WHERE
    A.CARD_NUMBER IS NOT NULL
),
EXPERIAN_CARD_NUM_JOIN AS (
  SELECT
    DISTINCT A.APP_NUMBER,
    A.MAST_ACCOUNT_ID_CARD_CURR AS MAST_ACCOUNT_ID_CARD_CURR,
    B.MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID_CARD_PREV,
    A.CARD_NUMBER,
    A.CARD_NUM_CURR AS CARD_NUM_CURR,
    B.CIFP_TRANS_FROM_ACCT_NO AS CARD_NUM_PREV
  FROM
    EXPERIAN_CARD_NUM_FIRST_JOIN A
    LEFT JOIN EXPERIAN_ALL_ACCOUNTS B ON
       A.CARD_NUMBER = B.CIFP_TRANS_FROM_ACCT_NO
  WHERE
    A.CARD_NUMBER IS NOT NULL
),
EXPERIAN_NAME_DOB_JOIN AS (
  SELECT
    DISTINCT A.APP_NUMBER,
    B.MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID_NAME_DOB,
    A.FIRST_NAME,
    B.CIFP_FIRST_NAME,
    A.LAST_NAME,
    B.CIFP_LAST_NAME,
    A.DOB,
    B.CIFP_DATE_OF_BIRTH,
    A.APP_MODIFIED_DATE,
    B.CIFP_DATE_OPEN
  FROM
    EXPERIAN_BASE_DATA A
    INNER JOIN EXPERIAN_ALL_ACCOUNTS B ON A.FIRST_NAME = B.CIFP_FIRST_NAME
    AND A.LAST_NAME = B.CIFP_LAST_NAME
    AND DATETIME_ADD(DATETIME_TRUNC(A.DOB, DAY), INTERVAL 1 DAY) = DATETIME_TRUNC(B.CIFP_DATE_OF_BIRTH , DAY)
    AND DATE_DIFF(B.CIFP_DATE_OPEN, DATETIME_ADD(DATETIME_TRUNC(A.APP_MODIFIED_DATE, DAY), INTERVAL 1 DAY), DAY) BETWEEN 1 AND 2
    AND A.FIRST_NAME IS NOT NULL
    AND A.LAST_NAME IS NOT NULL
    AND A.DOB IS NOT NULL
    AND A.APP_MODIFIED_DATE IS NOT NULL
    AND B.APP_NUMBER IS NULL
),
EXPERIAN_JOINED AS (
  SELECT
    DISTINCT A.*,
    COALESCE(
      B.MAST_ACCOUNT_ID_APP_NUM,
      c.MAST_ACCOUNT_ID_CARD_CURR,
      c.MAST_ACCOUNT_ID_CARD_PREV,
      D.MAST_ACCOUNT_ID_NAME_DOB
    ) AS MAST_ACCOUNT_ID,
    CASE WHEN B.MAST_ACCOUNT_ID_APP_NUM IS NOT NULL THEN 'APP NUM' WHEN C.MAST_ACCOUNT_ID_CARD_CURR IS NOT NULL THEN 'CARD NUM CURR' WHEN C.MAST_ACCOUNT_ID_CARD_PREV IS NOT NULL THEN 'CARD NUM PREV' WHEN D.MAST_ACCOUNT_ID_NAME_DOB IS NOT NULL THEN 'NAME/DOB' ELSE 'NOT FOUND' END AS JOIN_TYPE
  FROM
    EXPERIAN_BASE_DATA A
    LEFT JOIN EXPERIAN_APP_NUM_JOIN B ON A.APP_NUMBER = B.APP_NUMBER
    LEFT JOIN EXPERIAN_CARD_NUM_JOIN C ON A.APP_NUMBER = C.APP_NUMBER
    LEFT JOIN EXPERIAN_NAME_DOB_JOIN D ON A.APP_NUMBER = D.APP_NUMBER
),
EXPERIAN_TS2_JOINED AS (
  SELECT
    DISTINCT A.*
  EXCEPT
    (MAST_ACCOUNT_ID),
    B.ACTIVE_IND,
    B.MAST_ACCOUNT_ID,
    ACCOUNT_CLOSE_DATE,
    CIFP_CRVK_DATE,
    LST_FINANCIAL_ACT_DATE,
    CURRENT_BALANCE
  FROM
    EXPERIAN_JOINED A
    LEFT JOIN EXPERIAN_ALL_ACCOUNTS B ON A.MAST_ACCOUNT_ID = B.MAST_ACCOUNT_ID
),

EXPERIAN_TS2_JOINED2 AS (
  SELECT DISTINCT

    /*IF ACTIVE THEN NO PURGE, THE REST PURGE*/
    CASE WHEN ACTIVE_IND = 1 THEN 0 ELSE 1 END AS PURGE_IND,
    ETJ.APP_NUMBER AS APP_NUMBER,

    /*IF NOT ACTIVE, THEN TYPE IS CLOSED
    ELSE IF NO FOUND AND APPROVED, ASSUME CLOSED
    ELSE DECLINED*/
    CASE WHEN ACTIVE_IND = 1 THEN '' WHEN ACTIVE_IND = 0 THEN 'CLOSED' WHEN ACTIVE_IND IS NULL
    AND APP_STATUS = 'APPROVED' THEN 'ACCOUNT CLOSED > 5 YEARS AND 0 BALANCE' ELSE 'APP DECLINED > 5 YEARS' END AS APP_TYPE,
    MAST_ACCOUNT_ID,
    IMAGE_ID,
    CASE WHEN APP_STATUS != 'APPROVED'
    AND ACTIVE_IND IS NULL THEN APP_MODIFIED_DATE END AS DECLINE_DATE,
    ACCOUNT_CLOSE_DATE,
    CIFP_CRVK_DATE,
    LST_FINANCIAL_ACT_DATE,
    CURRENT_BALANCE,
    'EXPERIAN' AS APP_SOURCE,
    CURRENT_DATE() AS PURGE_LIST_DATE
  FROM
    EXPERIAN_TS2_JOINED ETJ
),
FINAL_EXPERIAN_PURGE_LIST AS (
  SELECT
    APP_NUMBER,
    APP_TYPE,
    SAFE_CAST(MAST_ACCOUNT_ID AS INT64) AS MAST_ACCOUNT_ID,
    CASE WHEN SUBSTR(IMAGE_ID, 1, 3)='PCA' THEN IMAGE_ID ELSE '' END AS IMAGE_ID,
    CURRENT_BALANCE,
    APP_SOURCE,
    0 AS PURGE_IND,
    DATE(ACCOUNT_CLOSE_DATE) AS ACCOUNT_CLOSE_DATE,
    DATE(CIFP_CRVK_DATE) AS CREDIT_REVOKE_DATE,
    DATE(DECLINE_DATE) AS DECLINE_DATE,
    DATE(LST_FINANCIAL_ACT_DATE) AS LAST_FINANCIAL_ACTIVITY_DATE,
    PURGE_LIST_DATE,
    CURRENT_DATETIME() AS CREATE_TS,
    '{purge_cycle}' AS PURGE_CYCLE,
    'Y' AS IS_TERMINUS
  FROM
    EXPERIAN_TS2_JOINED2
  WHERE
    PURGE_IND = 1
    AND APP_NUMBER NOT IN (
      SELECT
        APP_NUMBER
      FROM
        EXPERIAN_TS2_JOINED2
      WHERE
        PURGE_IND = 0
    )
)
SELECT
  *
FROM
  FINAL_EXPERIAN_PURGE_LIST ORDER BY APP_NUMBER


