EXPORT DATA
  OPTIONS (
    uri = 'gs://pcb-{env}-staging-extract/sync-loyalty-profile/loyalty-profile-initial-segment-*.parquet',
    format = 'PARQUET',
    overwrite = true
  )
AS
(
WITH RANKED_EXCLUDED_CUSTOMER_IDENTIFIER AS (
    SELECT DISTINCT
        SAFE_CAST(CI_S.CUSTOMER_IDENTIFIER_NO AS STRING) AS CUSTOMER_IDENTIFIER_NO,
        SAFE_CAST(CI_S.CUSTOMER_UID AS STRING) AS CUSTOMER_UID
    FROM
        `pcb-{env}-landing.domain_customer_management.CUSTOMER_IDENTIFIER` CI_S
    LEFT JOIN
        `pcb-{env}-landing.domain_account_management.ACCOUNT_CUSTOMER` AC_S
    ON
        CI_S.CUSTOMER_UID = AC_S.CUSTOMER_UID
    WHERE
        AC_S.CUSTOMER_UID IS NULL
        AND LOWER(CI_S.DISABLED_IND) = 'n'
        AND LOWER(CI_S.TYPE) = 'pcf-customer-id'
), RANKED_CUSTOMER_IDENTIFIER AS (
    SELECT DISTINCT
        SAFE_CAST(CI_T.CUSTOMER_IDENTIFIER_NO AS STRING) AS CUSTOMER_IDENTIFIER_NO,
        SAFE_CAST(CI_T.CUSTOMER_UID AS STRING) AS CUSTOMER_UID,
    FROM
        `pcb-{env}-landing.domain_customer_management.CUSTOMER_IDENTIFIER` CI_T
    INNER JOIN
        `pcb-{env}-landing.domain_account_management.ACCOUNT_CUSTOMER` AC_A
    ON
        CI_T.CUSTOMER_UID = AC_A.CUSTOMER_UID
    WHERE
        LOWER(AC_A.ACTIVE_IND) = 'y'
        AND LOWER(CI_T.DISABLED_IND) = 'n'
        AND LOWER(CI_T.TYPE) = 'pcf-customer-id'
), RANKED_CUSTOMER_IDENTIFIER_FINAL AS (
    SELECT DISTINCT
        RCI.CUSTOMER_IDENTIFIER_NO,
        RCI.CUSTOMER_UID,
        ROW_NUMBER() OVER (ORDER BY RCI.CUSTOMER_UID ASC) AS ROW_NUM
    FROM
        RANKED_CUSTOMER_IDENTIFIER RCI
    LEFT JOIN
        RANKED_EXCLUDED_CUSTOMER_IDENTIFIER RECI
    ON
        RCI.CUSTOMER_IDENTIFIER_NO = RECI.CUSTOMER_IDENTIFIER_NO
        AND RCI.CUSTOMER_UID = RECI.CUSTOMER_UID
    WHERE
        RECI.CUSTOMER_IDENTIFIER_NO IS NULL
        AND RECI.CUSTOMER_UID IS NULL
)
SELECT
    *
FROM
    RANKED_CUSTOMER_IDENTIFIER_FINAL
WHERE
    ROW_NUM <= 1000
);