-- {env}_reverse_etl.vw_bi_query_edi_pymt_inb_req source
CREATE
OR REPLACE VIEW {env}_reverse_etl.vw_bi_query_edi_pymt_inb_req AS
SELECT
    EDI.pcf_cust_id,
    EDI.account_no,
    EDI.card_number,
    EDI.payer_name,
    EDI.amount,
    EDI.orig_fi_dt,
    EDI.eff_pymt_dt,
    EDI.trace_id,
    EDI.fi_trace_num,
    EDI.payment_trace_no,
    EDI.institution_id,
    EDI.create_dt,
    EDI.hdr_id,
    EDI.edi_pymt_uid,
    EDI.card_deposit_fulfillment_uid,
    EDI.orig_co_supp_cd,
    EDI.create_user_id,
    EDI.create_function_name,
    EDI.update_dt,
    EDI.update_user_id,
    EDI.update_function_name,
    EDI.bi_query_edi_uid,
    EDI.edi_source
FROM
    (
        SELECT
            bi_query_edi_ods.pcf_cust_id AS pcf_cust_id,
            bi_query_edi_ods.account_no AS account_no,
            bi_query_edi_ods.card_number AS card_number,
            bi_query_edi_ods.payer_name AS payer_name,
            bi_query_edi_ods.amount AS amount,
            bi_query_edi_ods.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_edi_ods.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_edi_ods.trace_id AS trace_id,
            bi_query_edi_ods.fi_trace_num AS fi_trace_num,
            bi_query_edi_ods.payment_trace_no AS payment_trace_no,
            bi_query_edi_ods.institution_id AS institution_id,
            bi_query_edi_ods.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_edi_ods.hdr_id AS hdr_id,
            bi_query_edi_ods.edi_pymt_uid AS edi_pymt_uid,
            bi_query_edi_ods.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_edi_ods.orig_co_supp_cd AS orig_co_supp_cd,
            bi_query_edi_ods.create_user_id AS create_user_id,
            bi_query_edi_ods.create_function_name AS create_function_name,
            bi_query_edi_ods.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_edi_ods.update_user_id AS update_user_id,
            bi_query_edi_ods.update_function_name AS update_function_name,
            bi_query_edi_ods.bi_query_edi_uid AS bi_query_edi_uid,
            bi_query_edi_ods.edi_source AS edi_source
        FROM
            {env}_reverse_etl.bi_query_edi_ods
        UNION
        DISTINCT
        SELECT
            bi_query_edi_ods_default.pcf_cust_id AS pcf_cust_id,
            bi_query_edi_ods_default.account_no AS account_no,
            bi_query_edi_ods_default.card_number AS card_number,
            bi_query_edi_ods_default.payer_name AS payer_name,
            bi_query_edi_ods_default.amount AS amount,
            bi_query_edi_ods_default.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_edi_ods_default.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_edi_ods_default.trace_id AS trace_id,
            bi_query_edi_ods_default.fi_trace_num AS fi_trace_num,
            bi_query_edi_ods_default.payment_trace_no AS payment_trace_no,
            bi_query_edi_ods_default.institution_id AS institution_id,
            bi_query_edi_ods_default.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_edi_ods_default.hdr_id AS hdr_id,
            bi_query_edi_ods_default.edi_pymt_uid AS edi_pymt_uid,
            bi_query_edi_ods_default.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_edi_ods_default.orig_co_supp_cd AS orig_co_supp_cd,
            bi_query_edi_ods_default.create_user_id AS create_user_id,
            bi_query_edi_ods_default.create_function_name AS create_function_name,
            bi_query_edi_ods_default.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_edi_ods_default.update_user_id AS update_user_id,
            bi_query_edi_ods_default.update_function_name AS update_function_name,
            bi_query_edi_ods_default.bi_query_edi_uid AS bi_query_edi_uid,
            bi_query_edi_ods_default.edi_source AS edi_source
        FROM
            {env}_reverse_etl.bi_query_edi_ods_default
        UNION
        DISTINCT
        SELECT
            bi_query_edi_053.pcf_cust_id AS pcf_cust_id,
            bi_query_edi_053.account_no AS account_no,
            bi_query_edi_053.card_number AS card_number,
            bi_query_edi_053.payer_name AS payer_name,
            bi_query_edi_053.amount AS amount,
            bi_query_edi_053.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_edi_053.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_edi_053.trace_id AS trace_id,
            bi_query_edi_053.fi_trace_num AS fi_trace_num,
            bi_query_edi_053.payment_trace_no AS payment_trace_no,
            bi_query_edi_053.institution_id AS institution_id,
            bi_query_edi_053.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_edi_053.hdr_id AS hdr_id,
            bi_query_edi_053.edi_pymt_uid AS edi_pymt_uid,
            bi_query_edi_053.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_edi_053.orig_co_supp_cd AS orig_co_supp_cd,
            bi_query_edi_053.create_user_id AS create_user_id,
            bi_query_edi_053.create_function_name AS create_function_name,
            bi_query_edi_053.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_edi_053.update_user_id AS update_user_id,
            bi_query_edi_053.update_function_name AS update_function_name,
            bi_query_edi_053.bi_query_edi_uid AS bi_query_edi_uid,
            bi_query_edi_053.edi_source AS edi_source
        FROM
            {env}_reverse_etl.bi_query_edi_053
        UNION
        DISTINCT
        SELECT
            bi_query_edi_053_default.pcf_cust_id AS pcf_cust_id,
            bi_query_edi_053_default.account_no AS account_no,
            bi_query_edi_053_default.card_number AS card_number,
            bi_query_edi_053_default.payer_name AS payer_name,
            bi_query_edi_053_default.amount AS amount,
            bi_query_edi_053_default.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_edi_053_default.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_edi_053_default.trace_id AS trace_id,
            bi_query_edi_053_default.fi_trace_num AS fi_trace_num,
            bi_query_edi_053_default.payment_trace_no AS payment_trace_no,
            bi_query_edi_053_default.institution_id AS institution_id,
            bi_query_edi_053_default.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_edi_053_default.hdr_id AS hdr_id,
            bi_query_edi_053_default.edi_pymt_uid AS edi_pymt_uid,
            bi_query_edi_053_default.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_edi_053_default.orig_co_supp_cd AS orig_co_supp_cd,
            bi_query_edi_053_default.create_user_id AS create_user_id,
            bi_query_edi_053_default.create_function_name AS create_function_name,
            bi_query_edi_053_default.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_edi_053_default.update_user_id AS update_user_id,
            bi_query_edi_053_default.update_function_name AS update_function_name,
            bi_query_edi_053_default.bi_query_edi_uid AS bi_query_edi_uid,
            bi_query_edi_053_default.edi_source AS edi_source
        FROM
            {env}_reverse_etl.bi_query_edi_053_default
    ) AS EDI;

-- {env}_reverse_etl.vw_bi_query_eft_pcborigin_in_req source
CREATE
OR REPLACE VIEW {env}_reverse_etl.vw_bi_query_eft_pcborigin_in_req AS
SELECT
    EFT.pcf_cust_id,
    EFT.account_no,
    EFT.card_number,
    EFT.payer_name,
    EFT.amount,
    EFT.eft_req_uid,
    EFT.eft_fulfillment_uid,
    EFT.eft_reqtype_cd,
    EFT.fundsmove_instruction_id,
    EFT.fundsmove_gl_req_uid,
    EFT.fundsmove_processing_dt,
    EFT.institution_id,
    EFT.transit_number,
    EFT.eft_account_no,
    EFT.originator_name,
    EFT.originator_id,
    EFT.settle_on,
    EFT.pcb_assigned_opacct_nickname,
    EFT.opacct_institution_no,
    EFT.opacct_transit_number,
    EFT.opacct_number,
    EFT.trace_id,
    EFT.executed_on,
    EFT.request_on,
    EFT.create_dt,
    EFT.create_user_id,
    EFT.create_function_name,
    EFT.update_dt,
    EFT.update_user_id,
    EFT.update_function_name,
    EFT.transfer_type,
    EFT.cpa_transaction_type,
    EFT.pcb_institution_id,
    EFT.pcb_transit_number,
    EFT.pcb_customer_account_number,
    EFT.pcb_customer_name,
    EFT.origin_cross_reference_number,
    EFT.origin_institution_id,
    EFT.origin_transit_number,
    EFT.origin_account_number,
    EFT.origin_trace_number,
    EFT.bi_query_eft_uid,
    EFT.eft_source
FROM
    (
        SELECT
            bi_query_eft.pcf_cust_id AS pcf_cust_id,
            bi_query_eft.account_no AS account_no,
            bi_query_eft.card_number AS card_number,
            bi_query_eft.payer_name AS payer_name,
            bi_query_eft.amount AS amount,
            bi_query_eft.eft_req_uid AS eft_req_uid,
            bi_query_eft.eft_fulfillment_uid AS eft_fulfillment_uid,
            bi_query_eft.eft_reqtype_cd AS eft_reqtype_cd,
            bi_query_eft.fundsmove_instruction_id AS fundsmove_instruction_id,
            bi_query_eft.fundsmove_gl_req_uid AS fundsmove_gl_req_uid,
            bi_query_eft.fundsmove_processing_dt :: TIMESTAMP WITHOUT TIME ZONE AS fundsmove_processing_dt,
            bi_query_eft.institution_id AS institution_id,
            bi_query_eft.transit_number AS transit_number,
            bi_query_eft.eft_account_no AS eft_account_no,
            bi_query_eft.originator_name AS originator_name,
            bi_query_eft.originator_id AS originator_id,
            bi_query_eft.settle_on AS settle_on,
            bi_query_eft.pcb_assigned_opacct_nickname AS pcb_assigned_opacct_nickname,
            bi_query_eft.opacct_institution_no AS opacct_institution_no,
            bi_query_eft.opacct_transit_number AS opacct_transit_number,
            bi_query_eft.opacct_number AS opacct_number,
            bi_query_eft.trace_id AS trace_id,
            bi_query_eft.executed_on :: TIMESTAMP WITHOUT TIME ZONE AS executed_on,
            bi_query_eft.request_on :: TIMESTAMP WITHOUT TIME ZONE AS request_on,
            bi_query_eft.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_eft.create_user_id AS create_user_id,
            bi_query_eft.create_function_name AS create_function_name,
            bi_query_eft.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_eft.update_user_id AS update_user_id,
            bi_query_eft.update_function_name AS update_function_name,
            bi_query_eft.transfer_type AS transfer_type,
            bi_query_eft.cpa_transaction_type AS cpa_transaction_type,
            bi_query_eft.pcb_institution_id AS pcb_institution_id,
            bi_query_eft.pcb_transit_number AS pcb_transit_number,
            bi_query_eft.pcb_customer_account_number AS pcb_customer_account_number,
            bi_query_eft.pcb_customer_name AS pcb_customer_name,
            bi_query_eft.origin_cross_reference_number AS origin_cross_reference_number,
            bi_query_eft.origin_institution_id AS origin_institution_id,
            bi_query_eft.origin_transit_number AS origin_transit_number,
            bi_query_eft.origin_account_number AS origin_account_number,
            bi_query_eft.origin_trace_number AS origin_trace_number,
            bi_query_eft.bi_query_eft_uid AS bi_query_eft_uid,
            bi_query_eft.eft_source AS eft_source
        FROM
            {env}_reverse_etl.bi_query_eft
        UNION
        DISTINCT
        SELECT
            bi_query_eft_default.pcf_cust_id AS pcf_cust_id,
            bi_query_eft_default.account_no AS account_no,
            bi_query_eft_default.card_number AS card_number,
            bi_query_eft_default.payer_name AS payer_name,
            bi_query_eft_default.amount AS amount,
            bi_query_eft_default.eft_req_uid AS eft_req_uid,
            bi_query_eft_default.eft_fulfillment_uid AS eft_fulfillment_uid,
            bi_query_eft_default.eft_reqtype_cd AS eft_reqtype_cd,
            bi_query_eft_default.fundsmove_instruction_id AS fundsmove_instruction_id,
            bi_query_eft_default.fundsmove_gl_req_uid AS fundsmove_gl_req_uid,
            bi_query_eft_default.fundsmove_processing_dt :: TIMESTAMP WITHOUT TIME ZONE AS fundsmove_processing_dt,
            bi_query_eft_default.institution_id AS institution_id,
            bi_query_eft_default.transit_number AS transit_number,
            bi_query_eft_default.eft_account_no AS eft_account_no,
            bi_query_eft_default.originator_name AS originator_name,
            bi_query_eft_default.originator_id AS originator_id,
            bi_query_eft_default.settle_on AS settle_on,
            bi_query_eft_default.pcb_assigned_opacct_nickname AS pcb_assigned_opacct_nickname,
            bi_query_eft_default.opacct_institution_no AS opacct_institution_no,
            bi_query_eft_default.opacct_transit_number AS opacct_transit_number,
            bi_query_eft_default.opacct_number AS opacct_number,
            bi_query_eft_default.trace_id AS trace_id,
            bi_query_eft_default.executed_on :: TIMESTAMP WITHOUT TIME ZONE AS executed_on,
            bi_query_eft_default.request_on :: TIMESTAMP WITHOUT TIME ZONE AS request_on,
            bi_query_eft_default.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_eft_default.create_user_id AS create_user_id,
            bi_query_eft_default.create_function_name AS create_function_name,
            bi_query_eft_default.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_eft_default.update_user_id AS update_user_id,
            bi_query_eft_default.update_function_name AS update_function_name,
            bi_query_eft_default.transfer_type AS transfer_type,
            bi_query_eft_default.cpa_transaction_type AS cpa_transaction_type,
            bi_query_eft_default.pcb_institution_id AS pcb_institution_id,
            bi_query_eft_default.pcb_transit_number AS pcb_transit_number,
            bi_query_eft_default.pcb_customer_account_number AS pcb_customer_account_number,
            bi_query_eft_default.pcb_customer_name AS pcb_customer_name,
            bi_query_eft_default.origin_cross_reference_number AS origin_cross_reference_number,
            bi_query_eft_default.origin_institution_id AS origin_institution_id,
            bi_query_eft_default.origin_transit_number AS origin_transit_number,
            bi_query_eft_default.origin_account_number AS origin_account_number,
            bi_query_eft_default.origin_trace_number AS origin_trace_number,
            bi_query_eft_default.bi_query_eft_uid AS bi_query_eft_uid,
            bi_query_eft_default.eft_source AS eft_source
        FROM
            {env}_reverse_etl.bi_query_eft_default
    ) AS EFT;

-- {env}_reverse_etl.vw_bi_query_paper_pymt_tx source
CREATE
OR REPLACE VIEW {env}_reverse_etl.vw_bi_query_paper_pymt_tx AS
SELECT
    PAPER_PAYMENT.pcf_cust_id,
    PAPER_PAYMENT.account_no,
    PAPER_PAYMENT.card_number,
    PAPER_PAYMENT.amount,
    PAPER_PAYMENT.seq_num,
    PAPER_PAYMENT.cheque_num,
    PAPER_PAYMENT.cheque_date,
    PAPER_PAYMENT.process_date,
    PAPER_PAYMENT.transit_number,
    PAPER_PAYMENT.institution_id,
    PAPER_PAYMENT.fdr_flag,
    PAPER_PAYMENT.fdr_date,
    PAPER_PAYMENT.create_dt,
    PAPER_PAYMENT.update_user_id,
    PAPER_PAYMENT.update_dt,
    PAPER_PAYMENT.st_cd,
    PAPER_PAYMENT.st_dt,
    PAPER_PAYMENT.csh_ind,
    PAPER_PAYMENT.create_user_id,
    PAPER_PAYMENT.create_function_name,
    PAPER_PAYMENT.trace_id,
    PAPER_PAYMENT.update_function_name,
    PAPER_PAYMENT.bi_query_paper_payment_uid,
    PAPER_PAYMENT.paper_payment_source
FROM
    (
        SELECT
            bi_query_paper_payment.pcf_cust_id AS pcf_cust_id,
            bi_query_paper_payment.account_no AS account_no,
            bi_query_paper_payment.card_number AS card_number,
            bi_query_paper_payment.amount AS amount,
            bi_query_paper_payment.seq_num AS seq_num,
            bi_query_paper_payment.cheque_num AS cheque_num,
            bi_query_paper_payment.cheque_date AS cheque_date,
            bi_query_paper_payment.process_date :: TIMESTAMP WITHOUT TIME ZONE AS process_date,
            bi_query_paper_payment.transit_number AS transit_number,
            bi_query_paper_payment.institution_id AS institution_id,
            bi_query_paper_payment.fdr_flag AS fdr_flag,
            bi_query_paper_payment.fdr_date :: TIMESTAMP WITHOUT TIME ZONE AS fdr_date,
            bi_query_paper_payment.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_paper_payment.update_user_id AS update_user_id,
            bi_query_paper_payment.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_paper_payment.st_cd AS st_cd,
            bi_query_paper_payment.st_dt :: TIMESTAMP WITHOUT TIME ZONE AS st_dt,
            bi_query_paper_payment.csh_ind AS csh_ind,
            bi_query_paper_payment.create_user_id AS create_user_id,
            bi_query_paper_payment.create_function_name AS create_function_name,
            bi_query_paper_payment.trace_id AS trace_id,
            bi_query_paper_payment.update_function_name AS update_function_name,
            bi_query_paper_payment.bi_query_paper_payment_uid AS bi_query_paper_payment_uid,
            bi_query_paper_payment.paper_payment_source AS paper_payment_source
        FROM
            {env}_reverse_etl.bi_query_paper_payment
        UNION
        DISTINCT
        SELECT
            bi_query_paper_payment_default.pcf_cust_id AS pcf_cust_id,
            bi_query_paper_payment_default.account_no AS account_no,
            bi_query_paper_payment_default.card_number AS card_number,
            bi_query_paper_payment_default.amount AS amount,
            bi_query_paper_payment_default.seq_num AS seq_num,
            bi_query_paper_payment_default.cheque_num AS cheque_num,
            bi_query_paper_payment_default.cheque_date AS cheque_date,
            bi_query_paper_payment_default.process_date :: TIMESTAMP WITHOUT TIME ZONE AS process_date,
            bi_query_paper_payment_default.transit_number AS transit_number,
            bi_query_paper_payment_default.institution_id AS institution_id,
            bi_query_paper_payment_default.fdr_flag AS fdr_flag,
            bi_query_paper_payment_default.fdr_date :: TIMESTAMP WITHOUT TIME ZONE AS fdr_date,
            bi_query_paper_payment_default.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_paper_payment_default.update_user_id AS update_user_id,
            bi_query_paper_payment_default.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_paper_payment_default.st_cd AS st_cd,
            bi_query_paper_payment_default.st_dt :: TIMESTAMP WITHOUT TIME ZONE AS st_dt,
            bi_query_paper_payment_default.csh_ind AS csh_ind,
            bi_query_paper_payment_default.create_user_id AS create_user_id,
            bi_query_paper_payment_default.create_function_name AS create_function_name,
            bi_query_paper_payment_default.trace_id AS trace_id,
            bi_query_paper_payment_default.update_function_name AS update_function_name,
            bi_query_paper_payment_default.bi_query_paper_payment_uid AS bi_query_paper_payment_uid,
            bi_query_paper_payment_default.paper_payment_source AS paper_payment_source
        FROM
            {env}_reverse_etl.bi_query_paper_payment_default
    ) AS PAPER_PAYMENT;

-- {env}_reverse_etl.vw_bi_query_telpay_pymt_inb_req source
CREATE
OR REPLACE VIEW {env}_reverse_etl.vw_bi_query_telpay_pymt_inb_req AS
SELECT
    TELPAY.pcf_cust_id,
    TELPAY.account_no,
    TELPAY.card_number,
    TELPAY.payer_name,
    TELPAY.amount,
    TELPAY.orig_fi_dt,
    TELPAY.eff_pymt_dt,
    TELPAY.run_timestamp,
    TELPAY.create_dt,
    TELPAY.update_dt,
    TELPAY.trace_id,
    TELPAY.report_number,
    TELPAY.run_number,
    TELPAY.telpay_pymt_uid,
    TELPAY.card_deposit_fulfillment_uid,
    TELPAY.hdr_id,
    TELPAY.version,
    TELPAY.biller_cd,
    TELPAY.create_user_id,
    TELPAY.create_function_name,
    TELPAY.update_user_id,
    TELPAY.update_function_name,
    TELPAY.bi_query_telpay_uid,
    TELPAY.telpay_source
FROM
    (
        SELECT
            bi_query_telpay_ods.pcf_cust_id AS pcf_cust_id,
            bi_query_telpay_ods.account_no AS account_no,
            bi_query_telpay_ods.card_number AS card_number,
            bi_query_telpay_ods.payer_name AS payer_name,
            bi_query_telpay_ods.amount AS amount,
            bi_query_telpay_ods.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_telpay_ods.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_telpay_ods.run_timestamp :: TIMESTAMP WITHOUT TIME ZONE AS run_timestamp,
            bi_query_telpay_ods.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_telpay_ods.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_telpay_ods.trace_id AS trace_id,
            bi_query_telpay_ods.report_number AS report_number,
            bi_query_telpay_ods.run_number AS run_number,
            bi_query_telpay_ods.telpay_pymt_uid AS telpay_pymt_uid,
            bi_query_telpay_ods.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_telpay_ods.hdr_id AS hdr_id,
            bi_query_telpay_ods.version AS version,
            bi_query_telpay_ods.biller_cd AS biller_cd,
            bi_query_telpay_ods.create_user_id AS create_user_id,
            bi_query_telpay_ods.create_function_name AS create_function_name,
            bi_query_telpay_ods.update_user_id AS update_user_id,
            bi_query_telpay_ods.update_function_name AS update_function_name,
            bi_query_telpay_ods.bi_query_telpay_uid AS bi_query_telpay_uid,
            bi_query_telpay_ods.telpay_source AS telpay_source
        FROM
            {env}_reverse_etl.bi_query_telpay_ods
        UNION
        DISTINCT
        SELECT
            bi_query_telpay_ods_default.pcf_cust_id AS pcf_cust_id,
            bi_query_telpay_ods_default.account_no AS account_no,
            bi_query_telpay_ods_default.card_number AS card_number,
            bi_query_telpay_ods_default.payer_name AS payer_name,
            bi_query_telpay_ods_default.amount AS amount,
            bi_query_telpay_ods_default.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_telpay_ods_default.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_telpay_ods_default.run_timestamp :: TIMESTAMP WITHOUT TIME ZONE AS run_timestamp,
            bi_query_telpay_ods_default.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_telpay_ods_default.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_telpay_ods_default.trace_id AS trace_id,
            bi_query_telpay_ods_default.report_number AS report_number,
            bi_query_telpay_ods_default.run_number AS run_number,
            bi_query_telpay_ods_default.telpay_pymt_uid AS telpay_pymt_uid,
            bi_query_telpay_ods_default.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_telpay_ods_default.hdr_id AS hdr_id,
            bi_query_telpay_ods_default.version AS version,
            bi_query_telpay_ods_default.biller_cd AS biller_cd,
            bi_query_telpay_ods_default.create_user_id AS create_user_id,
            bi_query_telpay_ods_default.create_function_name AS create_function_name,
            bi_query_telpay_ods_default.update_user_id AS update_user_id,
            bi_query_telpay_ods_default.update_function_name AS update_function_name,
            bi_query_telpay_ods_default.bi_query_telpay_uid AS bi_query_telpay_uid,
            bi_query_telpay_ods_default.telpay_source AS telpay_source
        FROM
            {env}_reverse_etl.bi_query_telpay_ods_default
        UNION
        DISTINCT
        SELECT
            bi_query_telpay_053.pcf_cust_id AS pcf_cust_id,
            bi_query_telpay_053.account_no AS account_no,
            bi_query_telpay_053.card_number AS card_number,
            bi_query_telpay_053.payer_name AS payer_name,
            bi_query_telpay_053.amount AS amount,
            bi_query_telpay_053.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_telpay_053.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_telpay_053.run_timestamp :: TIMESTAMP WITHOUT TIME ZONE AS run_timestamp,
            bi_query_telpay_053.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_telpay_053.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_telpay_053.trace_id AS trace_id,
            bi_query_telpay_053.report_number AS report_number,
            bi_query_telpay_053.run_number AS run_number,
            bi_query_telpay_053.telpay_pymt_uid AS telpay_pymt_uid,
            bi_query_telpay_053.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_telpay_053.hdr_id AS hdr_id,
            bi_query_telpay_053.version AS version,
            bi_query_telpay_053.biller_cd AS biller_cd,
            bi_query_telpay_053.create_user_id AS create_user_id,
            bi_query_telpay_053.create_function_name AS create_function_name,
            bi_query_telpay_053.update_user_id AS update_user_id,
            bi_query_telpay_053.update_function_name AS update_function_name,
            bi_query_telpay_053.bi_query_telpay_uid AS bi_query_telpay_uid,
            bi_query_telpay_053.telpay_source AS telpay_source
        FROM
            {env}_reverse_etl.bi_query_telpay_053
        UNION
        DISTINCT
        SELECT
            bi_query_telpay_053_default.pcf_cust_id AS pcf_cust_id,
            bi_query_telpay_053_default.account_no AS account_no,
            bi_query_telpay_053_default.card_number AS card_number,
            bi_query_telpay_053_default.payer_name AS payer_name,
            bi_query_telpay_053_default.amount AS amount,
            bi_query_telpay_053_default.orig_fi_dt :: TIMESTAMP WITHOUT TIME ZONE AS orig_fi_dt,
            bi_query_telpay_053_default.eff_pymt_dt :: TIMESTAMP WITHOUT TIME ZONE AS eff_pymt_dt,
            bi_query_telpay_053_default.run_timestamp :: TIMESTAMP WITHOUT TIME ZONE AS run_timestamp,
            bi_query_telpay_053_default.create_dt :: TIMESTAMP WITHOUT TIME ZONE AS create_dt,
            bi_query_telpay_053_default.update_dt :: TIMESTAMP WITHOUT TIME ZONE AS update_dt,
            bi_query_telpay_053_default.trace_id AS trace_id,
            bi_query_telpay_053_default.report_number AS report_number,
            bi_query_telpay_053_default.run_number AS run_number,
            bi_query_telpay_053_default.telpay_pymt_uid AS telpay_pymt_uid,
            bi_query_telpay_053_default.card_deposit_fulfillment_uid AS card_deposit_fulfillment_uid,
            bi_query_telpay_053_default.hdr_id AS hdr_id,
            bi_query_telpay_053_default.version AS version,
            bi_query_telpay_053_default.biller_cd AS biller_cd,
            bi_query_telpay_053_default.create_user_id AS create_user_id,
            bi_query_telpay_053_default.create_function_name AS create_function_name,
            bi_query_telpay_053_default.update_user_id AS update_user_id,
            bi_query_telpay_053_default.update_function_name AS update_function_name,
            bi_query_telpay_053_default.bi_query_telpay_uid AS bi_query_telpay_uid,
            bi_query_telpay_053_default.telpay_source AS telpay_source
        FROM
            {env}_reverse_etl.bi_query_telpay_053_default
    ) AS TELPAY;