CREATE OR REPLACE VIEW
  pcb-{env}-processing.domain_account_management.CONCAT_BLOCK_CODES
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
) AS
SELECT
  CAST(cifp_account_id5 AS INT64) AS cifp_account_id5,
  ACTIVE_CUSTOMER_BASE.customer_uid,
  CONCAT(cifp_status_code_01,cifp_reason_code_01) AS cifp_block_code_01,
  CONCAT(cifp_status_code_02,cifp_reason_code_02) AS cifp_block_code_02,
  CONCAT(cifp_status_code_03,cifp_reason_code_03) AS cifp_block_code_03,
  CONCAT(cifp_status_code_04,cifp_reason_code_04) AS cifp_block_code_04,
  CONCAT(cifp_status_code_05,cifp_reason_code_05) AS cifp_block_code_05,
  CONCAT(cifp_status_code_06,cifp_reason_code_06) AS cifp_block_code_06,
  CONCAT(cifp_status_code_07,cifp_reason_code_07) AS cifp_block_code_07,
  CONCAT(cifp_status_code_08,cifp_reason_code_08) AS cifp_block_code_08,
  CONCAT(cifp_status_code_09,cifp_reason_code_09) AS cifp_block_code_09,
  CONCAT(cifp_status_code_10,cifp_reason_code_10) AS cifp_block_code_10,
  CONCAT(cifp_status_code_11,cifp_reason_code_11) AS cifp_block_code_11,
  CONCAT(cifp_status_code_12,cifp_reason_code_12) AS cifp_block_code_12,
  CONCAT(cifp_status_code_13,cifp_reason_code_13) AS cifp_block_code_13,
  CONCAT(cifp_status_code_14,cifp_reason_code_14) AS cifp_block_code_14,
  CONCAT(cifp_status_code_15,cifp_reason_code_15) AS cifp_block_code_15,
  CONCAT(cifp_status_code_16,cifp_reason_code_16) AS cifp_block_code_16,
  CONCAT(cifp_status_code_17,cifp_reason_code_17) AS cifp_block_code_17,
  CONCAT(cifp_status_code_18,cifp_reason_code_18) AS cifp_block_code_18,
  CONCAT(cifp_status_code_19,cifp_reason_code_19) AS cifp_block_code_19,
  CONCAT(cifp_status_code_20,cifp_reason_code_20) AS cifp_block_code_20,
  CONCAT(cifp_status_code_21,cifp_reason_code_21) AS cifp_block_code_21,
  CONCAT(cifp_status_code_22,cifp_reason_code_22) AS cifp_block_code_22,
  CONCAT(cifp_status_code_23,cifp_reason_code_23) AS cifp_block_code_23,
  CONCAT(cifp_status_code_24,cifp_reason_code_24) AS cifp_block_code_24,
  CONCAT(cifp_status_code_25,cifp_reason_code_25) AS cifp_block_code_25,
  CONCAT(cifp_status_code_26,cifp_reason_code_26) AS cifp_block_code_26,
  CONCAT(cifp_status_code_27,cifp_reason_code_27) AS cifp_block_code_27,
  CONCAT(cifp_status_code_28,cifp_reason_code_28) AS cifp_block_code_28,
  CONCAT(cifp_status_code_29,cifp_reason_code_29) AS cifp_block_code_29,
  CONCAT(cifp_status_code_30,cifp_reason_code_30) AS cifp_block_code_30,
  CONCAT(cifp_status_code_31,cifp_reason_code_31) AS cifp_block_code_31,
  CONCAT(cifp_status_code_32,cifp_reason_code_32) AS cifp_block_code_32,
  CONCAT(cifp_status_code_33,cifp_reason_code_33) AS cifp_block_code_33,
  CONCAT(cifp_status_code_34,cifp_reason_code_34) AS cifp_block_code_34,
  CONCAT(cifp_status_code_35,cifp_reason_code_35) AS cifp_block_code_35,
  CONCAT(cifp_status_code_36,cifp_reason_code_36) AS cifp_block_code_36,
  CONCAT(cifp_status_code_37,cifp_reason_code_37) AS cifp_block_code_37,
  CONCAT(cifp_status_code_38,cifp_reason_code_38) AS cifp_block_code_38,
  CONCAT(cifp_status_code_39,cifp_reason_code_39) AS cifp_block_code_39,
  CONCAT(cifp_status_code_40,cifp_reason_code_40) AS cifp_block_code_40,
  CONCAT(cifp_status_code_41,cifp_reason_code_41) AS cifp_block_code_41,
  CONCAT(cifp_status_code_42,cifp_reason_code_42) AS cifp_block_code_42,
  CONCAT(cifp_status_code_43,cifp_reason_code_43) AS cifp_block_code_43,
  CONCAT(cifp_status_code_44,cifp_reason_code_44) AS cifp_block_code_44,
  CONCAT(cifp_status_code_45,cifp_reason_code_45) AS cifp_block_code_45,
  CONCAT(cifp_status_code_46,cifp_reason_code_46) AS cifp_block_code_46,
  CONCAT(cifp_status_code_47,cifp_reason_code_47) AS cifp_block_code_47,
  CONCAT(cifp_status_code_48,cifp_reason_code_48) AS cifp_block_code_48,
  CONCAT(cifp_status_code_49,cifp_reason_code_49) AS cifp_block_code_49,
  CONCAT(cifp_status_code_50,cifp_reason_code_50) AS cifp_block_code_50,
  CONCAT(cifp_status_code_51,cifp_reason_code_51) AS cifp_block_code_51,
  CONCAT(cifp_status_code_52,cifp_reason_code_52) AS cifp_block_code_52,
  CONCAT(cifp_status_code_53,cifp_reason_code_53) AS cifp_block_code_53,
  CONCAT(cifp_status_code_54,cifp_reason_code_54) AS cifp_block_code_54,
  CONCAT(cifp_status_code_55,cifp_reason_code_55) AS cifp_block_code_55,
  CONCAT(cifp_status_code_56,cifp_reason_code_56) AS cifp_block_code_56,
  CONCAT(cifp_status_code_57,cifp_reason_code_57) AS cifp_block_code_57,
  CONCAT(cifp_status_code_58,cifp_reason_code_58) AS cifp_block_code_58,
  CONCAT(cifp_status_code_59,cifp_reason_code_59) AS cifp_block_code_59,
  CONCAT(cifp_status_code_60,cifp_reason_code_60) AS cifp_block_code_60,
  CONCAT(cifp_status_code_61,cifp_reason_code_61) AS cifp_block_code_61,
  CONCAT(cifp_status_code_62,cifp_reason_code_62) AS cifp_block_code_62,
  CONCAT(cifp_status_code_63,cifp_reason_code_63) AS cifp_block_code_63,
  CONCAT(cifp_status_code_64,cifp_reason_code_64) AS cifp_block_code_64,
  CONCAT(cifp_status_code_65,cifp_reason_code_65) AS cifp_block_code_65,
  CONCAT(cifp_status_code_66,cifp_reason_code_66) AS cifp_block_code_66,
  CONCAT(cifp_status_code_67,cifp_reason_code_67) AS cifp_block_code_67,
  CONCAT(cifp_status_code_68,cifp_reason_code_68) AS cifp_block_code_68,
  CONCAT(cifp_status_code_69,cifp_reason_code_69) AS cifp_block_code_69,
  CONCAT(cifp_status_code_70,cifp_reason_code_70) AS cifp_block_code_70,
  CONCAT(cifp_status_code_71,cifp_reason_code_71) AS cifp_block_code_71,
  CONCAT(cifp_status_code_72,cifp_reason_code_72) AS cifp_block_code_72,
  CONCAT(cifp_status_code_73,cifp_reason_code_73) AS cifp_block_code_73,
  CONCAT(cifp_status_code_74,cifp_reason_code_74) AS cifp_block_code_74,
  CONCAT(cifp_status_code_75,cifp_reason_code_75) AS cifp_block_code_75,
  CONCAT(cifp_status_code_76,cifp_reason_code_76) AS cifp_block_code_76,
  CONCAT(cifp_status_code_77,cifp_reason_code_77) AS cifp_block_code_77,
  CONCAT(cifp_status_code_78,cifp_reason_code_78) AS cifp_block_code_78,
  CONCAT(cifp_status_code_79,cifp_reason_code_79) AS cifp_block_code_79,
  CONCAT(cifp_status_code_80,cifp_reason_code_80) AS cifp_block_code_80,
  CONCAT(cifp_status_code_81,cifp_reason_code_81) AS cifp_block_code_81,
  CONCAT(cifp_status_code_82,cifp_reason_code_82) AS cifp_block_code_82
FROM
  pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR
JOIN
  pcb-{env}-processing.domain_account_management.ACTIVE_CUSTOMER_BASE
ON
  ACTIVE_CUSTOMER_BASE.account_no=CAST(cifp_account_id5 AS INT64);