CREATE OR REPLACE VIEW
    `pcb-{env}-processing.domain_scoring.AM00_VIEW`
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
    description = "View for AM00 segment"
) AS
    SELECT MAST_ACCOUNT_ID,AM00_APPLICATION_SUFFIX AS APPLICATION_SUFFIX,AM00_AUTO_PAYMENT_CODE AS AUTO_PAYMENT_CODE,AM00_AUTO_PAYMENT_METHOD AS AUTO_PAYMENT_METHOD,AM00_AUTO_PAYMENT_USER_ACCT AS AUTO_PAYMENT_USER_ACCT,AM00_BILLING_CYCLE AS BILLING_CYCLE,AM00_CASH_AVAILABLE AS CASH_AVAILABLE,AM00_CASH_LIMIT AS CASH_LIMIT,AM00_CB_RISK_SCORE_ORG AS CB_RISK_SCORE_ORG,AM00_CLCHG_STATUS AS CLCHG_STATUS,AM00_CLCHG_TYPE AS CLCHG_TYPE,AM00_CLIENT_PRODUCT_CODE AS CLIENT_PRODUCT_CODE,AM00_CREDIT_SCORE_ORG AS CREDIT_SCORE_ORG,AM00_CUSTOM_DATA_10 AS CUSTOM_DATA_10,AM00_CUSTOM_DATA_11 AS CUSTOM_DATA_11,AM00_CUSTOM_DATA_12 AS CUSTOM_DATA_12,AM00_CUSTOM_DATA_13 AS CUSTOM_DATA_13,AM00_CUSTOM_DATA_14 AS CUSTOM_DATA_14,AM00_CUSTOM_DATA_20 AS CUSTOM_DATA_20,AM00_CUSTOM_DATA_21 AS CUSTOM_DATA_21,AM00_CUSTOM_DATA_22 AS CUSTOM_DATA_22,AM00_CUSTOM_DATA_23 AS CUSTOM_DATA_23,AM00_CUSTOM_DATA_24 AS CUSTOM_DATA_24,AM00_CUSTOM_DATA_40 AS CUSTOM_DATA_40,AM00_CUSTOM_DATA_41 AS CUSTOM_DATA_41,AM00_CUSTOM_DATA_42 AS CUSTOM_DATA_42,AM00_CUSTOM_DATA_43 AS CUSTOM_DATA_43,AM00_CUSTOM_DATA_44 AS CUSTOM_DATA_44,AM00_CUSTOM_DATA_60 AS CUSTOM_DATA_60,AM00_CUSTOM_DATA_61 AS CUSTOM_DATA_61,AM00_CUSTOM_DATA_62 AS CUSTOM_DATA_62,AM00_CUSTOM_DATA_63 AS CUSTOM_DATA_63,AM00_CUSTOM_DATA_64 AS CUSTOM_DATA_64,AM00_CUSTOM_DATA_80 AS CUSTOM_DATA_80,AM00_CUSTOM_DATA_81 AS CUSTOM_DATA_81,AM00_CUSTOM_DATA_90 AS CUSTOM_DATA_90,AM00_CUSTOM_DATA_91 AS CUSTOM_DATA_91,AM00_CUSTOM_DATA_92 AS CUSTOM_DATA_92,AM00_CUSTOM_DATA_93 AS CUSTOM_DATA_93,AM00_DATE_ACCOUNT_OPEN AS DATE_ACCOUNT_OPEN,AM00_DATE_CLOSE AS DATE_CLOSE,AM00_DATE_LAST_LIMIT_CHG AS DATE_LAST_LIMIT_CHG,AM00_DATE_LAST_PERM_CR_CHG AS DATE_LAST_PERM_CR_CHG,AM00_DT_FIRST_DLQ AS DT_FIRST_DLQ,AM00_INACTIVE_FLAG AS INACTIVE_FLAG,AM00_LIMIT_CREDIT AS LIMIT_CREDIT_AM,AM00_LIMIT_ORIGINAL_CREDIT AS LIMIT_ORIGINAL_CREDIT,AM00_STATC_CHARGEOFF AS STATC_CHARGEOFF,AM00_STATC_CLOSED AS STATC_CLOSED,AM00_STATC_CLOSED_DATE_MNT AS STATC_CLOSED_DATE_MNT,AM00_STATC_CREDIT_REVOKED AS STATC_CREDIT_REVOKED,AM00_STATC_CRVK_ADD_DATE AS STATC_CRVK_ADD_DATE,AM00_STATC_CRVK_MNT_DATE AS STATC_CRVK_MNT_DATE,AM00_STATC_CURRENT_PAST_DUE AS STATC_CURRENT_PAST_DUE,AM00_STATC_FIRST_USE AS STATC_FIRST_USE,AM00_STATC_FIXED_PAYMENT AS STATC_FIXED_PAYMENT,AM00_STATC_RETURN_MAIL AS STATC_RETURN_MAIL,AM00_STATC_SECURITY_FRAUD AS STATC_SECURITY_FRAUD,AM00_STATC_TIERED_AUTH AS STATC_TIERED_AUTH,AM00_STATC_WATCH AS STATC_WATCH,AM00_STATF_ACTIVE_THIS_CYCLE AS STATF_ACTIVE_THIS_CYCLE,AM00_STATF_ACTIVE_THIS_MONTH AS STATF_ACTIVE_THIS_MONTH,AM00_STATF_ACTIVE_THIS_YEAR AS STATF_ACTIVE_THIS_YEAR,AM00_STATF_ADDR_CHNG_THIS_CYC AS STATF_ADDR_CHNG_THIS_CYC,AM00_STATF_CASH_REV_THIS_CYC AS STATF_CASH_REV_THIS_CYC,AM00_STATF_FRAUD AS STATF_FRAUD,AM00_STATF_INACTIVE AS STATF_INACTIVE,AM00_STATF_INACTIVE_DATE AS STATF_INACTIVE_DATE,AM00_TNDM_AUTH_PROC_TIER_EDATE AS TNDM_AUTH_PROC_TIER_EDATE,AM00_TNDM_AUTH_PROC_TIER_SDATE AS TNDM_AUTH_PROC_TIER_SDATE,AM00_TRIAD_SCORE_ALIGNED AS TRIAD_SCORE_ALIGNED,AM00_TRIAD_SCORE_CARD_ID AS TRIAD_SCORE_CARD_ID,AM00_TSYS_PRODUCT_CODE AS TSYS_PRODUCT_CODE,AM00_TYPEC_VIP AS TYPEC_VIP, FILE_CREATE_DT as AM00_FILE_CREATE_DT
    FROM pcb-{env}-curated.domain_account_management.AM00
       WHERE FILE_CREATE_DT = '{am_file_create_date}' and AM00_APPLICATION_SUFFIX=0;

CREATE OR REPLACE VIEW
    `pcb-{env}-processing.domain_scoring.AM01_VIEW`
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
    description = "View for AM01 segment"
) AS
    SELECT MAST_ACCOUNT_ID as AM01_MAST_ACCOUNT_ID,AM01_ACCOUNT_NUM AS ACCOUNT_NUM, AM01_ACCOUNT_REL_STAT AS ACCOUNT_REL_STAT
    FROM pcb-{env}-curated.domain_account_management.AM01
    WHERE FILE_CREATE_DT = '{am_file_create_date}' and am00_application_suffix = 0  and am01_customer_type = 0 and am01_account_rel_stat in('A','',' ');

CREATE OR REPLACE VIEW
    `pcb-{env}-processing.domain_scoring.AM02_VIEW`
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
    description = "View for AM02 segment"
) AS
    SELECT MAST_ACCOUNT_ID as AM02_MAST_ACCOUNT_ID,AM02_AMT_CASH_LTD AS AMT_CASH_LTD,AM02_AMT_CASH_YTD AS AMT_CASH_YTD,AM02_AMT_CONV_CHECKS_LTD AS AMT_CONV_CHECKS_LTD,AM02_AMT_CONV_CHECKS_YTD AS AMT_CONV_CHECKS_YTD,AM02_AMT_FCHG_BILLED_PYE AS AMT_FCHG_BILLED_PYE,AM02_AMT_FCHG_BILLED_YTD AS AMT_FCHG_BILLED_YTD,AM02_AMT_FCHG_PAID_LTD AS AMT_FCHG_PAID_LTD,AM02_AMT_FCHG_PAID_PYE AS AMT_FCHG_PAID_PYE,AM02_AMT_FCHG_PAID_YTD AS AMT_FCHG_PAID_YTD,AM02_AMT_LAST_CASH AS AMT_LAST_CASH,AM02_AMT_LAST_NSF_PAYMENT AS AMT_LAST_NSF_PAYMENT,AM02_AMT_LAST_PAYMENT AS AMT_LAST_PAYMENT,AM02_AMT_LIMIT_DECREASE_LTD AS AMT_LIMIT_DECREASE_LTD,AM02_AMT_LIMIT_DECREASE_PYE AS AMT_LIMIT_DECREASE_PYE,AM02_AMT_LIMIT_DECREASE_YTD AS AMT_LIMIT_DECREASE_YTD,AM02_AMT_LIMIT_INCREASE_LTD AS AMT_LIMIT_INCREASE_LTD,AM02_AMT_LIMIT_INCREASE_PYE AS AMT_LIMIT_INCREASE_PYE,AM02_AMT_LIMIT_INCREASE_YTD AS AMT_LIMIT_INCREASE_YTD,AM02_AMT_NSF_PAYMENTS_CTD AS AMT_NSF_PAYMENTS_CTD,AM02_AMT_NSF_PAYMENTS_LTD AS AMT_NSF_PAYMENTS_LTD,AM02_AMT_NSF_PAYMENTS_PYE AS AMT_NSF_PAYMENTS_PYE,AM02_AMT_NSF_PAYMENTS_YTD AS AMT_NSF_PAYMENTS_YTD,AM02_AMT_PAYMENTS_CTD AS AMT_PAYMENTS_CTD,AM02_AMT_PAYMENTS_LTD AS AMT_PAYMENTS_LTD,AM02_AMT_PAYMENTS_PYE AS AMT_PAYMENTS_PYE,AM02_AMT_PAYMENTS_YTD AS AMT_PAYMENTS_YTD,AM02_AMT_PURCHASES_LTD AS AMT_PURCHASES_LTD,AM02_AMT_PURCHASES_YTD AS AMT_PURCHASES_YTD,AM02_BALANCE_CURRENT AS BALANCE_CURRENT_AM,AM02_BALANCE_PREV_STATEMENT AS BALANCE_PREV_STATEMENT_AM,AM02_DATE_FIRST_USE AS DATE_FIRST_USE,AM02_DATE_LAST_CASH AS DATE_LAST_CASH,AM02_DATE_LAST_NSF_PAYMENT AS DATE_LAST_NSF_PAYMENT,AM02_DATE_LAST_PAID_BALANCE AS DATE_LAST_PAID_BALANCE,AM02_DATE_LAST_PAYMENT AS DATE_LAST_PAYMENT,AM02_DATE_LAST_PURCHASE AS DATE_LAST_PURCHASE,AM02_MTHS_CONSECUTIVE_MIN_PAY AS MTHS_CONSECUTIVE_MIN_PAY,AM02_NUM_CASH_LTD AS NUM_CASH_LTD,AM02_NUM_CASH_YTD AS NUM_CASH_YTD,AM02_NUM_LIMIT_DECREASE_LTD AS NUM_LIMIT_DECREASE_LTD,AM02_NUM_LIMIT_DECREASE_PYE AS NUM_LIMIT_DECREASE_PYE,AM02_NUM_LIMIT_DECREASE_YTD AS NUM_LIMIT_DECREASE_YTD,AM02_NUM_LIMIT_INCREASE_LTD AS NUM_LIMIT_INCREASE_LTD,AM02_NUM_LIMIT_INCREASE_PYE AS NUM_LIMIT_INCREASE_PYE,AM02_NUM_LIMIT_INCREASE_YTD AS NUM_LIMIT_INCREASE_YTD,AM02_NUM_NSF_PAYMENTS_CTD AS NUM_NSF_PAYMENTS_CTD,AM02_NUM_NSF_PAYMENTS_PYE AS NUM_NSF_PAYMENTS_PYE,AM02_NUM_NSF_PAYMENTS_YTD AS NUM_NSF_PAYMENTS_YTD,AM02_NUM_PAYMENTS_CTD AS NUM_PAYMENTS_CTD,AM02_NUM_PAYMENTS_LTD AS NUM_PAYMENTS_LTD,AM02_NUM_PAYMENTS_PYE AS NUM_PAYMENTS_PYE,AM02_NUM_PAYMENTS_YTD AS NUM_PAYMENTS_YTD,AM02_NUM_PURCHASES_LTD AS NUM_PURCHASES_LTD,AM02_NUM_PURCHASES_YTD AS NUM_PURCHASES_YTD,AM02_PAID_IN_FULL_CYCLE_IND AS PAID_IN_FULL_CYCLE_IND,AM02_PASTDUE_AT_CYCLE_1 AS PASTDUE_AT_CYCLE_1,AM02_PASTDUE_AT_CYCLE_10 AS PASTDUE_AT_CYCLE_10,AM02_PASTDUE_AT_CYCLE_11 AS PASTDUE_AT_CYCLE_11,AM02_PASTDUE_AT_CYCLE_12 AS PASTDUE_AT_CYCLE_12,AM02_PASTDUE_AT_CYCLE_2 AS PASTDUE_AT_CYCLE_2,AM02_PASTDUE_AT_CYCLE_3 AS PASTDUE_AT_CYCLE_3,AM02_PASTDUE_AT_CYCLE_4 AS PASTDUE_AT_CYCLE_4,AM02_PASTDUE_AT_CYCLE_5 AS PASTDUE_AT_CYCLE_5,AM02_PASTDUE_AT_CYCLE_6 AS PASTDUE_AT_CYCLE_6,AM02_PASTDUE_AT_CYCLE_7 AS PASTDUE_AT_CYCLE_7,AM02_PASTDUE_AT_CYCLE_8 AS PASTDUE_AT_CYCLE_8,AM02_PASTDUE_AT_CYCLE_9 AS PASTDUE_AT_CYCLE_9
    FROM pcb-{env}-curated.domain_account_management.AM02
    WHERE FILE_CREATE_DT = '{am_file_create_date}' and am00_application_suffix = 0;

CREATE OR REPLACE VIEW
       `pcb-{env}-processing.domain_scoring.AH01_VIEW`
    OPTIONS (
        expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
        description = "View for AH01 segment"
    ) AS
       SELECT * EXCEPT(LATEST_CYCLED_RECORD_RN) FROM (
       SELECT MAST_ACCOUNT_ID as AH01_MAST_ACCOUNT_ID, AH01_ACTUAL_APR as ACTUAL_APR, AH01_AMT_NSF_PAYMENTS AS AMT_NSF_PAYMENTS, AH01_AMT_OVERLIMIT AS AMT_OVERLIMIT, AH01_AMT_PASTDUE_1 AS AMT_PASTDUE_1,AH01_AMT_PASTDUE_2 AS AMT_PASTDUE_2,AH01_AMT_PASTDUE_3 AS AMT_PASTDUE_3,AH01_AMT_PASTDUE_4 AS AMT_PASTDUE_4,AH01_AMT_PASTDUE_5 AS AMT_PASTDUE_5,AH01_AMT_PASTDUE_6 AS AMT_PASTDUE_6,AH01_AMT_PASTDUE_7 AS AMT_PASTDUE_7,AH01_AMT_PASTDUE_8 AS AMT_PASTDUE_8,AH01_AMT_PASTDUE_9 AS AMT_PASTDUE_9,AH01_AMT_PASTDUE_10 AS AMT_PASTDUE_10,AH01_AMT_PASTDUE_11 AS AMT_PASTDUE_11,AH01_AMT_PASTDUE_12 AS AMT_PASTDUE_12,AH01_AMT_PAYMENTS AS AMT_PAYMENTS,AH01_BALANCE_CURRENT AS BALANCE_CURRENT_AH,AH01_BALANCE_PREV_STATEMENT AS BALANCE_PREV_STATEMENT_AH,AH01_NUM_PAYMENTS AS NUM_PAYMENTS, AH01_DATE_HIGH_OL_CTD AS DATE_HIGH_OL_CTD, AH01_NUM_OVERLIMIT AS NUM_OVERLIMIT, IFNULL(AH01_CHARGEOFF,"") AS CHARGEOFF, AH01_LIMIT_CREDIT AS LIMIT_CREDIT, AH01_WEIGHTED_AVG_APR AS WEIGHTED_AVG_APR, IFNULL(AH01_PAST_DUE_REAGE,"") AS PAST_DUE_REAGE,
       dense_rank() OVER(PARTITION BY MAST_ACCOUNT_ID ORDER BY FILE_CREATE_DT desc, AH01_CDATE_CYCLE desc) as LATEST_CYCLED_RECORD_RN
       FROM pcb-{env}-curated.domain_account_management.AH01
       WHERE FILE_CREATE_DT BETWEEN DATE_SUB('{ah_file_create_date}', INTERVAL 1 MONTH) AND '{ah_file_create_date}'
       AND AH00_APPLICATION_SUFFIX = 0) where LATEST_CYCLED_RECORD_RN =1 ;


   CREATE OR REPLACE VIEW
        `pcb-{env}-processing.domain_scoring.AH02_REAGE_VIEW`
       OPTIONS (
          expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
          description = "View for AH02_REAGE segment"
       ) AS
           SELECT * EXCEPT(LATEST_CYCLED_RECORD_RN) FROM (
        SELECT MAST_ACCOUNT_ID as AH02_REAGE_MAST_ACCOUNT_ID, AH02_DATE_AUTO_PASTDUE_REAGE AS DATE_AUTO_PASTDUE_REAGE,AH02_DATE_MAN_PASTDUE_REAGE AS DATE_MAN_PASTDUE_REAGE,AH02_NUM_AUTO_PD_REAGE_LTD AS NUM_AUTO_PD_REAGE_LTD,
        dense_rank() OVER(PARTITION BY MAST_ACCOUNT_ID ORDER BY FILE_CREATE_DT desc, AH02_CDATE_HISTORY desc) as LATEST_CYCLED_RECORD_RN
        FROM pcb-{env}-curated.domain_account_management.AH02_REAGE
        WHERE FILE_CREATE_DT BETWEEN DATE_SUB('{ah_file_create_date}', INTERVAL 1 MONTH) AND '{ah_file_create_date}'
        AND AH00_APPLICATION_SUFFIX = 0) where LATEST_CYCLED_RECORD_RN =1 ;

CREATE OR REPLACE VIEW
    `pcb-{env}-processing.domain_scoring.AM0B_VIEW`
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
    description = "View for AM0B segment"
) AS
    SELECT MAST_ACCOUNT_ID as AM0B_MAST_ACCOUNT_ID,CAST(AM0B_TEST_DIGIT_1 AS STRING) AS TEST_DIGIT_1,CAST(AM0B_TEST_DIGIT_2 AS STRING) AS TEST_DIGIT_2,CAST(AM0B_TEST_DIGIT_3 AS STRING) AS TEST_DIGIT_3,CAST(AM0B_TEST_DIGIT_4 AS STRING) AS TEST_DIGIT_4,CAST(AM0B_USAGE_IND AS STRING) AS USAGE_IND
    FROM pcb-{env}-curated.domain_account_management.AM0BH
    WHERE FILE_CREATE_DT = '{am_file_create_date}' and am00_application_suffix = 0;

CREATE OR REPLACE VIEW
    `pcb-{env}-processing.domain_scoring.AM0E_VIEW`
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
    description = "View for AM0E segment"
) AS
    SELECT MAST_ACCOUNT_ID as AM0E_MAST_ACCOUNT_ID, AM0E_ADDRESS_LINE1 AS ADDRESS_LINE1,AM0E_ADDRESS_LINE2 AS ADDRESS_LINE2,AM0E_CITY AS CITY,AM0E_DATE_BIRTH AS DATE_BIRTH,AM0E_NAME AS NAME,AM0E_SOCIAL_SECURITY_NUM AS SOCIAL_SECURITY_NUM,AM0E_STATE_PROV_CODE AS STATE_PROV_CODE,AM0E_ZIP_POSTAL_CODE AS ZIP_POSTAL_CODE
    FROM pcb-{env}-curated.domain_account_management.AM0E
    WHERE FILE_CREATE_DT = '{am_file_create_date}' and am00_application_suffix = 0;

CREATE OR REPLACE VIEW
    `pcb-{env}-processing.domain_scoring.AM0A_VIEW`
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
    description = "View for AM0A segment"
) AS
    SELECT MAST_ACCOUNT_ID as AM0A_MAST_ACCOUNT_ID, AM0A_END_CARD_WATCH_DATE AS END_CARD_WATCH_DATE,AM0A_START_CARD_WATCH_DATE AS START_CARD_WATCH_DATE,AM0A_STATC_CARD_WATCH AS STATC_CARD_WATCH, AM0A_ACCOUNT_NUM
    FROM pcb-{env}-curated.domain_account_management.AM0A
    WHERE FILE_CREATE_DT = '{am_file_create_date}' and am00_application_suffix = 0;

CREATE OR REPLACE VIEW
               `pcb-{env}-processing.domain_scoring.AT31_VIEW`
            OPTIONS (
                expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
                description = "View for AT31 segment"
            ) AS
           WITH LCL_DATA AS
                   (
                       SELECT AT31_MAST_ACCOUNT_ID,
                        AT31_ACCOUNT_NUMB,
                        sum(AMT_TRANSACTION) as AT31_AMT_TRANSACTION
                       FROM (
                       SELECT MAST_ACCOUNT_ID as AT31_MAST_ACCOUNT_ID,
                       AT31_ACCOUNT_NUMB,
                         CASE
                           when AT31_DEBIT_CREDIT_INDICATOR = 'C' then (-1)*AT31_AMT_TRANSACTION
                           else AT31_AMT_TRANSACTION
                         end AS AMT_TRANSACTION
                               FROM pcb-{env}-curated.domain_account_management.AT31
                               WHERE FILE_CREATE_DT BETWEEN DATE_SUB('{am_file_create_date}', INTERVAL 1 MONTH) AND '{am_file_create_date}'
                                AND AT31_DATE_TRANSACTION BETWEEN DATE_SUB('{am_file_create_date}', INTERVAL 1 MONTH) AND '{am_file_create_date}'
                                AND SAFE_CAST(AT31_MERCHANT_ID AS NUMERIC) IN (SELECT SAFE_CAST(MERCHANT_ID AS NUMERIC) AS MERCHANT_ID FROM pcb-{env}-curated.domain_retail.GLOBAL_PAYMENT_MERCHANT)
                       ) GROUP BY AT31_MAST_ACCOUNT_ID, AT31_ACCOUNT_NUMB
                   ),
           NON_LCL_DATA AS
                   (
                       SELECT AT31_MAST_ACCOUNT_ID,
                        AT31_ACCOUNT_NUMB,
                        sum(AMT_TRANSACTION) as AT31_AMT_TRANSACTION
                       FROM (
                       SELECT MAST_ACCOUNT_ID as AT31_MAST_ACCOUNT_ID,
                       AT31_ACCOUNT_NUMB,
                         CASE
                           when AT31_DEBIT_CREDIT_INDICATOR = 'C' then (-1)*AT31_AMT_TRANSACTION
                           else AT31_AMT_TRANSACTION
                         end AS AMT_TRANSACTION
                               FROM pcb-{env}-curated.domain_account_management.AT31
                               WHERE FILE_CREATE_DT BETWEEN DATE_SUB('{am_file_create_date}', INTERVAL 1 MONTH) AND '{am_file_create_date}'
                                AND AT31_DATE_TRANSACTION BETWEEN DATE_SUB('{am_file_create_date}', INTERVAL 1 MONTH) AND '{am_file_create_date}'
                                AND SAFE_CAST(AT31_MERCHANT_ID AS NUMERIC) NOT IN (SELECT SAFE_CAST(MERCHANT_ID AS NUMERIC) AS MERCHANT_ID FROM pcb-{env}-curated.domain_retail.GLOBAL_PAYMENT_MERCHANT)
                       ) GROUP BY AT31_MAST_ACCOUNT_ID, AT31_ACCOUNT_NUMB
                   )
               SELECT AT31_MAST_ACCOUNT_ID, SUM(AMT_TRANSACTION) AS AMT_TRANSACTION, SUM(TOTALPOINTS) AS TOTALPOINTS
               FROM (
                   SELECT IFNULL(ld.AT31_MAST_ACCOUNT_ID, nld.AT31_MAST_ACCOUNT_ID) as AT31_MAST_ACCOUNT_ID,
                   ld.AT31_AMT_TRANSACTION as AMT_TRANSACTION,
                   case
                        when IFNULL(ld.AT31_ACCOUNT_NUMB,nld.AT31_ACCOUNT_NUMB)  like '518127%' then 10*IFNULL(ld.AT31_AMT_TRANSACTION,0) + 10*IFNULL(nld.AT31_AMT_TRANSACTION,0)
                        when IFNULL(ld.AT31_ACCOUNT_NUMB,nld.AT31_ACCOUNT_NUMB) like '522879%' then 20*IFNULL(ld.AT31_AMT_TRANSACTION,0) + 10*IFNULL(nld.AT31_AMT_TRANSACTION,0)
                        when IFNULL(ld.AT31_ACCOUNT_NUMB,nld.AT31_ACCOUNT_NUMB) like '518116%' then 30*IFNULL(ld.AT31_AMT_TRANSACTION,0) + 10*IFNULL(nld.AT31_AMT_TRANSACTION,0)
                        when IFNULL(ld.AT31_ACCOUNT_NUMB,nld.AT31_ACCOUNT_NUMB) like '516179%' then 40*IFNULL(ld.AT31_AMT_TRANSACTION,0) + 10*IFNULL(nld.AT31_AMT_TRANSACTION,0)
                        when IFNULL(ld.AT31_ACCOUNT_NUMB,nld.AT31_ACCOUNT_NUMB) like '533866%' then 10*IFNULL(ld.AT31_AMT_TRANSACTION,0) + 5*IFNULL(nld.AT31_AMT_TRANSACTION,0)
                        else 0
                   end AS TOTALPOINTS
                   from LCL_DATA ld FULL OUTER JOIN NON_LCL_DATA nld ON
                   nld.AT31_MAST_ACCOUNT_ID = ld.AT31_MAST_ACCOUNT_ID
                   AND nld.AT31_ACCOUNT_NUMB = ld.AT31_ACCOUNT_NUMB
               ) GROUP BY AT31_MAST_ACCOUNT_ID;

 CREATE OR REPLACE VIEW
     `pcb-{env}-processing.domain_scoring.SC01_VIEW`
     OPTIONS (
         expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
         description = "View for SC01 Risk Index segment"
     ) AS
     WITH CTE_RISK AS (
         SELECT
             MAST_ACCOUNT_ID,
             AVG(SC01_SCORE_RAW) AS AVG_RISK
         FROM `pcb-{env}-curated.domain_account_management.SC01`
         WHERE
             SC00_APPLICATION_SUFFIX = 0
             AND SC01_SCORE_TYPE = 'T0030'
             AND FILE_CREATE_DT BETWEEN DATE_SUB(DATE('{sc_file_create_date}'), INTERVAL 36 MONTH) AND DATE('{sc_file_create_date}')
         GROUP BY MAST_ACCOUNT_ID
     ),
     CTE_MONTH AS (
         SELECT DISTINCT
             MAST_ACCOUNT_ID,
             EXTRACT(MONTH FROM FILE_CREATE_DT) AS CREATE_MONTH
         FROM `pcb-{env}-curated.domain_account_management.SC01`
         WHERE
             SC00_APPLICATION_SUFFIX = 0
             AND FILE_CREATE_DT = '{sc_file_create_date}'
     ),
     LATEST_ALL_COLUMNS AS (
         SELECT
             MAST_ACCOUNT_ID,
             SC01_SCORE_TYPE,
             SC01_SCORE_ALIGNED,
             SC01_SCORE_REASON_2,
             FILE_CREATE_DT as SC01_FILE_CREATE_DT,
             ROW_NUMBER() OVER (PARTITION BY MAST_ACCOUNT_ID, SC00_APPLICATION_NUM, SC01_SCORE_TYPE ORDER BY SC01_DATE_SCORE_ADDED DESC) AS rn
         FROM `pcb-{env}-curated.domain_account_management.SC01`
         WHERE FILE_CREATE_DT = '{sc_file_create_date}'
             AND SC00_APPLICATION_SUFFIX = 0
             AND SC01_SCORE_TYPE IN ('T0064', 'T0066', 'T0080', 'T0081', 'T0001', 'T0010','T0030')
     ),
     LATEST_FILTER_RECORDS AS (
       SELECT
         MAST_ACCOUNT_ID,
         SC01_FILE_CREATE_DT,
         MAX(CASE WHEN SC01_SCORE_TYPE = 'T0064' THEN SC01_SCORE_ALIGNED END) AS CAAS1,
         MAX(CASE WHEN SC01_SCORE_TYPE = 'T0066' THEN SC01_SCORE_ALIGNED END) AS CAAS2,
         MAX(CASE WHEN SC01_SCORE_TYPE = 'T0080' THEN SC01_SCORE_ALIGNED END) AS APP_BCN,
         MAX(CASE WHEN SC01_SCORE_TYPE = 'T0081' THEN SC01_SCORE_ALIGNED END) AS APP_BNI,
         MAX(CASE WHEN SC01_SCORE_TYPE = 'T0001' THEN SC01_SCORE_ALIGNED END) AS BHV,
         MAX(CASE WHEN SC01_SCORE_TYPE = 'T0010' THEN SC01_SCORE_ALIGNED END) AS BNI,
         MAX(CASE WHEN SC01_SCORE_TYPE = 'T0030' THEN SC01_SCORE_ALIGNED END) AS MAX_SCORE
         FROM LATEST_ALL_COLUMNS
     WHERE rn = 1
     GROUP BY MAST_ACCOUNT_ID,SC01_FILE_CREATE_DT
     )
     SELECT
         L.MAST_ACCOUNT_ID AS SC01_MAST_ACCOUNT_ID,
         L.CAAS1,
         L.CAAS2,
         L.APP_BCN,
         L.APP_BNI,
         CAST(L.BHV AS STRING) AS BHV,
         CAST(L.BNI AS STRING) AS BNI,
         L.SC01_FILE_CREATE_DT,
         L.MAX_SCORE,
         C.CREATE_MONTH,
         R.AVG_RISK
     FROM LATEST_FILTER_RECORDS L
           LEFT JOIN CTE_RISK R ON L.MAST_ACCOUNT_ID = R.MAST_ACCOUNT_ID
           LEFT JOIN CTE_MONTH C ON L.MAST_ACCOUNT_ID = C.MAST_ACCOUNT_ID;

   CREATE OR REPLACE VIEW
           `pcb-{env}-processing.domain_scoring.EXPERIAN_VIEW`
       OPTIONS (
           expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
           description = "View for EXPERIAN segment"
       ) AS
           SELECT eb.EQ_P_ESG_BEACON_SCR as APPBEACON1, eb.TU_P_ESG_EMPERICA_SCR as APPBEACON2, er.APP_NUMBER as EXP_APP_NUMBER, er.CC_PO_B_SC_RSK_S as APPSCORE, er.CC_PO_B_SC_RSK_SCID as APPSCORECARD, er.CC_PO_B_SC_RSK_COMBOSCORE as COMBO_SCORE
           FROM pcb-{env}-curated.domain_customer_acquisition.EXPERIAN_BUREAU AS eb
           LEFT JOIN pcb-{env}-curated.domain_customer_acquisition.EXPERIAN_RESULTS AS er ON er.APP_NUMBER = eb.APP_NUMBER;

   CREATE OR REPLACE VIEW
       `pcb-{env}-processing.domain_scoring.CIF_CARD_CURR_VIEW`
   OPTIONS (
       expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
       description = "View for CIF_CARD_CURR_VIEW segment"
   ) AS
       SELECT SUBSTR(IFNULL(CIFP_PCF_CUST_ID,""),6) AS CUST_ID, CIFP_ACCOUNT_ID6 AS CIF_MAST_ACCOUNT_ID, CIFP_ACCOUNT_NUM
       FROM `pcb-{env}-curated.domain_account_management.CIF_CARD_CURR`
       WHERE
           (CIFP_RELATIONSHIP_STAT = "" or CIFP_RELATIONSHIP_STAT = 'A' OR CIFP_RELATIONSHIP_STAT IS null)
           AND CIFP_CUSTOMER_TYPE = 0;

   CREATE OR REPLACE VIEW
    `pcb-{env}-processing.domain_scoring.FINAL_VIEW_ALL_SEGMENT`
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 6 HOUR),
    description = "Combined view for all segment"
) AS
       SELECT
            DISTINCT * EXCEPT (AM01_MAST_ACCOUNT_ID, AM02_MAST_ACCOUNT_ID, AT31_MAST_ACCOUNT_ID, AM0A_MAST_ACCOUNT_ID,
                               AM0E_MAST_ACCOUNT_ID, AM0B_MAST_ACCOUNT_ID, SC01_MAST_ACCOUNT_ID, AH01_MAST_ACCOUNT_ID,
                               AH02_REAGE_MAST_ACCOUNT_ID, APP_BCN, APP_BNI, APPBEACON1, APPBEACON2,
                               APPSCORE, APPSCORECARD, EXP_APP_NUMBER, AM00_FILE_CREATE_DT, DATE_HIGH_OL_CTD,
                               DATE_ACCOUNT_OPEN, DATE_CLOSE, DATE_LAST_LIMIT_CHG, DATE_LAST_PERM_CR_CHG, DT_FIRST_DLQ,
                               STATC_CLOSED_DATE_MNT, STATC_CRVK_ADD_DATE, STATC_CRVK_MNT_DATE, STATF_INACTIVE_DATE,
                               TNDM_AUTH_PROC_TIER_EDATE, TNDM_AUTH_PROC_TIER_SDATE, DATE_FIRST_USE, DATE_LAST_CASH,
                               DATE_LAST_NSF_PAYMENT, DATE_LAST_PAID_BALANCE, DATE_LAST_PAYMENT, DATE_BIRTH,
                               END_CARD_WATCH_DATE, START_CARD_WATCH_DATE, DATE_AUTO_PASTDUE_REAGE, DATE_MAN_PASTDUE_REAGE,
                               CREATE_MONTH,AVG_RISK,MAX_SCORE,SC01_FILE_CREATE_DT, CIF_MAST_ACCOUNT_ID, TEST_DIGIT_1,
                               TEST_DIGIT_2, TEST_DIGIT_3, TEST_DIGIT_4, USAGE_IND, BHV, BNI, COMBO_SCORE, CUST_ID, TOTALPOINTS, AM0A_ACCOUNT_NUM, CIFP_ACCOUNT_NUM),
            SAFE_CAST(NULL AS STRING) AS APP_NUMBER,
            CURRENT_DATETIME AS CREATE_DATE,
            SAFE_CAST(COMBO_SCORE AS NUMERIC) AS COMBOSCORE,
            score.MAX_SCORE as BCN,
            SAFE_CAST(TEST_DIGIT_1 AS NUMERIC) AS TEST_DIGIT_1,
            SAFE_CAST(TEST_DIGIT_2 AS NUMERIC) AS TEST_DIGIT_2,
            SAFE_CAST(TEST_DIGIT_3 AS NUMERIC) AS TEST_DIGIT_3,
            SAFE_CAST(TEST_DIGIT_4 AS NUMERIC) AS TEST_DIGIT_4,
            SAFE_CAST(USAGE_IND AS NUMERIC) AS USAGE_IND,
            SAFE_CAST(BHV AS NUMERIC) AS BHV,
            SAFE_CAST(BNI AS NUMERIC) AS BNI,
            SAFE_CAST(CUST_ID AS NUMERIC) AS CUST_ID,
            SAFE_CAST(FLOOR(TOTALPOINTS) AS STRING) AS TOTALPOINTS,
            FORMAT_DATE('%Y%m%d',DATE_HIGH_OL_CTD) AS DATE_HIGH_OL_CTD,
            FORMAT_DATE('%Y%m%d',DATE_ACCOUNT_OPEN) AS DATE_ACCOUNT_OPEN,
            FORMAT_DATE('%Y%m%d',DATE_CLOSE) AS DATE_CLOSE,
            FORMAT_DATE('%Y%m%d',DATE_LAST_LIMIT_CHG) AS DATE_LAST_LIMIT_CHG,
            FORMAT_DATE('%Y%m%d',DATE_LAST_PERM_CR_CHG) AS DATE_LAST_PERM_CR_CHG,
            FORMAT_DATE('%Y%m%d',DT_FIRST_DLQ) AS DT_FIRST_DLQ,
            FORMAT_DATE('%Y%m%d',STATC_CLOSED_DATE_MNT) AS STATC_CLOSED_DATE_MNT,
            FORMAT_DATE('%Y%m%d',STATC_CRVK_ADD_DATE) AS STATC_CRVK_ADD_DATE,
            FORMAT_DATE('%Y%m%d',STATC_CRVK_MNT_DATE) AS STATC_CRVK_MNT_DATE,
            FORMAT_DATE('%Y%m%d',STATF_INACTIVE_DATE) AS STATF_INACTIVE_DATE,
            FORMAT_DATE('%Y%m%d',TNDM_AUTH_PROC_TIER_EDATE) AS TNDM_AUTH_PROC_TIER_EDATE,
            FORMAT_DATE('%Y%m%d',TNDM_AUTH_PROC_TIER_SDATE) AS TNDM_AUTH_PROC_TIER_SDATE,
            FORMAT_DATE('%Y%m%d',DATE_FIRST_USE) AS DATE_FIRST_USE,
            FORMAT_DATE('%Y%m%d',DATE_LAST_CASH) AS DATE_LAST_CASH,
            FORMAT_DATE('%Y%m%d',DATE_LAST_NSF_PAYMENT) AS DATE_LAST_NSF_PAYMENT,
            FORMAT_DATE('%Y%m%d',DATE_LAST_PAID_BALANCE) AS DATE_LAST_PAID_BALANCE,
            FORMAT_DATE('%Y%m%d',DATE_LAST_PAYMENT) AS DATE_LAST_PAYMENT,
            FORMAT_DATE('%Y%m%d',DATE_BIRTH) AS DATE_BIRTH,
            FORMAT_DATE('%Y%m%d',END_CARD_WATCH_DATE) AS END_CARD_WATCH_DATE,
            FORMAT_DATE('%Y%m%d',START_CARD_WATCH_DATE) AS START_CARD_WATCH_DATE,
            FORMAT_DATE('%Y%m%d',DATE_AUTO_PASTDUE_REAGE) AS DATE_AUTO_PASTDUE_REAGE,
            FORMAT_DATE('%Y%m%d',DATE_MAN_PASTDUE_REAGE) AS DATE_MAN_PASTDUE_REAGE,
            IF(DATE_ACCOUNT_OPEN >= DATETIME(2015, 03, 15, 00, 00, 00), score.APP_BCN, NULL) AS APP_BCN,
            IF(DATE_ACCOUNT_OPEN >= DATETIME(2015, 03, 15, 00, 00, 00), score.APP_BNI, NULL) AS APP_BNI,
            IF(DATE_ACCOUNT_OPEN <= DATETIME(2015, 07, 27, 00, 00, 00), experian.APPBEACON1, NULL) AS APPBEACON1,
            IF(DATE_ACCOUNT_OPEN <= DATETIME(2015, 07, 27, 00, 00, 00), experian.APPBEACON2, NULL) AS APPBEACON2,
            IF(DATE_ACCOUNT_OPEN <= DATETIME(2015, 07, 27, 00, 00, 00), experian.APPSCORE, NULL) AS APPSCORE,
            IF(DATE_ACCOUNT_OPEN <= DATETIME(2015, 07, 27, 00, 00, 00), experian.APPSCORECARD, NULL) AS APPSCORECARD,
            IF(DATE_ACCOUNT_OPEN <= DATETIME(2015, 07, 27, 00, 00, 00), experian.EXP_APP_NUMBER, NULL) AS EXP_APP_NUMBER,
            '{file_id}' as FILE_ID
       FROM
           pcb-{env}-processing.domain_scoring.AM00_VIEW AS am00
           LEFT JOIN pcb-{env}-processing.domain_scoring.AM01_VIEW AS am01 ON am01.AM01_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.AM02_VIEW AS am02 ON am02.AM02_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.AT31_VIEW AS at31 ON at31.AT31_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.AM0A_VIEW AS am0a ON (am0a.AM0A_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID AND am0a.AM0A_ACCOUNT_NUM = am01.ACCOUNT_NUM)
           LEFT JOIN pcb-{env}-processing.domain_scoring.AM0E_VIEW AS am0e ON am0e.AM0E_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.AM0B_VIEW AS am0bh ON am0bh.AM0B_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.AH01_VIEW AS ah01 ON ah01.AH01_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.AH02_REAGE_VIEW AS ah02_reage ON ah02_reage.AH02_REAGE_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.EXPERIAN_VIEW AS experian ON CAST(experian.EXP_APP_NUMBER as STRING) = am00.CUSTOM_DATA_81
           LEFT JOIN pcb-{env}-processing.domain_scoring.SC01_VIEW AS score ON score.SC01_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
           LEFT JOIN pcb-{env}-processing.domain_scoring.CIF_CARD_CURR_VIEW AS cif ON (cif.CIF_MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID AND cif.CIFP_ACCOUNT_NUM = am01.ACCOUNT_NUM)
           WHERE
                    NOT (ACCOUNT_NUM LIKE '533893%') AND
                    NOT (CUSTOM_DATA_11 = 'T') AND
                    NOT (ACCOUNT_NUM = '') AND
                    NOT (
                        EXTRACT(MONTH FROM AM00_FILE_CREATE_DT) IN (2, 3, 5, 6, 8, 9, 11, 12) AND
                        ACCOUNT_NUM LIKE '533866%'
                    ) AND
                    NOT (
                        TRIAD_SCORE_ALIGNED = 14 AND
                        IFNULL(DATE_DIFF(AM00_FILE_CREATE_DT, IFNULL(DATE_ACCOUNT_OPEN,DATETIME(1990, 01, 01, 00, 00, 00)), MONTH),0) > 12
                    ) AND
                    NOT (
                        TRIAD_SCORE_ALIGNED = 13
                        AND IFNULL(DATE_DIFF(AM00_FILE_CREATE_DT, IFNULL(DATE_LAST_PAYMENT,DATETIME(1990, 01, 01, 00, 00, 00)), MONTH), 0) > 18
                        AND IFNULL(DATE_DIFF(AM00_FILE_CREATE_DT, IFNULL(DATE_LAST_CASH,DATETIME(1990, 01, 01, 00, 00, 00)), MONTH),0) > 18
                        AND IFNULL(DATE_DIFF(AM00_FILE_CREATE_DT, IFNULL(DATE_LAST_PURCHASE,DATETIME(1990, 01, 01, 00, 00, 00)), MONTH),0) > 18
                    ) AND
                    NOT (
                        TRIAD_SCORE_ALIGNED IN (1, 2, 12)
                    ) AND
                    (STATC_CLOSED = '' ) AND
                    (STATC_CREDIT_REVOKED = '' ) AND
                    (STATC_SECURITY_FRAUD = '' ) AND
                    (STATF_FRAUD = '' ) AND
                    (STATC_CHARGEOFF = '' ) AND
                    (
                       case when IFNULL(DATE_DIFF(SC01_FILE_CREATE_DT, DATE_ACCOUNT_OPEN, MONTH),0) > 36
                        then (
                                (score.CREATE_MONTH IN (2, 3, 5, 6, 8, 9, 11, 12) AND NOT(IFNULL(score.MAX_SCORE,0 ) > 840 AND IFNULL(score.AVG_RISK,0) = 1) )
                                 OR (score.CREATE_MONTH NOT IN (2, 3, 5, 6, 8, 9, 11, 12))
                            )
                        else
                            1 = 1
                        end
                    );




   CREATE OR REPLACE TABLE
       `pcb-{env}-curated.domain_scoring.RISK_ADAPTIVE`
   AS
       SELECT *
           FROM pcb-{env}-processing.domain_scoring.FINAL_VIEW_ALL_SEGMENT LIMIT 0;


   INSERT INTO
       `pcb-{env}-curated.domain_scoring.RISK_ADAPTIVE`
   SELECT *
   FROM pcb-{env}-processing.domain_scoring.FINAL_VIEW_ALL_SEGMENT;
