CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_account_management.{output_table_name}
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
SELECT
  REC_TYPE_03,
    TSYS_PRODUCT_CODE_03,
    APP_CODE_03,
    ACCOUNT_NUMBER_03,
    CAST(POST_DATE AS INT64) AS POST_DATE,
    CAST(TRANSACTION_DATE AS INT64) AS TRANSACTION_DATE,
    TRANSACTION_CODE,
    SIGN_TRANSACTION_AMOUNT,
    CAST(TRANSACTION_AMOUNT AS INT64) AS TRANSACTION_AMOUNT,
    MERCHANT_DBA,
    REFERENCE_NUMBER,
    DEBIT_CREDIT_IND,
    FILLER_03,
    FILE_CREATE_DT,
    REC_LOAD_TIMESTAMP
FROM
  pcb-{env}-landing.domain_account_management.RMS_TRANSACTION_03
WHERE
  ACCOUNT_NUMBER_03 IN (
  SELECT
    ACCOUNT_NUMBER
  FROM
    pcb-{env}-landing.domain_account_management.PCH_RMS_KEYCONTROL)
  AND FILE_CREATE_DT = '{file_create_dt}';