CREATE OR REPLACE TABLE
  `{staging_table_id}`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
) AS
SELECT SIGNATURE_ID, CNST_EVENT_ID, REC_CREATE_TMS, REC_CHNG_TMS, REC_CHNG_ID, 'ID' as DOCUMENT_ID
FROM `pcb-{env}-curated.domain_consent.CNST_SIGNATURE`
LIMIT 0;
INSERT INTO `{staging_table_id}`
(SIGNATURE_ID, CNST_EVENT_ID, REC_CREATE_TMS, REC_CHNG_TMS, REC_CHNG_ID, DOCUMENT_ID)
SELECT SIGNATURE_ID, CNST_EVENT_ID, REC_CREATE_TMS, REC_CHNG_TMS, REC_CHNG_ID, 'ID'
FROM `pcb-{env}-curated.domain_consent.CNST_SIGNATURE`;
