INSERT INTO `pcb-{env}-landing.domain_consent.CNST_EVENTS_ANALYTICS`
SELECT DISTINCT
  '4' AS cnsteventsource,
  'HIST LOAD' AS cnsteventsourcedesc,
  CAST(NULL AS STRING) AS cnsteventid,
  eventtype,
  CAST(NULL AS STRING) AS eventtypedesc,
  TIMESTAMP(eventdate, 'America/Toronto') AS eventdate,
  TIMESTAMP(sourcedt, 'America/Toronto') AS sourcedt,
  sourceorg,
  CAST(NULL AS STRING) AS cnsttype,
  CAST(NULL AS STRING) AS cnsttypedesc,
  'I' AS cnsttypecode,
  CAST(NULL AS STRING) AS cnsttypever,
  cnstcategory,
  cnstlangcode,
  CAST(NULL AS STRING) AS sourceorgdesc,
  CAST(NULL AS STRING) AS mktggrp,
  CAST(NULL AS STRING) AS mktggrpdesc,
  CAST(NULL AS STRING) AS externalidtypecode,
  CAST(NULL AS STRING) AS externalidtype,
  CAST(NULL AS STRING) AS externalidvalue,
  CAST(NULL AS STRING) AS evidenceid,
  pcfcustid,
  CAST(applicationid AS STRING) as applicationid,
  singaturepathoriginal,
  signaturepathcurrent,
  signaturefile,
  CAST(NULL AS STRING) AS documentstoragelink,
  channel,
  facetofaceind,
  CURRENT_TIMESTAMP AS ingestion_timestamp,
  STRUCT<stream_name STRING, topic_partition INT64, partition_offset INT64, stream_offset INT64, offset_diff INT64, environment STRING, topic_version INT64>(NULL, NULL, NULL, NULL, NULL, NULL, NULL) AS metadata,
  {db_053} AS legacydatasource
FROM
  `pcb-{env}-processing.domain_consent.cnst_events_analytics_v6_tdc_join`