SELECT
wallet_id,
PCO_Score,
DATETIME(PCO_Score_Date) as PCO_Score_Date,
Scorecard_Segment,
Score_version,
PCO_Feature_1,
PCO_Feature_2,
PCO_Feature_3,
PCO_Feature_4,
PCO_Feature_5,
PCO_Feature_6,
PCO_Feature_7,
PCO_Feature_8,
PCO_Feature_9,
PCO_Feature_10,
PCO_Feature_11,
PCO_Feature_12,
PCO_Feature_13,
PCO_Feature_14,
PCO_Feature_15,
execution_id,
load_timestamp,
source_filename
FROM `pcb-{env}-processing.PCOScoresDataset.PCO_SCORES_Back_Up`