CREATE OR REPLACE TABLE pcb-{env}-landing.domain_card_management.CARD_EMBOSSING_FILE_AUDIT_LOG(
 FILE_UUID STRING(100) NOT NULL,
 DAG_ID STRING(100) NOT NULL,
 JOB_TYPE STRING(100) NOT NULL,
 JOB_NAME STRING(255) NOT NULL,
 RUN_START DATETIME NOT NULL,
 RUN_END DATETIME,
 SOURCE_LOCATION STRING(1000) NOT NULL,
 TARGET_LOCATION STRING(1000) NOT NULL,
 TRLR_CNT NUMERIC(29,0) NOT NULL,
 WRITE_CNT NUMERIC(29,0),
 STATUS STRING(50) NOT NULL,
 FILE_NAME STRING(1000) NOT NULL,
 REC_LOAD_TIMESTAMP TIMESTAMP NOT NULL
 )