tsys_postedtx_file_loader:
  default_args:
    owner: "team-digital-adoption-alerts"
    capability: "account-management"
    sub_capability: "payments"
    business_impact: 'Posted tx table will not be created in BQ'
    customer_impact: 'No Impact'
    severity: "P3"
  tags: ["MoneyMove - payments"]
  job_size: medium
  source_bucket: tsys-inbound-pcb
  processing_bucket: pcb-{env}-staging
  processing_bucket_config: pcb-{env}-staging-artifacts
  processing_bucket_extract: pcb-{env}-staging-extract
  file_prefix: tsys_pcb_postedtx
  spark:
    jar_file_uris:
      - gs://pcb-{env}-staging-artifacts/jarfiles/tsys-spark-batch-2.0.0.jar
    main_class: com.pcb.batch.spark.tsys.TsysSparkBatchApplication
    filtering_job_args:
      pcb.tsys.processor.datafile.path: _tempplaceholder
      pcb.tsys.processor.datafile.type: POSTED_TX
      pcb.tsys.processor.filtering: true
    parsing_job_args:
      pcb.tsys.processor.datafile.path: _tempplaceholder
      pcb.tsys.processor.datafile.type: POSTED_TX
      pcb.tsys.processor.output.format: parquet
      pcb.tsys.processor.output.path: _tempplaceholder
    segment_dependency_groups:
      - group_name: trailer_group
        segments: TRLR
      - group_name: detail_group
        segments: DETL
      - group_name: header_group
        segments: HEDR
    segment_args:
      HEDR:
        pcb.tsys.processor.copybook.path: gs://pcb-{env}-staging-artifacts/copybooks/tsys_pcb_postedtx/HEDR.CPY
        pcb.tsys.processor.segment.name: 1
        pcb.tsys.processor.layout.name: HEDR_REC
      DETL:
        pcb.tsys.processor.copybook.path: gs://pcb-{env}-staging-artifacts/copybooks/tsys_pcb_postedtx/DETL.CPY
        pcb.tsys.processor.segment.name: 5
        pcb.tsys.processor.layout.name: DETL_REC
      TRLR:
        pcb.tsys.processor.copybook.path: gs://pcb-{env}-staging-artifacts/copybooks/tsys_pcb_postedtx/TRLR.CPY
        pcb.tsys.processor.segment.name: 8
        pcb.tsys.processor.layout.name: TRLR_REC
  bigquery:
    project_id: pcb-{env}-landing
    landing_proj_id: pcb-{env}-landing
    dataset_id: domain_account_management
    data_load_type: APPEND_ONLY
    tables:
      HEDR:
        table_name: POST_MON_HEDR
        add_columns:
          - CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP
      DETL:
        table_name: POST_MON
        add_columns:
          - CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP
          - D_RECORD_ID AS RECORD_ID
        drop_columns:
          - D_RECORD_ID
      TRLR:
        table_name: POST_MON_TRLR
        add_columns:
          - CURRENT_DATETIME('America/Toronto')  AS REC_LOAD_TIMESTAMP