UPDATE `{bq_target_table_id}` AS main
SET main.END_DATE = vr.EFFECTIVE_DATE
FROM `{bq_invalid_tmp_table_id}` AS vr
WHERE vr.ERROR_MESSAGE IS NULL
AND TRIM(LOWER(vr.ACTION)) = 'change'
AND main.VENDOR_CODE = TRIM(LOWER(vr.VENDOR_CODE))
AND main.INSTRUMENT_TYPE = TRIM(LOWER(vr.INSTRUMENT_TYPE))
AND main.FIELD_NAME = TRIM(LOWER(vr.FIELD_NAME))
AND main.BANK = TRIM(LOWER(vr.BANK))
AND main.LOAD_DATE = (
    SELECT MAX(LOAD_DATE) 
    FROM `{bq_target_table_id}` 
    WHERE VENDOR_CODE = main.VENDOR_CODE
    AND INSTRUMENT_TYPE = main.INSTRUMENT_TYPE
    AND FIELD_NAME = main.FIELD_NAME
    AND BANK = main.BANK
)
AND (main.END_DATE IS NULL OR main.END_DATE > CURRENT_DATE());

INSERT INTO `{bq_target_table_id}`
SELECT 
    vr.REQUESTOR_EMAIL, 
    vr.REFERENCE_TABLE_ID, 
    TRIM(LOWER(vr.ACTION)) AS ACTION,
    TRIM(LOWER(vr.VENDOR_CODE)) AS VENDOR_CODE,  
    TRIM(LOWER(vr.INSTRUMENT_TYPE)) AS INSTRUMENT_TYPE,  
    TRIM(LOWER(vr.FIELD_NAME)) AS FIELD_NAME,
    TRIM(LOWER(vr.BANK)) AS BANK,
    CASE 
        WHEN SAFE_CAST(vr.NEW_RATE AS FLOAT64) IS NOT NULL 
        THEN FORMAT("%.3f", SAFE_CAST(vr.NEW_RATE AS FLOAT64))  
        ELSE LOWER(vr.NEW_RATE)  
    END AS RATE,
    vr.EFFECTIVE_DATE, 
    vr.END_DATE,
    vr.LOAD_DATE
FROM `{bq_invalid_tmp_table_id}` AS vr
WHERE vr.ERROR_MESSAGE IS NULL 
AND TRIM(LOWER(vr.ACTION)) = 'change';
