INSERT INTO `{bq_target_table_id}`
SELECT 
    vr.REQUESTOR_EMAIL,
    vr.REFERENCE_TABLE_ID,
    TRIM(LOWER(vr.ACTION)) AS ACTION,
    TRIM(LOWER(vr.VENDOR_CODE)) AS VENDOR_CODE,  
    TRIM(LOWER(vr.INSTRUMENT_TYPE)) AS INSTRUMENT_TYPE,  
    TRIM(LOWER(vr.FIELD_NAME)) AS FIELD_NAME,
    TRIM(LOWER(vr.BANK)) AS BANK,
    CASE 
        WHEN SAFE_CAST(vr.NEW_RATE AS FLOAT64) IS NOT NULL 
            THEN FORMAT("%.3f", SAFE_CAST(vr.NEW_RATE AS FLOAT64))  
        ELSE LOWER(vr.NEW_RATE)  
    END AS RATE,
    vr.EFFECTIVE_DATE,
    vr.END_DATE,
    vr.LOAD_DATE
FROM `{bq_invalid_tmp_table_id}` vr
WHERE ERROR_MESSAGE IS NULL 
AND TRIM(LOWER(ACTION)) = 'add';
