CREATE OR REPLACE TABLE {bq_staging_tmp_table_id}
OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 1 HOUR),
    description = "Temporary table for storing extracted data"
)
AS
SELECT DISTINCT
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(0)], '') AS REQUESTOR_EMAIL,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(1)], '') AS REFERENCE_TABLE_ID,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(2)], '') AS ACTION,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(3)], '') AS VENDOR_CODE,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(4)], '') AS INSTRUMENT_TYPE,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(5)], '') AS FIELD_NAME,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(6)], '') AS BANK,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(7)], '') AS OLD_RATE,
    NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(8)], '') AS NEW_RATE,
    COALESCE(
        SAFE.PARSE_DATE('%Y-%m-%d', NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(9)], '')), 
        SAFE.PARSE_DATE('%m/%d/%Y', NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(9)], '')),
        SAFE.PARSE_DATE('%d-%m-%Y', NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(9)], ''))
    ) AS EFFECTIVE_DATE,
    COALESCE(
        SAFE.PARSE_DATE('%Y-%m-%d', NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(10)], '')), 
        SAFE.PARSE_DATE('%m/%d/%Y', NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(10)], '')),
        SAFE.PARSE_DATE('%d-%m-%Y', NULLIF(SPLIT(ALL_RECORDS, ',')[SAFE_OFFSET(10)], ''))
    ) AS END_DATE,
    {load_date} AS LOAD_DATE
FROM {bq_source_tmp_table_id}
WHERE LOWER(ALL_RECORDS) NOT LIKE '%header%'
AND LOWER(ALL_RECORDS) NOT LIKE '%footer%'
AND LOWER(ALL_RECORDS) NOT LIKE '%eof%';
