CREATE
OR REPLACE TABLE `{staging_table_id}` OPTIONS (
    expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 14 DAY)
) AS
WITH RANKED_EXCLUDED_CUSTOMER_IDENTIFIER AS (
    SELECT
        DISTINCT SAFE_CAST(CI_S.CUSTOMER_IDENTIFIER_NO AS STRING) AS CUSTOMER_IDENTIFIER_NO,
        SAFE_CAST(CI_S.CUSTOMER_UID AS STRING) AS CUSTOMER_UID
    FROM
        `pcb-{env}-curated.domain_customer_management.CUSTOMER_IDENTIFIER` CI_S
        LEFT JOIN `pcb-{env}-curated.domain_account_management.ACCOUNT_CUSTOMER` AC_S ON CI_S.CUSTOMER_UID = AC_S.CUSTOMER_UID
    WHERE
        AC_S.CUSTOMER_UID IS NULL
        AND UPPER(CI_S.DISABLED_IND) = 'N'
        AND UPPER(CI_S.TYPE) = 'PCF-CUSTOMER-ID'
),
RANKED_CUSTOMER_IDENTIFIER AS (
    SELECT
        DISTINCT SAFE_CAST(CI_T.CUSTOMER_IDENTIFIER_NO AS STRING) AS CUSTOMER_IDENTIFIER_NO,
        SAFE_CAST(CI_T.CUSTOMER_UID AS STRING) AS CUSTOMER_UID,
    FROM
        `pcb-{env}-curated.domain_customer_management.CUSTOMER_IDENTIFIER` CI_T
        INNER JOIN `pcb-{env}-curated.domain_account_management.ACCOUNT_CUSTOMER` AC_A ON CI_T.CUSTOMER_UID = AC_A.CUSTOMER_UID
    WHERE
        UPPER(AC_A.ACTIVE_IND) = 'Y'
        AND UPPER(CI_T.DISABLED_IND) = 'N'
        AND UPPER(CI_T.TYPE) = 'PCF-CUSTOMER-ID'
),
RANKED_CUSTOMER_IDENTIFIER_FINAL AS (
    SELECT
        DISTINCT RCI.CUSTOMER_IDENTIFIER_NO,
        RCI.CUSTOMER_UID,
        ROW_NUMBER() OVER (
            ORDER BY
                RCI.CUSTOMER_UID ASC
        ) AS ROW_NUM
    FROM
        RANKED_CUSTOMER_IDENTIFIER RCI
        LEFT JOIN RANKED_EXCLUDED_CUSTOMER_IDENTIFIER RECI ON RCI.CUSTOMER_IDENTIFIER_NO = RECI.CUSTOMER_IDENTIFIER_NO
        AND RCI.CUSTOMER_UID = RECI.CUSTOMER_UID
    WHERE
        RECI.CUSTOMER_IDENTIFIER_NO IS NULL
        AND RECI.CUSTOMER_UID IS NULL
)
SELECT
    DISTINCT c.CUSTOMER_UID,
    '{run_id}' AS CDIC_RUN_ID
FROM
    `pcb-{env}-curated.domain_customer_management.CUSTOMER` c
    LEFT JOIN RANKED_CUSTOMER_IDENTIFIER_FINAL s ON CAST(c.CUSTOMER_UID AS STRING) = s.CUSTOMER_UID
WHERE
    s.CUSTOMER_UID IS NULL;