-- Reads from OUTPUT_TRS_T0090_LATEST (repeated record OUTPUTS) and pivots
-- OUTPUT_NAME/OUTPUT_VALUE into flat columns for the TRS extract file format.
EXPORT DATA
  OPTIONS ( uri = '{output_uri_processing}',
    format = 'CSV',
    header = TRUE,
    field_delimiter = '|',
    OVERWRITE = TRUE ) AS
-- Raw rows from the TRS T0090 output table (one row per record, OUTPUTS is REPEATED).
-- source_row_id identifies each source row so we can group back to one row per record
-- when EXECUTION_ID, REC_LOAD_TIMESTAMP, JOB_ID are the same across many rows.
SELECT DISTINCT
  '{client_id}' AS CLIENT_ID,
  '{record_type}' AS RECORD_TYPE,
  '{reject_code}' AS REJECT_CODE,
  '{account_number}' AS ACCOUNT_NUMBER,
  '{filler_1}' AS FILLER_1,
  output_trs_t0090_unnested_latest.MAST_ACCOUNT_ID AS ACCOUNT_IDENTIFIER,
  '{filler_2}' AS FILLER_2,
  '{primary_customer_id}' AS PRIMARY_CUSTOMER_ID,
  '{customer_type}' AS CUSTOMER_TYPE,
  '{filler_3}' AS FILLER_3,
  '{score_type}' AS SCORE_TYPE,
  '{score_calc_date}' AS SCORE_CALC_DATE,
  '{score_calc_time}' AS SCORE_CALC_TIME,
  '{score_raw_sign}' AS SCORE_RAW_SIGN,
  output_trs_t0090_unnested_latest.SCORE_RUN_COUNTER AS SCORE_RAW,
  '{score_aligned_sign}' AS SCORE_ALIGNED_SIGN,
  CAST(CAST(CAST(output_trs_t0090_unnested_latest.SCORECARD_POINTS AS FLOAT64) AS INT64) AS STRING) AS SCORE_ALIGNED,
  '{score_source}' AS SCORE_SOURCE,
  '{rating_grade}' AS RATING_GRADE,
  '{bureau_id}' AS BUREAU_ID,
  '{market_address_code}' AS MARKET_ADDRESS_CODE,
  output_trs_t0090_unnested_latest.N_TOT_TRANS AS SCORE_REASON_1,
  output_trs_t0090_unnested_latest.SCORECARD AS SCORE_REASON_2,
  output_trs_t0090_unnested_latest.PRIZM AS SCORE_REASON_3,
  output_trs_t0090_unnested_latest.CIFP_TEST_DIGIT_TYPE5 AS SCORE_REASON_4,
  output_trs_t0090_unnested_latest.CIFP_ACQUISITION_CODE_SIGN AS REASON_DIFF_1_SIGN,
  output_trs_t0090_unnested_latest.CIFP_ACQUISITION_CODE AS REASON_DIFF_1,
  output_trs_t0090_unnested_latest.MORTGAGE_IND_SIGN AS REASON_DIFF_2_SIGN,
  output_trs_t0090_unnested_latest.MORTGAGE_IND AS REASON_DIFF_2,
  output_trs_t0090_unnested_latest.APP_BCN_SIGN AS REASON_DIFF_3_SIGN,
  output_trs_t0090_unnested_latest.APP_BCN AS REASON_DIFF_3,
  output_trs_t0090_unnested_latest.TTLPOINTS_SIGN AS REASON_DIFF_4_SIGN,
  output_trs_t0090_unnested_latest.TTLPOINTS AS REASON_DIFF_4,
  '{acct_relation_code}' AS ACCT_RELATION_CODE,
  '{operator_id}' AS OPERATOR_ID,
  output_trs_t0090_unnested_latest.IAL_INQS_PST12_MNTH AS USER_DEFINED_1,
  output_trs_t0090_unnested_latest.TNC_TRD_CURR_PST_DUE AS USER_DEFINED_2,
  output_trs_t0090_unnested_latest.TNC_UTIL_PERCENTAGE_OPEN_TRD AS USER_DEFINED_3,
  '{user_defined_s1_sign}' AS USER_DEFINED_S1_SIGN,
  '{user_defined_s1}' AS USER_DEFINED_S1,
  '{user_defined_s2_sign}' AS USER_DEFINED_S2_SIGN,
  '{user_defined_s2}' AS USER_DEFINED_S2,
  '{tts_dollar_value}' AS TTS_DOLLAR_VALUE,
  '{inquiry_flag}' AS INQUIRY_FLAG,
  '{low_range_sign}' AS LOW_RANGE_SIGN,
  '{low_score_range}' AS LOW_SCORE_RANGE,
  '{high_range_sign}' AS HIGH_RANGE_SIGN,
  '{high_score_range}' AS HIGH_SCORE_RANGE,
  '{percentile_ranking}' AS PERCENTILE_RANKING,
  '{filler_4}' AS FILLER_4,
  '{score_type_2}' AS SCORE_TYPE_2
FROM
  `pcb-{env}-curated.domain_scoring.OUTPUT_TRS_T0090_UNNESTED_LATEST` AS output_trs_t0090_unnested_latest;
