SELECT count(APPL_SAVINGS_REMINDER_UID) as account_count
FROM `pcb-{env}-landing.domain_customer_acquisition.APPL_SAVINGS_REMINDER`
WHERE
STATUS = 'REMIND-ME'
AND UPDATE_DT BETWEEN
    CAST(TIMESTAMP(DATETIME(CURRENT_TIMESTAMP(), "America/Toronto")) - INTERVAL {lookback_start_hours} HOUR AS DATETIME)
    AND
    CAST(TIMESTAMP(DATETIME(CURRENT_TIMESTAMP(), "America/Toronto")) - INTERVAL {lookback_end_hours} HOUR AS DATETIME)
AND ACCOUNT_UID IS NOT NULL
AND CUSTOMER_UID IS NOT NULL;