WITH LATEST_TRANSACT_ACCOUNT AS (
    SELECT * FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY POSTING_DATE DESC,EVENT_DATE_TIME DESC) AS rn
        FROM pcb-{env}-curated.domain_account_management.TRANSACT_ACCOUNT
        WHERE POSTING_DATE <= <<<report_date_goes_here>>>
    ) WHERE rn = 1
),
LATEST_TRANSACT_ACCOUNT_INTEREST AS (
    SELECT * FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY POSTING_DATE DESC,EVENT_DATE_TIME DESC,TRANSACT_DATE_TIME DESC) AS rn
        FROM pcb-{env}-curated.domain_account_management.TRANSACT_ACCOUNT_INTEREST
        WHERE POSTING_DATE <= <<<report_date_goes_here>>>
    ) WHERE rn = 1
),
LATEST_TRANSACT_ACCOUNT_BALANCE AS (
    SELECT * FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY POSTING_DATE DESC,TRANSACT_DATE_TIME DESC) AS rn
        FROM pcb-{env}-curated.domain_account_management.TRANSACT_ACCOUNT_BALANCE
        WHERE POSTING_DATE <= <<<report_date_goes_here>>>
    ) WHERE rn = 1
),
PREVIOUS_TRANSACT_ACCOUNT_BALANCE AS (
    SELECT * FROM (
        SELECT *, ROW_NUMBER() OVER (PARTITION BY ACCOUNT_ID ORDER BY POSTING_DATE DESC,TRANSACT_DATE_TIME DESC) AS rn
        FROM pcb-{env}-curated.domain_account_management.TRANSACT_ACCOUNT_BALANCE
        WHERE POSTING_DATE <= (DATE(<<<report_date_goes_here>>>) - 1)
    ) WHERE rn = 1
)
SELECT
  DATETIME(<<<report_date_goes_here>>>) AS RECORD_LOAD_TIMESTAMP,
  ta.ACCOUNT_ID,
  ta.ARRANGEMENT_ID,
  tai.INTEREST AS INTEREST_AMOUNT,
  a.OPEN_DT AS ACCOUNT_OPEN_DATE,
  ta.PRODUCT_NAME,
  ta.PRODUCT_LINE,
  ta.PRODUCT_GROUP,
  ta.STATUS,
  ta.CUSTOMER_ID,
  ta.LEDGER_CUSTOMER_ID,
  ta.CUSTOMER_TYPE,
  ta.CLOSURE_REASON,
  ta.CLOSURE_NOTES,
  ta.CLOSURE_DATE,
  ta.STATUS_PRIOR_TO_CLOSURE,
  ta.INTEREST AS INTEREST_RATE,
  tab.BALANCE_NAME,
  tab.BALANCE_DATE_TYPE,
  tab.BALANCE_CURRENT AS BALANCE_CLOSING,
  ptab.BALANCE_CURRENT AS BALANCE_OPENING,
  tai.POSTING_DATE
FROM
  LATEST_TRANSACT_ACCOUNT ta
INNER JOIN
  pcb-{env}-curated.domain_account_management.ACCOUNT a
ON
  CAST(ta.ACCOUNT_ID AS string) = a.MAST_ACCOUNT_ID
LEFT JOIN
  LATEST_TRANSACT_ACCOUNT_INTEREST tai
ON
  ta.ACCOUNT_ID = tai.ACCOUNT_ID
LEFT JOIN
  LATEST_TRANSACT_ACCOUNT_BALANCE tab
ON
  ta.ACCOUNT_ID = tab.ACCOUNT_ID
LEFT JOIN
  PREVIOUS_TRANSACT_ACCOUNT_BALANCE ptab
ON
  ta.ACCOUNT_ID = ptab.ACCOUNT_ID;