CREATE OR REPLACE TABLE pcb-{env}-processing.domain_marketing.CME_BATCH_STAGE_AAU
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  DISTINCT 'AAU' AS CAMPAIGN_TYPE,
  C.CIFP_ACCOUNT_ID6 TSYS_ACCOUNT_ID,
  C.CIFP_CUSTOMER_ID_2 TSYS_CUSTOMER_ID,
  C.CIFP_ACCOUNT_NUM CARD_NUMBER,
  C.CIFP_DATE_CUST_REC_OPEN OFFER_CHANGE_DATE,
  C.CIFP_PCF_CUST_ID,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  `pcb-{env}-curated.domain_account_management.CIF_CARD_CURR` C,
  (
  SELECT
    CIFP_ACCOUNT_ID6
  FROM
    `pcb-{env}-curated.domain_account_management.CIF_CARD_CURR`
  WHERE
    CIFP_CUSTOMER_TYPE = 2
    AND CIFP_PRIM_CARD_ID NOT IN ('SSTF')
    AND CIFP_DATE_CUST_REC_OPEN IS NOT NULL
    AND CIFP_DATE_CUST_REC_OPEN >= (
    SELECT
      MAX(CAST(DATE_LAST_RUN AS DATE))
    FROM
      `pcb-{env}-landing.domain_account_management.CME_BATCH_PARAM`
    WHERE
      CAMPAIGN_TYPE = 'AAU')
    AND CIFP_DATE_CUST_REC_OPEN < CURRENT_DATE()) A
WHERE
  C.CIFP_ACCOUNT_ID6 = A.CIFP_ACCOUNT_ID6
  AND C.CIFP_CUSTOMER_TYPE = 0
  AND (C.CIFP_TRANS_TO_ACCT_NO IS NULL
    OR C.CIFP_TRANS_TO_ACCT_NO = '')
  AND C.CIFP_DATE_CUST_REC_OPEN < CURRENT_DATE()