CREATE OR REPLACE TABLE pcb-{env}-processing.domain_marketing.CME_BATCH_STAGE_PCH
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  DISTINCT 'PCH' AS CAMPAIGN_TYPE,
  C.CIFP_ACCOUNT_ID6 TSYS_ACCOUNT_ID,
  C.CIFP_CUSTOMER_ID_2 TSYS_CUSTOMER_ID,
  C.CIFP_ACCOUNT_NUM CARD_NUMBER,
  A.CIFP_DATE_PROD_CHG OFFER_CHANGE_DATE,
  C.CIFP_PCF_CUST_ID,
  CURRENT_DATETIME() AS REC_CREATE_TMS
FROM
  `pcb-{env}-curated.domain_account_management.CIF_CARD_CURR` C,
  `pcb-{env}-curated.domain_account_management.CIF_ACCOUNT_CURR` A
WHERE
  C.CIFP_ACCOUNT_ID6 = A.CIFP_ACCOUNT_ID5
  AND A.CIFP_DATE_PROD_CHG IS NOT NULL
  AND A.CIFP_DATE_PROD_CHG < CURRENT_DATE()
  AND A.CIFP_DATE_PROD_CHG >= (
  SELECT
    MAX(CAST(DATE_LAST_RUN AS DATE))
  FROM
    `pcb-{env}-landing.domain_account_management.CME_BATCH_PARAM`
  WHERE
    CAMPAIGN_TYPE = 'PCH')
  AND (C.CIFP_TRANS_TO_ACCT_NO IS NULL
    OR C.CIFP_TRANS_TO_ACCT_NO = '')
  AND C.CIFP_PRIM_CARD_ID NOT IN ('SSTF')
  AND C.CIFP_CUSTOMER_TYPE = 0
  AND A.CIFP_CLIENT_PRODUCT_CODE IN ('PCH')
  AND A.CIFP_TSYS_PRODUCT_CODE IN ('MW')