CREATE OR REPLACE TABLE `pcb-{env}-processing.domain_marketing.CME_CUSTOMER_LOOKUP_STG`
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
WITH
  execution_id AS (
  SELECT
    MAX(CAST(execution_id AS NUMERIC)) + 1 AS execution_id_value
  FROM
    `pcb-{env}-landing.domain_account_management.CME_BATCH_PARAM`
  WHERE
    INTERFACE_ID='CME1'),
  max_ref AS (
  SELECT
    MAX(CAST(CUSTOMER_REF AS INT64)) AS max_ref_value
  FROM
    `pcb-{env}-landing.domain_marketing.CUSTOMER_LOOKUP` )
SELECT
  DISTINCT
  TSYS_ACCOUNT_ID,
  CAST(NULL AS INT64) AS TSYS_CUSTOMER_ID,
  CAST(NULL AS INT64) AS CARD_NUMBER,
  CIFP_PCF_CUST_ID AS PCB_CIF_REFERENCE,
  '0' AS LCL_CIF_REFERENCE,
  ROW_NUMBER() OVER (ORDER BY TSYS_ACCOUNT_ID, TSYS_CUSTOMER_ID, CARD_NUMBER ASC) + (
  SELECT
    max_ref_value
  FROM
    max_ref) AS CUSTOMER_REF,
  CURRENT_DATETIME('America/Toronto') AS REC_CREATE_TMS,
  'CME1' AS REC_CHNG_ID,
  CAST(NULL AS DATE) AS REC_CHNG_TMS,
  NULL AS ST_CD,
  CAST(NULL AS DATETIME) AS ST_DT,
  (
  SELECT
    execution_id_value
  FROM
    execution_id) AS EXECUTION_ID,
  'CME1' AS INTERFACE_ID
FROM (
  SELECT
    *,
    ROW_NUMBER() OVER(PARTITION BY TSYS_ACCOUNT_ID, TSYS_CUSTOMER_ID, CARD_NUMBER ORDER BY TSYS_ACCOUNT_ID, TSYS_CUSTOMER_ID, CARD_NUMBER ASC) AS ROW_NUM
  FROM (
    SELECT
      CME_BATCH_STAGING.* EXCEPT (REC_CREATE_TMS),
      CUSTLOOKUP.CUSTOMER_REF,
    FROM
      `pcb-{env}-processing.domain_marketing.CME_BATCH_STAGING` CME_BATCH_STAGING
    LEFT JOIN
      `pcb-{env}-curated.domain_marketing.CUSTOMER_LOOKUP` CUSTLOOKUP
    ON
      CME_BATCH_STAGING.TSYS_ACCOUNT_ID = CUSTLOOKUP.TSYS_ACCOUNT_ID
      AND CME_BATCH_STAGING.CIFP_PCF_CUST_ID = CUSTLOOKUP.PCB_CIF_REFERENCE
      AND CUSTLOOKUP.TSYS_CUSTOMER_ID IS NULL
      AND CUSTLOOKUP.CARD_NUMBER IS NULL AND CIFP_PCF_CUST_ID IS NOT NULL)
  WHERE
    CUSTOMER_REF IS NULL)
WHERE
  ROW_NUM = 1