CREATE OR REPLACE TABLE `pcb-{env}-processing.domain_marketing.CME_DISPOSITION_STG`
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
WITH
  execution_id AS (
  SELECT
    MAX(CAST(execution_id AS NUMERIC)) + 1 AS execution_id_value
  FROM
    `pcb-{env}-landing.domain_account_management.CME_BATCH_PARAM`
  WHERE
    INTERFACE_ID='CME1'),
  max_disp AS (
  SELECT
    MAX(DISPOSITION_SEQ) AS max_disp_val
  FROM
    `pcb-{env}-landing.domain_marketing.DISPOSITION` D
  INNER JOIN
    `pcb-{env}-processing.domain_marketing.CME_BATCH_OFFER_STG` C
  ON
    D.OFFER_ID = C.OFFER_ID
    AND D.CUSTOMER_REF = C.CUSTOMER_REF )
SELECT
  DISTINCT
  CME_OFFER.OFFER_ID,
  CME_OFFER.CUSTOMER_REF,
  CASE
    WHEN IFNULL(( SELECT max_disp_val FROM max_disp),0) >=1 THEN ( SELECT max_disp_val FROM max_disp) + 1
    ELSE 1
END
  AS DISPOSITION_SEQ,
  'BATCH_FULFILLED' AS DISPOSITION_STATUS,
  CME_OFFER.OFFER_CHANGE_DATE AS DISPOSITION_DATE,
  'BATCH' AS DISPOSITION_CHANNEL,
  '' AS DISPOSITION_VARIABLE1,
  '' AS DISPOSITION_VARIABLE2,
  '' AS DISPOSITION_VARIABLE3,
  '' AS DISPOSITION_VARIABLE4,
  '' AS DISPOSITION_VARIABLE5,
  '' AS FULLFILLED_INDICATOR,
  '' AS CONTACT_ID,
  CURRENT_DATETIME('America/Toronto') AS REC_CREATE_TMS,
  'CME1' AS REC_CHNG_ID,
  CAST(NULL AS DATETIME) AS REC_CHNG_TMS,
  '' AS ST_CD,
  CAST(NULL AS DATETIME) AS ST_DT,
  'BATCH' AS MESSAGE_ID_IN,
  '' AS MESSAGE_ID_OUT,
  (
  SELECT
    execution_id_value
  FROM
    execution_id) AS EXECUTION_ID,
  'CME1' AS INTERFACE_ID
FROM
  `pcb-{env}-processing.domain_marketing.CME_BATCH_OFFER_STG` CME_OFFER
WHERE
  CME_OFFER.LAST_OFFER_STATUS <> 'Acceptance'
  AND CME_OFFER.LAST_OFFER_STATUS <>'Partially Accepted'
  AND CME_OFFER.LAST_OFFER_STATUS <> 'BATCH_FULFILLED'
  AND CME_OFFER.LAST_OFFER_STATUS <> 'Decline'
  AND CME_OFFER.OFFER_START_DATE <= CME_OFFER.OFFER_CHANGE_DATE
  AND CME_OFFER.OFFER_END_DATE >= CME_OFFER.OFFER_CHANGE_DATE
  AND CME_OFFER.CUSTOMER_OFFER_EXPIRY_DATE >= CME_OFFER.OFFER_CHANGE_DATE