CREATE OR REPLACE TABLE `pcb-{env}-processing.domain_marketing.CME_CUSTOMER_STG`
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
WITH
  execution_id AS (
      SELECT
        MAX(CAST(execution_id AS NUMERIC)) + 1 AS execution_id_value
      FROM
        `pcb-{env}-landing.domain_account_management.CME_BATCH_PARAM`
      WHERE
        INTERFACE_ID='CME1')
SELECT
  DISTINCT
  CME_OFFER.OFFER_ID,
  CME_OFFER.CUSTOMER_REF,
  'BATCH_FULFILLED' AS LAST_OFFER_STATUS,
  CAST(CME_OFFER.OFFER_CHANGE_DATE AS DATE) AS LAST_OFFER_STATUS_DATE,
  CME_OFFER.NUMBER_OF_TIME_PRESENTED,
  CME_OFFER.CUSTOMER_MEDIA_REF,
  CME_OFFER.PROVINCE,
  CME_OFFER.PHONE_NUMBER,
  CME_OFFER.OFFER_SEQ_OVERRIDE,
  CME_OFFER.LANGUAGE,
  CME_OFFER.REC_CREATE_TMS,
  'BATCH' AS REC_CHNG_ID,
  CURRENT_DATETIME('America/Toronto') AS REC_CHNG_TMS,
  CME_OFFER.ST_CD,
  CME_OFFER.ST_DT,
  CME_OFFER.CUSTOMER_OFFER_EXPIRY_DATE,
  CME_OFFER.PROMO_SOL_CODE,
  CME_OFFER.ACQ_STRAT_CODE,
  (
  SELECT
    execution_id_value
  FROM
    execution_id) AS EXECUTION_ID,
  CASE
    WHEN CME_OFFER.LAST_OFFER_STATUS_DATE IS NULL THEN ('CME1' || '          ') || CME_OFFER.STORE_CUSTOMER_STATUS
    ELSE ('CME1' || CAST(CME_OFFER.LAST_OFFER_STATUS_DATE AS DATE)) || CME_OFFER.STORE_CUSTOMER_STATUS
END
  AS INTERFACE_ID
FROM
  `pcb-{env}-processing.domain_marketing.CME_BATCH_OFFER_STG` CME_OFFER
WHERE
  CME_OFFER.LAST_OFFER_STATUS <> 'Acceptance'
  AND CME_OFFER.LAST_OFFER_STATUS <>'Partially Accepted'
  AND CME_OFFER.LAST_OFFER_STATUS <> 'BATCH_FULFILLED'
  AND CME_OFFER.LAST_OFFER_STATUS <> 'Decline'
  AND CME_OFFER.OFFER_START_DATE <= CME_OFFER.OFFER_CHANGE_DATE
  AND CME_OFFER.OFFER_END_DATE >= CME_OFFER.OFFER_CHANGE_DATE
  AND CME_OFFER.CUSTOMER_OFFER_EXPIRY_DATE >= CME_OFFER.OFFER_CHANGE_DATE