CREATE OR REPLACE TABLE pcb-{env}-processing.domain_marketing.CME_CUSTOMER_CUSTLOOKUP_JOIN_STG
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  CME_CUSTOMER.*,
  CUSTOMER_LOOKUP.TSYS_ACCOUNT_ID,
  CUSTOMER_LOOKUP.TSYS_CUSTOMER_ID,
  CUSTOMER_LOOKUP.CARD_NUMBER,
  CUSTOMER_LOOKUP.PCB_CIF_REFERENCE
FROM
  `pcb-{env}-curated.domain_marketing.CME_CUSTOMER` CME_CUSTOMER
INNER JOIN
  `pcb-{env}-curated.domain_marketing.CUSTOMER_LOOKUP` CUSTOMER_LOOKUP
ON
  CME_CUSTOMER.CUSTOMER_REF = CUSTOMER_LOOKUP.CUSTOMER_REF