CREATE OR REPLACE TABLE `pcb-{env}-processing.domain_marketing.CME_BATCH_CUSTLOOKUP_STG`
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  CME_BATCH_STAGING.* EXCEPT (REC_CREATE_TMS),
  CUSTLOOKUP.* EXCEPT (CARD_NUMBER,
    TSYS_ACCOUNT_ID,
    TSYS_CUSTOMER_ID,
    PCB_CIF_REFERENCE,
    INTERFACE_ID,
    CME_ID),
  'CME1' AS INTERFACE_ID,
  '' AS CME_ID
FROM
  `pcb-{env}-processing.domain_marketing.CME_BATCH_STAGING` CME_BATCH_STAGING
INNER JOIN
  `pcb-{env}-processing.domain_marketing.CME_CUSTOMER_CUSTLOOKUP_JOIN_STG` CUSTLOOKUP
ON
  CME_BATCH_STAGING.TSYS_ACCOUNT_ID = CUSTLOOKUP.TSYS_ACCOUNT_ID
  AND CME_BATCH_STAGING.CIFP_PCF_CUST_ID = CUSTLOOKUP.PCB_CIF_REFERENCE
  AND CME_BATCH_STAGING.CAMPAIGN_TYPE = SUBSTR(CUSTLOOKUP.OFFER_ID, 1, 3)