CREATE OR REPLACE TABLE `pcb-{env}-processing.domain_marketing.CME_BATCH_OFFER_STG`
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  CME_BATCH.*,
  CME_BATCH.LAST_OFFER_STATUS AS STORE_CUSTOMER_STATUS,
  OFFER.OFFER_START_DATE,
  OFFER.OFFER_END_DATE
FROM
  `pcb-{env}-processing.domain_marketing.CME_BATCH_CUSTLOOKUP_STG` CME_BATCH,
  `pcb-{env}-curated.domain_marketing.OFFER` OFFER
WHERE
  OFFER.OFFER_ID = CME_BATCH.OFFER_ID
  AND CME_BATCH.CUSTOMER_REF IS NOT null