CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_customer_management.RETURNCFF_INTERMEDIATE
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
WITH
  INTERN_TABLE AS (
SELECT
    so.ACCOUNT_ID AS ACCOUNT_ID,
    CUSTOMER_ID,
    CYCLE,
    SAFE_CAST(PRINTED_DATE AS DATETIME) AS PRINTED_DATE,
    SAFE_CAST(PROCESSED_TMS AS DATETIME) AS PROCESSED_TMS,
    NUM_OF_PAGES,
    NUM_OF_INSERTS,
    NUM_OF_OFFERS,
    MSG_INSERT_ID,
    OFFER_ID,
    REASON,
    CONTENTS_TYPE,
    EXTRA_PAGE_ID,
    SO.RECORD_SEQ AS RECORD_SEQ
  FROM
    `pcb-{env}-landing.domain_customer_management.STMT_CUSTOMER` sc
  INNER JOIN
    `pcb-{env}-landing.domain_customer_management.STMT_OFFER` so
  ON
    so.ACCOUNT_ID = sc.ACCOUNT_ID
    AND so.FILE_NAME = sc.FILE_NAME
    AND so.FILE_NAME = '{file_name}')
SELECT
  ROW_NUMBER() OVER (ORDER BY RECORD_SEQ ) AS SEQ_NUM,
  * EXCEPT(RECORD_SEQ)
FROM
  INTERN_TABLE