CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_customer_management.STMT_CME_FEEDBACK_Y
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
SELECT
  STMT_CME_FEEDBACK_INTER_Y.SEQ_NUM,
  STMT_CME_FEEDBACK_INTER_Y.ACCOUNT_ID,
  STMT_CME_FEEDBACK_INTER_Y.CUSTOMER_ID,
  STMT_CME_FEEDBACK_INTER_Y.CYCLE,
  STMT_CME_FEEDBACK_INTER_Y.PRINTED_DATE,
  STMT_CME_FEEDBACK_INTER_Y.PROCESSED_TMS,
  STMT_CME_FEEDBACK_INTER_Y.NUM_OF_PAGES,
  STMT_CME_FEEDBACK_INTER_Y.NUM_OF_INSERTS,
  STMT_CME_FEEDBACK_INTER_Y.NUM_OF_OFFERS,
  STMT_CME_FEEDBACK_INTER_Y.MSG_INSERT_ID,
  STMT_CME_FEEDBACK_INTER_Y.OFFER_ID,
  STMT_CME_FEEDBACK_INTER_Y.REASON,
  STMT_CME_FEEDBACK_INTER_Y.CONTENTS_TYPE,
  STMT_CME_FEEDBACK_INTER_Y.EXTRA_PAGE_ID,
  'Y' AS CUSTOMER_UPDATE_ID
FROM
  pcb-{env}-landing.domain_marketing.STMT_FEEDBACK_STAGING STMT_CME_FEEDBACK_STAGING,
  pcb-{env}-processing.domain_customer_management.STMT_CME_FEEDBACK_INTER_Y
WHERE
  STMT_CME_FEEDBACK_INTER_Y.ACCOUNT_ID=STMT_CME_FEEDBACK_STAGING.ACCOUNT_ID
  AND STMT_CME_FEEDBACK_INTER_Y.CUSTOMER_ID=STMT_CME_FEEDBACK_STAGING.CUSTOMER_ID