CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_customer_management.STMT_CME_FEEDBACK_N
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
WITH
  MAX_SEQ AS (
  SELECT
    MAX(SEQ_NUM) AS SEQ_NUM
  FROM
    `pcb-{env}-landing.domain_marketing.STMT_FEEDBACK_STAGING` )
SELECT
  RETURNCFF_INTERMEDIATE.* REPLACE(MAX_SEQ.SEQ_NUM + RETURNCFF_INTERMEDIATE.SEQ_NUM AS SEQ_NUM),
  'N' AS CUSTOMER_UPDATE_ID
FROM
  pcb-{env}-processing.domain_customer_management.RETURNCFF_INTERMEDIATE RETURNCFF_INTERMEDIATE
LEFT OUTER JOIN
  pcb-{env}-processing.domain_customer_management.STMT_CME_FEEDBACK_DISTINCT
ON
  RETURNCFF_INTERMEDIATE.ACCOUNT_ID = STMT_CME_FEEDBACK_DISTINCT.ACCOUNT_ID
  AND RETURNCFF_INTERMEDIATE.CUSTOMER_ID = STMT_CME_FEEDBACK_DISTINCT.CUSTOMER_ID
  AND RETURNCFF_INTERMEDIATE.OFFER_ID = STMT_CME_FEEDBACK_DISTINCT.OFFER_ID
CROSS JOIN
  MAX_SEQ