CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_customer_management.STMT_CME_FEEDBACK_D
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
SELECT
  RETURNCFF_INTERMEDIATE.ACCOUNT_ID AS ACCOUNT_ID,
  RETURNCFF_INTERMEDIATE.CUSTOMER_ID AS CUSTOMER_ID,
  RETURNCFF_INTERMEDIATE.OFFER_ID AS OFFER_ID,
  'D' AS CUSTOMER_UPDATE_ID
FROM
  pcb-{env}-processing.domain_customer_management.RETURNCFF_INTERMEDIATE RETURNCFF_INTERMEDIATE
LEFT OUTER JOIN
  pcb-{env}-processing.domain_customer_management.STMT_CME_FEEDBACK_DISTINCT
ON
  RETURNCFF_INTERMEDIATE.ACCOUNT_ID = STMT_CME_FEEDBACK_DISTINCT.ACCOUNT_ID
  AND RETURNCFF_INTERMEDIATE.CUSTOMER_ID = STMT_CME_FEEDBACK_DISTINCT.CUSTOMER_ID
  AND RETURNCFF_INTERMEDIATE.OFFER_ID = STMT_CME_FEEDBACK_DISTINCT.OFFER_ID
WHERE
  RETURNCFF_INTERMEDIATE.ACCOUNT_ID IS NOT NULL
  OR RETURNCFF_INTERMEDIATE.ACCOUNT_ID != 0
  AND RETURNCFF_INTERMEDIATE.CUSTOMER_ID IS NOT NULL
  OR RETURNCFF_INTERMEDIATE.CUSTOMER_ID != 0
  AND RETURNCFF_INTERMEDIATE.OFFER_ID IS NOT NULL
  OR RETURNCFF_INTERMEDIATE.OFFER_ID != ''