CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_customer_management.STMT_UPDATE_CUST
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
SELECT
  STMT_UPDATE_CUST_INTER.OFFER_ID AS OFFER_ID,
  STMT_UPDATE_CUST_INTER.CUSTOMER_REF AS CUSTOMER_REF,
  'Presented' AS LAST_OFFER_STATUS,
  CURRENT_TIMESTAMP() AS LAST_OFFER_STATUS_DATE,
  CUSTOMER.NUMBER_OF_TIME_PRESENTED + 1 AS NUMBER_OF_TIME_PRESENTED
FROM
  pcb-{env}-processing.domain_customer_management.STMT_UPDATE_CUST_INTER,
  pcb-{env}-curated.domain_marketing.CME_CUSTOMER CUSTOMER
WHERE
  STMT_UPDATE_CUST_INTER.OFFER_ID = CUSTOMER.OFFER_ID
  AND STMT_UPDATE_CUST_INTER.CUSTOMER_REF = CUSTOMER.CUSTOMER_REF