CREATE OR REPLACE TABLE
  pcb-{env}-processing.domain_customer_management.STMT_CME_FEEDBACK_INTER_Y
  OPTIONS ( expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR) )
AS
SELECT
  SEQ_NUM,
  ACCOUNT_ID,
  CUSTOMER_ID,
  CYCLE,
  PRINTED_DATE,
  PROCESSED_TMS,
  NUM_OF_PAGES,
  NUM_OF_INSERTS,
  NUM_OF_OFFERS,
  MSG_INSERT_ID,
  STMT_CME_FEEDBACK_STAGING.OFFER_ID,
  REASON,
  CONTENTS_TYPE,
  EXTRA_PAGE_ID,
  CUSTOMER_UPDATE_ID
FROM
  pcb-{env}-landing.domain_marketing.STMT_FEEDBACK_STAGING STMT_CME_FEEDBACK_STAGING,
  pcb-{env}-curated.domain_marketing.CUSTOMER_LOOKUP CUSTOMER_LOOKUP,
  pcb-{env}-curated.domain_marketing.CME_CUSTOMER CUSTOMER
WHERE
  CUSTOMER.OFFER_ID = STMT_CME_FEEDBACK_STAGING.OFFER_ID
  AND CUSTOMER.CUSTOMER_REF = CUSTOMER_LOOKUP.CUSTOMER_REF
  AND CUSTOMER_LOOKUP.TSYS_ACCOUNT_ID = STMT_CME_FEEDBACK_STAGING.ACCOUNT_ID
  AND CUSTOMER_LOOKUP.TSYS_CUSTOMER_ID = STMT_CME_FEEDBACK_STAGING.CUSTOMER_ID
  AND STMT_CME_FEEDBACK_STAGING.CUSTOMER_UPDATE_ID = 'N'