UPDATE `pcb-{env}-landing.domain_loyalty.ESSO_FUEL_TRANSACTIONS` T
SET
  T.LITERS_PURCHASED = LPAD(S.PRODUCT_QUANTITY, 7, '0'),
  T.FUEL_TYPE = LPAD(S.NATIVE_MERCHANDISE_CODE, 3, '0')
FROM `pcb-{env}-processing.domain_loyalty.ESSO_FUEL_TRANSACTIONS_STAGING` S
WHERE
  T.MERCHANT_NUMBER = REGEXP_REPLACE(S.EXTERNAL_MERCHANT_ID, r'^0+', '')
  AND REGEXP_REPLACE(T.TRANSACTION_AMOUNT, r'^0+', '') = S.AMOUNT
  AND T.CARD_NUMBER = S.CARD_NUMBER
  AND ABS(
    DATETIME_DIFF(
      SAFE.PARSE_DATETIME('%Y%m%d%H%M%S', T.TRANSACTION_DATE),
      S.TRANSACTION_DATE,
      MINUTE)) <= 1
