CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.AH01_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.AH00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AH00_CLIENT_NUM,
  AH00_APPLICATION_NUM,
  AH00_APPLICATION_SUFFIX,
  AH01_SEGMENT_LENGTH,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH01_CDATE_CYCLE) AS INT64) AS AH01_CDATE_CYCLE,
  CONCAT(
  IF(AH01_FIXED_PAYMENT_INDICATOR IS NULL OR AH01_FIXED_PAYMENT_INDICATOR = '', ' ', AH01_FIXED_PAYMENT_INDICATOR),
  IF(AH01_PAYMENT_STATUS_CTD IS NULL OR AH01_PAYMENT_STATUS_CTD = '', ' ', AH01_PAYMENT_STATUS_CTD),
  IF(AH01_PAYMENT_TIMING_CTD IS NULL OR AH01_PAYMENT_TIMING_CTD = '', ' ', AH01_PAYMENT_TIMING_CTD),
  IF(AH01_SKIP_A_PAY_FLAG IS NULL OR AH01_SKIP_A_PAY_FLAG = '', ' ', AH01_SKIP_A_PAY_FLAG),
  IF(AH01_SKIP_A_PAY_RESULT IS NULL OR AH01_SKIP_A_PAY_RESULT = '', ' ', AH01_SKIP_A_PAY_RESULT),
  IF(AH01_HIT_HIGH_BALANCE IS NULL OR AH01_HIT_HIGH_BALANCE = '', ' ', AH01_HIT_HIGH_BALANCE),
  IF(AH01_PAST_DUE_REAGE IS NULL OR AH01_PAST_DUE_REAGE = '', ' ', AH01_PAST_DUE_REAGE),
  IF(AH01_CHARGEOFF IS NULL OR AH01_CHARGEOFF = '', ' ', AH01_CHARGEOFF),
  IF(AH01_DISCLOSURE_GRP IS NULL OR AH01_DISCLOSURE_GRP = '', ' ', AH01_DISCLOSURE_GRP),
  IF(AH01_ALTERNATE_DISCLOSURE_GRP IS NULL OR AH01_ALTERNATE_DISCLOSURE_GRP = '', '        ', AH01_ALTERNATE_DISCLOSURE_GRP),
  IF(AH01_ALT_DISCLOSURE_STATUS IS NULL OR AH01_ALT_DISCLOSURE_STATUS = '', ' ', AH01_ALT_DISCLOSURE_STATUS),
  IF(AH01_RES_PAYMENT_TYPE IS NULL, ' ', CAST(AH01_RES_PAYMENT_TYPE AS STRING)),
  LPAD(CAST(AH01_STMT_INSERT_GROUP_ID AS STRING), 3, '0'),
  IF(AH01_BKDT_PIF_FLAG IS NULL OR AH01_BKDT_PIF_FLAG = '', ' ', AH01_BKDT_PIF_FLAG)
  )  AS AH01_ACT_HIST_CYCLE_DATA,
  * EXCEPT (FILE_CREATE_DT,REC_LOAD_TIMESTAMP, MAST_ACCOUNT_ID, MAST_REC_TYPE, AH00_CLIENT_NUM,
            AH00_APPLICATION_NUM, AH00_APPLICATION_SUFFIX, AH01_SEGMENT_LENGTH, AH01_CDATE_CYCLE)
FROM
  pcb-{env}-landing.domain_account_management.AH01
WHERE
    file_create_dt = '{file_create_dt}'