CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.AH02_DISPUTES_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.AH00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AH00_CLIENT_NUM,
  AH00_APPLICATION_NUM,
  AH00_APPLICATION_SUFFIX,
  AH02_SEGMENT_LENGTH,
  AH02_HISTORY_TYPE,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH02_CDATE_HISTORY) AS INT64) AS AH02_CDATE_HISTORY,
  CASE
  WHEN AH02_CTIME_HISTORY = '0' THEN 0
  ELSE 10000000 - CAST(REPLACE(AH02_CTIME_HISTORY, ":", "") AS INT64)
  END AS AH02_CTIME_HISTORY,
  CONCAT(
   AH02_DISPUTE_CASE_TRACKING_NUM,
   AH02_DISPUTE_TYPE,
   AH02_FCHG_BYP_IND,
   AH02_DISPUTE_OPERATOR,
   AH02_OPER_LAST_WORKED,
   AH02_ACCOUNT_NUMBER,
   '   ',
   AH02_REFERENCE_NUMBER,
   AH02_TRANSACTION_DESCRIPTION,
   ' ',
   AH02_MERCHANT_DBA_COUNTRY,
   AH02_CREDIT_ISSUED,
   AH02_DEBIT_CREDIT_FLAG,
   AH02_RESOLVE_STATUS,
   IF(AH02_RESOLVE_ACTIONS IS NULL OR AH02_RESOLVE_ACTIONS = '', '    ', AH02_RESOLVE_ACTIONS),
   AH02_DECISION_BY_OPERATOR,
   IF(AH02_CORRESP_ID IS NULL OR AH02_CORRESP_ID = '', '      ', AH02_CORRESP_ID),
   AH02_ACTION_CODE,
   AH02_RESULT_CODE,
   AH02_TRNS_ACCT_FUNC,
   AH02_DISP_ENTIRE_BALANCE_FLAG,
   IF(AH02_PS2000_TRAN_ID IS NULL OR AH02_PS2000_TRAN_ID = '', '              ', AH02_PS2000_TRAN_ID),
   IF(AH02_BANKNET_REF_NUMBER IS NULL OR AH02_BANKNET_REF_NUMBER = '', ' ', AH02_BANKNET_REF_NUMBER),
   AH02_MERCHANT_CATEGORY_CODE,
   AH02_TRANSACTION_CODE,
   AH02_TRANSACTION_CATEGORY,
   AH02_DISPUTE_TEXT,
   CAST(
       10000000 - CAST(
       FORMAT('%04d%03d',
        EXTRACT(YEAR FROM DATE(AH02_BKDATE_EFFECT_DATE)),
        EXTRACT(DAYOFYEAR FROM DATE(AH02_BKDATE_EFFECT_DATE))
      ) AS INT64
    ) AS STRING
   )
   ) AS AH02_ACT_HIST_DETAIL_DATA,
  AH02_DISPUTE_CASE_TRACKING_NUM,
  AH02_DISPUTE_TYPE,
  AH02_FCHG_BYP_IND,
  AH02_DISPUTE_OPERATOR,
  AH02_OPER_LAST_WORKED,
  AH02_ACCOUNT_NUMBER,
  AH02_REFERENCE_NUMBER,
  AH02_TRANSACTION_DESCRIPTION,
  AH02_MERCHANT_DBA_NAME,
  AH02_MERCHANT_DBA_CITY,
  AH02_MERCHANT_DBA_STATE,
  AH02_MERCHANT_DBA_COUNTRY,
  AH02_CREDIT_ISSUED,
  AH02_DEBIT_CREDIT_FLAG,
  AH02_RESOLVE_STATUS,
  AH02_RESOLVE_ACTIONS,
  AH02_DECISION_BY_OPERATOR,
  AH02_CORRESP_ID,
  AH02_ACTION_CODE,
  AH02_RESULT_CODE,
  AH02_TRNS_ACCT_FUNC,
  AH02_DISP_ENTIRE_BALANCE_FLAG,
  AH02_PS2000_TRAN_ID,
  AH02_BANKNET_REF_NUMBER,
  AH02_MERCHANT_CATEGORY_CODE,
  AH02_TRANSACTION_CODE,
  AH02_TRANSACTION_CATEGORY,
  AH02_DISPUTE_TEXT,
  AH02_BKDATE_EFFECT_DATE,
  AH02_DATE_DISPUTE,
  AH02_AMT_DISPUTE,
  AH02_DATE_MAIL_STAMP,
  AH02_DATE_DISPUTE_SETTLED,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH02_CDATE_STMT_BEGIN) AS INT64) AS AH02_CDATE_STMT_BEGIN,
  AH02_DATE_POST,
  AH02_TIME_POST,
  AH02_DATE_LAST_WORKED,
  AH02_DATE_TRANSACTION,
  AH02_AMT_TRANSACTION,
  AH02_CENTRAL_PROC_DATE
FROM
  pcb-{env}-landing.domain_account_management.AH02_DISPUTES
WHERE
    file_create_dt = '{file_create_dt}'