CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.AH02_COLL_AGENCY_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.AH00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AH00_CLIENT_NUM,
  AH00_APPLICATION_NUM,
  AH00_APPLICATION_SUFFIX,
  AH02_SEGMENT_LENGTH,
  AH02_HISTORY_TYPE,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH02_CDATE_HISTORY) AS INT64) AS AH02_CDATE_HISTORY,
  CASE
  WHEN AH02_CTIME_HISTORY = '0' THEN 0
  ELSE 10000000 - CAST(REPLACE(AH02_CTIME_HISTORY, ":", "") AS INT64)
  END AS AH02_CTIME_HISTORY,
  CONCAT(
  IF(AH02_AGENCY_CODE IS NULL OR AH02_AGENCY_CODE = '', ' ', AH02_AGENCY_CODE),
  '    ',
  IF(AH02_AGCY_ASSIGN_PAST_DUE IS NULL OR AH02_AGCY_ASSIGN_PAST_DUE = '', ' ', AH02_AGCY_ASSIGN_PAST_DUE),
  IF(AH02_AGCY_ASSIGN_METHOD IS NULL OR AH02_AGCY_ASSIGN_METHOD = '', ' ', AH02_AGCY_ASSIGN_METHOD),
  IF(AH02_RECALL_DATE IS NULL, ' ', CAST(10000000 - CAST(FORMAT_DATE('%Y%j', AH02_RECALL_DATE) AS INT64) AS STRING)),
  IF(AH02_RECALL_PAST_DUE IS NULL OR AH02_RECALL_PAST_DUE = '', ' ', AH02_RECALL_PAST_DUE),
  IF(AH02_AGCY_RECALL_METHOD IS NULL OR AH02_AGCY_RECALL_METHOD = '', ' ', AH02_AGCY_RECALL_METHOD)
  )AS AH02_ACT_HIST_DETAIL_DATA,
  AH02_AGENCY_CODE,
  AH02_AGCY_ASSIGN_PAST_DUE,
  AH02_AGCY_ASSIGN_METHOD,
  AH02_RECALL_DATE,
  AH02_RECALL_PAST_DUE,
  AH02_AGCY_RECALL_METHOD
FROM
  pcb-{env}-landing.domain_account_management.AH02_COLL_AGENCY
WHERE
    file_create_dt = '{file_create_dt}'