CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.AH02_HIST_TYPE10_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.AH00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AH00_CLIENT_NUM,
  AH00_APPLICATION_NUM,
  AH00_APPLICATION_SUFFIX,
  AH02_SEGMENT_LENGTH,
  AH02_HISTORY_TYPE,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH02_CDATE_HISTORY) AS INT64) AS AH02_CDATE_HISTORY,
  CASE
  WHEN AH02_CTIME_HISTORY = '0' THEN 0
  ELSE 10000000 - CAST(REPLACE(AH02_CTIME_HISTORY, ":", "") AS INT64)
  END AS AH02_CTIME_HISTORY,
  IF(AH02_PROJ_PIF_AMT >= 99999999999.99,'rrrrrr',NULL)  AS AH02_ACT_HIST_DETAIL_DATA,
  AH02_PROJ_PIF_AMT
FROM
  pcb-{env}-landing.domain_account_management.AH02_HIST_TYPE10
WHERE
    file_create_dt = '{file_create_dt}'