CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.AH31_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.AH00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AH00_CLIENT_NUM,
  AH00_APPLICATION_NUM,
  AH00_APPLICATION_SUFFIX,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH01_CDATE_CYCLE) AS INT64) AS AH01_CDATE_CYCLE,
  * EXCEPT (FILE_CREATE_DT,REC_LOAD_TIMESTAMP, MAST_ACCOUNT_ID, MAST_REC_TYPE, AH00_CLIENT_NUM,
            AH00_APPLICATION_NUM, AH00_APPLICATION_SUFFIX, AH01_CDATE_CYCLE)
FROM
  pcb-{env}-landing.domain_account_management.AH31
WHERE
    file_create_dt = '{file_create_dt}'