CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.AH35_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.AH00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AH00_CLIENT_NUM,
  AH00_APPLICATION_NUM,
  AH00_APPLICATION_SUFFIX,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH01_CDATE_CYCLE) AS INT64) AS AH01_CDATE_CYCLE,
  AH35_SEGMENT_LENGTH,
  AH35_EXPIRATION_DATE,
  AH35_TLP_TYPE_TRAN,
  10000000 - CAST(FORMAT_DATE('%Y%j', AH35_CDATE_STMT_BEG) AS INT64) AS AH35_CDATE_STMT_BEG,
  AH35_DATE_POST,
  AH35_TIME_POST,
  NULL AS AH35_TLP_HIST_DATA,
  * EXCEPT (FILE_CREATE_DT,REC_LOAD_TIMESTAMP, MAST_ACCOUNT_ID, MAST_REC_TYPE, AH00_CLIENT_NUM,
            AH00_APPLICATION_NUM, AH00_APPLICATION_SUFFIX, AH01_CDATE_CYCLE, AH35_SEGMENT_LENGTH,
            AH35_EXPIRATION_DATE, AH35_TLP_TYPE_TRAN, AH35_CDATE_STMT_BEG, AH35_DATE_POST, AH35_TIME_POST)
FROM
  pcb-{env}-landing.domain_account_management.AH35
WHERE
    file_create_dt = '{file_create_dt}'