CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.CIF_CARD_XREF_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  REC_LOAD_TIMESTAMP AS REC_LOAD_DT_TM_STAMP,
  CIFP_ACCOUNT_ID6,
  CIFP_ACCOUNT_NUM,
  CIFP_CUSTOMER_ID_2,
  CIFP_RELATIONSHIP_STAT,
  * EXCEPT (FILE_CREATE_DT,REC_LOAD_TIMESTAMP, CIFP_ACCOUNT_ID6, CIFP_ACCOUNT_NUM, CIFP_CUSTOMER_ID_2, CIFP_RELATIONSHIP_STAT)
FROM
  pcb-{env}-landing.domain_account_management.CIF_CARD_XREF
WHERE
    file_create_dt = '{file_create_dt}'