CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.CIF_ACCOUNT_CURR_TEMP
CLUSTER BY
CIFP_ACCOUNT_ID5,
CIFP_CLIENT_PRODUCT_CODE
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  CAST(NULL AS NUMERIC) as EXECUTION_ID,
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  FORMAT_TIMESTAMP('%Y-%m-%d %H:%M:%S', REC_LOAD_TIMESTAMP) AS REC_LOAD_DT_TM_STAMP,                               -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_RECORD_ID5 AS BYTES), 1, 1)) AS CIFP_RECORD_ID5,                    -- VARCHAR2(1 BYTE)
  CAST(ROUND(CIFP_ACCOUNT_ID5, 0) AS NUMERIC) AS CIFP_ACCOUNT_ID5,                          -- NUMBER(11,0)
  CAST(ROUND(CIFP_CLIENT_NUM, 0) AS NUMERIC) AS CIFP_CLIENT_NUM,                            -- NUMBER(4,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_TSYS_PRODUCT_CODE AS BYTES), 1, 2)) AS CIFP_TSYS_PRODUCT_CODE,     -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CLIENT_PRODUCT_CODE AS BYTES), 1, 3)) AS CIFP_CLIENT_PRODUCT_CODE, -- VARCHAR2(3 BYTE)
  CAST(ROUND(CIFP_SUFFIX_NUMBER, 0) AS NUMERIC) AS CIFP_SUFFIX_NUMBER,                      -- NUMBER(2,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_ACTION_CODE AS BYTES), 1, 1)) AS CIFP_ACTION_CODE,                  -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_BRANCH AS BYTES), 1, 6)) AS CIFP_BRANCH,                            -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_OFFICER_NBR AS BYTES), 1, 6)) AS CIFP_OFFICER_NBR,                  -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_MEMBERSHIP_NO AS BYTES), 1, 19)) AS CIFP_MEMBERSHIP_NO,             -- VARCHAR2(19 BYTE)
  CAST(ROUND(CIFP_NO_CARDS_OUTSTAND, 0) AS NUMERIC) AS CIFP_NO_CARDS_OUTSTAND,              -- NUMBER(7,0)
  CAST(ROUND(CIFP_NO_CARDS_REISSUE, 0) AS NUMERIC) AS CIFP_NO_CARDS_REISSUE,                -- NUMBER(7,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_INS_RATE_CODE AS BYTES), 1, 1)) AS CIFP_INS_RATE_CODE,              -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_VIP AS BYTES), 1, 2)) AS CIFP_VIP,                                  -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_EMPLOYEE AS BYTES), 1, 2)) AS CIFP_EMPLOYEE,                        -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_ACCOUNT_TYPE AS BYTES), 1, 2)) AS CIFP_ACCOUNT_TYPE,                -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_AUTO_DEDUCT_TYPE AS BYTES), 1, 2)) AS CIFP_AUTO_DEDUCT_TYPE,        -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REISSUE_RATING AS BYTES), 1, 2)) AS CIFP_REISSUE_RATING,            -- VARCHAR2(2 BYTE)
  CAST(ROUND(CIFP_STATEMENT_HOLD, 0) AS NUMERIC) AS CIFP_STATEMENT_HOLD,                    -- NUMBER(3,0)
  CAST(CIFP_ENROLL_DATE AS DATE) AS CIFP_ENROLL_DATE,                                       -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_PROMO_SOLICIT AS BYTES), 1, 15)) AS CIFP_PROMO_SOLICIT,             -- VARCHAR2(15 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REGION AS BYTES), 1, 3)) AS CIFP_REGION,                            -- VARCHAR2(3 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_SEC_POOL_ID1 AS BYTES), 1, 6)) AS CIFP_SEC_POOL_ID1,                -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_10 AS BYTES), 1, 1)) AS CIFP_CUSTOM_DATA_10,           -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_11 AS BYTES), 1, 1)) AS CIFP_CUSTOM_DATA_11,           -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_12 AS BYTES), 1, 1)) AS CIFP_CUSTOM_DATA_12,           -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_13 AS BYTES), 1, 1)) AS CIFP_CUSTOM_DATA_13,           -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_14 AS BYTES), 1, 1)) AS CIFP_CUSTOM_DATA_14,           -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_20 AS BYTES), 1, 2)) AS CIFP_CUSTOM_DATA_20,           -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_21 AS BYTES), 1, 2)) AS CIFP_CUSTOM_DATA_21,           -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_22 AS BYTES), 1, 2)) AS CIFP_CUSTOM_DATA_22,           -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_23 AS BYTES), 1, 2)) AS CIFP_CUSTOM_DATA_23,           -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_24 AS BYTES), 1, 2)) AS CIFP_CUSTOM_DATA_24,           -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_40 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_40,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_41 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_41,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_42 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_42,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_43 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_43,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_44 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_44,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_60 AS BYTES), 1, 6)) AS CIFP_CUSTOM_DATA_60,           -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_61 AS BYTES), 1, 6)) AS CIFP_CUSTOM_DATA_61,           -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_62 AS BYTES), 1, 6)) AS CIFP_CUSTOM_DATA_62,           -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_63 AS BYTES), 1, 6)) AS CIFP_CUSTOM_DATA_63,           -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_64 AS BYTES), 1, 6)) AS CIFP_CUSTOM_DATA_64,           -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_80 AS BYTES), 1, 8)) AS CIFP_CUSTOM_DATA_80,           -- VARCHAR2(8 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_81 AS BYTES), 1, 8)) AS CIFP_CUSTOM_DATA_81,           -- VARCHAR2(8 BYTE)
  CAST(ROUND(CIFP_CUSTOM_DATA_90, 0) AS NUMERIC) AS CIFP_CUSTOM_DATA_90,                    -- NUMBER(9,0)
  CAST(ROUND(CIFP_CUSTOM_DATA_91, 0) AS NUMERIC) AS CIFP_CUSTOM_DATA_91,                    -- NUMBER(9,0)
  CAST(ROUND(CIFP_CUSTOM_DATA_92, 0) AS NUMERIC) AS CIFP_CUSTOM_DATA_92,                    -- NUMBER(9,0)
  CAST(ROUND(CIFP_CUSTOM_DATA_93, 0) AS NUMERIC) AS CIFP_CUSTOM_DATA_93,                    -- NUMBER(9,0)
  CAST(ROUND(CIFP_TRIAD_SCORE, 0) AS NUMERIC) AS CIFP_TRIAD_SCORE,                         -- NUMBER(3,0)
  CAST(ROUND(CIFP_FINAL_SCORE_ACE, 0) AS NUMERIC) AS CIFP_FINAL_SCORE_ACE,                 -- NUMBER(5,0)
  CAST(ROUND(CIFP_AVAIL_AMT_TO_BUY, 0) AS NUMERIC) AS CIFP_AVAIL_AMT_TO_BUY,               -- NUMBER(11,0)
  CAST(CIFP_DATE_EXPIRED AS DATE) AS CIFP_DATE_EXPIRED,                                     -- DATE
  CAST(ROUND(CIFP_CYCLE_NUM, 0) AS NUMERIC) AS CIFP_CYCLE_NUM,                             -- NUMBER(2,0)
  CAST(ROUND(CIFP_ORIG_CREDIT_LIMIT, 0) AS NUMERIC) AS CIFP_ORIG_CREDIT_LIMIT,              -- NUMBER(11,0)
  CAST(CIFP_DT_LAST_MAIN AS DATE) AS CIFP_DT_LAST_MAIN,                                     -- DATE
  CAST(CIFP_DT_COLL_STAT_MAIN AS DATE) AS CIFP_DT_COLL_STAT_MAIN,                          -- DATE
  CAST(CIFP_DT_SEC_FRAUD_STAT AS DATE) AS CIFP_DT_SEC_FRAUD_STAT,                          -- DATE
  CAST(CIFP_DT_LAST_STATEMENT AS DATE) AS CIFP_DT_LAST_STATEMENT,                          -- DATE
  CAST(ROUND(CIFP_NUM_STATEMENTS, 0) AS NUMERIC) AS CIFP_NUM_STATEMENTS,                   -- NUMBER(3,0)
  CAST(CIFP_DATE_OPEN AS DATE) AS CIFP_DATE_OPEN,                                           -- DATE
  CAST(CIFP_DATE_PROD_CHG AS DATE) AS CIFP_DATE_PROD_CHG,                                   -- DATE
  CAST(CIFP_DATE_CLOSE AS DATE) AS CIFP_DATE_CLOSE,                                         -- DATE
  CAST(CIFP_DATE_FRAUD AS DATE) AS CIFP_DATE_FRAUD,                                         -- DATE
  CAST(ROUND(CIFP_CREDIT_LIMIT, 0) AS NUMERIC) AS CIFP_CREDIT_LIMIT,                       -- NUMBER(11,0)
  CAST(CIFP_DT_POT_PURGE AS DATE) AS CIFP_DT_POT_PURGE,                                     -- DATE
  CAST(CIFP_DT_ACCT_STAT_MAIN AS DATE) AS CIFP_DT_ACCT_STAT_MAIN,                          -- DATE
  CAST(CIFP_DT_CREDIT_SCORE AS DATE) AS CIFP_DT_CREDIT_SCORE,                               -- DATE
  CAST(CIFP_DT_LAST_LIMIT_CHG AS DATE) AS CIFP_DT_LAST_LIMIT_CHG,                          -- DATE
  CAST(CIFP_DT_LAST_DSCL_GRP_CHG AS DATE) AS CIFP_DT_LAST_DSCL_GRP_CHG,                    -- DATE
  CAST(CIFP_CLOSED_MAINT_DATE AS DATE) AS CIFP_CLOSED_MAINT_DATE,                           -- DATE
  CAST(CIFP_CRVK_MAINT_DATE AS DATE) AS CIFP_CRVK_MAINT_DATE,                               -- DATE
  CAST(CIFP_CRVK_DATE AS DATE) AS CIFP_CRVK_DATE,                                           -- DATE
  CAST(CIFP_DT_HIGH_BALANCE AS DATE) AS CIFP_DT_HIGH_BALANCE,                               -- DATE
  CAST(CIFP_DT_LAST_CASH AS DATE) AS CIFP_DT_LAST_CASH,                                     -- DATE
  CAST(CIFP_DT_LAST_PURCHASE AS DATE) AS CIFP_DT_LAST_PURCHASE,                             -- DATE
  CAST(CIFP_DT_LAST_CREDIT AS DATE) AS CIFP_DT_LAST_CREDIT,                                 -- DATE
  CAST(CIFP_DT_LAST_PAYMENT AS DATE) AS CIFP_DT_LAST_PAYMENT,                               -- DATE
  CAST(CIFP_DT_LAST_SYS_GEN_TRAN AS DATE) AS CIFP_DT_LAST_SYS_GEN_TRAN,                     -- DATE
  CAST(CIFP_FIRST_USE_DATE AS DATE) AS CIFP_FIRST_USE_DATE,                                 -- DATE
  CAST(CIFP_DATE_CHARGE_OFF AS DATE) AS CIFP_DATE_CHARGE_OFF,                               -- DATE
  CAST(CIFP_DATE_CHARGEOFF_REIN AS DATE) AS CIFP_DATE_CHARGEOFF_REIN,                       -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_AM0F_AWD_OPT_SET AS BYTES), 1, 4)) AS CIFP_AM0F_AWD_OPT_SET,        -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_WAIVE_FCHG_FLAG AS BYTES), 1, 1)) AS CIFP_WAIVE_FCHG_FLAG,          -- VARCHAR2(1 BYTE)
  CAST(ROUND(CIFP_CURRENT_CRED_SC, 0) AS NUMERIC) AS CIFP_CURRENT_CRED_SC,                  -- NUMBER(5,0)
  CAST(ROUND(CIFP_CURRENT_BALANCE, 2) AS NUMERIC) AS CIFP_CURRENT_BALANCE,                  -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_LAST_PAID, 2) AS NUMERIC) AS CIFP_AMT_LAST_PAID,                      -- NUMBER(13,2)
  CAST(ROUND(CIFP_CASH_APR, 9) AS NUMERIC) AS CIFP_CASH_APR,                                -- NUMBER(13,9)
  CAST(ROUND(CIFP_PURCHASE_APR, 9) AS NUMERIC) AS CIFP_PURCHASE_APR,                        -- NUMBER(13,9)
  CAST(ROUND(CIFP_AMT_LAST_AUTO, 2) AS NUMERIC) AS CIFP_AMT_LAST_AUTO,                      -- NUMBER(13,2)
  CAST(CIFP_DT_LAST_AUTO_PAY AS DATE) AS CIFP_DT_LAST_AUTO_PAY,                             -- DATE
  CAST(ROUND(CIFP_AMT_FIX_PAY, 2) AS NUMERIC) AS CIFP_AMT_FIX_PAY,                          -- NUMBER(13,2)
  CAST(CIFP_DT_BEG_FIX_PAY AS DATE) AS CIFP_DT_BEG_FIX_PAY,                                 -- DATE
  CAST(CIFP_DT_END_FIX_PAY AS DATE) AS CIFP_DT_END_FIX_PAY,                                 -- DATE
  CAST(ROUND(CIFP_NUM_PAY_YTD, 0) AS NUMERIC) AS CIFP_NUM_PAY_YTD,                          -- NUMBER(5,0)
  CAST(ROUND(CIFP_AMT_PAY_YTD, 2) AS NUMERIC) AS CIFP_AMT_PAY_YTD,                          -- NUMBER(13,2)
  CAST(ROUND(CIFP_NUM_PAY_CTD, 0) AS NUMERIC) AS CIFP_NUM_PAY_CTD,                          -- NUMBER(5,0)
  CAST(ROUND(CIFP_AMT_PAY_CTD, 2) AS NUMERIC) AS CIFP_AMT_PAY_CTD,                          -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_LAST_ANN_FEE, 2) AS NUMERIC) AS CIFP_AMT_LAST_ANN_FEE,                -- NUMBER(13,2)
  CAST(CIFP_DT_LAST_ANN_FEE AS DATE) AS CIFP_DT_LAST_ANN_FEE,                               -- DATE
  CAST(CIFP_DT_CHRGE_ANN_FEE AS DATE) AS CIFP_DT_CHRGE_ANN_FEE,                             -- DATE
  CAST(ROUND(CIFP_PREV_STAT_BAL, 2) AS NUMERIC) AS CIFP_PREV_STAT_BAL,                      -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PURCH_YTD, 2) AS NUMERIC) AS CIFP_AMT_PURCH_YTD,                      -- NUMBER(13,2)
  CAST(ROUND(CIFP_NUM_PURCH_YTD, 0) AS NUMERIC) AS CIFP_NUM_PURCH_YTD,                      -- NUMBER(7,0)
  CAST(ROUND(CIFP_NUM_PURCH_LIFE, 0) AS NUMERIC) AS CIFP_NUM_PURCH_LIFE,                    -- NUMBER(7,0)
  CAST(ROUND(CIFP_YTD_FIN_CRG_ASES, 2) AS NUMERIC) AS CIFP_YTD_FIN_CRG_ASES,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_YTD_FIN_CRG_PAID, 2) AS NUMERIC) AS CIFP_YTD_FIN_CRG_PAID,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_MINIMUM_PAY_DUE, 2) AS NUMERIC) AS CIFP_MINIMUM_PAY_DUE,                  -- NUMBER(13,2)
  CAST(ROUND(CIFP_HIGH_BALANCE, 2) AS NUMERIC) AS CIFP_HIGH_BALANCE,                        -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_ACT_CRG_OFF, 2) AS NUMERIC) AS CIFP_AMT_ACT_CRG_OFF,                  -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_1_30, 2) AS NUMERIC) AS CIFP_AMT_PDUE_1_30,                      -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_31_60, 2) AS NUMERIC) AS CIFP_AMT_PDUE_31_60,                    -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_61_90, 2) AS NUMERIC) AS CIFP_AMT_PDUE_61_90,                    -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_91_120, 2) AS NUMERIC) AS CIFP_AMT_PDUE_91_120,                  -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_121_150, 2) AS NUMERIC) AS CIFP_AMT_PDUE_121_150,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_151_180, 2) AS NUMERIC) AS CIFP_AMT_PDUE_151_180,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_181_210, 2) AS NUMERIC) AS CIFP_AMT_PDUE_181_210,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_211_240, 2) AS NUMERIC) AS CIFP_AMT_PDUE_211_240,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_241_270, 2) AS NUMERIC) AS CIFP_AMT_PDUE_241_270,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_PDUE_271_UP, 2) AS NUMERIC) AS CIFP_AMT_PDUE_271_UP,                  -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMT_OUT_AUTH, 2) AS NUMERIC) AS CIFP_AMT_OUT_AUTH,                        -- NUMBER(13,2)
  CAST(ROUND(CIFP_NUM_PDUE_1_30, 0) AS NUMERIC) AS CIFP_NUM_PDUE_1_30,                      -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_31_60, 0) AS NUMERIC) AS CIFP_NUM_PDUE_31_60,                    -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_61_90, 0) AS NUMERIC) AS CIFP_NUM_PDUE_61_90,                    -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_91_120, 0) AS NUMERIC) AS CIFP_NUM_PDUE_91_120,                  -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_121_150, 0) AS NUMERIC) AS CIFP_NUM_PDUE_121_150,                -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_151_180, 0) AS NUMERIC) AS CIFP_NUM_PDUE_151_180,                -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_181_210, 0) AS NUMERIC) AS CIFP_NUM_PDUE_181_210,                -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_211_240, 0) AS NUMERIC) AS CIFP_NUM_PDUE_211_240,                -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_241_270, 0) AS NUMERIC) AS CIFP_NUM_PDUE_241_270,                -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_PDUE_271_UP, 0) AS NUMERIC) AS CIFP_NUM_PDUE_271_UP,                  -- NUMBER(3,0)
  CAST(CIFP_DATE_LAST_PDUE AS DATE) AS CIFP_DATE_LAST_PDUE,                                 -- DATE
  CAST(ROUND(CIFP_OVERLIMIT, 2) AS NUMERIC) AS CIFP_OVERLIMIT,                              -- NUMBER(13,2)
  CAST(ROUND(CIFP_TIMES_DEL_LIFE, 0) AS NUMERIC) AS CIFP_TIMES_DEL_LIFE,                    -- NUMBER(5,0)
  CAST(ROUND(CIFP_AVG_DEL_AMT_MONTH, 2) AS NUMERIC) AS CIFP_AVG_DEL_AMT_MONTH,              -- NUMBER(13,2)
  CAST(ROUND(CIFP_ADB, 2) AS NUMERIC) AS CIFP_ADB,                                          -- NUMBER(13,2)
  CAST(ROUND(CIFP_PUR_TAPPC, 2) AS NUMERIC) AS CIFP_PUR_TAPPC,                              -- NUMBER(13,2)
  CAST(ROUND(CIFP_CUR_SERV_CHRG_CTD, 2) AS NUMERIC) AS CIFP_CUR_SERV_CHRG_CTD,              -- NUMBER(13,2)
  CAST(ROUND(CIFP_CUR_CASH_ADV_CTD, 2) AS NUMERIC) AS CIFP_CUR_CASH_ADV_CTD,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_NUM_OF_PUR_CTD, 0) AS NUMERIC) AS CIFP_NUM_OF_PUR_CTD,                    -- NUMBER(7,0)
  CAST(ROUND(CIFP_NUM_OF_TRANS_FEE_CTD, 0) AS NUMERIC) AS CIFP_NUM_OF_TRANS_FEE_CTD,        -- NUMBER(7,0)
  CAST(ROUND(CIFP_SCE0_CB_SCORE, 0) AS NUMERIC) AS CIFP_SCE0_CB_SCORE,                      -- NUMBER(5,0)
  CAST(CIFP_SCE0_DATE_CB_SCORE AS DATE) AS CIFP_SCE0_DATE_CB_SCORE,                         -- DATE
  CAST(ROUND(CIFP_UNP_FIN_CHRG_CTD, 2) AS NUMERIC) AS CIFP_UNP_FIN_CHRG_CTD,                -- NUMBER(13,2)
  CAST(ROUND(CIFP_YTD_LATE_FEES_ASSES, 2) AS NUMERIC) AS CIFP_YTD_LATE_FEES_ASSES,          -- NUMBER(13,2)
  CAST(ROUND(CIFP_YTD_OVERLIMIT_FEE_AS, 2) AS NUMERIC) AS CIFP_YTD_OVERLIMIT_FEE_AS,        -- NUMBER(13,2)
  CAST(ROUND(CIFP_YTD_CASH_ADV_FEE_AS, 0) AS NUMERIC) AS CIFP_YTD_CASH_ADV_FEE_AS,          -- NUMBER(7,0)
  CAST(CIFP_TRIAD_SCORE_DATE AS DATE) AS CIFP_TRIAD_SCORE_DATE,                             -- DATE
  CAST(CIFP_LAST_REAGE_DATE AS DATE) AS CIFP_LAST_REAGE_DATE,                               -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_LAST_REAGE_TYPE AS BYTES), 1, 1)) AS CIFP_LAST_REAGE_TYPE,           -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_DISCLOSURE_GROUP AS BYTES), 1, 8)) AS CIFP_DISCLOSURE_GROUP,         -- VARCHAR2(8 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_ACQUISITION_CODE AS BYTES), 1, 6)) AS CIFP_ACQUISITION_CODE,         -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_ANNUAL_FEE_OV_REAS AS BYTES), 1, 2)) AS CIFP_ANNUAL_FEE_OV_REAS,     -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_PROF_GRADE AS BYTES), 1, 1)) AS CIFP_PROF_GRADE,                     -- VARCHAR2(1 BYTE)
  CAST(ROUND(CIFP_CONS_BILL_PASTDUE, 0) AS NUMERIC) AS CIFP_CONS_BILL_PASTDUE,              -- NUMBER(3,0)
  CAST(ROUND(CIFP_CONS_DAYS_PASTDUE, 0) AS NUMERIC) AS CIFP_CONS_DAYS_PASTDUE,              -- NUMBER(3,0)
  CAST(ROUND(CIFP_AMOUNT_CYCLE_1P_OUT, 2) AS NUMERIC) AS CIFP_AMOUNT_CYCLE_1P_OUT,          -- NUMBER(13,2)
  CAST(ROUND(CIFP_AMOUNT_UNPAID_FEES, 2) AS NUMERIC) AS CIFP_AMOUNT_UNPAID_FEES,            -- NUMBER(13,2)
  CAST(CIFP_APP_ENTRY_DT AS DATE) AS CIFP_APP_ENTRY_DT,                                     -- DATE
  CAST(CIFP_CS_STAT_DT AS DATE) AS CIFP_CS_STAT_DT,                                         -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_ALT_DISCLOSURE_GRP AS BYTES), 1, 8)) AS CIFP_ALT_DISCLOSURE_GRP,     -- VARCHAR2(8 BYTE)
  CAST(ROUND(CIFP_CASH_AVAILABLE, 0) AS NUMERIC) AS CIFP_CASH_AVAILABLE,                    -- NUMBER(11,0)
  CAST(ROUND(CIFP_CASH_LIMIT, 2) AS NUMERIC) AS CIFP_CASH_LIMIT,                            -- NUMBER(13,2)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_MULTI_CARD_NUM_IND AS BYTES), 1, 1)) AS CIFP_MULTI_CARD_NUM_IND,    -- VARCHAR2(1 BYTE)
  CAST(ROUND(CIFP_OPT_SET_TRAN_REBATE, 0) AS NUMERIC) AS CIFP_OPT_SET_TRAN_REBATE,          -- NUMBER(3,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_TYPEC_EMPLOYEE AS BYTES), 1, 2)) AS CIFP_TYPEC_EMPLOYEE,            -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_BK_DISCLOSURE_GRP AS BYTES), 1, 8)) AS CIFP_BK_DISCLOSURE_GRP,       -- VARCHAR2(8 BYTE)
  CAST(ROUND(CIFP_BALANCE_CURRENT_1ST, 2) AS NUMERIC) AS CIFP_BALANCE_CURRENT_1ST,          -- NUMBER(13,2)
  CAST(ROUND(CIFP_TRIAD_SCORE_ALIGNED, 0) AS NUMERIC) AS CIFP_TRIAD_SCORE_ALIGNED,          -- NUMBER(3,0)
  CAST(ROUND(CIFP_AMT_CURRENT_OUT, 2) AS NUMERIC) AS CIFP_AMT_CURRENT_OUT,                  -- NUMBER(13,2)
  CAST(CIFP_DATE_POLICY_MAINT AS DATE) AS CIFP_DATE_POLICY_MAINT,                           -- DATE
  CAST(CIFP_DATE_NOTIFICATION AS DATE) AS CIFP_DATE_NOTIFICATION,                           -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_PRIVACY_POLICY_1 AS BYTES), 1, 1)) AS CIFP_PRIVACY_POLICY_1,        -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_PRIVACY_POLICY_2 AS BYTES), 1, 1)) AS CIFP_PRIVACY_POLICY_2,        -- VARCHAR2(1 BYTE)
  CAST(ROUND(CIFP_AMT_LAST_CASH, 2) AS NUMERIC) AS CIFP_AMT_LAST_CASH,                      -- NUMBER(13,2)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_BILL_STMT_AT_CYCLE AS BYTES), 1, 1)) AS CIFP_BILL_STMT_AT_CYCLE,    -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_PASTDUE_AT_CYCLE AS BYTES), 1, 1)) AS CIFP_PASTDUE_AT_CYCLE,        -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATC_TRANSFER AS BYTES), 1, 2)) AS CIFP_STATC_TRANSFER,            -- VARCHAR2(2 BYTE)
  CAST(ROUND(CIFP_REQUEST_LMT, 0) AS NUMERIC) AS CIFP_REQUEST_LMT,                          -- NUMBER(11,0)
  CAST(CIFP_APP_RECD_DT AS DATE) AS CIFP_APP_RECD_DT,                                       -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CODE_83 AS BYTES), 1, 8)) AS CIFP_CODE_83,                          -- VARCHAR2(8 BYTE)
  CAST(ROUND(CIFP_OPT_SET_CONV_CK, 0) AS NUMERIC) AS CIFP_OPT_SET_CONV_CK,                  -- NUMBER(2,0)
  CAST(ROUND(CIFP_OPT_SET_CSRW, 0) AS NUMERIC) AS CIFP_OPT_SET_CSRW,                        -- NUMBER(3,0)
  CAST(CIFP_DATE_RE_SCHED_OVRD AS DATE) AS CIFP_DATE_RE_SCHED_OVRD,                         -- DATE
  CAST(CIFP_DATE_RE_ACTION AS DATE) AS CIFP_DATE_RE_ACTION,                                 -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REISSUE_ACTION1 AS BYTES), 1, 2)) AS CIFP_REISSUE_ACTION1,          -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_OPER_RE_ACTION AS BYTES), 1, 6)) AS CIFP_OPER_RE_ACTION,            -- VARCHAR2(6 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_RE_OVRD_OPERATOR AS BYTES), 1, 6)) AS CIFP_RE_OVRD_OPERATOR,        -- VARCHAR2(6 BYTE)
  CAST(CIFP_DTE_LST_FEAT_OS_MNT AS DATE) AS CIFP_DTE_LST_FEAT_OS_MNT,                      -- DATE
  CAST(CIFP_DTE_EXP_ACCT_PRIOR_CD AS DATE) AS CIFP_DTE_EXP_ACCT_PRIOR_CD,                   -- DATE
  CAST(CIFP_DTE_LST_RE_EVAL AS DATE) AS CIFP_DTE_LST_RE_EVAL,                               -- DATE
  CAST(CIFP_DTE_NXT_RE_EVAL AS DATE) AS CIFP_DTE_NXT_RE_EVAL,                               -- DATE
  CAST(CIFP_DTE_LST_FINANCIAL_ACT AS DATE) AS CIFP_DTE_LST_FINANCIAL_ACT,                   -- DATE
  CAST(CIFP_DTE_LST_NSF_PYMT AS DATE) AS CIFP_DTE_LST_NSF_PYMT,                             -- DATE
  CAST(ROUND(CIFP_NUM_AUTO_REAGE_LTD, 0) AS NUMERIC) AS CIFP_NUM_AUTO_REAGE_LTD,            -- NUMBER(3,0)
  CAST(ROUND(CIFP_NUM_MAN_REAGE_LTD, 0) AS NUMERIC) AS CIFP_NUM_MAN_REAGE_LTD,              -- NUMBER(3,0)
  CAST(CIFP_DTE_MAN_PSTDUE_REAGE AS DATE) AS CIFP_DTE_MAN_PSTDUE_REAGE,                     -- DATE
  CAST(ROUND(CIFP_RE_STRATEGY_ID, 0) AS NUMERIC) AS CIFP_RE_STRATEGY_ID,                    -- NUMBER(3,0)
  CAST(ROUND(CIFP_RE_SCENARIO_ID, 0) AS NUMERIC) AS CIFP_RE_SCENARIO_ID,                    -- NUMBER(5,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_FRD_ASSGNMNT_IND AS BYTES), 1, 2)) AS CIFP_FRD_ASSGNMNT_IND,        -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_TRIAD_FLAG AS BYTES), 1, 1)) AS CIFP_TRIAD_FLAG,                    -- VARCHAR2(1 BYTE)
  CAST(ROUND(CIFP_RE_REVIEW_PERIOD, 0) AS NUMERIC) AS CIFP_RE_REVIEW_PERIOD,                -- NUMBER(1,0)
  CAST(ROUND(CIFP_INCURRENT_IND, 0) AS NUMERIC) AS CIFP_INCURRENT_IND,                      -- NUMBER(1,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_45 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_45,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_46 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_46,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_47 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_47,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_48 AS BYTES), 1, 4)) AS CIFP_CUSTOM_DATA_48,           -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_ODP_FLAG AS BYTES), 1, 1)) AS CIFP_ODP_FLAG,                        -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATC_RETURN_MAIL AS BYTES), 1, 2)) AS CIFP_STATC_RETURN_MAIL,      -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATF_ACTIVE_TODAY AS BYTES), 1, 1)) AS CIFP_STATF_ACTIVE_TODAY,    -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_PRIVACY_POLICY_IND AS BYTES), 1, 1)) AS CIFP_PRIVACY_POLICY_IND,    -- VARCHAR2(1 BYTE)
  CAST(CIFP_DATE_MONEY_AVAIL_CHG AS DATE) AS CIFP_DATE_MONEY_AVAIL_CHG,                     -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_LEGAL AS BYTES), 1, 2)) AS CIFP_LEGAL,                               -- VARCHAR2(2 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_94 AS BYTES), 1, 9)) AS CIFP_CUSTOM_DATA_94,           -- VARCHAR2(9 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_CUSTOM_DATA_96 AS BYTES), 1, 9)) AS CIFP_CUSTOM_DATA_96,           -- VARCHAR2(9 BYTE)
  CAST(CIFP_DATE_PAYMENT_DUE AS DATE) AS CIFP_DATE_PAYMENT_DUE,                             -- DATE
  CAST(ROUND(CIFP_INSURANCE_OPTION_SET, 0) AS NUMERIC) AS CIFP_INSURANCE_OPTION_SET,        -- NUMBER(3,0)
  CAST(ROUND(CIFP_CB_RISK_SCORE_ORG, 0) AS NUMERIC) AS CIFP_CB_RISK_SCORE_ORG,              -- NUMBER(5,0)
  CAST(ROUND(CIFP_ACTUAL_DAYS_PASTDUE, 0) AS NUMERIC) AS CIFP_ACTUAL_DAYS_PASTDUE,          -- NUMBER(5,0)
  CAST(CIFP_CUST_SERV_PREV_REAGE_DATE AS DATE) AS CIFP_CUST_SERV_PREV_REAGE_DATE,           -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_FILLER AS BYTES), 1, 4)) AS CIFP_FILLER,                           -- VARCHAR2(4 BYTE)
  CAST(ROUND(CIFP_STATUS_COUNT, 0) AS NUMERIC) AS CIFP_STATUS_COUNT,                        -- NUMBER(3,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_01 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_01,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_01 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_01,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_02 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_02,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_02 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_02,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_03 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_03,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_03 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_03,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_04 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_04,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_04 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_04,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_05 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_05,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_05 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_05,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_06 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_06,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_06 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_06,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_07 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_07,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_07 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_07,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_08 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_08,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_08 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_08,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_09 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_09,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_09 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_09,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_10 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_10,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_10 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_10,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_11 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_11,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_11 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_11,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_12 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_12,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_12 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_12,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_13 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_13,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_13 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_13,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_14 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_14,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_14 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_14,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_15 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_15,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_15 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_15,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_16 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_16,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_16 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_16,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_17 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_17,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_17 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_17,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_18 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_18,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_18 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_18,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_19 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_19,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_19 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_19,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_20 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_20,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_20 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_20,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_21 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_21,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_21 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_21,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_22 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_22,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_22 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_22,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_23 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_23,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_23 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_23,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_24 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_24,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_24 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_24,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_25 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_25,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_25 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_25,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_26 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_26,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_26 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_26,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_27 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_27,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_27 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_27,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_28 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_28,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_28 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_28,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_29 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_29,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_29 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_29,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_30 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_30,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_30 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_30,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_31 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_31,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_31 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_31,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_32 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_32,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_32 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_32,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_33 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_33,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_33 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_33,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_34 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_34,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_34 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_34,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_35 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_35,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_35 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_35,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_36 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_36,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_36 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_36,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_37 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_37,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_37 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_37,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_38 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_38,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_38 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_38,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_39 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_39,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_39 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_39,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_40 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_40,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_40 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_40,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_41 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_41,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_41 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_41,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_42 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_42,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_42 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_42,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_43 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_43,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_43 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_43,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_44 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_44,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_44 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_44,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_45 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_45,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_45 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_45,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_46 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_46,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_46 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_46,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_47 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_47,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_47 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_47,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_48 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_48,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_48 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_48,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_49 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_49,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_49 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_49,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_50 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_50,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_50 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_50,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_51 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_51,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_51 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_51,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_52 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_52,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_52 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_52,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_53 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_53,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_53 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_53,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_54 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_54,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_54 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_54,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_55 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_55,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_55 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_55,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_56 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_56,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_56 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_56,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_57 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_57,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_57 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_57,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_58 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_58,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_58 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_58,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_59 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_59,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_59 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_59,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_60 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_60,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_60 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_60,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_61 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_61,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_61 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_61,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_62 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_62,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_62 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_62,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_63 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_63,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_63 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_63,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_64 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_64,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_64 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_64,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_65 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_65,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_65 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_65,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_66 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_66,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_66 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_66,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_67 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_67,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_67 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_67,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_68 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_68,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_68 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_68,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_69 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_69,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_69 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_69,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_70 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_70,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_70 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_70,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_71 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_71,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_71 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_71,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_72 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_72,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_72 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_72,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_73 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_73,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_73 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_73,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_74 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_74,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_74 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_74,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_75 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_75,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_75 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_75,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_76 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_76,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_76 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_76,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_77 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_77,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_77 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_77,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_78 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_78,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_78 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_78,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_79 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_79,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_79 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_79,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_80 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_80,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_80 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_80,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_81 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_81,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_81 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_81,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_STATUS_CODE_82 AS BYTES), 1, 2)) AS CIFP_STATUS_CODE_82,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_REASON_CODE_82 AS BYTES), 1, 2)) AS CIFP_REASON_CODE_82,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_FAM_CARD_OPTION AS BYTES), 1, 4)) AS CIFP_FAM_CARD_OPTION,           -- VARCHAR2(4 BYTE)
  CAST(CIFP_DATE_LAST_FAM_CARD_MAINT AS DATE) AS CIFP_DATE_LAST_FAM_CARD_MAINT,             -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_SPEND_LIMITS_IND AS BYTES), 1, 1)) AS CIFP_SPEND_LIMITS_IND,         -- VARCHAR2(1 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_FAM_CARD_MAINT_TDY AS BYTES), 1, 1)) AS CIFP_FAM_CARD_MAINT_TDY,     -- VARCHAR2(1 BYTE)
  CAST(CIFP_AM0F_AWD_ENROLL_DATE AS DATE) AS CIFP_AM0F_AWD_ENROLL_DATE,                     -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_EBPP_OPT_SET AS BYTES), 1, 4)) AS CIFP_EBPP_OPT_SET,                -- VARCHAR2(4 BYTE)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_PROFIT_CENTER AS BYTES), 1, 10)) AS CIFP_PROFIT_CENTER,              -- VARCHAR2(10 BYTE)
  CAST(CIFP_EBPP_ENROLMNT_DATE AS DATE) AS CIFP_EBPP_ENROLMNT_DATE,                        -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_EBPP_ENROLMNT_IND AS BYTES), 1, 1)) AS CIFP_EBPP_ENROLMNT_IND,      -- VARCHAR2(1 BYTE)
  CAST(ROUND(CIFP_SCE0_CB_SCORE_FIRST, 0) AS NUMERIC) AS CIFP_SCE0_CB_SCORE_FIRST,         -- NUMBER(5,0)
  CAST(ROUND(CIFP_SCE0_CB_SCORE_LAST, 0) AS NUMERIC) AS CIFP_SCE0_CB_SCORE_LAST,           -- NUMBER(5,0)
  CAST(ROUND(CIFP_SPID_TYPE5, 0) AS NUMERIC) AS CIFP_SPID_TYPE5,                           -- NUMBER(3,0)
  CAST(ROUND(CIFP_TEST_DIGIT_TYPE5, 0) AS NUMERIC) AS CIFP_TEST_DIGIT_TYPE5,                -- NUMBER(5,0)
  CAST(CIFP_SECONDARY_CHGOFF_DATE AS DATE) AS CIFP_SECONDARY_CHGOFF_DATE,                   -- DATE
  CAST(ROUND(CIFP_COLL_SCENARIO_ID, 0) AS NUMERIC) AS CIFP_COLL_SCENARIO_ID,                -- NUMBER(5,0)
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(CIFP_COLLECTION_AGENCY AS BYTES), 1, 6)) AS CIFP_COLLECTION_AGENCY,     -- VARCHAR2(6 BYTE)
  CAST(CIFP_DT_LAST_CHECK_ORDER AS DATE) AS CIFP_DT_LAST_CHECK_ORDER,                       -- DATE
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ASSIGNOR_LOAN_ASSUM AS BYTES), 1, 2)) AS AM00_STATF_ASSIGNOR_LOAN_ASSUM,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ADDR_CHNG_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_ADDR_CHNG_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ADVANTAGE AS BYTES), 1, 2)) AS AM00_STATF_ADVANTAGE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_ASST_PROGRAM AS BYTES), 1, 2)) AS AM00_STATC_ASST_PROGRAM,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_APPLICATION AS BYTES), 1, 2)) AS AM00_STATC_APPLICATION,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ACTIVE_TODAY AS BYTES), 1, 2)) AS AM00_STATF_ACTIVE_TODAY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ACTIVE_THISCYCLE AS BYTES), 1, 2)) AS AM00_STATF_ACTIVE_THISCYCLE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_BLOCKED_CARDS_CNT AS BYTES), 1, 2)) AS AM00_BLOCKED_CARDS_CNT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_BANKRUPTCY_TYPE AS BYTES), 1, 2)) AS AM00_BANKRUPTCY_TYPE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_BROKEN_PROMISE AS BYTES), 1, 2)) AS AM00_STATF_BROKEN_PROMISE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_BUREAU_DISPUTE AS BYTES), 1, 2)) AS AM00_STATC_BUREAU_DISPUTE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CASH_ACT_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_CASH_ACT_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CREDIT_COUNSELING AS BYTES), 1, 2)) AS AM00_STATF_CREDIT_COUNSELING,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CREDIT_ACTV_TODAY AS BYTES), 1, 2)) AS AM00_STATF_CREDIT_ACTV_TODAY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CHGOFF_LAG AS BYTES), 1, 2)) AS AM00_STATF_CHGOFF_LAG,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CLI_THIS_CYCLE AS BYTES), 1, 2)) AS AM00_STATF_CLI_THIS_CYCLE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CLOSED AS BYTES), 1, 2)) AS AM00_STATC_CLOSED,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_AM0A_STATC_WATCH AS BYTES), 1, 2)) AS AM00_AM0A_STATC_WATCH,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CHARGEOFF AS BYTES), 1, 2)) AS AM00_STATC_CHARGEOFF,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CREDIT_REVOKED AS BYTES), 1, 2)) AS AM00_STATC_CREDIT_REVOKED,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CIT_ACCEPTED AS BYTES), 1, 2)) AS AM00_STATC_CIT_ACCEPTED,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CRV AS BYTES), 1, 2)) AS AM00_STATF_CRV,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_AM0A_STATC_CARD_WATCH AS BYTES), 1, 2)) AS AM00_AM0A_STATC_CARD_WATCH,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CREDIT_ACT_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_CREDIT_ACT_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CLIENT_DEFINED AS BYTES), 1, 2)) AS AM00_STATC_CLIENT_DEFINED,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_DISPUTE_DISAGREE AS BYTES), 1, 2)) AS AM00_STATF_DISPUTE_DISAGREE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_DISPUTE AS BYTES), 1, 2)) AS AM00_STATC_DISPUTE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_DEBIT_ACTV_TODAY AS BYTES), 1, 2)) AS AM00_STATF_DEBIT_ACTV_TODAY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_TYPEC_EMPLOYEE AS BYTES), 1, 2)) AS AM00_TYPEC_EMPLOYEE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ASSOC_EXCP_FILE AS BYTES), 1, 2)) AS AM00_STATF_ASSOC_EXCP_FILE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM0A_STATC_FRAUD_ALERT AS BYTES), 1, 2)) AS AM0A_STATC_FRAUD_ALERT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM0A_STATC_FRAUD_VICTIM AS BYTES), 1, 2)) AS AM0A_STATC_FRAUD_VICTIM,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_FRAUD_AUTH_EXCL AS BYTES), 1, 2)) AS AM00_STATF_FRAUD_AUTH_EXCL,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_FORECLOSURE AS BYTES), 1, 2)) AS AM00_STATC_FORECLOSURE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_FIXED_PAYMENT AS BYTES), 1, 2)) AS AM00_STATC_FIXED_PAYMENT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_FRAUD AS BYTES), 1, 2)) AS AM00_STATF_FRAUD,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_FIRST_USE AS BYTES), 1, 2)) AS AM00_STATC_FIRST_USE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_GUARANTEED_LOAN AS BYTES), 1, 2)) AS AM00_STATF_GUARANTEED_LOAN,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_HIGHLY_ACTIVE AS BYTES), 1, 2)) AS AM00_STATC_HIGHLY_ACTIVE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_ICS AS BYTES), 1, 2)) AS AM00_STATC_ICS,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_INACTIVE AS BYTES), 1, 2)) AS AM00_STATF_INACTIVE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ACTIVE_LAST_YEAR AS BYTES), 1, 2)) AS AM00_STATF_ACTIVE_LAST_YEAR,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_LEGAL AS BYTES), 1, 2)) AS AM00_STATC_LEGAL,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CLM AS BYTES), 1, 2)) AS AM00_STATF_CLM,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_OL_LETTER_OVRIDE AS BYTES), 1, 2)) AS AM00_STATF_OL_LETTER_OVRIDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PD_LETTER_OVRIDE AS BYTES), 1, 2)) AS AM00_STATF_PD_LETTER_OVRIDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_XFER_ANOTHER_LENDE AS BYTES), 1, 2)) AS AM00_STATF_XFER_ANOTHER_LENDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ACTIVE_THIS_MONTH AS BYTES), 1, 2)) AS AM00_STATF_ACTIVE_THIS_MONTH,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_MOC AS BYTES), 1, 2)) AS AM00_STATC_MOC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_OL_STMT_MSG_OVRIDE AS BYTES), 1, 2)) AS AM00_STATF_OL_STMT_MSG_OVRIDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PD_STMT_MSGOVRIDE AS BYTES), 1, 2)) AS AM00_STATF_PD_STMT_MSGOVRIDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_MEMO_POST_TODAY AS BYTES), 1, 2)) AS AM00_STATF_MEMO_POST_TODAY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_MISC_TRANSFER AS BYTES), 1, 2)) AS AM00_STATC_MISC_TRANSFER,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_NEW_ACCT_TDY AS BYTES), 1, 2)) AS AM00_STATF_NEW_ACCT_TDY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_OL_NOTICE_OVRIDE AS BYTES), 1, 2)) AS AM00_STATF_OL_NOTICE_OVRIDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PD_NOTICE_OVRIDE AS BYTES), 1, 2)) AS AM00_STATF_PD_NOTICE_OVRIDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ACTIVE_SINCE_OPENED AS BYTES), 1, 2)) AS AM00_STATF_ACTIVE_SINCE_OPENED,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CURRENT_OVERLIMIT AS BYTES), 1, 2)) AS AM00_STATC_CURRENT_OVERLIMIT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_POTENTIAL_CHARGEOFF AS BYTES), 1, 2)) AS AM00_STATF_POTENTIAL_CHARGEOFF,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CURRENT_PAST_DUE AS BYTES), 1, 2)) AS AM00_STATC_CURRENT_PAST_DUE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PRIOR_CARD_EXP AS BYTES), 1, 2)) AS AM00_STATF_PRIOR_CARD_EXP,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PRODUCT_CHANGE AS BYTES), 1, 2)) AS AM00_STATF_PRODUCT_CHANGE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PAID_BY_DEALER AS BYTES), 1, 2)) AS AM00_STATF_PAID_BY_DEALER,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PMAX_IE AS BYTES), 1, 2)) AS AM00_STATF_PMAX_IE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_POTENTIAL_PURGE AS BYTES), 1, 2)) AS AM00_STATF_POTENTIAL_PURGE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PURCH_REV_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_PURCH_REV_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PAID_BY_COSIGNER AS BYTES), 1, 2)) AS AM00_STATF_PAID_BY_COSIGNER,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PUR_ACT_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_PUR_ACT_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PYMT_ACT_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_PYMT_ACT_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_REFUND_BLOCK AS BYTES), 1, 2)) AS AM00_STATF_REFUND_BLOCK,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CREDIT_REV_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_CREDIT_REV_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_DECLINED_REISSUE AS BYTES), 1, 2)) AS AM00_STATF_DECLINED_REISSUE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_RECENCY AS BYTES), 1, 2)) AS AM00_STATC_RECENCY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_REFINANCED AS BYTES), 1, 2)) AS AM00_STATF_REFINANCED,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_REAGE_MAN AS BYTES), 1, 2)) AS AM00_STATC_REAGE_MAN,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_REAGE_AUTO AS BYTES), 1, 2)) AS AM00_STATC_REAGE_AUTO,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_REINSTATE_CHARGEOFF AS BYTES), 1, 2)) AS AM00_STATF_REINSTATE_CHARGEOFF,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_RETURN_MAIL AS BYTES), 1, 2)) AS AM00_STATC_RETURN_MAIL,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_REISSUE_OVERRIDE AS BYTES), 1, 2)) AS AM00_STATF_REISSUE_OVERRIDE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_REFUSED_TO_PAY AS BYTES), 1, 2)) AS AM00_STATF_REFUSED_TO_PAY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_DLQ AS BYTES), 1, 2)) AS AM00_STATC_DLQ,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_RECOVERY AS BYTES), 1, 2)) AS AM00_STATF_RECOVERY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_REORDER_CHECK_TODAY AS BYTES), 1, 2)) AS AM00_STATF_REORDER_CHECK_TODAY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_PYMT_REV_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_PYMT_REV_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM0A_STATC_SUB_DIFF AS BYTES), 1, 2)) AS AM0A_STATC_SUB_DIFF,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_SECURITY_FRAUD AS BYTES), 1, 2)) AS AM00_STATC_SECURITY_FRAUD,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_SKIP_A_PAYMENT AS BYTES), 1, 2)) AS AM00_STATC_SKIP_A_PAYMENT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_STOP_PMT_ON_FILE AS BYTES), 1, 2)) AS AM00_STATC_STOP_PMT_ON_FILE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_SOLDIER_SAILOR_ACT AS BYTES), 1, 2)) AS AM00_STATF_SOLDIER_SAILOR_ACT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_SKIP_TRACE AS BYTES), 1, 2)) AS AM00_STATF_SKIP_TRACE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_TYPEC_TYPE AS BYTES), 1, 2)) AS AM00_TYPEC_TYPE,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_TERMS_DEFAULT AS BYTES), 1, 2)) AS AM00_STATF_TERMS_DEFAULT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_CO_1099_RPT AS BYTES), 1, 2)) AS AM00_STATC_CO_1099_RPT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_TIERED_AUTH AS BYTES), 1, 2)) AS AM00_STATC_TIERED_AUTH,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CASH_REV_THIS_CYC AS BYTES), 1, 2)) AS AM00_STATF_CASH_REV_THIS_CYC,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_TYPEC_VIP AS BYTES), 1, 2)) AS AM00_TYPEC_VIP,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_CLOS_RVOK_TDY AS BYTES), 1, 2)) AS AM00_STATF_CLOS_RVOK_TDY,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_WATCH AS BYTES), 1, 2)) AS AM00_STATC_WATCH,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_WARNING_BULLETIN AS BYTES), 1, 2)) AS AM00_STATF_WARNING_BULLETIN,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATC_TRANSFER AS BYTES), 1, 2)) AS AM00_STATC_TRANSFER,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_POST_XFR_PAYMENT AS BYTES), 1, 2)) AS AM00_STATF_POST_XFR_PAYMENT,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ACTIVE_THIS_YEAR AS BYTES), 1, 2)) AS AM00_STATF_ACTIVE_THIS_YEAR,
  SAFE_CONVERT_BYTES_TO_STRING(SUBSTR(CAST(AM00_STATF_ACCT_CYCLED_TODAY AS BYTES), 1, 2)) AS AM00_STATF_ACCT_CYCLED_TODAY

FROM
  pcb-{env}-landing.domain_account_management.CIF_ACCOUNT_CURR
WHERE
    file_create_dt = '{file_create_dt}'