CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.CIF_ACCOUNT_PREV_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  NULL as EXECUTION_ID,
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  REC_LOAD_TIMESTAMP AS REC_LOAD_DT_TM_STAMP,
  * EXCEPT (FILE_CREATE_DT,REC_LOAD_TIMESTAMP)
FROM
  pcb-{env}-landing.domain_account_management.CIF_ACCOUNT_PREV