CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.EVENTS_TEMP
OPTIONS (
expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  REC_LOAD_TIMESTAMP AS REC_LOAD_DT_TM_STAMP,
  * EXCEPT (FILE_CREATE_DT,REC_LOAD_TIMESTAMP)

FROM
  pcb-{env}-landing.domain_account_management.EVENTS
WHERE
    file_create_dt = '{file_create_dt}'