CREATE OR REPLACE TABLE pcb-{env}-processing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM04_S_TEMP
CLUSTER BY
MAST_ACCOUNT_ID,
AM00_APPLICATION_SUFFIX
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AM00_CLIENT_NUM,
  AM00_APPLICATION_NUM,
  AM00_APPLICATION_SUFFIX,
  AM04_SEGMENT_LENGTH,
  AM04_POP_SEGMENT_CODE,
  AM04_SEGMENT_SEQ,
  AM04_POP_SEGMENT_DATA,
  AM04_DATE_LAST_INTO_PD_CATEG_1,
  AM04_DATE_LAST_INTO_PD_CATEG_2,
  AM04_DATE_LAST_INTO_PD_CATEG_3,
  AM04_DATE_LAST_INTO_PD_CATEG_4,
  AM04_DATE_LAST_INTO_PD_CATEG_5,
  AM04_DATE_LAST_INTO_PD_CATEG_6,
  AM04_DATE_LAST_INTO_PD_CATEG_7,
  AM04_DATE_LAST_INTO_PD_CATEG_8,
  AM04_DATE_LAST_INTO_PD_CATEG_9,
  AM04_DATE_LAST_INTO_PD_CATEG10,
  AM04_DATE_LAST_INTO_PD_CATEG11,
  AM04_DATE_LAST_INTO_PD_CATEG12,
  AM04_MIN_PD_AT_PAY_DD_1,
  AM04_MIN_PD_AT_PAY_DD_2,
  AM04_MIN_PD_AT_PAY_DD_3,
  AM04_MIN_PD_AT_PAY_DD_4,
  AM04_MIN_PD_AT_PAY_DD_5,
  AM04_MIN_PD_AT_PAY_DD_6,
  AM04_MIN_PD_AT_PAY_DD_7,
  AM04_MIN_PD_AT_PAY_DD_8,
  AM04_MIN_PD_AT_PAY_DD_9,
  AM04_MIN_PD_AT_PAY_DD_10,
  AM04_MIN_PD_AT_PAY_DD_11,
  AM04_MIN_PD_AT_PAY_DD_12
FROM
  pcb-{env}-landing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM04_S
WHERE
  FILE_CREATE_DT = '{file_create_dt}';
