CREATE OR REPLACE TABLE `pcb-{env}-processing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM0A_TEMP`
CLUSTER BY
MAST_ACCOUNT_ID,
AM00_APPLICATION_SUFFIX
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_ACCOUNT_ID,
  MAST_REC_TYPE,
  AM00_CLIENT_NUM,
  AM00_APPLICATION_NUM,
  AM00_APPLICATION_SUFFIX,
  * EXCEPT (
    FILE_CREATE_DT,
    REC_LOAD_TIMESTAMP,
    MAST_ACCOUNT_ID,
    MAST_REC_TYPE,
    AM00_CLIENT_NUM,
    AM00_APPLICATION_NUM,
    AM00_APPLICATION_SUFFIX
  )
FROM
  pcb-{env}-landing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM0A
WHERE
  FILE_CREATE_DT = '{file_create_dt}';
