CREATE OR REPLACE TABLE pcb-{env}-processing.domain_customer_management.TSYS_PCB_MC_CUSTMASTER_MONTHLY_CM01_TEMP
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_customer_management.TSYS_PCB_MC_CUSTMASTER_MONTHLY_CM00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_CUSTOMER_ID,
  MAST_REC_TYPE,
  7607 AS CM00_CLIENT_NUM,
  MAST_CUSTOMER_ID AS CM00_CUSTOMER_ID,
  * EXCEPT (FILE_CREATE_DT, REC_LOAD_TIMESTAMP, MAST_CUSTOMER_ID, MAST_REC_TYPE)
FROM
  pcb-{env}-landing.domain_customer_management.TSYS_PCB_MC_CUSTMASTER_MONTHLY_CM01
WHERE
  FILE_CREATE_DT = '{file_create_dt}';