CREATE OR REPLACE TABLE pcb-{env}-processing.domain_customer_management.TSYS_PCB_MC_CUSTMASTER_MONTHLY_CM05_TEMP
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 12 HOUR)
)
AS
SELECT
  EXTRACT(YEAR FROM FILE_CREATE_DT) AS YYYY,
  EXTRACT(MONTH FROM FILE_CREATE_DT) AS MM,
  EXTRACT(DAY FROM FILE_CREATE_DT) AS DD,
  (select MAX(REC_LOAD_DT_TM_STAMP) FROM pcb-{env}-processing.domain_customer_management.TSYS_PCB_MC_CUSTMASTER_MONTHLY_CM00_TEMP ) AS REC_LOAD_DT_TM_STAMP,
  MAST_CUSTOMER_ID,
  MAST_REC_TYPE,
  7607 AS CM00_CLIENT_NUM,
  MAST_CUSTOMER_ID AS CM00_CUSTOMER_ID,
  CM05_SEGMENT_LENGTH,
  CM05_CHECKING2,
  CM05_CHECKING3,
  CM05_SAVINGS2,
  CM05_FINANCIAL_RELATIONSHIPS,
  CM05_TAX_ID_NUM,
  CM05_HOME_TYPE_CODE,
  CM05_HOBBIES,
  CM05_BANKRUPTCY_STAGE_FIELD,
  CM05_PERSONAL_DECEASED_FLAG,
  CM05_STATE_BANKRUPTCY_FILED,
  CM05_MARITAL_STATUS,
  CM05_BANKRUPTCY_TYPE,
  CM05_SAV2_DATE_LAST_MAINTENANCE AS CM05_SAV2_DATE_LAST_MAINT,
  CM05_DDA2_DATE_LAST_MAINTENANCE AS CM05_DDA2_DATE_LAST_MAINT,
  CM05_DDA3_DATE_LAST_MAINTENANCE AS CM05_DDA3_DATE_LAST_MAINT,
  * EXCEPT (
    FILE_CREATE_DT, REC_LOAD_TIMESTAMP, MAST_CUSTOMER_ID, MAST_REC_TYPE,
    CM05_SEGMENT_LENGTH, CM05_CHECKING2, CM05_CHECKING3, CM05_SAVINGS2,
    CM05_FINANCIAL_RELATIONSHIPS, CM05_TAX_ID_NUM, CM05_HOME_TYPE_CODE, CM05_HOBBIES,
    CM05_BANKRUPTCY_STAGE_FIELD, CM05_PERSONAL_DECEASED_FLAG, CM05_STATE_BANKRUPTCY_FILED,
    CM05_MARITAL_STATUS, CM05_BANKRUPTCY_TYPE,
    CM05_SAV2_DATE_LAST_MAINTENANCE, CM05_DDA2_DATE_LAST_MAINTENANCE, CM05_DDA3_DATE_LAST_MAINTENANCE
  )
FROM
  pcb-{env}-landing.domain_customer_management.TSYS_PCB_MC_CUSTMASTER_MONTHLY_CM05
WHERE
  FILE_CREATE_DT = '{file_create_dt}';
