CREATE OR REPLACE TABLE
  `{staging_table_id}`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
) AS
WITH
  TMX_CODE AS (
  SELECT
    DISTINCT A.ACCOUNT_NUMBER AS CARD_NUMBER,
    A.POS_ENTRY_MODE AS EVENT_TYPE,
    A.RESPONSE_CODE,
    CONCAT(A.MERCHANT_CITY, A.TERMINAL_ID) AS FRAUD_RISK_ASSESMENT_UID,
    DATE(A.TRANS_DATE_YYYYDDMM) AS EVENTDATE,
    PARSE_TIME('%H%M%S', LPAD(CAST(TRANS_TIME_HHMMSS AS STRING), 6, '0')) AS EVENTTIME,
    CASE
      /* USED TO CLASSIFY ATO FRAUD*/
      WHEN ((CA.FRAUD_TYPE_1 = '5' AND NOT CA.FRAUD_TYPE_2 IN ('6', '7') ) OR CA.FRAUD_TYPE_2 = '5') AND B.CURRENT_FRAUD_FLAG = 'Y' THEN 'account_takeover'
      /* USED TO CLASSIFY FA FRAUD */
      WHEN (CA.FRAUD_TYPE_1 = '3'
      OR CA.FRAUD_TYPE_2 = '3') THEN 'identity_fraud_stolen_credentials'
      /* USED TO CLASSIFY FIRST PARTY/SYNTHETIC FRAUD */
      WHEN (CA.FRAUD_TYPE_1 = '5' AND CA.FRAUD_TYPE_2 = '7') THEN 'sythentic_identity'
      ELSE NULL
  END
    AS EVENT_CLASSIFICATION,
  FROM
    /* TABLE HOLDS NON MONETARY RECORDS  */
    `pcb-{env}-curated.domain_fraud.CARDGUARD_AUTHLOG` A
  LEFT JOIN (
    SELECT
      DISTINCT a.ACCOUNT_NUMBER AS CRDNO,
      a.TRANSACTION_DATE,
      a.AUTH_LOG_TIME,
      a.MERCHANT_CLASS,
      a.TRANSACTION_AMOUNT AS TXN_AMT,
      a.MESSAGE_TYPE,
      a.CURRENT_FRAUD_FLAG,
      a.OPERATOR_ID,
      a.TRANSACTION_ID,
      a.REC_LOAD_TIMESTAMP
    FROM
      `pcb-{env}-curated.domain_fraud.CARDGUARD_FRAUDFLAG` a,
      /* USED TO PULL MOST RECENT TAGGED EVENT */
      (SELECT
        DISTINCT ACCOUNT_NUMBER,
        TRANSACTION_DATE,
        AUTH_LOG_TIME,
        MERCHANT_CLASS,
        TRANSACTION_AMOUNT,
        MESSAGE_TYPE,
        TRANSACTION_ID,
        MAX(REC_LOAD_TIMESTAMP) AS maxload
      FROM
        `pcb-{env}-curated.domain_fraud.CARDGUARD_FRAUDFLAG`
      GROUP BY
        ACCOUNT_NUMBER,
        TRANSACTION_DATE,
        AUTH_LOG_TIME,
        MERCHANT_CLASS,
        TRANSACTION_AMOUNT,
        MESSAGE_TYPE,
        TRANSACTION_ID) b
    WHERE
      a.ACCOUNT_NUMBER = b.ACCOUNT_NUMBER
      AND a.TRANSACTION_DATE = b.TRANSACTION_DATE
      AND a.AUTH_LOG_TIME = b.AUTH_LOG_TIME
      AND a.MERCHANT_CLASS = b.MERCHANT_CLASS
      AND a.TRANSACTION_AMOUNT = b.TRANSACTION_AMOUNT
      AND a.MESSAGE_TYPE = b.MESSAGE_TYPE
      AND a.TRANSACTION_ID = b.TRANSACTION_ID
      AND a.REC_LOAD_TIMESTAMP = b.maxload) B
  ON
    B.CRDNO = A.ACCOUNT_NUMBER
    AND B.TRANSACTION_DATE = A.TRANS_DATE_YYYYDDMM
    AND B.AUTH_LOG_TIME = CAST(LPAD(A.TRANS_TIME_HHMMSS,6, '0') AS NUMERIC)
    AND B.MESSAGE_TYPE = CAST(A.TYPE AS NUMERIC)
  LEFT JOIN
    `pcb-{env}-curated.domain_fraud.CARDGUARD_CASELOG` CA
  ON
    CA.ACCOUNT_NUMBER = A.ACCOUNT_NUMBER
  WHERE {file_create_date_filter}
       )
SELECT
   'content_type'   AS CONTENT_TYPE,
  FR.RequestId as REQUEST_ID,
  'update_review_status' as ACTION,
  'Reject' AS FINAL_REVIEW_STATUS,
   TC.EVENT_CLASSIFICATION,
  'fraud_confirmed' AS EVENT_TAG,
   GENERATE_UUID() AS TRUTHDATAUID
FROM
  TMX_CODE TC
LEFT JOIN `pcb-{env}-landing.domain_fraud_risk_intelligence.FRAUD_RISK_ASSESSMENT_RESPONSE` FR
       ON FR.FraudRiskAssessmentUID = TC.FRAUD_RISK_ASSESMENT_UID
WHERE
  /* USED TO ONLY RETRIEVE CONFIRMED FRAUD EVENTS */
  EVENT_CLASSIFICATION IS NOT NULL
  /* WILL BE USED TO ONLY FILTER TMX NON MONS */
  AND EVENT_TYPE IN ('TP','TD','TF')
  AND RESPONSE_CODE in ('PX');


EXPORT DATA
  OPTIONS (
    uri = 'gs://pcb-{env}-staging-extract/tmx_login_fraud/login-confirmed-fraud-*.parquet',
    format = 'PARQUET',
    overwrite = true
    )
AS
(SELECT
    SAFE_CAST(CONTENT_TYPE AS STRING) AS CONTENT_TYPE,
    SAFE_CAST(REQUEST_ID AS STRING) AS REQUEST_ID,
    SAFE_CAST(ACTION AS STRING) AS ACTION,
    SAFE_CAST(FINAL_REVIEW_STATUS AS STRING) AS FINAL_REVIEW_STATUS,
    SAFE_CAST(EVENT_CLASSIFICATION AS STRING) AS EVENT_CLASSIFICATION,
    SAFE_CAST(EVENT_TAG AS STRING) AS EVENT_TAG,
    SAFE_CAST(TRUTHDATAUID AS STRING) AS TRUTHDATAUID
FROM `{staging_table_id}`);
