CREATE OR REPLACE TABLE `pcb-{env}-landing.domain_account_management.CIF_CARD_XREF`
AS
SELECT
DISTINCT
CIF_CARD_CURR.CIFP_ACCOUNT_NUM,
CIF_CARD_CURR.CIFP_RELATIONSHIP_STAT,
CIF_CARD_CURR.CIFP_ACCOUNT_ID6,
CIF_CARD_CURR.CIFP_CUSTOMER_ID_2,
CIF_CARD_CURR.CIFP_CUSTOMER_TYPE,
CIF_CARD_CURR.CIFP_FIRST_NAME,
CIF_CARD_CURR.CIFP_LAST_NAME,
CIF_CARD_CURR.CIFP_TRANS_FROM_ACCT_NO,
CIF_CARD_CURR.CIFP_TRANS_TO_ACCT_NO,
CIF_CARD_CURR_1.CIFP_ACCOUNT_NUM AS CIFP_ACCOUNT_NUM_PRIM,
CIF_CARD_CURR_1.CIFP_CUSTOMER_ID_2 AS CIFP_CUSTOMER_ID_PRIM,
CIF_CARD_CURR_1.CIFP_FIRST_NAME AS CIFP_FIRST_NAME_PRIM,
CIF_CARD_CURR_1.CIFP_LAST_NAME AS CIFP_LAST_NAME_PRIM,
CIF_CARD_CURR.CIFP_CRV_STATUS,
CIF_CARD_CURR.CIFP_CRV_DATE,
CIF_CARD_CURR.CIFP_SECURITY_FRAUD,
CIF_CARD_CURR.FILE_CREATE_DT,
CURRENT_TIMESTAMP() AS REC_LOAD_TIMESTAMP
from
`pcb-{env}-curated.domain_account_management.CIF_CARD_CURR` CIF_CARD_CURR
INNER JOIN
`pcb-{env}-curated.domain_account_management.CIF_CARD_CURR` CIF_CARD_CURR_1
ON
CIF_CARD_CURR.CIFP_ACCOUNT_ID6 =  CIF_CARD_CURR_1.CIFP_ACCOUNT_ID6
AND
(CIF_CARD_CURR_1.cifp_relationship_stat is null or CIF_CARD_CURR_1.cifp_relationship_stat = 'A')
and CIF_CARD_CURR_1.CIFP_CUSTOMER_TYPE = 0