import logging
import time
from datetime import datetime, timedelta

import pandas as pd
import pendulum
from airflow import DAG, settings
from airflow.exceptions import AirflowException
from airflow.models import DagModel
from airflow.operators.empty import EmptyOperator
from airflow.operators.python import PythonOperator
from airflow.settings import Session

import util.constants as consts
from util.miscutils import (
    read_yamlfile_env,
    read_variable_or_file
)
from dag_factory.terminus_dag_factory import add_tags

"""
  Pause or unpause dags based on dag report (generated by dag_report_generator.py).
"""

logger = logging.getLogger(__name__)

DAG_DEFAULT_ARGS = {
    "owner": "team-centaurs",
    'capability': 'Terminus Data Platform',
    'severity': 'P3',
    'sub_capability': 'Terminus Data Platform',
    'business_impact': 'NA',
    'customer_impact': 'NA',
    "email": [],
    "email_on_failure": False,
    "email_on_retry": False,
    "retries": 3,
    "retry_delay": timedelta(seconds=10),
    "retry_exponential_backoff": True
}


def toggle_dag(session, index: int, dag_id: str, is_paused: bool) -> 1:
    logger.info(f'index={index}, dag_id={dag_id}, is_paused={is_paused}')
    num_toggled = 0
    try:
        d = session.query(DagModel).filter(DagModel.dag_id == dag_id).first()
        if not d:
            logger.info(f"{dag_id} is not found")
            return num_toggled

        logger.info(f'{dag_id}.is_paused={d.is_paused}')
        if d.is_paused != is_paused:
            d.is_paused = is_paused
            session.commit()
            logger.info(f'index={index}, toggle dag {dag_id} from {d.is_paused} to {is_paused}')
            num_toggled = 1
        else:
            logger.info(f'skipped toggling {dag_id}')
    except Exception:
        logger.exception('failed to toggle dag.')
        session.rollback()
    finally:
        session.close()

    return num_toggled


def toggle_all_dags(concurrency_limit: int, interval: int, filter_substr: str = None):
    logger.info(f"""toggle_all_dags with args:
                    concurrency_limit: {concurrency_limit},
                    interval: {interval},
                    filter_substr: {filter_substr}""")
    gcp_config = read_variable_or_file(consts.GCP_CONFIG)
    deploy_env = gcp_config[consts.DEPLOYMENT_ENVIRONMENT_NAME]
    dag_metadata_file = f'gs://pcb-{deploy_env}-staging-extract/operations/dag_metadata.csv'
    df = pd.read_csv(dag_metadata_file, names=['dag_id', 'is_paused', 'timestamp'])
    df = df.reset_index()  # make sure indexes pair with number of rows

    logger.info(f'total num of dags is {len(df.index)}')

    session = Session()
    count = 0
    try:
        for index, row in df.iterrows():
            dag_id = row['dag_id']
            is_paused = row['is_paused']

            logger.info(f'checking {dag_id}')

            if filter_substr and (filter_substr not in dag_id):
                logger.info(f'skipping dag as it does not contain {filter_substr}')
                continue

            num_toggled = 0
            if not is_paused:
                num_toggled = toggle_dag(session, index, dag_id, is_paused)
                count += num_toggled
                logger.info(f'count={count}')
            else:
                logger.info(f'skipping dag as is_paused={is_paused}')

            # just toggled and reach the batch limit
            if (num_toggled == 1) and (count % concurrency_limit == concurrency_limit - 1):
                logger.info(f'index={index}, wait for {interval} seconds')
                time.sleep(interval)
    except Exception:
        logger.exception('failed to toggle dag.')
        session.rollback()
    finally:
        session.close()

    logger.info(f'final count={count}')


def toggle_dags_by_config(is_paused, dag_ids: list, concurrency_limit: int, interval: int):
    if is_paused is None:
        raise AirflowException('Invalid config: is_paused is not set.')

    session = Session()
    count = 0

    try:
        for index, dag_id in enumerate(dag_ids):
            num_toggled = toggle_dag(session, index, dag_id, is_paused)
            count += num_toggled

            logger.info(f'count={count}')

            # just toggled and reach the batch limit
            if (num_toggled == 1) and (count % concurrency_limit == concurrency_limit - 1):
                logger.info(f'index={index}, wait for {interval} seconds')
                time.sleep(interval)
    except Exception:
        logger.exception('failed to toggle dag.')
        session.rollback()
    finally:
        session.close()

    logger.info(f'final count={count}')


def toggle_dags(is_paused, activation_config: dict):
    throttle_config = activation_config.get(consts.THROTTLE)

    concurrency_limit = throttle_config.get(consts.CONCURRENCY_LIMIT)
    interval = throttle_config.get(consts.INTERVAL)

    if not (concurrency_limit and interval):
        raise AirflowException('Invalid config: missed required config items in throttle config.')

    dag_ids = activation_config.get(consts.DAG_IDS)
    filter_substr = activation_config.get(consts.FILTER_SUBSTR)

    if not dag_ids:
        toggle_all_dags(concurrency_limit, interval, filter_substr)
    else:
        toggle_dags_by_config(is_paused, dag_ids, concurrency_limit, interval)


def build_dag(dag_id: str, is_paused, activation_config: dict) -> DAG:
    """
    The majority of our dags submit Spark jobs. When we unpause a large number of dags at the same time,
    we will run out of CPU quotas in the Spark cluster. As a result, the dags will fail.
    To avoid this problem, we want to add throttling into this dag activator. With the throttle config,
    we only unpause one batch dags a time and wait for the specified interval (in seconds)
    before we unpause the next batch. The batch size is configured by throttle_config.concurrency_limit.
    :param dag_id:
    :param is_paused:
    :param activation_config:
    :return:
    """
    dag = DAG(
        dag_id=dag_id,
        default_args=DAG_DEFAULT_ARGS,
        schedule=None,
        start_date=datetime(2024, 1, 1, tzinfo=pendulum.timezone('America/Toronto')),
        catchup=False,
        dagrun_timeout=timedelta(hours=10),
        is_paused_upon_creation=True,
        max_active_tasks=5
    )
    with dag:
        start = EmptyOperator(task_id='start')
        end = EmptyOperator(task_id='end')

        toggle_dags_task = PythonOperator(
            task_id="toggle_dags",
            python_callable=toggle_dags,
            op_kwargs={
                'is_paused': is_paused,
                'activation_config': activation_config
            }
        )

        start >> toggle_dags_task >> end

    return add_tags(dag)


def create_dags() -> dict:
    dags = {}

    config = read_yamlfile_env(f'{settings.DAGS_FOLDER}/config/operations/dag_activation_config.yaml')

    if not config:
        logger.info('Activator config is empty.')
        return dags

    for job_id, activation_config in config.items():
        is_paused = activation_config.get(consts.IS_PAUSED)

        dags[job_id] = build_dag(job_id, is_paused, activation_config)

    return dags


globals().update(create_dags())
