UPDATE `pcb-{env}-landing.domain_retail.GLOBAL_PAYMENT_MERCHANT`
SET VAL = "D", UPDATE_DT = CURRENT_DATE
WHERE MERCHANT_ID NOT IN
(SELECT MERCHANT_ID FROM `pcb-{env}-processing.domain_retail.GLOBAL_PAYMENT_MERCHANT_STAGING`);