MERGE `pcb-{env}-curated.domain_loyalty.LOYALTY_MANUAL_TRANSACTIONS` A
USING (
    SELECT *
    FROM `pcb-{env}-curated.domain_loyalty.LOYALTY_MANUAL_TRANSACTIONS_VW`
    WHERE LENGTH(CARD_NUMBER) <= 19
    AND LENGTH(SAFE_CAST(CARD_BIN AS STRING)) <= 6
    AND LENGTH(SAFE_CAST(CARD_LAST4 AS STRING)) <= 4
    AND LENGTH(SOURCE_CD) <= 5
    AND LENGTH(SAFE_CAST(TRANSACTION_CODE AS STRING)) <= 15
    AND LENGTH(SAFE_CAST(TRANSACTION_AMOUNT AS STRING)) <= 14
    AND LENGTH(MERCHANT_NAME) <= 50
    AND LENGTH(MERCHANT_NUMBER) <= 30
    AND LENGTH(MERCHANT_CATEGORY_CODE) <= 10
    AND LENGTH(MERCHANT_COUNTRY_CODE) <= 5
    AND LENGTH(TRANSACTION_REF_NUMBER) <= 30
    AND LENGTH(PROMO_CODE) <= 10
    AND LENGTH(PROCESS_FLAG) <= 1
    AND LENGTH(PCF_PRD) <= 2
    AND LENGTH(TRANS_REF_ID) <= 15
    AND LENGTH(REC_CHNG_ID) <= 30
) B
ON A.ROW_HASH = B.ROW_HASH
WHEN NOT MATCHED THEN
    INSERT (
        ROW_HASH,
        TSYS_ACCOUNT_ID,
        CARD_NUMBER,
        CARD_BIN,
        CARD_LAST4,
        SOURCE_CD,
        TRANSACTION_DATE,
        TRANSACTION_CODE,
        TRANSACTION_AMOUNT,
        POST_DATE,
        MERCHANT_NAME,
        MERCHANT_NUMBER,
        MERCHANT_CATEGORY_CODE,
        MERCHANT_COUNTRY_CODE,
        TRANSACTION_REF_NUMBER,
        PROMO_CODE,
        PROCESS_FLAG,
        PCF_PRD,
        TRANS_REF_ID,
        REC_CHNG_ID,
        CONSUMED_TIME
    )
    VALUES (
        B.ROW_HASH,
        B.TSYS_ACCOUNT_ID,
        B.CARD_NUMBER,
        B.CARD_BIN,
        B.CARD_LAST4,
        B.SOURCE_CD,
        B.TRANSACTION_DATE,
        B.TRANSACTION_CODE,
        B.TRANSACTION_AMOUNT,
        B.POST_DATE,
        B.MERCHANT_NAME,
        B.MERCHANT_NUMBER,
        B.MERCHANT_CATEGORY_CODE,
        B.MERCHANT_COUNTRY_CODE,
        B.TRANSACTION_REF_NUMBER,
        B.PROMO_CODE,
        B.PROCESS_FLAG,
        B.PCF_PRD,
        B.TRANS_REF_ID,
        B.REC_CHNG_ID,
        null
    )