CREATE
OR REPLACE VIEW `pcb-{env}-curated.domain_loyalty.LOYALTY_MANUAL_TRANSACTIONS_VW` AS
SELECT
    FARM_FINGERPRINT(CONCAT(CAST(CARD_NUMBER AS STRING), '|', CAST(POST_DATE AS STRING), '|',
         CAST(TRANSACTION_AMOUNT AS STRING), '|', MERCHANT_CATEGORY_CODE, '|',
         TRANS_REF_ID)) AS ROW_HASH,
    TSYS_ACCOUNT_ID,
    CARD_NUMBER,
    CARD_BIN,
    CARD_LAST4,
    SOURCE_CD,
    TRANSACTION_DATE,
    TRANSACTION_CODE,
    TRANSACTION_AMOUNT,
    POST_DATE,
    MERCHANT_NAME,
    MERCHANT_NUMBER,
    MERCHANT_CATEGORY_CODE,
    MERCHANT_COUNTRY_CODE,
    TRANSACTION_REF_NUMBER,
    PROMO_CODE,
    PROCESS_FLAG,
    PCF_PRD,
    TRANS_REF_ID,
    REC_CHNG_ID
FROM
    `pcb-{deploy-env}-pds.{pds-dataset}.LOYALTY_MANUAL_TRANSACTIONS_PDS`