UPDATE `pcb-{env}-curated.domain_loyalty.LOYALTY_MANUAL_TRANSACTIONS`
SET ROW_HASH = FARM_FINGERPRINT(CONCAT(CAST(CARD_NUMBER AS STRING), '|', CAST(POST_DATE AS STRING), '|',
     CAST(TRANSACTION_AMOUNT AS STRING), '|', MERCHANT_CATEGORY_CODE, '|',
     TRANS_REF_ID))
WHERE 1=1