BEGIN

DECLARE report_month DATE;

SET report_month = (
  SELECT (get_report_month).report_month
FROM (SELECT `pcb-{env}-landing.domain_scoring.get_report_month`('{report_year}', '{report_month}') AS get_report_month)
);


CREATE TEMP TABLE WK_TSYS_CYCLE1 AS
SELECT DISTINCT
  CAST(ah01.MAST_ACCOUNT_ID AS INTEGER) AS MAST_ACCOUNT_ID,
  ah01.AH01_BALANCE_CURRENT AS STMT_BAL,
  ah01.AH01_LIMIT_CREDIT AS STMT_CRLN,
  ah01.AH01_STMT_MIN_PAYMENT AS TOT_DUE,
  ah01.AH01_AMT_PAYMENTS AS CYC_PYMT,
  ah01.AH01_AMT_PAYMENTS - AH01_AMT_NSF_PAYMENTS AS CYC_PYMT_NET,
  ah01.AH01_WEIGHTED_AVG_APR AS ANN_RATE,
  ah01.AH01_ACTUAL_APR AS ACT_ANN_RATE,
  ah01.AH01_BALANCE_PREV_STATEMENT AS PREV_STMT_BAL,
  DATE(ah01.AH01_DATE_PAYMENT_DUE) AS STMT_DUE_DT,
  CASE
    WHEN ah01.AH01_AMT_PASTDUE_12 > 0 THEN 12
    WHEN ah01.AH01_AMT_PASTDUE_11 > 0 THEN 11
    WHEN ah01.AH01_AMT_PASTDUE_10 > 0 THEN 10
    WHEN ah01.AH01_AMT_PASTDUE_9 > 0 THEN 9
    WHEN ah01.AH01_AMT_PASTDUE_8 > 0 THEN 8
    WHEN ah01.AH01_AMT_PASTDUE_7 > 0 THEN 7
    WHEN ah01.AH01_AMT_PASTDUE_6 > 0 THEN 6
    WHEN ah01.AH01_AMT_PASTDUE_5 > 0 THEN 5
    WHEN ah01.AH01_AMT_PASTDUE_4 > 0 THEN 4
    WHEN ah01.AH01_AMT_PASTDUE_3 > 0 THEN 3
    WHEN ah01.AH01_AMT_PASTDUE_2 > 0 THEN 2
    WHEN ah01.AH01_AMT_PASTDUE_1 > 0 THEN 1
    ELSE 0
END
  AS STMT_PD_STAT,
  DATE_TRUNC(ah01.FILE_CREATE_DT, MONTH) AS PROCESS_DT,
  ah01.AH01_CDATE_CYCLE
FROM
  `pcb-{env}-curated.domain_account_management.AH01` AS ah01
WHERE
  DATE_TRUNC(ah01.FILE_CREATE_DT, MONTH)=DATE_TRUNC(report_month, MONTH)
  AND ah01.AH00_APPLICATION_SUFFIX = 0 ;


CREATE OR REPLACE TABLE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CYCLE` AS
SELECT DISTINCT
  *
FROM (
  SELECT DISTINCT
    *,
    ROW_NUMBER() OVER (PARTITION BY wk_tsys_cycle1.MAST_ACCOUNT_ID ORDER BY wk_tsys_cycle1.AH01_CDATE_CYCLE) AS RN
  FROM
    WK_TSYS_CYCLE1 AS wk_tsys_cycle1)
WHERE
  RN = 1
ORDER BY
  MAST_ACCOUNT_ID ;


-- TSYS_CYC_TRANS
CREATE TEMP TABLE WK_TSYS_CYC_TRANS1 AS
SELECT DISTINCT
  CAST(ah31.MAST_ACCOUNT_ID AS INTEGER) AS MAST_ACCOUNT_ID,
  DATE_TRUNC(ah31.FILE_CREATE_DT, MONTH) AS PROCESS_DT,
  CASE
    WHEN ah31.AH31_TERMS_BALANCE_CODE IN (1, 3) THEN ah31.AH31_AMT_DEBITS_CTD - ah31.AH31_AMT_CREDITS_CTD
END
  AS CYC_MRCH,
  CASE
    WHEN ah31.AH31_TERMS_BALANCE_CODE IN (2) THEN ah31.AH31_AMT_DEBITS_CTD - ah31.AH31_AMT_CREDITS_CTD
END
  AS CYC_CASH
FROM
  `pcb-{env}-curated.domain_account_management.AH31` AS ah31
WHERE
  DATE_TRUNC(ah31.FILE_CREATE_DT, MONTH)=DATE_TRUNC(report_month, MONTH)
  AND ah31.AH00_APPLICATION_SUFFIX = 0
ORDER BY
  ah31.MAST_ACCOUNT_ID ;


CREATE OR REPLACE TABLE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CYC_TRANS` AS
SELECT DISTINCT
  wk_tsys_cyc_trans1.MAST_ACCOUNT_ID,
  wk_tsys_cyc_trans1.PROCESS_DT,
  SUM(wk_tsys_cyc_trans1.CYC_MRCH) AS CYC_MRCH,
  SUM(wk_tsys_cyc_trans1.CYC_CASH) AS CYC_CASH
FROM
  WK_TSYS_CYC_TRANS1 AS wk_tsys_cyc_trans1
GROUP BY
  1,
  2
ORDER BY
  1 ;


CREATE OR REPLACE TABLE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF_FULL` AS
SELECT DISTINCT
  am08.MAST_ACCOUNT_ID,
  am08.AM00_APPLICATION_SUFFIX,
  DATE_TRUNC(am08.FILE_CREATE_DT, MONTH) AS PROCESS_DT,
  DATE(am08.AM08_DATE_CHARGEOFF_COMPLETE) AS CHGOFF_DT,
  am00.AM00_STATC_CHARGEOFF,
  CASE
    WHEN DATE_TRUNC(am08.AM08_DATE_CHARGEOFF_COMPLETE, MONTH)=DATE_TRUNC(report_month, MONTH) AND am00.AM00_STATC_CHARGEOFF IN ('13', '07') THEN am08.AM08_BALANCE_CHARGEOFF
END
  AS BK_AMT,
  CASE
    WHEN DATE_TRUNC(am08.AM08_DATE_CHARGEOFF_COMPLETE, MONTH)=DATE_TRUNC(report_month, MONTH) AND am00.AM00_STATC_CHARGEOFF IN ('BD', 'DC', 'ST') THEN am08.AM08_BALANCE_CHARGEOFF
END
  AS CO_AMT,
  CASE
    WHEN DATE_TRUNC(am08.AM08_DATE_CHARGEOFF_COMPLETE, MONTH)=DATE_TRUNC(report_month, MONTH) AND am00.AM00_STATC_CHARGEOFF IN ('FR') THEN am08.AM08_BALANCE_CHARGEOFF
END
  AS FR_AMT,
  am08.AM08_BALANCE_CHARGEOFF AS ORIG_CHGOFF_AMT
FROM
  `pcb-{env}-curated.domain_account_management.AM08` AS am08
INNER JOIN
  `pcb-{env}-curated.domain_account_management.AM00` AS am00
ON am08.MAST_ACCOUNT_ID  = am00.MAST_ACCOUNT_ID 
WHERE
  DATE_TRUNC(am08.FILE_CREATE_DT, MONTH) = DATE_TRUNC(report_month,MONTH)
  AND (({mode} = "PCMC"
    AND am00.AM00_CLIENT_PRODUCT_CODE NOT LIKE 'PD%'))
  OR (({mode} != "PCMC"
    AND am00.AM00_CLIENT_PRODUCT_CODE LIKE 'PD%'))
  AND am00.AM00_STATC_CHARGEOFF IN ('13',
    '07',
    'BD',
    'DC',
    'ST',
    'FR')
  AND am08.AM08_CHARGEOFF_COMPLETE='C'
  AND am08.FILE_CREATE_DT = am00.FILE_CREATE_DT
  AND am08.MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
  AND am08.AM00_APPLICATION_SUFFIX = am00.AM00_APPLICATION_SUFFIX
ORDER BY
  1,
  2,
  3 ;


CREATE OR REPLACE TABLE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF` AS
SELECT DISTINCT
  *
FROM
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF_FULL` AS wk_tsys_chgoff_full
WHERE
  wk_tsys_chgoff_full.AM00_APPLICATION_SUFFIX=0; 
  
CREATE TEMP TABLE WK_TSYS_CHGOFF_SUFFIX1 AS
SELECT DISTINCT
  *
FROM
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF_FULL` AS wk_tsys_chgoff_full
WHERE
  wk_tsys_chgoff_full.AM00_APPLICATION_SUFFIX>0;


ALTER TABLE
  WK_TSYS_CHGOFF_SUFFIX1
RENAME
  COLUMN BK_AMT TO BK_AMT_SUFFIX;

ALTER TABLE
  WK_TSYS_CHGOFF_SUFFIX1
RENAME
  COLUMN CO_AMT TO CO_AMT_SUFFIX; 


CREATE TEMP TABLE WK_TSYS_CHGOFF_FR1 AS
SELECT DISTINCT
  *
FROM
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF_FULL` AS wk_tsys_chgoff_full
WHERE
  wk_tsys_chgoff_full.FR_AMT IS NOT NULL;


CREATE OR REPLACE TABLE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF_FR` AS
SELECT DISTINCT
  wk_tsys_chgoff_fr1.MAST_ACCOUNT_ID,
  wk_tsys_chgoff_fr1.PROCESS_DT,
  SUM(wk_tsys_chgoff_fr1.FR_AMT) AS FR_AMT,
  COUNT(wk_tsys_chgoff_fr1.FR_AMT) AS FR_CNT
FROM
  WK_TSYS_CHGOFF_FR1 AS wk_tsys_chgoff_fr1
GROUP BY
  1,
  2;


CREATE OR REPLACE TABLE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF_SUFFIX` AS
SELECT DISTINCT
  wk_tsys_chgoff_suffix1.MAST_ACCOUNT_ID,
  wk_tsys_chgoff_suffix1.PROCESS_DT,
  SUM(wk_tsys_chgoff_suffix1.BK_AMT_SUFFIX) AS BK_AMT_SUFFIX,
  COUNT(wk_tsys_chgoff_suffix1.BK_AMT_SUFFIX) AS BK_CNT_SUFFIX,
  SUM(wk_tsys_chgoff_suffix1.CO_AMT_SUFFIX) AS CO_AMT_SUFFIX,
  COUNT(wk_tsys_chgoff_suffix1.CO_AMT_SUFFIX) AS CO_CNT_SUFFIX
FROM
  WK_TSYS_CHGOFF_SUFFIX1 AS wk_tsys_chgoff_suffix1
GROUP BY
  1,
  2;
END
