BEGIN

DECLARE report_month DATE;
DECLARE CODE_PREFIX STRING;
DECLARE TRNS_ACCT_FUNC_COND ARRAY<STRING>;

SET CODE_PREFIX = CASE WHEN {mode} = 'PCMA' THEN '100' ELSE '' END;
SET TRNS_ACCT_FUNC_COND = ['PFC','CFC','FCA','FDA','FCV','FDV','CCF','CPF','WCF','WPF']; 


SET report_month = (
  SELECT (get_report_month).report_month
FROM (SELECT `pcb-{env}-landing.domain_scoring.get_report_month`('{report_year}', '{report_month}') AS get_report_month)
);

CREATE OR REPLACE TABLE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_TRANS` AS

-- TRANSACTION TABLE
WITH WK_TSYS_TRANS3 AS (
SELECT DISTINCT
  DATE_TRUNC(at31.FILE_CREATE_DT, MONTH) AS PROCESS_DT,
  DATE(at31.AT31_DATE_POST) AS AT31_DATE_POST,
  CAST(at31.MAST_ACCOUNT_ID AS INTEGER) AS MAST_ACCOUNT_ID,
  at31.AT00_APPLICATION_SUFFIX,
  at31.AT31_DEBIT_CREDIT_INDICATOR,
  at31.AT31_TERMS_BALANCE_CODE,
  at31.AT31_TRANSACTION_CATEGORY,
  at31.AT31_TRANSACTION_CODE,
  at31.AT31_ENHANCEMENT_ID,
  at31.AT31_TRNS_ACCT_FUNC,
  CASE
    WHEN at31.AT31_CURRENCY_CODE = 124 THEN 1
    ELSE 0
END
  AS CDN_IND,
  CASE
    WHEN at31.AT31_TERMS_BALANCE_CODE= CAST(CONCAT(CODE_PREFIX, 2) AS INT64) AND at31.AT31_TRANSACTION_CODE=101 THEN 1
    ELSE 0
END
  AS WRONG_IND,
  -- CONVERT(AT31_MERCHANT_ID,'US7ASCII','WE8ISO8859P1') AS AT31_MERCHANT_ID ,
  at31.AT31_MERCHANT_ID,
  SUM((at31.AT31_INTERCHG_PERCENTAGE_RATE/100)*at31.AT31_AMT_TRANSACTION) AS INTERCHG,
  SUM(at31.AT31_TRAN_MARK_UP_AMT) AS FOREX,
  SUM(at31.AT31_AMT_TRANSACTION) AS TRANS_AMT,
  COUNT(*) AS TRANS_CNT
FROM
  `pcb-{env}-curated.domain_account_management.AT31` AS at31
WHERE
  EXTRACT(YEAR
  FROM
    at31.FILE_CREATE_DT) = EXTRACT(YEAR
  FROM
    DATE(report_month))
  AND EXTRACT(MONTH
  FROM
    at31.FILE_CREATE_DT) = EXTRACT(MONTH
  FROM
    DATE(report_month))
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13
ORDER BY 3,4,1 
),

WK_TSYS_TRANS2 AS (
SELECT DISTINCT
  wk_tsys_trans3.* EXCEPT(FOREX, INTERCHG ),
  wk_tsys_chgoff_full.AM00_APPLICATION_SUFFIX,
  wk_tsys_chgoff_full.AM00_STATC_CHARGEOFF,
  wk_tsys_chgoff_full.CHGOFF_DT,
  CASE
    WHEN wk_tsys_trans3.AT31_DEBIT_CREDIT_INDICATOR='C' THEN -FOREX
    ELSE FOREX
END
  AS FOREX,
  CASE
    WHEN wk_tsys_trans3.AT31_DEBIT_CREDIT_INDICATOR='C' THEN -INTERCHG
    ELSE INTERCHG
END
  AS INTERCHG,
  CASE
    WHEN wk_tsys_trans3.AT31_DEBIT_CREDIT_INDICATOR='C' THEN -TRANS_AMT
    ELSE TRANS_AMT
END
  AS AMT,
  CASE
    WHEN wk_tsys_trans3.AT31_DEBIT_CREDIT_INDICATOR='C' THEN TRANS_AMT
    ELSE -TRANS_AMT
END
  AS AMT2,
  wk_tsys_trans3.TRANS_CNT AS CNT,
FROM
  WK_TSYS_TRANS3 AS wk_tsys_trans3
LEFT JOIN
  `pcb-{env}-landing.domain_scoring.WK_TSYS_CHGOFF_FULL` AS wk_tsys_chgoff_full
ON
  wk_tsys_trans3.MAST_ACCOUNT_ID = wk_tsys_chgoff_full.MAST_ACCOUNT_ID
  AND wk_tsys_trans3.AT00_APPLICATION_SUFFIX = wk_tsys_chgoff_full.AM00_APPLICATION_SUFFIX
  AND wk_tsys_trans3.PROCESS_DT = wk_tsys_chgoff_full.PROCESS_DT
WHERE
  wk_tsys_trans3.WRONG_IND != 1
),
  

WK_TSYS_TRANS_BAD_ACCOUNT AS (
SELECT DISTINCT
  wk_tsys_trans2.MAST_ACCOUNT_ID,
  wk_tsys_trans2.PROCESS_DT,
  NULL AS INTERCHG,
  NULL AS FOREX,
  CASE
    WHEN wk_tsys_trans2.AM00_STATC_CHARGEOFF IN ('DC', 'BD', 'ST') THEN AMT2
END
  AS MTHEND_CO_REC,
  CASE
    WHEN wk_tsys_trans2.AM00_STATC_CHARGEOFF IN ('07', '13') THEN AMT2
END
  AS MTHEND_BK_REC,
  CASE
    WHEN wk_tsys_trans2.AM00_STATC_CHARGEOFF IN ('FR') THEN AMT2
END
  AS MTHEND_FR_REC,
  NULL AS MTHEND_INT,
  NULL AS MTHEND_PYMT,
  NULL AS MTHEND_MRCH,
  NULL AS MTHEND_CASH,
  NULL AS MTHEND_CONVC,
  NULL AS MTHEND_BTFER,
  NULL AS CIBC_CASH_CNT,
  NULL AS FRGN_CASH_CNT,
  NULL AS CDN_CASH_CNT,
  NULL AS MTHEND_TRANS,
  NULL AS OLIM_FEE,
  NULL AS ABP_FEE,
  NULL AS CASH_FEE,
  NULL AS NSF_FEE,
  NULL AS CRS_FEE,
  NULL AS IDREST_FEE,
  NULL AS CREDALRT_FEE,
  NULL AS RSASST_FEE,
  NULL AS OTHR_FEE,
  NULL AS ANNUAL_FEE
FROM
  WK_TSYS_TRANS2 AS wk_tsys_trans2
WHERE
  NULLIF(TRIM(wk_tsys_trans2.AM00_STATC_CHARGEOFF),"") IS NOT NULL
  AND wk_tsys_trans2.CHGOFF_DT <= wk_tsys_trans2.AT31_DATE_POST 
),
  
WK_TSYS_TRANS_GOOD_ACCOUNT AS (
SELECT DISTINCT
  wk_tsys_trans2.MAST_ACCOUNT_ID,
  wk_tsys_trans2.PROCESS_DT,
  wk_tsys_trans2.INTERCHG,
  wk_tsys_trans2.FOREX,
  NULL AS MTHEND_CO_REC,
  NULL AS MTHEND_BK_REC,
  NULL AS MTHEND_FR_REC,
  CASE
    WHEN wk_tsys_trans2.AT31_TRNS_ACCT_FUNC IN UNNEST (TRNS_ACCT_FUNC_COND) THEN wk_tsys_trans2.AMT
END
  AS MTHEND_INT,
  CASE
    WHEN wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE= CAST(CONCAT(code_prefix,'0') AS INT64) THEN wk_tsys_trans2.AMT2
END
  AS MTHEND_PYMT,
  CASE
    WHEN wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'1') AS INT64) THEN wk_tsys_trans2.AMT
END
  AS MTHEND_MRCH,
  CASE
    WHEN (wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'2') AS INT64) OR wk_tsys_trans2.AT31_TERMS_BALANCE_CODE>= CAST(CONCAT(code_prefix,'4') AS INT64)) THEN wk_tsys_trans2.AMT
END
  AS MTHEND_CASH,
  CASE
    WHEN (wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'2') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=4) OR (wk_tsys_trans2.AT31_TERMS_BALANCE_CODE>= CAST(CONCAT(code_prefix,'4') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY < 6000) THEN wk_tsys_trans2.AMT
END
  AS MTHEND_CONVC,
  CASE
    WHEN (wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'2') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=5) OR (wk_tsys_trans2.AT31_TERMS_BALANCE_CODE>= CAST(CONCAT(code_prefix,'4') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY >= 6000) THEN wk_tsys_trans2.AMT
END
  AS MTHEND_BTFER,
  CASE
    WHEN wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'2') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=6702 THEN wk_tsys_trans2.CNT
END
  AS CIBC_CASH_CNT,
  CASE
    WHEN wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'2') AS INT64) AND NOT wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=6702 AND wk_tsys_trans2.CDN_IND=0 THEN wk_tsys_trans2.CNT
END
  AS FRGN_CASH_CNT,
  CASE
    WHEN wk_tsys_trans2.AT31_TRNS_ACCT_FUNC NOT IN UNNEST (TRNS_ACCT_FUNC_COND) AND wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'2') AS INT64) AND NOT wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=6702 AND wk_tsys_trans2.CDN_IND=1 THEN wk_tsys_trans2.CNT
END
  AS CDN_CASH_CNT,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'1') AS INT64) THEN wk_tsys_trans2.CNT
END
  AS MTHEND_TRANS,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=8 THEN wk_tsys_trans2.AMT
END
  AS OLIM_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=9 THEN wk_tsys_trans2.AMT
END
  AS ABP_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=10 THEN wk_tsys_trans2.AMT
END
  AS CASH_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=11 THEN wk_tsys_trans2.AMT
END
  AS NSF_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=12 THEN wk_tsys_trans2.AMT
END
  AS ANNUAL_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=48 AND wk_tsys_trans2.AT31_ENHANCEMENT_ID='0001' THEN wk_tsys_trans2.AMT
END
  AS CRS_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=48 AND wk_tsys_trans2.AT31_ENHANCEMENT_ID='0002' THEN wk_tsys_trans2.AMT
END
  AS IDREST_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=48 AND wk_tsys_trans2.AT31_ENHANCEMENT_ID='0003' THEN wk_tsys_trans2.AMT
END
  AS CREDALRT_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND wk_tsys_trans2.AT31_TRANSACTION_CATEGORY=48 AND wk_tsys_trans2.AT31_ENHANCEMENT_ID='0004' THEN wk_tsys_trans2.AMT
END
  AS RSASST_FEE,
  CASE
    WHEN wk_tsys_trans2.AT31_TERMS_BALANCE_CODE=CAST(CONCAT(code_prefix,'3') AS INT64) AND (wk_tsys_trans2.AT31_TRANSACTION_CATEGORY NOT IN (8, 9, 10, 11, 12, 48) OR (wk_tsys_trans2.AT31_TRANSACTION_CATEGORY = 48 AND wk_tsys_trans2.AT31_ENHANCEMENT_ID NOT IN ('0001', '0002', '0003', '0004'))) THEN wk_tsys_trans2.AMT
END
  AS OTHR_FEE,
FROM
  WK_TSYS_TRANS2 AS wk_tsys_trans2
WHERE
  NOT (NULLIF(TRIM(wk_tsys_trans2.AM00_STATC_CHARGEOFF),"") IS NOT NULL
    AND wk_tsys_trans2.CHGOFF_DT <= wk_tsys_trans2.AT31_DATE_POST)
),
    
WK_TSYS_TRANS1 AS (
SELECT DISTINCT
  *
FROM
  WK_TSYS_TRANS_GOOD_ACCOUNT
UNION ALL
SELECT DISTINCT
  *
FROM
  WK_TSYS_TRANS_BAD_ACCOUNT 
)

SELECT DISTINCT
  wk_tsys_trans1.MAST_ACCOUNT_ID,
  wk_tsys_trans1.PROCESS_DT,
  SUM(wk_tsys_trans1.INTERCHG) AS INTERCHG,
  SUM(wk_tsys_trans1.FOREX) AS FOREX,
  SUM(wk_tsys_trans1.MTHEND_CO_REC) AS MTHEND_CO_REC,
  SUM(wk_tsys_trans1.MTHEND_BK_REC) AS MTHEND_BK_REC,
  SUM(wk_tsys_trans1.MTHEND_FR_REC) AS MTHEND_FR_REC,
  SUM(wk_tsys_trans1.MTHEND_INT) AS MTHEND_INT,
  SUM(wk_tsys_trans1.MTHEND_PYMT) AS MTHEND_PYMT,
  SUM(wk_tsys_trans1.MTHEND_MRCH) AS MTHEND_MRCH,
  SUM(wk_tsys_trans1.MTHEND_CASH) AS MTHEND_CASH,
  SUM(wk_tsys_trans1.MTHEND_TRANS) AS MTHEND_TRANS,
  SUM(wk_tsys_trans1.CIBC_CASH_CNT) AS CIBC_CASH_CNT,
  SUM(wk_tsys_trans1.FRGN_CASH_CNT) AS FRGN_CASH_CNT,
  SUM(wk_tsys_trans1.CDN_CASH_CNT) AS CDN_CASH_CNT,
  SUM(wk_tsys_trans1.OLIM_FEE) AS OLIM_FEE,
  SUM(wk_tsys_trans1.ABP_FEE) AS ABP_FEE,
  SUM(wk_tsys_trans1.CASH_FEE) AS CASH_FEE,
  SUM(wk_tsys_trans1.NSF_FEE) AS NSF_FEE,
  SUM(wk_tsys_trans1.CRS_FEE) AS CRS_FEE,
  SUM(wk_tsys_trans1.IDREST_FEE) AS IDREST_FEE,
  SUM(wk_tsys_trans1.CREDALRT_FEE) AS CREDALRT_FEE,
  SUM(wk_tsys_trans1.RSASST_FEE) AS RSASST_FEE,
  SUM(wk_tsys_trans1.OTHR_FEE) AS OTHR_FEE,
  SUM(wk_tsys_trans1.MTHEND_CONVC) AS MTHEND_CONVC,
  SUM(wk_tsys_trans1.MTHEND_BTFER) AS MTHEND_BTFER,
  SUM(wk_tsys_trans1.ANNUAL_FEE) AS ANNUAL_FEE
FROM
  WK_TSYS_TRANS1 AS wk_tsys_trans1
GROUP BY
  wk_tsys_trans1.MAST_ACCOUNT_ID,
  wk_tsys_trans1.PROCESS_DT;

UPDATE
  `pcb-{env}-landing.domain_scoring.WK_TSYS_TRANS`
SET
  MTHEND_TRANS=MTHEND_TRANS+FRGN_CASH_CNT+CDN_CASH_CNT
WHERE
  TRUE;

END
