BEGIN

DECLARE report_month DATE;
DECLARE table_name_suffix STRING;
DECLARE target_schema ARRAY<STRUCT<column_name STRING, data_type STRING>>;
DECLARE YEAR STRING;
DECLARE MONTH STRING;
DECLARE select_sql STRING;
DECLARE insert_sql STRING;

SET report_month = (
  SELECT (get_report_month).report_month
FROM (SELECT `pcb-{env}-landing.domain_scoring.get_report_month`('{report_year}', '{report_month}') AS get_report_month)
);

SET table_name_suffix = REPLACE(CAST(report_month AS STRING),'-','') ;
SET YEAR = SUBSTR(table_name_suffix, 1, 4);
SET MONTH = SUBSTR(table_name_suffix, 5, 2);


CREATE TEMP TABLE MTH_SCORING_STAGE1 AS
SELECT DISTINCT
  wk_mth6.* EXCEPT(FOREX,
    OLIM_FEE,
    ABP_FEE,
    CASH_FEE,
    NSF_FEE,
    CRS_FEE,
    IDREST_FEE,
    CREDALRT_FEE,
    RSASST_FEE,
    ANNUAL_FEE,
    OTHR_FEE,
    MTHEND_MRCH,
    MTHEND_INT,
    INTERCHG),
  wk_hist_6mth.* EXCEPT(ACCT_KEY),
  wk_hist_3mth.* EXCEPT(ACCT_KEY),
  CASE
    WHEN PROCESS_DT < '2011-11-01' THEN CASE
    WHEN NULLIF(CAST(ORIG_CB_SCORE AS FLOAT64), 0) IS NULL
  AND OPEN_DT>='2010-08-01'
  AND TOB <24 THEN 'NHNS'
    WHEN SUBSTR(ACCOUNT_NUMBER,1,4)='5228' THEN 'MCRY'
    ELSE 'SLVR'
END
    ELSE CASE
    WHEN AM00_CLIENT_PRODUCT_CODE ='PFE' THEN 'INSD'
    WHEN AM00_CLIENT_PRODUCT_CODE = 'PCP' THEN 'PRLD'
    WHEN NULLIF(CAST(ORIG_CB_SCORE AS FLOAT64), 0) IS NULL AND OPEN_DT>='2010-08-01' AND TOB <24 THEN 'NHNS'
    WHEN SUBSTR(ACCOUNT_NUMBER,1,4)='5228' THEN 'MCRY'
    WHEN SUBSTR(ACCOUNT_NUMBER,1,6)='518116' THEN 'ELIT'
    ELSE 'SLVR'
END
END AS PROD_CD,
  -- REPLACE NULL AS 0 FOR CALCULATION SINCE NULL + 1 = NULL
  COALESCE(FOREX, 0) AS FOREX,
  COALESCE(OLIM_FEE, 0) AS OLIM_FEE,
  COALESCE(ABP_FEE, 0) AS ABP_FEE,
  COALESCE(CASH_FEE, 0) AS CASH_FEE,
  COALESCE(NSF_FEE, 0) AS NSF_FEE,
  COALESCE(CRS_FEE, 0) AS CRS_FEE,
  COALESCE(IDREST_FEE, 0) AS IDREST_FEE,
  COALESCE(CREDALRT_FEE, 0) AS CREDALRT_FEE,
  COALESCE(RSASST_FEE, 0) AS RSASST_FEE,
  COALESCE(ANNUAL_FEE, 0) AS ANNUAL_FEE,
  COALESCE(OTHR_FEE, 0) AS OTHR_FEE,
  COALESCE(MTHEND_MRCH, 0) AS MTHEND_MRCH,
  COALESCE(MTHEND_INT, 0) AS MTHEND_INT,
  COALESCE(INTERCHG, 0) AS INTERCHG
FROM
  `pcb-{env}-landing.domain_scoring.WK_MTH6` AS wk_mth6
LEFT JOIN
  `pcb-{env}-landing.domain_scoring.WK_HIST_6MTH` AS wk_hist_6mth
ON
  CAST(wk_mth6.ACCT_KEY AS STRING) = wk_hist_6mth.ACCT_KEY
LEFT JOIN
  `pcb-{env}-landing.domain_scoring.WK_HIST_3MTH` AS wk_hist_3mth
ON
  CAST(wk_mth6.ACCT_KEY AS STRING) = wk_hist_3mth.ACCT_KEY;


CREATE OR REPLACE TABLE `pcb-{env}-landing.domain_scoring.MTH_CURRENT_SCORING` AS
SELECT DISTINCT
  * EXCEPT(B_DT,
    CHGOFF_DT,
    CLOSED_DT,
    CRVK_DT,
    DOB,
    FST_ACTV_DT,
    LST_CASH_DT,
    LST_CRED_DT,
    LST_MRCH_DT,
    LST_PYMT_DT,
    OFFER_DT,
    OPEN_DT,
    PROCESS_DT,
    SCORE_DT,
    SEC_FRD_DT,
    STMT_DUE_DT,
    ACCOUNT_NUMBER,
    AM00_CUSTOM_DATA_81,
    AM00_TYPEC_VIP),
  -- CHANGE TO NUMBERIC TO MATCH SAS
  SAFE_CAST(AM00_CUSTOM_DATA_81 AS INTEGER) AS AM00_CUSTOM_DATA_81,
  SAFE_CAST(AM00_TYPEC_VIP AS INTEGER) AS AM00_TYPEC_VIP,
  -- CHANGE DATE TO DATETIME TO BE SAME AS OLD TABLES. SKIP.
  CAST(ACCOUNT_NUMBER AS INTEGER) AS ACCOUNT_NUMBER,
  CAST(B_DT AS DATE) AS B_DT,
  CAST(CHGOFF_DT AS DATE) AS CHGOFF_DT,
  CAST(CLOSED_DT AS DATE) AS CLOSED_DT,
  CAST(CRVK_DT AS DATE) AS CRVK_DT,
  CAST(DOB AS DATE) AS DOB,
  CAST(FST_ACTV_DT AS DATE) AS FST_ACTV_DT,
  CAST(LST_CASH_DT AS DATE) AS LST_CASH_DT,
  CAST(LST_CRED_DT AS DATE) AS LST_CRED_DT,
  CAST(LST_MRCH_DT AS DATE) AS LST_MRCH_DT,
  CAST(LST_PYMT_DT AS DATE) AS LST_PYMT_DT,
  CAST(OFFER_DT AS DATE) AS OFFER_DT,
  CAST(OPEN_DT AS DATE) AS OPEN_DT,
  CAST(PROCESS_DT AS DATE) AS PROCESS_DT,
  CAST(SCORE_DT AS DATE) AS SCORE_DT,
  CAST(SEC_FRD_DT AS DATE) AS SEC_FRD_DT,
  -- CAST(STATUS_CHG_DT  AS DATE) AS STATUS_CHG_DT , NOT IN TABLE
  CAST(STMT_DUE_DT AS DATE) AS STMT_DUE_DT,
  CASE
    WHEN CAST(CB_SCORE AS FLOAT64)>=1 AND PROD_CD='PRLD' THEN 'PRLD'
    WHEN CAST(CB_SCORE AS FLOAT64)>=1
  AND CAST(CB_SCORE AS FLOAT64)<660 THEN 'SUBP'
    WHEN CAST(CB_SCORE AS FLOAT64)>=660 AND CAST(CB_SCORE AS FLOAT64)<780 THEN 'PRIM'
    WHEN CAST(CB_SCORE AS FLOAT64)>=780 THEN 'SUPP'
    ELSE 'NHNS'
END
  AS CB_GRP,
  CASE
    WHEN CO_AMT>0 THEN 'C'
    WHEN BK_AMT>0 THEN 'B'
    WHEN FR_AMT>0 THEN 'F'
    WHEN CO_IND=1
  AND CO_AMT IS NULL THEN 'OCO'
    WHEN BK_IND=1 AND BK_AMT IS NULL THEN 'OBK'
    WHEN FR_IND=1
  AND FR_AMT IS NULL THEN 'OFR'
    WHEN CHGOFF_DT IS NULL OR CHGOFF_DT<=PROCESS_DT THEN CAST(STMT_PD_STAT AS STRING)
END
  AS STMT_PD_STATUS,
  CASE
    WHEN CHGOFF_DT IS NULL AND CO_IND IS NULL AND BK_IND IS NULL AND FR_IND IS NULL THEN MTHEND_BAL
END
  AS BAL,
  CASE
    WHEN CO_AMT>0 THEN 'C'
    WHEN BK_AMT>0 THEN 'B'
    WHEN FR_AMT>0 THEN 'F'
    WHEN CO_IND=1
  AND CO_AMT IS NULL THEN 'OCO'
    WHEN BK_IND=1 AND BK_AMT IS NULL THEN 'OBK'
    WHEN FR_IND=1
  AND FR_AMT IS NULL THEN 'OFR'
    ELSE CAST(MTHEND_PD_STAT AS STRING)
END
  AS PD_STATUS,
  CASE
    WHEN PROCESS_DT ='2009-11-01' THEN 'PRE_CONSENT'
    WHEN PROCESS_DT>='2009-12-01'
  AND PROCESS_DT<'2010-08-01' THEN 'OTHER'
    WHEN PROCESS_DT>='2010-08-01' AND PROCESS_DT<'2011-07-01' THEN 'TRIAD_BASE'
    WHEN PROCESS_DT>='2011-07-01'
  AND PROCESS_DT<'2011-10-01'
  AND STATE = 'QC' THEN 'TRIAD_BASE'
    WHEN PROCESS_DT>='2011-07-01' AND PROCESS_DT<'2011-10-01' AND STATE != 'QC' THEN CASE
    WHEN TEST_DIGIT<=499 THEN 'TRIAD_BASE'
    WHEN TEST_DIGIT<=999 THEN 'TRIAD_DDS'
    WHEN TEST_DIGIT<=1499 THEN 'TRIAD_BASE'
    WHEN TEST_DIGIT<=2999 THEN 'TRIAD_DDS'
    WHEN TEST_DIGIT<=3999 THEN 'TRIAD_BASE'
    WHEN TEST_DIGIT<=4999 THEN 'TRIAD_DDS'
    WHEN TEST_DIGIT<=9999 THEN 'TRIAD_BASE'
END
    WHEN PROCESS_DT>='2011-10-01' AND PROCESS_DT <'2012-08-01' AND STATE = 'QC' THEN CASE
    WHEN TEST_DIGIT<=999 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=6999 THEN 'TRIAD_BASE'
    WHEN TEST_DIGIT<=9999 THEN 'TRIAD_OPT'
END
    WHEN PROCESS_DT>='2011-10-01' AND PROCESS_DT <'2012-08-01' AND STATE != 'QC' THEN CASE
    WHEN TEST_DIGIT<=499 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=999 THEN 'TRIAD_DDS'
    WHEN TEST_DIGIT<=1499 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=2999 THEN 'TRIAD_DDS'
    WHEN TEST_DIGIT<=3999 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=4999 THEN 'TRIAD_DDS'
    WHEN TEST_DIGIT<=7999 THEN 'TRIAD_BASE'
    WHEN TEST_DIGIT<=9999 THEN 'TRIAD_OPT'
END
    WHEN PROCESS_DT>='2012-08-01' AND STATE = 'QC' THEN CASE
    WHEN TEST_DIGIT<=999 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=1499 THEN 'TRIAD_BASE'
    WHEN TEST_DIGIT<=6999 THEN 'TRIAD_OPT2'
    WHEN TEST_DIGIT<=9999 THEN 'TRIAD_OPT'
END
    WHEN PROCESS_DT>='2012-08-01' AND STATE != 'QC' THEN CASE
    WHEN TEST_DIGIT<=499 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=999 THEN 'TRIAD_OPT2'
    WHEN TEST_DIGIT<=1499 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=2999 THEN 'TRIAD_OPT2'
    WHEN TEST_DIGIT<=3999 THEN 'TRIAD_OPT'
    WHEN TEST_DIGIT<=7499 THEN 'TRIAD_OPT2'
    WHEN TEST_DIGIT<=7999 THEN 'TRIAD_BASE'
    WHEN TEST_DIGIT<=9999 THEN 'TRIAD_OPT'
END
END AS CLI_CTGY,
  -- NOLONGER NEEDED SINCE ALREADY IN THE TABLE
  -- EXTRACT(MONTH FROM OPEN_DT) AS OPEN_MTH,
  -- EXTRACT(YEAR FROM OPEN_DT) AS OPEN_YR,
  -- WHY? LOYALTY WIL ALWAYS = 0.01*MTHEND_MRCH
  CASE
    WHEN PROD_CD !='MCRY' THEN 0.01*MTHEND_MRCH
    WHEN PROD_CD ='MCRY' THEN 0.01*(MTHEND_MRCH)
    ELSE 0
END
  AS LOYALTY,
  CASE
    WHEN CO_IND IS NULL AND BK_IND IS NULL AND FR_IND IS NULL THEN MTHEND_BAL*(0.0202/12)
    ELSE 0
END
  AS COF,
  CASE
    WHEN ACTIVE_IND IS NULL THEN 0.3862
    WHEN ACTIVE_IND=1 THEN (1.7135+1.3294) + (0.3862) + LEAST(0,IFNULL(MTHEND_TRANS,0))*(0.02448+0.163321)
    ELSE 0
END
  AS OPEX,
  -- OPTIONAL PRODUCT MARGINS;
  0.84*IFNULL(ABP_FEE,0) AS ABP_INCOME,
  0.625*IFNULL(IDREST_FEE,0) AS IDREST_INCOME,
  0.34*IFNULL(CRS_FEE,0) AS CRS_INCOME,
  0.72*IFNULL(RSASST_FEE,0) AS RSASST_INCOME,
  0.625*IFNULL(CREDALRT_FEE,0) AS CREDALRT_INCOME,
FROM
  MTH_SCORING_STAGE1;


ALTER TABLE `pcb-{env}-landing.domain_scoring.MTH_CURRENT_SCORING` ADD COLUMN FEES FLOAT64;

ALTER TABLE `pcb-{env}-landing.domain_scoring.MTH_CURRENT_SCORING` ADD COLUMN PROFIT FLOAT64;

UPDATE `pcb-{env}-landing.domain_scoring.MTH_CURRENT_SCORING`
SET
  FEES = OLIM_FEE + ABP_INCOME + CASH_FEE + NSF_FEE + CRS_INCOME + IDREST_INCOME
    + CREDALRT_INCOME + RSASST_INCOME + ANNUAL_FEE + OTHR_FEE + FOREX,
  
  PROFIT = MTHEND_INT + INTERCHG
    + (
      OLIM_FEE + ABP_INCOME + CASH_FEE + NSF_FEE + CRS_INCOME + IDREST_INCOME
      + CREDALRT_INCOME + RSASST_INCOME + ANNUAL_FEE + OTHR_FEE + FOREX)
    - COF - LOYALTY - COALESCE(CO_AMT, 0) - COALESCE(CO_AMT_SUFFIX, 0)
    - COALESCE(BK_AMT, 0) - COALESCE(BK_AMT_SUFFIX, 0) - COALESCE(FR_AMT, 0)
    + COALESCE(MTHEND_CO_REC, 0) + COALESCE(MTHEND_BK_REC, 0)
    + COALESCE(MTHEND_FR_REC, 0) - OPEX,
  
  ACCOUNT_NUMBER = CASE
    WHEN MAST_ACCOUNT_ID = 333023 AND PROCESS_DT >= '2014-12-01'
      THEN 5181161904518917
    ELSE ACCOUNT_NUMBER
    END,
  
  AM01_PRIM_CARD_ID = CASE
    WHEN MAST_ACCOUNT_ID = 333023 AND PROCESS_DT >= '2014-12-01' THEN 'PETF'
    ELSE AM01_PRIM_CARD_ID
    END
WHERE
  TRUE;

-- APPEND to Final Table `pcb-{env}-landing.domain_scoring.SCORING_PREP_PCMC_DATA_DEPOT`

SET select_sql = (
  SELECT STRING_AGG(
           FORMAT("CAST(%s AS STRING) AS %s", column_name, column_name)
           ORDER BY ordinal_position
         )
  FROM `pcb-{env}-landing.domain_scoring.INFORMATION_SCHEMA.COLUMNS`
  WHERE table_name = 'SCORING_PREP_PCMC_DATA_DEPOT'
  AND column_name NOT IN ('YEAR', 'MONTH', 'REC_LOAD_TIMESTAMP', 'JOB_ID')
);

SET insert_sql = FORMAT("""
INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_PCMC_DATA_DEPOT`
(
  MAST_ACCOUNT_ID,
  BILLING_CYC,
  CRLN,
  CRLN_CHG_TYPE,
  OPEN_YR,
  OPEN_MTH,
  ACQ_STGY_CD,
  MTHEND_PD_STAT,
  BK_TYPE,
  BK_IND,
  CO_IND,
  FR_IND,
  B_IND,
  CRVK_IND,
  CLOSED_IND,
  CRVK_DT,
  CLOSED_DT,
  SEC_FRD_IND,
  AM00_STATF_FRAUD,
  SYS_ACTIVE,
  AM00_CLIENT_PRODUCT_CODE,
  AM00_TRIAD_SCORE_ALIGNED,
  AM00_TRIAD_SCORE_RAW,
  AM00_STATC_DISPUTE,
  AM00_TYPEC_VIP,
  AM00_CUSTOM_DATA_81,
  ACCOUNT_NUMBER,
  AM01_PRIM_CARD_ID,
  MTHEND_BAL,
  LST_CRED_DT,
  B_AMT,
  B_DT,
  MTHEND_BAL_SUFFIX,
  MTHEND_CNT_SUFFIX,
  POSTAL_FSA,
  STATE,
  REGION,
  STMT_BAL,
  STMT_CRLN,
  TOT_DUE,
  CYC_PYMT,
  CYC_PYMT_NET,
  ANN_RATE,
  ACT_ANN_RATE,
  PREV_STMT_BAL,
  STMT_DUE_DT,
  STMT_PD_STAT,
  INTERCHG,
  FOREX,
  MTHEND_CO_REC,
  MTHEND_BK_REC,
  MTHEND_FR_REC,
  MTHEND_INT,
  MTHEND_PYMT,
  MTHEND_MRCH,
  MTHEND_CASH,
  MTHEND_TRANS,
  CIBC_CASH_CNT,
  FRGN_CASH_CNT,
  CDN_CASH_CNT,
  OLIM_FEE,
  ABP_FEE,
  CASH_FEE,
  NSF_FEE,
  CRS_FEE,
  IDREST_FEE,
  CREDALRT_FEE,
  RSASST_FEE,
  OTHR_FEE,
  MTHEND_CONVC,
  MTHEND_BTFER,
  ANNUAL_FEE,
  CYC_MRCH,
  CYC_CASH,
  FR_AMT,
  FR_CNT,
  BK_AMT_SUFFIX,
  BK_CNT_SUFFIX,
  CO_AMT_SUFFIX,
  CO_CNT_SUFFIX,
  CHGOFF_DT,
  COFF_RSN_CD,
  BK_AMT,
  CO_AMT,
  ORIG_CHGOFF_AMT,
  BNI_SCORE,
  ORIG_BNI_SCORE,
  SCORE_DT,
  CB_SCORE,
  ORIG_CB_SCORE,
  OFFER_LIMIT,
  CURR_LIMIT,
  OFFER_DT,
  OFFER,
  BEHV_SCORE_RAW,
  CO_REC,
  BK_REC,
  STATUS_CD,
  TOB,
  DISCL_GRP,
  APR_CODE,
  TOB_RANGE,
  CB_SCR_RANGE,
  ACCT_KEY,
  TEST_DIGIT,
  ORIG_CRLN,
  PREV_MTHEND_BAL,
  PREV_MTHEND_BAL_SUFFIX,
  PREV_CB_SCORE_6MTH,
  PREV_CB_SCORE_9MTH,
  PREV_CB_SCORE_12MTH,
  ACTIVE_IND,
  TRANS_IND,
  RVLVR_IND,
  DELQ_CNT_6MTH,
  ACTIVE_CNT_6MTH,
  TRANS_CNT_6MTH,
  RVLVR_CNT_6MTH,
  TOT_INT_6MTH,
  AVG_BAL_6MTH,
  DELQ_CNT_3MTH,
  ACTIVE_CNT_3MTH,
  TRANS_CNT_3MTH,
  RVLVR_CNT_3MTH,
  PROD_CD,
  CB_GRP,
  PD_STATUS,
  STMT_PD_STATUS,
  BAL,
  CLI_CTGY,
  ABP_INCOME,
  IDREST_INCOME,
  CRS_INCOME,
  RSASST_INCOME,
  CREDALRT_INCOME,
  FEES,
  LOYALTY,
  COF,
  OPEX,
  PROFIT,
  OPEN_DT,
  PROCESS_DT,
  SEC_FRD_DT,
  LST_MRCH_DT,
  LST_CASH_DT,
  LST_PYMT_DT,
  FST_ACTV_DT,
  DOB,
  YEAR,
  MONTH,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
SELECT
  %s,
  '%s' AS YEAR,
  '%s' AS MONTH,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM `pcb-{env}-landing.domain_scoring.MTH_CURRENT_SCORING`
""",
select_sql,
YEAR,
MONTH
);

EXECUTE IMMEDIATE insert_sql;

END
