BEGIN
  DECLARE report_month DATE;

SET report_month = (
  SELECT (get_report_month).report_month
  FROM
    (
      SELECT
        `pcb-{env}-landing.domain_scoring.get_report_month`('{report_year}', '{report_month}')
          AS get_report_month
    )
);

INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_WK_TSYS_CHGOFF_FULL`
(
  MAST_ACCOUNT_ID,
  AM00_APPLICATION_SUFFIX,
  PROCESS_DT,
  CHGOFF_DT,
  AM00_STATC_CHARGEOFF,
  BK_AMT,
  CO_AMT,
  FR_AMT,
  ORIG_CHGOFF_AMT,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
SELECT DISTINCT
  CAST(am08.MAST_ACCOUNT_ID AS STRING) AS MAST_ACCOUNT_ID,
  CAST(am08.AM00_APPLICATION_SUFFIX AS STRING) AS AM00_APPLICATION_SUFFIX,
  CAST(DATE_TRUNC(am08.FILE_CREATE_DT, MONTH) AS STRING) AS PROCESS_DT,
  CAST(DATE(am08.AM08_DATE_CHARGEOFF_COMPLETE) AS STRING) AS CHGOFF_DT,
  am00.AM00_STATC_CHARGEOFF,
  CAST(
    CASE
      WHEN
        DATE_TRUNC(am08.AM08_DATE_CHARGEOFF_COMPLETE, MONTH)
          = DATE_TRUNC(report_month, MONTH)
        AND am00.AM00_STATC_CHARGEOFF IN ('13', '07')
        THEN am08.AM08_BALANCE_CHARGEOFF
      END
      AS STRING) AS BK_AMT,
  CAST(
    CASE
      WHEN
        DATE_TRUNC(am08.AM08_DATE_CHARGEOFF_COMPLETE, MONTH)
          = DATE_TRUNC(report_month, MONTH)
        AND am00.AM00_STATC_CHARGEOFF IN ('BD', 'DC', 'ST')
        THEN am08.AM08_BALANCE_CHARGEOFF
      END
      AS STRING) AS CO_AMT,
  CAST(
    CASE
      WHEN
        DATE_TRUNC(am08.AM08_DATE_CHARGEOFF_COMPLETE, MONTH)
          = DATE_TRUNC(report_month, MONTH)
        AND am00.AM00_STATC_CHARGEOFF IN ('FR')
        THEN am08.AM08_BALANCE_CHARGEOFF
      END
      AS STRING) AS FR_AMT,
  CAST(am08.AM08_BALANCE_CHARGEOFF AS STRING) AS ORIG_CHGOFF_AMT,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM
  `pcb-{env}-curated.domain_account_management.AM08` AS am08
INNER JOIN
  `pcb-{env}-curated.domain_account_management.AM00` AS am00
  ON  am08.MAST_ACCOUNT_ID = am00.MAST_ACCOUNT_ID
WHERE
  DATE_TRUNC(am08.FILE_CREATE_DT, MONTH) = DATE_TRUNC(report_month, MONTH)
  AND (('{mode}'  = 'PCMC' AND am00.AM00_CLIENT_PRODUCT_CODE NOT LIKE 'PD%'))
  OR  (('{mode}' != 'PCMC' AND am00.AM00_CLIENT_PRODUCT_CODE LIKE 'PD%'))
  AND am00.AM00_STATC_CHARGEOFF IN ('13','07','BD','DC','ST','FR')
  AND am08.AM08_CHARGEOFF_COMPLETE = 'C'
  AND am08.FILE_CREATE_DT = am00.FILE_CREATE_DT
  AND am08.AM00_APPLICATION_SUFFIX = am00.AM00_APPLICATION_SUFFIX
ORDER BY 1, 2, 3;

END
