INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_WK_TSYS_MTHEND_FULL`
(
  MAST_ACCOUNT_ID,
  AM00_APPLICATION_SUFFIX,
  ACCOUNT_NUMBER,
  MTHEND_BAL,
  BILLING_CYC,
  CRLN,
  CRLN_CHG_TYPE,
  OPEN_YR,
  OPEN_MTH,
  OPEN_DT,
  ACQ_STGY_CD,
  MTHEND_PD_STAT,
  BK_TYPE,
  PROCESS_DT,
  BK_IND,
  CO_IND,
  FR_IND,
  B_IND,
  LST_MRCH_DT,
  LST_CASH_DT,
  LST_PYMT_DT,
  LST_CRED_DT,
  FST_ACTV_DT,
  CRVK_IND,
  CLOSED_IND,
  CRVK_DT,
  CLOSED_DT,
  SEC_FRD_IND,
  SEC_FRD_DT,
  SYS_ACTIVE,
  AM00_CLIENT_PRODUCT_CODE,
  AM01_PRIM_CARD_ID,
  AM00_DISCLOSURE_GRP,
  AM00_ALTERNATE_DISCLOSURE_GRP,
  STR_DISCL_GRP,
  EXP_DISCL_GRP,
  AM00_TRIAD_SCORE_ALIGNED,
  AM00_TRIAD_SCORE_RAW,
  AM00_STATF_FRAUD,
  AM00_STATC_DISPUTE,
  AM00_TYPEC_VIP,
  AM00_CUSTOM_DATA_81,
  B_AMT,
  B_DT,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
SELECT DISTINCT
  tsys_am00.MAST_ACCOUNT_ID,
  tsys_am00.AM00_APPLICATION_SUFFIX,
  tsys_am01.ACCOUNT_NUMBER,
  tsys_am02.MTHEND_BAL,
  tsys_am00.BILLING_CYC,
  tsys_am00.CRLN,
  tsys_am00.CRLN_CHG_TYPE,
  tsys_am00.OPEN_YR,
  tsys_am00.OPEN_MTH,
  tsys_am00.OPEN_DT,
  tsys_am00.ACQ_STGY_CD,
  tsys_am00.MTHEND_PD_STAT,
  tsys_am00.BK_TYPE,
  tsys_am00.PROCESS_DT,
  tsys_am00.BK_IND,
  tsys_am00.CO_IND,
  tsys_am00.FR_IND,
  tsys_am00.B_IND,
  tsys_am02.LST_MRCH_DT,
  tsys_am02.LST_CASH_DT,
  tsys_am02.LST_PYMT_DT,
  tsys_am02.LST_CRED_DT,
  tsys_am02.FST_ACTV_DT,
  tsys_am00.CRVK_IND,
  tsys_am00.CLOSED_IND,
  tsys_am00.CRVK_DT,
  tsys_am00.CLOSED_DT,
  tsys_am00.SEC_FRD_IND,
  tsys_am00.SEC_FRD_DT,
  tsys_am00.SYS_ACTIVE,
  tsys_am00.AM00_CLIENT_PRODUCT_CODE,
  tsys_am01.AM01_PRIM_CARD_ID,
  tsys_am00.AM00_DISCLOSURE_GRP,
  tsys_am00.AM00_ALTERNATE_DISCLOSURE_GRP,
  tsys_am00.STR_DISCL_GRP,
  tsys_am00.EXP_DISCL_GRP,
  tsys_am00.AM00_TRIAD_SCORE_ALIGNED,
  tsys_am00.AM00_TRIAD_SCORE_RAW,
  tsys_am00.AM00_STATF_FRAUD,
  tsys_am00.AM00_STATC_DISPUTE,
  tsys_am00.AM00_TYPEC_VIP,
  tsys_am00.AM00_CUSTOM_DATA_81,
  CASE
    WHEN
      tsys_am00.CRVK_IND IN ('07', '13')
      AND NULLIF(tsys_am00.AM00_STATC_CHARGEOFF, '') IS NULL
      AND CAST(DATE_TRUNC(CAST(tsys_am00.CRVK_DT AS DATE), MONTH) AS STRING) = tsys_am00.PROCESS_DT
      THEN tsys_am02.MTHEND_BAL
    END
    AS B_AMT,
  CASE
    WHEN
      tsys_am00.CRVK_IND IN ('07', '13')
      AND NULLIF(tsys_am00.AM00_STATC_CHARGEOFF, '') IS NULL
      AND CAST(DATE_TRUNC(CAST(tsys_am00.CRVK_DT AS DATE), MONTH) AS STRING) = tsys_am00.PROCESS_DT
      THEN tsys_am00.CRVK_DT
    END
    AS B_DT,
CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
'{dag_id}' AS JOB_ID

FROM
  `pcb-{env}-curated.domain_scoring.SCORING_PREP_WK_TSYS_AM00_LATEST` tsys_am00
INNER JOIN
  `pcb-{env}-curated.domain_scoring.SCORING_PREP_WK_TSYS_AM01_LATEST` tsys_am01
  ON
    tsys_am00.MAST_ACCOUNT_ID = tsys_am01.MAST_ACCOUNT_ID
    AND tsys_am00.AM00_APPLICATION_SUFFIX = tsys_am01.AM00_APPLICATION_SUFFIX
    AND tsys_am00.FILE_CREATE_DT = tsys_am01.FILE_CREATE_DT
INNER JOIN
  `pcb-{env}-curated.domain_scoring.SCORING_PREP_WK_TSYS_AM02_LATEST` tsys_am02
  ON
    tsys_am00.MAST_ACCOUNT_ID = tsys_am02.MAST_ACCOUNT_ID
    AND tsys_am00.AM00_APPLICATION_SUFFIX = tsys_am02.AM00_APPLICATION_SUFFIX
    AND tsys_am00.FILE_CREATE_DT = tsys_am02.FILE_CREATE_DT
WHERE
  AM00_CLIENT_PRODUCT_CODE NOT LIKE 'PD%';
