BEGIN
  DECLARE report_month DATE;

SET report_month = (
  SELECT (get_report_month).report_month
  FROM
    (
      SELECT
        `pcb-{env}-landing.domain_scoring.get_report_month`('{report_year}', '{report_month}')
          AS get_report_month
    )
);

INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_WK_TSYS_CYCLE`
(
  MAST_ACCOUNT_ID,
  STMT_BAL,
  STMT_CRLN,
  TOT_DUE,
  CYC_PYMT,
  CYC_PYMT_NET,
  ANN_RATE,
  ACT_ANN_RATE,
  PREV_STMT_BAL,
  STMT_DUE_DT,
  STMT_PD_STAT,
  PROCESS_DT,
  AH01_CDATE_CYCLE,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
SELECT DISTINCT
  CAST(ah01.MAST_ACCOUNT_ID AS STRING) AS MAST_ACCOUNT_ID,
  CAST(ah01.AH01_BALANCE_CURRENT AS STRING) AS STMT_BAL,
  CAST(ah01.AH01_LIMIT_CREDIT AS STRING) AS STMT_CRLN,
  CAST(ah01.AH01_STMT_MIN_PAYMENT AS STRING) AS TOT_DUE,
  CAST(ah01.AH01_AMT_PAYMENTS AS STRING) AS CYC_PYMT,
  CAST((ah01.AH01_AMT_PAYMENTS - ah01.AH01_AMT_NSF_PAYMENTS) AS STRING)
    AS CYC_PYMT_NET,
  CAST(ah01.AH01_WEIGHTED_AVG_APR AS STRING) AS ANN_RATE,
  CAST(ah01.AH01_ACTUAL_APR AS STRING) AS ACT_ANN_RATE,
  CAST(ah01.AH01_BALANCE_PREV_STATEMENT AS STRING) AS PREV_STMT_BAL,
  CAST(DATE(ah01.AH01_DATE_PAYMENT_DUE) AS STRING) AS STMT_DUE_DT,
  CAST(
    CASE
      WHEN ah01.AH01_AMT_PASTDUE_12 > 0 THEN 12
      WHEN ah01.AH01_AMT_PASTDUE_11 > 0 THEN 11
      WHEN ah01.AH01_AMT_PASTDUE_10 > 0 THEN 10
      WHEN ah01.AH01_AMT_PASTDUE_9 > 0 THEN 9
      WHEN ah01.AH01_AMT_PASTDUE_8 > 0 THEN 8
      WHEN ah01.AH01_AMT_PASTDUE_7 > 0 THEN 7
      WHEN ah01.AH01_AMT_PASTDUE_6 > 0 THEN 6
      WHEN ah01.AH01_AMT_PASTDUE_5 > 0 THEN 5
      WHEN ah01.AH01_AMT_PASTDUE_4 > 0 THEN 4
      WHEN ah01.AH01_AMT_PASTDUE_3 > 0 THEN 3
      WHEN ah01.AH01_AMT_PASTDUE_2 > 0 THEN 2
      WHEN ah01.AH01_AMT_PASTDUE_1 > 0 THEN 1
      ELSE 0
      END AS STRING)
    AS STMT_PD_STAT,
  CAST(DATE_TRUNC(ah01.FILE_CREATE_DT, MONTH) AS STRING) AS PROCESS_DT,
  CAST(ah01.AH01_CDATE_CYCLE AS STRING) AS AH01_CDATE_CYCLE,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM
  `pcb-{env}-curated.domain_account_management.AH01` AS ah01
WHERE
  DATE_TRUNC(ah01.FILE_CREATE_DT, MONTH) = DATE_TRUNC(report_month, MONTH)
  AND ah01.AH00_APPLICATION_SUFFIX = 0;

END
