INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_TRANS_SUMMARY_DAILY`
(
  MAST_ACCOUNT_ID,
  TOB,
  OPEN_TOB,
  N_TOT_TRANS,
  TRNS_PER_MTH,
  TOT_SPEND,
  SPEND_PER_TRNS,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
WITH
  base_data AS (
    SELECT DISTINCT
      CAST(MAST_ACCOUNT_ID AS NUMERIC) AS MAST_ACCOUNT_ID,
      CAST(TOB AS NUMERIC) AS TOB,
      CAST(OPEN_TOB AS NUMERIC) AS OPEN_TOB,
      MERCH2,
      CAST(TRANS_AMT AS NUMERIC) AS TRANS_AMT
    FROM
      `pcb-{env}-curated.domain_scoring.SCORING_PREP_CUST_TRANS_FULL_DAILY_LATEST`
  ),
  enriched_data_1 AS (
    SELECT DISTINCT
      MAST_ACCOUNT_ID,
      MAX(TOB) AS TOB,
      MAX(OPEN_TOB) AS OPEN_TOB,
      COUNT(MERCH2) AS N_TOT_TRANS,
      ROUND(SAFE_DIVIDE(COUNT(MERCH2), MAX(TOB)), 2) AS TRNS_PER_MTH,
      SUM(TRANS_AMT) AS TOT_SPEND,
      ROUND(SAFE_DIVIDE(SUM(TRANS_AMT), COUNT(MERCH2)), 2) AS SPEND_PER_TRNS
    FROM
      base_data
    GROUP BY
      MAST_ACCOUNT_ID
  )
SELECT DISTINCT
  CAST(enriched_data_1.MAST_ACCOUNT_ID AS STRING),
  CAST(enriched_data_1.TOB AS STRING),
  CAST(enriched_data_1.OPEN_TOB AS STRING),
  CAST(enriched_data_1.N_TOT_TRANS AS STRING),
  CAST(enriched_data_1.TRNS_PER_MTH AS STRING),
  CAST(enriched_data_1.TOT_SPEND AS STRING),
  CAST(enriched_data_1.SPEND_PER_TRNS AS STRING),
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM enriched_data_1;
