INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_CUST_TRANS_FULL_DAILY`
(
  FILE_CREATE_DT,
  MAST_ACCOUNT_ID,
  CIFP_TRIAD_SCORE_ALIGNED,
  CIFP_CREDIT_LIMIT,
  CIFP_PREV_STAT_BAL,
  CIFP_DATE_OPEN,
  CIFP_FIRST_USE_DATE,
  CIFP_CLIENT_PRODUCT_CODE,
  CIFP_CURRENT_BALANCE,
  CIFP_AMT_PAY_CTD,
  OPEN_TOB,
  TOB,
  PYMT_RATIO,
  UTIL,
  CIFP_ZIP_CODE,
  CIFP_TEST_DIGIT_TYPE5,
  CIFP_ACQUISITION_CODE,
  MORTGAGE_IND,
  TTLPOINTS,
  PRIZM,
  APP_BCN,
  IAL_INQS_PST12_MNTH,
  TNC_TRD_CURR_PST_DUE,
  TNC_UTIL_PERCENTAGE_OPEN_TRD,
  TRANS_CNT_3MTH,
  TRANS_CNT_6MTH,
  AT31_ACCOUNT_NUMB,
  AT31_DATE_POST,
  AT31_DATE_TRANSACTION,
  AT31_DEBIT_CREDIT_INDICATOR,
  AT31_TERMS_BALANCE_CODE,
  TRANS_AMT,
  MERCHANT_ID,
  MERCHANT_NAME,
  TRANS_CODE,
  TRANS_CATEGORY,
  MCC,
  MERCH2,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
SELECT DISTINCT
  score_pop.FILE_CREATE_DT,
  score_pop.MAST_ACCOUNT_ID,
  score_pop.CIFP_TRIAD_SCORE_ALIGNED,
  score_pop.CIFP_CREDIT_LIMIT,
  score_pop.CIFP_PREV_STAT_BAL,
  score_pop.CIFP_DATE_OPEN,
  score_pop.CIFP_FIRST_USE_DATE,
  score_pop.CIFP_CLIENT_PRODUCT_CODE,
  score_pop.CIFP_CURRENT_BALANCE,
  score_pop.CIFP_AMT_PAY_CTD,
  score_pop.OPEN_TOB,
  score_pop.TOB,
  score_pop.PYMT_RATIO,
  score_pop.UTIL,
  score_pop.CIFP_ZIP_CODE,
  score_pop.CIFP_TEST_DIGIT_TYPE5,
  score_pop.CIFP_ACQUISITION_CODE,
  score_pop.MORTGAGE_IND,
  score_pop.TTLPOINTS,
  score_pop.PRIZM,
  score_pop.APP_BCN,
  score_pop.IAL_INQS_PST12_MNTH,
  score_pop.TNC_TRD_CURR_PST_DUE,
  score_pop.TNC_UTIL_PERCENTAGE_OPEN_TRD,
  score_pop.TRANS_CNT_3MTH,
  score_pop.TRANS_CNT_6MTH,
  trans_hist.at31_account_numb,
  trans_hist.at31_date_post,
  trans_hist.at31_date_transaction,
  trans_hist.at31_debit_credit_indicator,
  trans_hist.at31_terms_balance_code,
  trans_hist.trans_amt,
  trans_hist.merchant_id,
  trans_hist.merchant_name,
  trans_hist.trans_code,
  trans_hist.trans_category,
  CASE
    WHEN trans_hist.mcc BETWEEN '3000' AND '3299' THEN '3000'  -- airlines
    WHEN trans_hist.mcc BETWEEN '3300' AND '3499' THEN '3351' -- car rentals
    WHEN trans_hist.mcc BETWEEN '3500' AND '3999' THEN '3500' -- hotels
    ELSE trans_hist.mcc
  END AS mcc,
  trans_hist.merchant_name AS merch2, -- keep merchant name without formatting
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM
  `pcb-{env}-curated.domain_scoring.SCORING_PREP_SCORE_POP_DAILY_LATEST` score_pop
INNER JOIN
  `pcb-{env}-curated.domain_scoring.SCORING_PREP_TRANS_HIST_BASE_LATEST` trans_hist
ON score_pop.MAST_ACCOUNT_ID = trans_hist.MAST_ACCOUNT_ID;
