INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_SCORE_POP_DAILY`
(
  FILE_CREATE_DT,
  MAST_ACCOUNT_ID,
  CIFP_TRIAD_SCORE_ALIGNED,
  CIFP_CREDIT_LIMIT,
  CIFP_PREV_STAT_BAL,
  CIFP_DATE_OPEN,
  CIFP_FIRST_USE_DATE,
  CIFP_CLIENT_PRODUCT_CODE,
  CIFP_CURRENT_BALANCE,
  CIFP_AMT_PAY_CTD,
  OPEN_TOB,
  TOB,
  PYMT_RATIO,
  UTIL,
  CIFP_ZIP_CODE,
  CIFP_TEST_DIGIT_TYPE5,
  CIFP_ACQUISITION_CODE,
  MORTGAGE_IND,
  TTLPOINTS,
  PRIZM,
  APP_BCN,
  IAL_INQS_PST12_MNTH,
  TNC_TRD_CURR_PST_DUE,
  TNC_UTIL_PERCENTAGE_OPEN_TRD,
  TRANS_CNT_3MTH,
  TRANS_CNT_6MTH,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
SELECT DISTINCT
  CAST(trs.FILE_CREATE_DT AS STRING) AS FILE_CREATE_DT,
  CAST(trs.MAST_ACCOUNT_ID AS STRING) AS MAST_ACCOUNT_ID,
  CAST(trs.CIFP_TRIAD_SCORE_ALIGNED AS STRING) AS CIFP_TRIAD_SCORE_ALIGNED,
  CAST(trs.CIFP_CREDIT_LIMIT AS STRING) AS CIFP_CREDIT_LIMIT,
  CAST(trs.CIFP_PREV_STAT_BAL AS STRING) AS CIFP_PREV_STAT_BAL,
  CAST(trs.CIFP_DATE_OPEN AS STRING) AS CIFP_DATE_OPEN,
  CAST(trs.CIFP_FIRST_USE_DATE AS STRING) AS CIFP_FIRST_USE_DATE,
  CAST(trs.CIFP_CLIENT_PRODUCT_CODE AS STRING) AS CIFP_CLIENT_PRODUCT_CODE,
  CAST(trs.CIFP_CURRENT_BALANCE AS STRING) AS CIFP_CURRENT_BALANCE,
  CAST(trs.CIFP_AMT_PAY_CTD AS STRING) AS CIFP_AMT_PAY_CTD,
  CAST(trs.OPEN_TOB AS STRING) AS OPEN_TOB,
  CAST(trs.TOB AS STRING) AS TOB,
  CAST(trs.PYMT_RATIO AS STRING) AS PYMT_RATIO,
  CAST(trs.UTIL AS STRING) AS UTIL,
  CAST(trs.CIFP_ZIP_CODE AS STRING) AS CIFP_ZIP_CODE,
  CAST(substr(CAST(trs.CIFP_TEST_DIGIT_TYPE5 AS string), -2) AS STRING)
    AS CIFP_TEST_DIGIT_TYPE5,
  CAST(
    CASE
      WHEN trs.CIFP_Acquisition_code = "ACT" THEN 1
      WHEN trs.CIFP_Acquisition_code = "IIS" THEN 2
      WHEN trs.CIFP_Acquisition_code = "IMM" THEN 3
      WHEN trs.CIFP_Acquisition_code = "INT" THEN 4
      WHEN trs.CIFP_Acquisition_code = "JWR" THEN 5
      WHEN trs.CIFP_Acquisition_code = "MOS" THEN 6
      WHEN trs.CIFP_Acquisition_code = "PAV" THEN 7
      WHEN trs.CIFP_Acquisition_code = "RSM" THEN 8
      WHEN trs.CIFP_Acquisition_code = "SDI" THEN 9
      WHEN trs.CIFP_Acquisition_code = "TAB" THEN 10
      WHEN trs.CIFP_Acquisition_code = "TBE" THEN 11
      WHEN trs.CIFP_Acquisition_code = "TEL" THEN 12
      ELSE 99
      END AS STRING) AS CIFP_ACQUISITION_CODE,
  CAST(
    CASE
      WHEN
        safe_cast(das.TMG_TTL_BALNC_OPEN_TRD AS int) > 0
        OR safe_cast(das.THE_TTL_BALNC_OPEN_TRD AS int) > 0
        THEN 1
      ELSE 0
      END AS STRING) AS MORTGAGE_IND,
  CAST(CASE WHEN das.TTLPOINTS > 99999 THEN 99999 ELSE das.TTLPOINTS END AS STRING) AS TTLPOINTS,
  CAST(CASE WHEN prz.PRIZM IS NOT NULL THEN prz.PRIZM ELSE '69' END AS STRING) AS PRIZM,
  CAST(das.APP_BCN AS STRING) AS APP_BCN,
  CAST(safe_cast(substr(das.IAL_INQS_PST12_MNTH, 2) AS int) AS STRING) AS IAL_INQS_PST12_MNTH,
  CAST(safe_cast(substr(das.TNC_TRD_CURR_PST_DUE, 1) AS int) AS STRING) AS TNC_TRD_CURR_PST_DUE,
  CAST(safe_cast(substr(das.TNC_UTIL_PERCENTAGE_OPEN_TRD, 1) AS int) AS STRING)
    AS TNC_UTIL_PERCENTAGE_OPEN_TRD,
  CAST(pdd.trans_cnt_3mth AS STRING) AS TRANS_CNT_3MTH,
  CAST(pdd.trans_cnt_6mth AS STRING) AS TRANS_CNT_6MTH,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  CAST('{dag_id}' AS STRING) AS JOB_ID
FROM
  `pcb-{env}-curated.domain_scoring.SCORING_PREP_CUSTOMER_LIST_DAILY_LATEST` trs

-- Join with most recent data from DAS for each account to get some TSYS fields
LEFT JOIN
  (
    SELECT DISTINCT
      MAST_ACCOUNT_ID,
      FILE_CREATE_DT,
      APP_BCN,
      TTLPOINTS,
      IAL_INQS_PST12_MNTH,
      TNC_TRD_CURR_PST_DUE,
      TNC_UTIL_PERCENTAGE_OPEN_TRD,
      TMG_TTL_BALNC_OPEN_TRD,
      THE_TTL_BALNC_OPEN_TRD
    FROM `pcb-{env}-curated.domain_scoring.CREDSCORE_DAS`
    WHERE FILE_CREATE_DT < CURRENT_DATE()
    QUALIFY ROW_NUMBER() OVER (PARTITION BY MAST_ACCOUNT_ID ORDER BY FILE_CREATE_DT DESC) = 1
  ) das
  ON CAST(trs.MAST_ACCOUNT_ID AS STRING) = CAST(das.MAST_ACCOUNT_ID AS STRING)

-- Join with PRIZM using Zipcode to get prizm score
LEFT JOIN `pcb-{env}-curated.domain_scoring.SCORING_PREP_PRIZM_UNIQUE_LATEST` prz
  ON trs.CIFP_ZIP_CODE = prz.FSALDU
LEFT JOIN `pcb-{env}-curated.domain_scoring.SCORING_PREP_PCMC_DATA_DEPOT_LATEST` pdd
  ON
    trs.MAST_ACCOUNT_ID = pdd.MAST_ACCOUNT_ID
    AND pdd.YEAR = '{report_year}'
    AND pdd.MONTH = '{report_month}';

