INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_LCL_STORE_LIST`
(
  MERCHANT,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
SELECT DISTINCT
  CASE
    WHEN LENGTH(TRIM(MERCHANT)) = 16 AND SUBSTR(MERCHANT, 1, 1) = '0'
      THEN SUBSTR(MERCHANT, 2)
    ELSE MERCHANT
    END AS MERCHANT,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM
  (
    SELECT DISTINCT MERCHANT_ID AS MERCHANT,
    FROM
      `pcb-{env}-curated.domain_retail.GLOBAL_PAYMENT_MERCHANT`
    UNION DISTINCT
    SELECT DISTINCT
      MERCHANT_NUMBER AS MERCHANT,
    FROM
      `pcb-{env}-curated.domain_retail.SDM_STORES_LIST`
  );