INSERT INTO `pcb-{env}-landing.domain_scoring.SCORING_PREP_MTH_CURRENT_SCORING`
(
  MAST_ACCOUNT_ID,
  MTHEND_BAL,
  BILLING_CYC,
  CRLN,
  CRLN_CHG_TYPE,
  OPEN_YR,
  OPEN_MTH,
  ACQ_STGY_CD,
  MTHEND_PD_STAT,
  BK_TYPE,
  BK_IND,
  CO_IND,
  FR_IND,
  B_IND,
  CRVK_IND,
  CLOSED_IND,
  SEC_FRD_IND,
  SYS_ACTIVE,
  AM00_CLIENT_PRODUCT_CODE,
  AM01_PRIM_CARD_ID,
  AM00_TRIAD_SCORE_ALIGNED,
  AM00_TRIAD_SCORE_RAW,
  AM00_STATF_FRAUD,
  AM00_STATC_DISPUTE,
  B_AMT,
  MTHEND_BAL_SUFFIX,
  MTHEND_CNT_SUFFIX,
  POSTAL_FSA,
  STATE,
  REGION,
  STMT_BAL,
  STMT_CRLN,
  TOT_DUE,
  CYC_PYMT,
  CYC_PYMT_NET,
  ANN_RATE,
  ACT_ANN_RATE,
  PREV_STMT_BAL,
  STMT_PD_STAT,
  MTHEND_CO_REC,
  MTHEND_BK_REC,
  MTHEND_FR_REC,
  MTHEND_PYMT,
  MTHEND_CASH,
  MTHEND_TRANS,
  CIBC_CASH_CNT,
  FRGN_CASH_CNT,
  CDN_CASH_CNT,
  MTHEND_CONVC,
  MTHEND_BTFER,
  CYC_MRCH,
  CYC_CASH,
  FR_AMT,
  FR_CNT,
  BK_AMT_SUFFIX,
  BK_CNT_SUFFIX,
  CO_AMT_SUFFIX,
  CO_CNT_SUFFIX,
  BK_AMT,
  CO_AMT,
  ORIG_CHGOFF_AMT,
  BNI_SCORE,
  ORIG_BNI_SCORE,
  CB_SCORE,
  ORIG_CB_SCORE,
  CURR_LIMIT,
  OFFER_LIMIT,
  BEHV_SCORE_RAW,
  TEST_DIGIT,
  COFF_RSN_CD,
  CO_REC,
  BK_REC,
  STATUS_CD,
  TOB,
  DISCL_GRP,
  OFFER,
  APR_CODE,
  TOB_RANGE,
  CB_SCR_RANGE,
  ACCT_KEY,
  TRANS_IND,
  RVLVR_IND,
  ACTIVE_IND,
  ORIG_CRLN,
  PREV_MTHEND_BAL,
  PREV_MTHEND_BAL_SUFFIX,
  PREV_CB_SCORE_6MTH,
  PREV_CB_SCORE_9MTH,
  PREV_CB_SCORE_12MTH,
  DELQ_CNT_6MTH,
  ACTIVE_CNT_6MTH,
  TRANS_CNT_6MTH,
  RVLVR_CNT_6MTH,
  TOT_INT_6MTH,
  AVG_BAL_6MTH,
  DELQ_CNT_3MTH,
  ACTIVE_CNT_3MTH,
  TRANS_CNT_3MTH,
  RVLVR_CNT_3MTH,
  PROD_CD,
  FOREX,
  OLIM_FEE,
  ABP_FEE,
  CASH_FEE,
  NSF_FEE,
  CRS_FEE,
  IDREST_FEE,
  CREDALRT_FEE,
  RSASST_FEE,
  ANNUAL_FEE,
  OTHR_FEE,
  MTHEND_MRCH,
  MTHEND_INT,
  INTERCHG,
  AM00_CUSTOM_DATA_81,
  AM00_TYPEC_VIP,
  ACCOUNT_NUMBER,
  B_DT,
  CHGOFF_DT,
  CLOSED_DT,
  CRVK_DT,
  DOB,
  FST_ACTV_DT,
  LST_CASH_DT,
  LST_CRED_DT,
  LST_MRCH_DT,
  LST_PYMT_DT,
  OFFER_DT,
  OPEN_DT,
  PROCESS_DT,
  SCORE_DT,
  SEC_FRD_DT,
  STMT_DUE_DT,
  CB_GRP,
  STMT_PD_STATUS,
  BAL,
  PD_STATUS,
  CLI_CTGY,
  LOYALTY,
  COF,
  OPEX,
  ABP_INCOME,
  IDREST_INCOME,
  CRS_INCOME,
  RSASST_INCOME,
  CREDALRT_INCOME,
  FEES,
  PROFIT,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)
WITH
  MTH_SCORING_STAGE1 AS (
    SELECT DISTINCT
      wk_mth6.*
        EXCEPT (
          FOREX,
          OLIM_FEE,
          ABP_FEE,
          CASH_FEE,
          NSF_FEE,
          CRS_FEE,
          IDREST_FEE,
          CREDALRT_FEE,
          RSASST_FEE,
          ANNUAL_FEE,
          OTHR_FEE,
          MTHEND_MRCH,
          MTHEND_INT,
          INTERCHG,
          REC_LOAD_TIMESTAMP,
          JOB_ID),
      wk_hist_6mth.* EXCEPT (ACCT_KEY, REC_LOAD_TIMESTAMP, JOB_ID),
      wk_hist_3mth.* EXCEPT (ACCT_KEY, REC_LOAD_TIMESTAMP, JOB_ID),
      CASE
        WHEN SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) < DATE '2011-11-01'
          THEN
            CASE
              WHEN
                NULLIF(SAFE_CAST(ORIG_CB_SCORE AS FLOAT64), 0) IS NULL
                AND SAFE.PARSE_DATE('%Y-%m-%d', OPEN_DT) >= DATE '2010-08-01'
                AND SAFE_CAST(TOB AS INT64) < 24
                THEN 'NHNS'
              WHEN SUBSTR(ACCOUNT_NUMBER, 1, 4) = '5228' THEN 'MCRY'
              ELSE 'SLVR'
              END
        ELSE
          CASE
            WHEN AM00_CLIENT_PRODUCT_CODE = 'PFE' THEN 'INSD'
            WHEN AM00_CLIENT_PRODUCT_CODE = 'PCP' THEN 'PRLD'
            WHEN
              NULLIF(SAFE_CAST(ORIG_CB_SCORE AS FLOAT64), 0) IS NULL
              AND SAFE.PARSE_DATE('%Y-%m-%d', OPEN_DT) >= DATE '2010-08-01'
              AND SAFE_CAST(TOB AS INT64) < 24
              THEN 'NHNS'
            WHEN SUBSTR(ACCOUNT_NUMBER, 1, 4) = '5228' THEN 'MCRY'
            WHEN SUBSTR(ACCOUNT_NUMBER, 1, 6) = '518116' THEN 'ELIT'
            ELSE 'SLVR'
            END
        END AS PROD_CD,
      -- REPLACE NULL AS '0' FOR CALCULATION SINCE NULL + 1 = NULL
      COALESCE(FOREX, '0') AS FOREX,
      COALESCE(OLIM_FEE, '0') AS OLIM_FEE,
      COALESCE(ABP_FEE, '0') AS ABP_FEE,
      COALESCE(CASH_FEE, '0') AS CASH_FEE,
      COALESCE(NSF_FEE, '0') AS NSF_FEE,
      COALESCE(CRS_FEE, '0') AS CRS_FEE,
      COALESCE(IDREST_FEE, '0') AS IDREST_FEE,
      COALESCE(CREDALRT_FEE, '0') AS CREDALRT_FEE,
      COALESCE(RSASST_FEE, '0') AS RSASST_FEE,
      COALESCE(ANNUAL_FEE, '0') AS ANNUAL_FEE,
      COALESCE(OTHR_FEE, '0') AS OTHR_FEE,
      COALESCE(MTHEND_MRCH, '0') AS MTHEND_MRCH,
      COALESCE(MTHEND_INT, '0') AS MTHEND_INT,
      COALESCE(INTERCHG, '0') AS INTERCHG
    FROM
      `pcb-{env}-curated.domain_scoring.SCORING_PREP_WK_MTH6_LATEST` AS wk_mth6
    LEFT JOIN
      `pcb-{env}-curated.domain_scoring.SCORING_PREP_WK_HIST_6MTH_LATEST`
        AS wk_hist_6mth
      ON
        wk_mth6.ACCT_KEY = wk_hist_6mth.ACCT_KEY
    LEFT JOIN
      `pcb-{env}-curated.domain_scoring.SCORING_PREP_WK_HIST_3MTH_LATEST`
        AS wk_hist_3mth
      ON
        wk_mth6.ACCT_KEY = wk_hist_3mth.ACCT_KEY
  ),
  MTH_SCORING_STAGE2 AS (
    SELECT DISTINCT
      *,
      CASE
        WHEN SAFE_CAST(CB_SCORE AS FLOAT64) >= 1 AND PROD_CD = 'PRLD'
          THEN 'PRLD'
        WHEN
          SAFE_CAST(CB_SCORE AS FLOAT64) >= 1
          AND SAFE_CAST(CB_SCORE AS FLOAT64) < 660
          THEN 'SUBP'
        WHEN
          SAFE_CAST(CB_SCORE AS FLOAT64) >= 660
          AND SAFE_CAST(CB_SCORE AS FLOAT64) < 780
          THEN 'PRIM'
        WHEN SAFE_CAST(CB_SCORE AS FLOAT64) >= 780 THEN 'SUPP'
        ELSE 'NHNS'
        END
        AS CB_GRP,
      -- Common chargeoff status logic (reused for STMT_PD_STATUS and PD_STATUS)
      CASE
        WHEN SAFE_CAST(CO_AMT AS FLOAT64) > 0 THEN 'C'
        WHEN SAFE_CAST(BK_AMT AS FLOAT64) > 0 THEN 'B'
        WHEN SAFE_CAST(FR_AMT AS FLOAT64) > 0 THEN 'F'
        WHEN CO_IND = '1' AND CO_AMT IS NULL THEN 'OCO'
        WHEN BK_IND = '1' AND BK_AMT IS NULL THEN 'OBK'
        WHEN FR_IND = '1' AND FR_AMT IS NULL THEN 'OFR'
        ELSE NULL
        END
        AS CHARGOFF_STATUS
    FROM
      MTH_SCORING_STAGE1
  ),
  MTH_SCORING_STAGE3 AS (
    SELECT DISTINCT
      *,
      -- Simplified: LOYALTY always = 0.01*MTHEND_MRCH regardless of PROD_CD
      CAST(0.01 * SAFE_CAST(MTHEND_MRCH AS FLOAT64) AS STRING) AS LOYALTY,
      CASE
        WHEN CO_IND IS NULL AND BK_IND IS NULL AND FR_IND IS NULL
          THEN CAST(SAFE_CAST(MTHEND_BAL AS FLOAT64) * (0.0202 / 12) AS STRING)
        ELSE '0'
        END
        AS COF,
      CASE
        WHEN ACTIVE_IND IS NULL THEN '0.3862'
        WHEN ACTIVE_IND = '1'
          THEN
            CAST(
              3.0429
              + (0.3862)
              + LEAST(0, SAFE_CAST(IFNULL(MTHEND_TRANS, '0') AS FLOAT64))
                * 0.187801
              AS STRING)
        ELSE '0'
        END
        AS OPEX,
      -- OPTIONAL PRODUCT MARGINS;
      CAST(0.84 * SAFE_CAST(IFNULL(ABP_FEE, '0') AS FLOAT64) AS STRING)
        AS ABP_INCOME,
      CAST(0.625 * SAFE_CAST(IFNULL(IDREST_FEE, '0') AS FLOAT64) AS STRING)
        AS IDREST_INCOME,
      CAST(0.34 * SAFE_CAST(IFNULL(CRS_FEE, '0') AS FLOAT64) AS STRING)
        AS CRS_INCOME,
      CAST(0.72 * SAFE_CAST(IFNULL(RSASST_FEE, '0') AS FLOAT64) AS STRING)
        AS RSASST_INCOME,
      CAST(0.625 * SAFE_CAST(IFNULL(CREDALRT_FEE, '0') AS FLOAT64) AS STRING)
        AS CREDALRT_INCOME
    FROM
      MTH_SCORING_STAGE2
  )
SELECT DISTINCT
  MAST_ACCOUNT_ID AS MAST_ACCOUNT_ID,
  MTHEND_BAL AS MTHEND_BAL,
  BILLING_CYC AS BILLING_CYC,
  CRLN AS CRLN,
  CRLN_CHG_TYPE AS CRLN_CHG_TYPE,
  OPEN_YR AS OPEN_YR,
  OPEN_MTH AS OPEN_MTH,
  ACQ_STGY_CD AS ACQ_STGY_CD,
  MTHEND_PD_STAT AS MTHEND_PD_STAT,
  BK_TYPE AS BK_TYPE,
  BK_IND AS BK_IND,
  CO_IND AS CO_IND,
  FR_IND AS FR_IND,
  B_IND AS B_IND,
  CRVK_IND AS CRVK_IND,
  CLOSED_IND AS CLOSED_IND,
  SEC_FRD_IND AS SEC_FRD_IND,
  SYS_ACTIVE AS SYS_ACTIVE,
  AM00_CLIENT_PRODUCT_CODE AS AM00_CLIENT_PRODUCT_CODE,
  AM01_PRIM_CARD_ID AS AM01_PRIM_CARD_ID,
  AM00_TRIAD_SCORE_ALIGNED AS AM00_TRIAD_SCORE_ALIGNED,
  AM00_TRIAD_SCORE_RAW AS AM00_TRIAD_SCORE_RAW,
  AM00_STATF_FRAUD AS AM00_STATF_FRAUD,
  AM00_STATC_DISPUTE AS AM00_STATC_DISPUTE,
  B_AMT AS B_AMT,
  MTHEND_BAL_SUFFIX AS MTHEND_BAL_SUFFIX,
  MTHEND_CNT_SUFFIX AS MTHEND_CNT_SUFFIX,
  POSTAL_FSA AS POSTAL_FSA,
  STATE AS STATE,
  REGION AS REGION,
  STMT_BAL AS STMT_BAL,
  STMT_CRLN AS STMT_CRLN,
  TOT_DUE AS TOT_DUE,
  CYC_PYMT AS CYC_PYMT,
  CYC_PYMT_NET AS CYC_PYMT_NET,
  ANN_RATE AS ANN_RATE,
  ACT_ANN_RATE AS ACT_ANN_RATE,
  PREV_STMT_BAL AS PREV_STMT_BAL,
  STMT_PD_STAT AS STMT_PD_STAT,
  MTHEND_CO_REC AS MTHEND_CO_REC,
  MTHEND_BK_REC AS MTHEND_BK_REC,
  MTHEND_FR_REC AS MTHEND_FR_REC,
  MTHEND_PYMT AS MTHEND_PYMT,
  MTHEND_CASH AS MTHEND_CASH,
  MTHEND_TRANS AS MTHEND_TRANS,
  CIBC_CASH_CNT AS CIBC_CASH_CNT,
  FRGN_CASH_CNT AS FRGN_CASH_CNT,
  CDN_CASH_CNT AS CDN_CASH_CNT,
  MTHEND_CONVC AS MTHEND_CONVC,
  MTHEND_BTFER AS MTHEND_BTFER,
  CYC_MRCH AS CYC_MRCH,
  CYC_CASH AS CYC_CASH,
  FR_AMT AS FR_AMT,
  FR_CNT AS FR_CNT,
  BK_AMT_SUFFIX AS BK_AMT_SUFFIX,
  BK_CNT_SUFFIX AS BK_CNT_SUFFIX,
  CO_AMT_SUFFIX AS CO_AMT_SUFFIX,
  CO_CNT_SUFFIX AS CO_CNT_SUFFIX,
  BK_AMT AS BK_AMT,
  CO_AMT AS CO_AMT,
  ORIG_CHGOFF_AMT AS ORIG_CHGOFF_AMT,
  BNI_SCORE AS BNI_SCORE,
  ORIG_BNI_SCORE AS ORIG_BNI_SCORE,
  CB_SCORE AS CB_SCORE,
  ORIG_CB_SCORE AS ORIG_CB_SCORE,
  CURR_LIMIT AS CURR_LIMIT,
  OFFER_LIMIT AS OFFER_LIMIT,
  BEHV_SCORE_RAW AS BEHV_SCORE_RAW,
  TEST_DIGIT AS TEST_DIGIT,
  COFF_RSN_CD AS COFF_RSN_CD,
  CO_REC AS CO_REC,
  BK_REC AS BK_REC,
  STATUS_CD AS STATUS_CD,
  TOB AS TOB,
  DISCL_GRP AS DISCL_GRP,
  OFFER AS OFFER,
  APR_CODE AS APR_CODE,
  TOB_RANGE AS TOB_RANGE,
  CB_SCR_RANGE AS CB_SCR_RANGE,
  ACCT_KEY AS ACCT_KEY,
  TRANS_IND AS TRANS_IND,
  RVLVR_IND AS RVLVR_IND,
  ACTIVE_IND AS ACTIVE_IND,
  ORIG_CRLN AS ORIG_CRLN,
  PREV_MTHEND_BAL AS PREV_MTHEND_BAL,
  PREV_MTHEND_BAL_SUFFIX AS PREV_MTHEND_BAL_SUFFIX,
  PREV_CB_SCORE_6MTH AS PREV_CB_SCORE_6MTH,
  PREV_CB_SCORE_9MTH AS PREV_CB_SCORE_9MTH,
  PREV_CB_SCORE_12MTH AS PREV_CB_SCORE_12MTH,
  DELQ_CNT_6MTH AS DELQ_CNT_6MTH,
  ACTIVE_CNT_6MTH AS ACTIVE_CNT_6MTH,
  TRANS_CNT_6MTH AS TRANS_CNT_6MTH,
  RVLVR_CNT_6MTH AS RVLVR_CNT_6MTH,
  TOT_INT_6MTH AS TOT_INT_6MTH,
  AVG_BAL_6MTH AS AVG_BAL_6MTH,
  DELQ_CNT_3MTH AS DELQ_CNT_3MTH,
  ACTIVE_CNT_3MTH AS ACTIVE_CNT_3MTH,
  TRANS_CNT_3MTH AS TRANS_CNT_3MTH,
  RVLVR_CNT_3MTH AS RVLVR_CNT_3MTH,
  PROD_CD AS PROD_CD,
  FOREX AS FOREX,
  OLIM_FEE AS OLIM_FEE,
  ABP_FEE AS ABP_FEE,
  CASH_FEE AS CASH_FEE,
  NSF_FEE AS NSF_FEE,
  CRS_FEE AS CRS_FEE,
  IDREST_FEE AS IDREST_FEE,
  CREDALRT_FEE AS CREDALRT_FEE,
  RSASST_FEE AS RSASST_FEE,
  ANNUAL_FEE AS ANNUAL_FEE,
  OTHR_FEE AS OTHR_FEE,
  MTHEND_MRCH AS MTHEND_MRCH,
  MTHEND_INT AS MTHEND_INT,
  INTERCHG AS INTERCHG,
  AM00_CUSTOM_DATA_81 AS AM00_CUSTOM_DATA_81,
  AM00_TYPEC_VIP AS AM00_TYPEC_VIP,
  ACCOUNT_NUMBER AS ACCOUNT_NUMBER,
  B_DT AS B_DT,
  CHGOFF_DT AS CHGOFF_DT,
  CLOSED_DT AS CLOSED_DT,
  CRVK_DT AS CRVK_DT,
  DOB AS DOB,
  FST_ACTV_DT AS FST_ACTV_DT,
  LST_CASH_DT AS LST_CASH_DT,
  LST_CRED_DT AS LST_CRED_DT,
  LST_MRCH_DT AS LST_MRCH_DT,
  LST_PYMT_DT AS LST_PYMT_DT,
  OFFER_DT AS OFFER_DT,
  OPEN_DT AS OPEN_DT,
  PROCESS_DT AS PROCESS_DT,
  SCORE_DT AS SCORE_DT,
  SEC_FRD_DT AS SEC_FRD_DT,
  STMT_DUE_DT AS STMT_DUE_DT,
  CB_GRP AS CB_GRP,
  CASE
    WHEN CHARGOFF_STATUS IS NOT NULL THEN CHARGOFF_STATUS
    WHEN
      CHGOFF_DT IS NULL
      OR SAFE.PARSE_DATE('%Y-%m-%d', CHGOFF_DT)
        <= SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT)
      THEN STMT_PD_STAT
    END
    AS STMT_PD_STATUS,
  CASE
    WHEN
      CHGOFF_DT IS NULL
      AND CO_IND IS NULL
      AND BK_IND IS NULL
      AND FR_IND IS NULL
      THEN MTHEND_BAL
    END
    AS BAL,
  CASE
    WHEN CHARGOFF_STATUS IS NOT NULL THEN CHARGOFF_STATUS
    ELSE MTHEND_PD_STAT
    END
    AS PD_STATUS,
  CASE
    WHEN SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) = DATE '2009-11-01'
      THEN 'PRE_CONSENT'
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2009-12-01'
      AND SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) < DATE '2010-08-01'
      THEN 'OTHER'
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2010-08-01'
      AND SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) < DATE '2011-07-01'
      THEN 'TRIAD_BASE'
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2011-07-01'
      AND SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) < DATE '2011-10-01'
      AND STATE = 'QC'
      THEN 'TRIAD_BASE'
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2011-07-01'
      AND SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) < DATE '2011-10-01'
      AND STATE != 'QC'
      THEN
        CASE
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 499 THEN 'TRIAD_BASE'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 999 THEN 'TRIAD_DDS'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 1499 THEN 'TRIAD_BASE'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 2999 THEN 'TRIAD_DDS'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 3999 THEN 'TRIAD_BASE'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 4999 THEN 'TRIAD_DDS'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 9999 THEN 'TRIAD_BASE'
          END
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2011-10-01'
      AND SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) < DATE '2012-08-01'
      AND STATE = 'QC'
      THEN
        CASE
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 999 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 6999 THEN 'TRIAD_BASE'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 9999 THEN 'TRIAD_OPT'
          END
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2011-10-01'
      AND SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) < DATE '2012-08-01'
      AND STATE != 'QC'
      THEN
        CASE
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 499 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 999 THEN 'TRIAD_DDS'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 1499 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 2999 THEN 'TRIAD_DDS'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 3999 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 4999 THEN 'TRIAD_DDS'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 7999 THEN 'TRIAD_BASE'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 9999 THEN 'TRIAD_OPT'
          END
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2012-08-01'
      AND STATE = 'QC'
      THEN
        CASE
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 999 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 1499 THEN 'TRIAD_BASE'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 6999 THEN 'TRIAD_OPT2'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 9999 THEN 'TRIAD_OPT'
          END
    WHEN
      SAFE.PARSE_DATE('%Y-%m-%d', PROCESS_DT) >= DATE '2012-08-01'
      AND STATE != 'QC'
      THEN
        CASE
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 499 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 999 THEN 'TRIAD_OPT2'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 1499 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 2999 THEN 'TRIAD_OPT2'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 3999 THEN 'TRIAD_OPT'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 7499 THEN 'TRIAD_OPT2'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 7999 THEN 'TRIAD_BASE'
          WHEN SAFE_CAST(TEST_DIGIT AS INT64) <= 9999 THEN 'TRIAD_OPT'
          END
    END AS CLI_CTGY,
  LOYALTY AS LOYALTY,
  COF AS COF,
  OPEX AS OPEX,
  ABP_INCOME AS ABP_INCOME,
  IDREST_INCOME AS IDREST_INCOME,
  CRS_INCOME AS CRS_INCOME,
  RSASST_INCOME AS RSASST_INCOME,
  CREDALRT_INCOME AS CREDALRT_INCOME,
  -- NOLONGER NEEDED SINCE ALREADY IN THE TABLE
  -- EXTRACT(MONTH FROM OPEN_DT) AS OPEN_MTH,
  -- EXTRACT(YEAR FROM OPEN_DT) AS OPEN_YR,
  CAST(
    SAFE_CAST(OLIM_FEE AS FLOAT64) + SAFE_CAST(ABP_INCOME AS FLOAT64)
    + SAFE_CAST(CASH_FEE AS FLOAT64) + SAFE_CAST(NSF_FEE AS FLOAT64)
    + SAFE_CAST(CRS_INCOME AS FLOAT64) + SAFE_CAST(IDREST_INCOME AS FLOAT64)
    + SAFE_CAST(CREDALRT_INCOME AS FLOAT64)
    + SAFE_CAST(RSASST_INCOME AS FLOAT64)
    + SAFE_CAST(ANNUAL_FEE AS FLOAT64) + SAFE_CAST(OTHR_FEE AS FLOAT64)
    + SAFE_CAST(FOREX AS FLOAT64) AS STRING) AS FEES,
  CAST(
    SAFE_CAST(MTHEND_INT AS FLOAT64)
    + SAFE_CAST(INTERCHG AS FLOAT64)
    + (
      SAFE_CAST(OLIM_FEE AS FLOAT64)
      + SAFE_CAST(ABP_INCOME AS FLOAT64)
      + SAFE_CAST(CASH_FEE AS FLOAT64)
      + SAFE_CAST(NSF_FEE AS FLOAT64)
      + SAFE_CAST(CRS_INCOME AS FLOAT64)
      + SAFE_CAST(IDREST_INCOME AS FLOAT64)
      + SAFE_CAST(CREDALRT_INCOME AS FLOAT64)
      + SAFE_CAST(RSASST_INCOME AS FLOAT64)
      + SAFE_CAST(ANNUAL_FEE AS FLOAT64)
      + SAFE_CAST(OTHR_FEE AS FLOAT64)
      + SAFE_CAST(FOREX AS FLOAT64))
    - SAFE_CAST(COF AS FLOAT64)
    - SAFE_CAST(LOYALTY AS FLOAT64)
    - SAFE_CAST(COALESCE(CO_AMT, '0') AS FLOAT64)
    - SAFE_CAST(COALESCE(CO_AMT_SUFFIX, '0') AS FLOAT64)
    - SAFE_CAST(COALESCE(BK_AMT, '0') AS FLOAT64)
    - SAFE_CAST(COALESCE(BK_AMT_SUFFIX, '0') AS FLOAT64)
    - SAFE_CAST(COALESCE(FR_AMT, '0') AS FLOAT64)
    + SAFE_CAST(COALESCE(MTHEND_CO_REC, '0') AS FLOAT64)
    + SAFE_CAST(COALESCE(MTHEND_BK_REC, '0') AS FLOAT64)
    + SAFE_CAST(COALESCE(MTHEND_FR_REC, '0') AS FLOAT64)
    - SAFE_CAST(OPEX AS FLOAT64)
    AS STRING) AS PROFIT,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM
  MTH_SCORING_STAGE3;
