CREATE OR REPLACE TABLE
  `{staging_table_id}`
OPTIONS (
  expiration_timestamp = TIMESTAMP_ADD(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
) AS
SELECT
 M.TERMS_AND_CONDITIONS as TERMS_AND_CONDITIONS,
 M.TERMS_AND_CONDITIONS_TS as TERMS_AND_CONDITIONS_TS,
 M.ES5_TOKEN as ES5_TOKEN,
 M.LG3_DATE as LG3_DATE,
 M.TK_DEV_LANG_CODE as TK_DEV_LANG_CODE,
 M.CARDHOLDER_NUMBER as CARDHOLDER_NUMBER,
 CIFP_CUSTOMER_ID_2 as TSYS_CUSTOMER_ID,
 H1_TS2_INDICATOR as TRACE_NUMBER,
FROM `pcb-{env}-curated.domain_account_management.BATCH_AUTHORIZATION_LOG` M
LEFT OUTER JOIN `pcb-{env}-curated.domain_account_management.CIF_CARD_CURR` CIFC ON CIFC.CIFP_ACCOUNT_NUM=M.CARDHOLDER_NUMBER
WHERE TKN_MC_MSG_TYPE='TC' AND TKN_TRAN_IND='C' AND LENGTH(TRIM(TERMS_AND_CONDITIONS))>0 AND {file_create_date_filter}
ORDER BY M.FILE_CREATE_DT DESC;


EXPORT DATA
  OPTIONS (
    uri = 'gs://pcb-{env}-staging-extract/tokenized_consent/tokenized-consents-captures-*.parquet',
    format = 'PARQUET',
    overwrite = true
    )
AS
(SELECT
    SAFE_CAST(TSYS_CUSTOMER_ID AS STRING) AS TSYS_CUSTOMER_ID,
    SAFE_CAST(TERMS_AND_CONDITIONS AS STRING) AS TERMS_AND_CONDITIONS,
    SAFE_CAST(TERMS_AND_CONDITIONS_TS AS STRING) AS TERMS_AND_CONDITIONS_TS,
    SAFE_CAST(ES5_TOKEN AS STRING) AS ES5_TOKEN,
    SAFE_CAST(TK_DEV_LANG_CODE AS STRING) AS TK_DEV_LANG_CODE,
    FORMAT_TIMESTAMP('%Y-%m-%dT%H:%M:%SZ', LG3_DATE) AS LG3_DATE,
    SAFE_CAST(TRACE_NUMBER AS STRING) AS TRACE_NUMBER,
    SAFE_CAST(CARDHOLDER_NUMBER AS STRING) AS CARDHOLDER_NUMBER
FROM `{staging_table_id}`);
