SELECT
  ARRIVEDFILE_KEY,
  ARRAY_AGG(MESSAGE_ID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS MESSAGE_ID,
  ARRAY_AGG(USER_ID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS USER_ID,
  ARRAY_AGG(FILE_NAME IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS FILE_NAME,
  ARRAY_AGG(FILE_SIZE IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS FILE_SIZE,
  ARRAY_AGG(MAILBOX_PATH IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS MAILBOX_PATH,
  ARRAY_AGG(DATA_FLOW_ID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS DATA_FLOW_ID,
  ARRAY_AGG(PROD_ORG_KEY IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS PROD_ORG_KEY,
  ARRAY_AGG(PROD_ORG_NAME IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS PROD_ORG_NAME,
  ARRAY_AGG(STATE IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS STATE,
  ARRAY_AGG(DOCUMENT_ID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS DOCUMENT_ID,
  ARRAY_AGG(WFID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS WFID,
  ARRAY_AGG(REVIEWED IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS REVIEWED,
  ARRAY_AGG(REPLAY_AF_KEY IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS REPLAY_AF_KEY,
  ARRAY_AGG(REPLAY_COMMENT IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS REPLAY_COMMENT,
  ARRAY_AGG(ROUTES_REMAIN IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS ROUTES_REMAIN,
  ARRAY_AGG(LOCKID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS LOCKID,
  ARRAY_AGG(CREATETS IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS CREATETS,
  ARRAY_AGG(MODIFYTS IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS MODIFYTS,
  ARRAY_AGG(CREATEUSERID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS CREATEUSERID,
  ARRAY_AGG(MODIFYUSERID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS MODIFYUSERID,
  ARRAY_AGG(CREATEPROGID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS CREATEPROGID,
  ARRAY_AGG(MODIFYPROGID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS MODIFYPROGID,
  ARRAY_AGG(DELIVERY_STATE IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS DELIVERY_STATE,
  ARRAY_AGG(DIST_MSG_ID IGNORE NULLS ORDER BY CREATETS DESC)[OFFSET(0)] AS DIST_MSG_ID
FROM `pcb-{env}-landing.cots_mft_sterling.MFT_FG_ARRIVEDFILE`
  WHERE optype IN ('U', 'I')
GROUP BY
  ARRIVEDFILE_KEY