SELECT
  DELIVERY_KEY,
  ARRAY_AGG(ROUTE_KEY IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS ROUTE_KEY,
  ARRAY_AGG(DATA_FLOW_ID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS DATA_FLOW_ID,
  ARRAY_AGG(STATE IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS STATE,
  ARRAY_AGG(DELIVCHAN_KEY IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS DELIVCHAN_KEY,
  ARRAY_AGG(CONSUMER_DOCID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS CONSUMER_DOCID,
  ARRAY_AGG(CONTENT_TYPE IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS CONTENT_TYPE,
  ARRAY_AGG(FILENAME IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS FILENAME,
  ARRAY_AGG(CONSDOC_TYPE IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS CONSDOC_TYPE,
  ARRAY_AGG(MAILBOX_PATH IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS MAILBOX_PATH,
  ARRAY_AGG(LATE_CREATE_MBX IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS LATE_CREATE_MBX,
  ARRAY_AGG(CONSUMER_MSGID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS CONSUMER_MSGID,
  ARRAY_AGG(ASYNC_XFER_ID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS ASYNC_XFER_ID,
  ARRAY_AGG(LOCKID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS LOCKID,
  ARRAY_AGG(CREATETS IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS CREATETS,
  ARRAY_AGG(MODIFYTS IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS MODIFYTS,
  ARRAY_AGG(CREATEUSERID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS CREATEUSERID,
  ARRAY_AGG(MODIFYUSERID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS MODIFYUSERID,
  ARRAY_AGG(CREATEPROGID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS CREATEPROGID,
  ARRAY_AGG(MODIFYPROGID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS MODIFYPROGID,
  ARRAY_AGG(DIST_CONSUMER_MSGID IGNORE NULLS ORDER BY TIMESTAMP DESC, POSITION DESC)[OFFSET(0)] AS DIST_CONSUMER_MSGID
FROM
  `pcb-{env}-landing.cots_mft_sterling.MFT_FG_DELIVERY`
WHERE
  optype IN ('I', 'U')
GROUP BY
  DELIVERY_KEY