SELECT
  DATA_FLOW_ID,
  ARRAY_AGG(CREATE_TIME IGNORE NULLS ORDER BY CREATE_TIME DESC)[OFFSET(0)] AS CREATE_TIME,
  ARRAY_AGG(STATE IGNORE NULLS ORDER BY CREATE_TIME DESC)[OFFSET(0)] AS STATE,
  ARRAY_AGG(ROOT_DOCUMENT IGNORE NULLS ORDER BY CREATE_TIME DESC)[OFFSET(0)] AS ROOT_DOCUMENT,
  ARRAY_AGG(DOC_TRAK_ID IGNORE NULLS ORDER BY CREATE_TIME DESC)[OFFSET(0)] AS DOC_TRAK_ID,
  ARRAY_AGG(ROOT_DOC_NAME IGNORE NULLS ORDER BY CREATE_TIME DESC)[OFFSET(0)] AS ROOT_DOC_NAME,
  ARRAY_AGG(ROOT_DOC_SIZE IGNORE NULLS ORDER BY CREATE_TIME DESC)[OFFSET(0)] AS ROOT_DOC_SIZE
FROM `pcb-{env}-landing.cots_mft_sterling.MFT_DATA_FLOW`
  WHERE optype IN ('U', 'I')
GROUP BY
  DATA_FLOW_ID