WITH
  LABELED_DATA AS (
  SELECT
    CUSTOMER_EMP_HISTORY_UID,
    CUSTOMER_EMPLOYMENT_UID,
    CUSTOMER_UID,
    REF_OCCUPATION_UID,
    REF_EMPLOYMENT_STATUS_UID,
    REF_EDUCATION_LEVEL_UID,
    ANNUAL_HOUSEHOLD_INCOME,
    ANNUAL_PERSONAL_INCOME,
    EMPLOYER_NAME,CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    ACTION,
    ACTION_DT,
    MESSAGE_ID,
    REF_EMPLOYMENT_INDUSTRY_UID,
    ROW_NUMBER() OVER(PARTITION BY CUSTOMER_EMP_HISTORY_UID ORDER BY ACTION_DT DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_customer_management.CUSTOMER_EMPLOYMENT_HISTORY`)
SELECT
  * EXCEPT(REC_RANK)
FROM
  LABELED_DATA
WHERE
  REC_RANK=1
