SELECT
      IDV_REQUEST_UID,
      IDV_REQUEST_NO,
      REQUEST_DT,
      REQUESTOR_TYPE,
      REQUESTOR_NO,
      ALERT_NO,
      DIGITAL_IDV_ELIGIBLE,
      FIRST_NAME,
      LAST_NAME,
      DATE_OF_BIRTH,
      EMAIL,
      CREATE_DT,
      CREATE_USER_ID,
      CREATE_FUNCTION_NAME,
      UPDATE_DT,
      UPDATE_USER_ID,
      UPDATE_FUNCTION_NAME,
      LANGUAGE,
      CORRESPONDENCE_SENT_DT,
      INGESTION_TIMESTAMP
FROM pcb-{env}-landing.domain_validation_verification.IDV_REQUEST
QUALIFY ROW_NUMBER() OVER (
              PARTITION BY IDV_REQUEST_UID, IDV_REQUEST_NO
              ORDER BY UPDATE_DT DESC
    ) = 1
