SELECT
SEQ_NUM,
CHEQUE_NUM,
ACCESS_MEDIUM_NO,
DATE(CHEQUE_DATE) as CHEQUE_DATE,
DATE(PROCESS_DATE) as PROCESS_DATE,
AMOUNT,
FDR_FLAG,
ST_CD,
ST_DT,
CSH_IND,
TRANSIT_NUMBER,
INSTITUTION_ID,
FDR_DATE,
CREATE_DT as REC_CREATE_TMS,
UPDATE_USER_ID as REC_CHNG_ID,
UPDATE_DT as REC_CHNG_TMS
FROM
`pcb-{env}-landing.domain_payments.PAPER_PYMT_TX`

UNION ALL

SELECT
SEQ_NUM,
CHEQUE_NUM,
ACCOUNT_NUM as ACCESS_MEDIUM_NO,
PARSE_DATE('%Y%m%d', CAST(CHEQUE_DT as STRING)) as CHEQUE_DATE,
PARSE_DATE('%Y%m%d', CAST(PROCESS_DT as STRING)) as PROCESS_DATE,
AMOUNT,
'S' as FDR_FLAG,
'A' as ST_CD,
REC_CREATE_TMS as ST_DT,
CSH_IND,
TRANSIT_NUM as TRANSIT_NUMBER,
INSTITUTION_NUM as INSTITUTION_ID,
null as FDR_DATE,
REC_CREATE_TMS,
REC_CHNG_ID,
REC_CHNG_TMS
FROM
`pcb-{env}-landing.domain_payments.PAPER_PYMT_DETL`