WITH
  LABELED_DATA AS (
  SELECT
    MEDIA_REFERENCE,
    MEDIA_LANGUAGE,
    OFFER_DETAIL,
    OFFER_DETAIL_TEXT,
    MEDIA_PHRASE1,
    MEDIA_PHRASE2,
    MEDIA_PHRASE3,
    MEDIA_PHRASE4,
    MEDIA_PHRASE5,
    LEGAL_DISCLOSURE,
    MORE_INFO,
    ON_ACCEPTANCE,
    ON_DECLINE,
    ON_DEFER,
    ON_NO_OFFER_AVAILABLE,
    WHISPER_REFERENCE,
    REC_CREATE_TMS,
    REC_CHNG_ID,
    REC_CHNG_TMS,
    ST_CD,
    ST_DT,
    ROW_NUMBER() OVER (PARTITION BY MEDIA_REFERENCE, MEDIA_LANGUAGE ORDER BY REC_CREATE_TMS DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_marketing.MEDIA_REFERENCE` )
SELECT
  * EXCEPT(REC_RANK)
FROM
  LABELED_DATA
WHERE
  REC_RANK = 1;