SELECT
    requestId,
    notificationCode,
    contactStrategyCode,
    language,
    source,
    sourceId,
    channels,
    primaryPhone,
    alternatePhone,
    email, pushToken,
    domainCode,
    customerId,
    pcfCustomerId,
    accountId,
    tsysCustomerId,
    tsysAccountId,
    productCode,
    lastDigits,
    timezone,
    additionalIdentifiers,
    parameters,
    message_id,
    subscription_name,
    attributes,
    publish_time,
    data
FROM pcb-{env}-landing.domain_communication.COMMUNICATION_REQUEST
WHERE cast(publish_time as date) > '1900-01-01'