SELECT
    CAST(A.ORIG_FI_DT AS DATE)          AS DT_CREATED,
    CAST(A.RPT_NUM AS NUMERIC)          AS RPT_NUM,
    CAST(A.TRACE_ID AS NUMERIC)         AS ITEM_NUM,
    CAST(A.HDR_ID AS NUMERIC)           AS HDR_ID,
    CAST(B.ACCESS_MEDIUM_NO AS STRING)  AS BILLER_ACCT_NUM,
    CAST(A.AMOUNT AS NUMERIC)           AS PYMT_AMT,
    CAST(A.CUST_NM AS STRING)           AS CUST_NM,
    CAST(A.EFF_PYMT_DT AS DATE)         AS PYMT_DT,
    CAST(A.CREATE_DT AS DATETIME)       AS REC_CREATE_TMS,
    CAST(A.UPDATE_USER_ID AS STRING)    AS REC_CHNG_ID,
    CAST(A.UPDATE_DT AS DATETIME)       AS REC_CHNG_TMS
FROM
    `pcb-{env}-landing.domain_payments.TELPAY_PYMT_INB_REQ` A
INNER JOIN
   `pcb-{env}-landing.domain_payments.CARD_DEPOSIT_FULFILLMENT` B
ON
    A.CARD_DEPOSIT_FULFILLMENT_UID = B.CARD_DEPOSIT_FULFILLMENT_UID;
