SELECT
  customerId AS CUSTOMER_ID,
  initiationToken AS INITIATION_TOKEN,
  ELAT.transactionId AS TRANSACTION_ID,
  ELAT.transactionCode AS TRANSACTION_CODE,
  ELAT.description AS DESCRIPTION,
  ELAT.transactionDate AS TRANSACTION_DATE,
  ELAT.debitAmount AS DEBIT_AMOUNT,
  ELAT.creditAmount AS CREDIT_AMOUNT,
  ELAT.accountBalance AS ACCOUNT_BALANCE,
  ELAT.transactionCategory AS TRANSACTION_CATEGORY,
  ELAT.transactionSubCategory AS TRANSACTION_SUB_CATEGORY,
  eftLinkRequestAccount.externalAccountId AS EXTERNAL_ACCOUNT_ID,
  eftLinkRequestAccount.type AS TYPE,
  eftLinkRequestAccount.accountType AS ACCOUNT_TYPE,
  eftLinkRequestAccount.title AS TITLE,
  eftLinkRequestAccount.institutionNumber AS INSTITUTION_NUMBER,
  eftLinkRequestAccount.transitNumber AS TRANSIT_NUMBER,
  eftLinkRequestAccount.accountNumber AS ACCOUNT_NUMBER,
  eftLinkRequestAccount.currency AS CURRENCY,
  eftLinkRequestAccount.category AS CATEGORY,
  eftLinkRequestAccount.overdraftLimit AS OVERDRAFT_LIMIT,
  eftLinkRequestAccount.accountBalance.limit AS ACCOUNT_BALANCE_LIMIT,
  eftLinkRequestAccount.accountBalance.currentBalance AS CURRENT_BALANCE,
  eftLinkRequestAccount.accountBalance.availableBalance AS AVAILABLE_BALANCE,
  eftLinkRequestAccount.accountHolder.customerName AS CUSTOMER_NAME,
  eftLinkRequestAccount.accountHolder.email AS EMAIL,
  eftLinkRequestAccount.accountHolder.phoneNumber AS PHONE_NUMBER,
  eftLinkRequestAccount.accountHolder.accountHolderAddress.streetAddress AS STREET_ADDRESS,
  eftLinkRequestAccount.accountHolder.accountHolderAddress.POBox AS PO_BOX,
  eftLinkRequestAccount.accountHolder.accountHolderAddress.city AS CITY,
  eftLinkRequestAccount.accountHolder.accountHolderAddress.provinceState AS PROVINCE_STATE,
  eftLinkRequestAccount.accountHolder.accountHolderAddress.country AS COUNTRY,
  eftLinkRequestAccount.accountHolder.accountHolderAddress.postalCodeZip AS POSTAL_CODE_ZIP,
  DATETIME(TIMESTAMP(INGESTION_TIMESTAMP), 'America/Toronto') AS RECORD_LOAD_TIMESTAMP,
FROM
  `pcb-{env}-landing.domain_payments.EFT_LINK_REQUEST_ACCOUNT_TRANSACTIONS`,
  UNNEST(eftLinkRequestAccountTransactions) AS ELAT