SELECT
  SEQUENCE_NUMBER,
  TRANSACTION_CODE,
  ACCESS_MEDIUM_NO,
  TRANSACTION_DATE,
  PROCESS_FLAG,
  TRANSACTION_AMOUNT,
  MRCH_NAME,
  CHECK_NUMBER,
  TRACE_ID,
  ALLOW_MER_DESC_ON_CORR,
  REFERENCE_NUMBER,
  REJECT_REASON,
  OVERRIDE_FLAG,
  SOLICIT_OFFER_ID,
  DECLINE_CODE,
  MERCHANT_COUNTRY_CODE,
  MERCHANT_CLASS_SIC_CODE,
  ELIGABLE_FOR_DISCOUNT_QUAL,
  AUTHORIZATION_CODE,
  MAIL_PHONE_ORDER,
  FILE_CREATE_DT,
  REC_LOAD_TIMESTAMP
FROM
  `pcb-{env}-landing.domain_payments.CONVCHKCONF`

UNION DISTINCT
SELECT
  DF5_SEQUENCE_NUMBER AS SEQUENCE_NUMBER,
  DF5_TRANSACTION_CODE AS TRANSACTION_CODE,
  DF5_ACCOUNT_NUMBER AS ACCESS_MEDIUM_NO,
  DF5_TRANSACTION_DATE AS TRANSACTION_DATE,
  DF5_PROCESS_FLAG AS PROCESS_FLAG,
  DF5_TRANSACTION_AMOUNT AS TRANSACTION_AMOUNT,
  DF5_MRCH_NAME AS MRCH_NAME,
  DF5_CHECK_NUMBER AS CHECK_NUMBER,
  DF5_TRACE_ID AS TRACE_ID,
  DF5_ALLOW_MER_DESC_ON_CORR AS ALLOW_MER_DESC_ON_CORR,
  DF5_REFERENCE_NUMBER AS REFERENCE_NUMBER,
  DF5_REJECT_REASON AS REJECT_REASON,
  DF5_OVERRIDE_FLAG AS OVERRIDE_FLAG,
  DF5_SOLICIT_OFFER_ID AS SOLICIT_OFFER_ID,
  DF5_DECLINE_CODE AS DECLINE_CODE,
  DF5_MERCHANT_COUNTRY_CODE AS MERCHANT_COUNTRY_CODE,
  DF5_MERCHANT_CLASS_SIC_CODE AS MERCHANT_CLASS_SIC_CODE,
  DF5_ELIGABLE_FOR_DISCOUNT_QUAL AS ELIGABLE_FOR_DISCOUNT_QUAL,
  DF5_AUTHORIZATION_CODE AS AUTHORIZATION_CODE,
  DF5_MAIL_PHONE_ORDER AS MAIL_PHONE_ORDER,
  FILE_CREATE_DT,
  REC_LOAD_TIMESTAMP
FROM
  `pcb-{env}-landing.domain_payments.CONVCHQ_CONF_DETL` 