WITH LABELED_DATA AS (
    SELECT
        ACCT_CUSTOMER_PREF_CONTACT_UID,
		CONTACT_UID,
		ACCOUNT_CUSTOMER_PREF_UID,
		CREATE_DT,
		CREATE_USER_ID,
		CREATE_FUNCTION_NAME,
		UPDATE_DT,
		UPDATE_USER_ID,
		UPDATE_FUNCTION_NAME,
		MESSAGE_ID,
        ROW_NUMBER() OVER (PARTITION BY ACCT_CUSTOMER_PREF_CONTACT_UID ORDER BY UPDATE_DT DESC)
        AS REC_RANK
    FROM `pcb-{env}-landing.domain_account_management.ACCOUNT_CUSTOMER_PREF_CONTACT` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1
