WITH
  LABELED_DATA AS (
  SELECT
        APPLICATION_PRODUCT_ROLE_UID,
        APPLICATION_PRODUCT_UID,
        ROLE,
        ACCOUNT_CUSTOMER_NO,
        ACCESS_MEDIUM_NO,
        CREATE_DT,
        CREATE_USER_ID,
        CREATE_FUNCTION_NAME,
        UPDATE_DT,
        UPDATE_USER_ID,
        UPDATE_FUNCTION_NAME,
        CURRENT_STATUS,
        ROW_NUMBER() OVER (PARTITION BY APPLICATION_PRODUCT_ROLE_UID ORDER BY UPDATE_DT DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_customer_acquisition.APPLICATION_PRODUCT_ROLE` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1