WITH LABELED_DATA AS (
    SELECT
        FUNDSMOVE_INSTRUCTION_UID,
        ACCOUNT_UID,
        CUSTOMER_BILLER_UID,
        CREATE_DT,
        CREATE_USER_ID,
        CREATE_FUNCTION_NAME,
        UPDATE_DT,
        UPDATE_USER_ID,
        UPDATE_FUNCTION_NAME,
        ROW_NUMBER() OVER (PARTITION BY FUNDSMOVE_INSTRUCTION_UID ORDER BY UPDATE_DT DESC)
        AS REC_RANK
    FROM `pcb-{env}-landing.domain_payments.BILLPAY_INSTRUCTION` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1
