WITH LABELED_DATA AS (
    SELECT
        OFFER_ID,
        CUSTOMER_REF,
        LAST_OFFER_STATUS,
        LAST_OFFER_STATUS_DATE,
        NUMBER_OF_TIME_PRESENTED,
        CUSTOMER_MEDIA_REF,
        PROVINCE,
        PHONE_NUMBER,
        OFFER_SEQ_OVERRIDE,
        LANGUAGE,
        REC_CREATE_TMS,
        REC_CHNG_ID,
        REC_CHNG_TMS,
        ST_CD,
        ST_DT,
        CUSTOMER_OFFER_EXPIRY_DATE,
        PROMO_SOL_CODE,
        ACQ_STRAT_CODE,
        INTERFACE_ID,
        CME_ID,
        ROW_NUMBER() OVER (PARTITION BY CUSTOMER_REF, OFFER_ID ORDER BY LAST_OFFER_STATUS_DATE DESC)
        AS REC_RANK
    FROM `pcb-{env}-landing.domain_marketing.CME_CUSTOMER` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1