SELECT
  IDV_REQUEST_EVT_UID,
  EVENT_TYPE,
  OWNER_TYPE,
  OWNER_ID,
  OCCURRED_ON,
  EVENT_PAYLOAD,
  CREATE_DT,
  CREATE_USER_ID,
  CREATE_FUNCTION_NAME,
  UPDATE_DT,
  UPDATE_USER_ID,
  UPDATE_FUNCTION_NAME,
  INGESTION_TIMESTAMP
FROM pcb-{env}-landing.domain_validation_verification.IDV_EVENT
QUALIFY
  ROW_NUMBER()
    OVER (
      PARTITION BY IDV_REQUEST_EVT_UID
      ORDER BY UPDATE_DT DESC
    )
  = 1
