SELECT
    APPLICANT_IDENTIFIER_UID,
    APPLICANT_IDENTIFIER_NO,
    CUSTOMER_NO,
    APPLICANT_IDENTIFIER_TYPE,
    APPLICANT_IDENTIFIER_VALUE,
    JURISDICTION,
    NATIONALITY,
    GIVEN_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    GENDER,
    ISSUE_DATE,
    DATE_OF_BIRTH,
    EXPIRY_DATE,
    DATA_ENTRY_MODE,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    INGESTION_TIMESTAMP
FROM pcb-{env}-landing.domain_validation_verification.APPLICANT_PERSONAL_IDENTIFIER
QUALIFY ROW_NUMBER() OVER (
              PARTITION BY APPLICANT_IDENTIFIER_UID, APPLICANT_IDENTIFIER_NO
              ORDER BY UPDATE_DT DESC
    ) = 1
