WITH
  LABELED_DATA AS (
  SELECT
    CUSTOMER_HISTORY_UID,
    CUSTOMER_UID,
    PLATFORM_USER_UID,
    GIVEN_NAME,
    SURNAME,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    BIRTH_DT,
    NAME_PREFIX,
    NAME_SUFFIX,
    MIDDLE_NAME,
    ACTION,
    ACTION_DT,
    MESSAGE_ID,
    KYC_ASSESSED_ON,
    FIRST_TIME_LOGIN_COMPLETED_IND,
    ROW_NUMBER() OVER(PARTITION BY CUSTOMER_HISTORY_UID ORDER BY ACTION_DT DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_customer_management.CUSTOMER_HISTORY`)
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1