WITH
  LABELED_DATA AS (
  SELECT
    PUBLICATION_UID,
    REF_PUBLICATION_TYPE_UID,
    PUBLICATION_NO,
    CONTENT,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    PUBLICATION_CLASS,
    CORRELATION_ID,
    TRACEABILITY_ID,
    ROW_NUMBER() OVER (PARTITION BY PUBLICATION_UID ORDER BY CREATE_DT DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_technical.PUBLICATION` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1