SELECT
    ONFIDO_APPLICANT_UID,
    IDV_REQUEST_UID,
    APPLICANT_ID,
    CREATED_AT,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    INGESTION_TIMESTAMP
FROM pcb-{env}-landing.domain_validation_verification.ONFIDO_APPLICANT
QUALIFY ROW_NUMBER() OVER (
              PARTITION BY IDV_REQUEST_UID, ONFIDO_APPLICANT_UID
              ORDER BY UPDATE_DT DESC
    ) = 1
