SELECT
 CAST(EPIR.HDR_ID AS NUMERIC) HRD_ID
,CAST(CDF.ACCESS_MEDIUM_NO AS STRING) ACCT_NUM
,CAST(EPIR.INSTITUTION_ID AS STRING) BANK_ID
,CAST(EPIR.ORIG_FI_DT AS DATE) AS ORIG_FI_DATE
,CAST(EPIR.FI_TRACE_NUM AS STRING) ORIG_CO_SUPP_CD
,CAST(EPIR.EFF_PYMT_DT AS DATE) EFF_ENTRY_DATE
,CAST(EPIR.AMOUNT AS NUMERIC) AMOUNT
,CAST(EPIR.CUST_NM AS STRING) CUST_NAME
,CAST(EPIR.PAYMENT_TRACE_NO AS STRING) TRACE_NUM
,CAST(EPIR.CREATE_DT AS DATETIME) REC_CREATE_TMS
,CAST(EPIR.UPDATE_USER_ID AS STRING) REC_CHNG_ID
,CAST(EPIR.UPDATE_DT AS DATETIME) REC_CHNG_TMS
FROM `pcb-{env}-landing.domain_payments.EDI_PYMT_INB_REQ` EPIR
JOIN `pcb-{env}-landing.domain_payments.CARD_DEPOSIT_FULFILLMENT` CDF
ON EPIR.CARD_DEPOSIT_FULFILLMENT_UID = CDF.CARD_DEPOSIT_FULFILLMENT_UID;