SELECT
  PC_MC_CUST_APPL_ID,
  APA_APP_NUM,
  CARD_CVC,
  CARD_PIN_NM,
  TSYS_ACCT_NUM,
  CARD_EXP_DT,
  CREDIT_LT_AMT,
  MAGSTRIP_DATA,
  REC_CREATE_TMS,
  REC_CHNG_TMS,
  CUST_ID,
  CUST_TYPE,
  ACCOUNT_ID,
  REC_CHNG_ID,
  RECORD_CREATE_TMS,
  RECORD_CHNG_TMS,
  SEQ_ID,
  CUST_SER_ID,
  INGESTION_TIMESTAMP
FROM `pcb-{env}-landing.domain_customer_acquisition.ADM_INST_CARD_INFO`
QUALIFY ROW_NUMBER() OVER (
              PARTITION BY PC_MC_CUST_APPL_ID, APA_APP_NUM,  CUST_ID, TSYS_ACCT_NUM
              ORDER BY RECORD_CHNG_TMS DESC
    ) = 1