SELECT
  IDV_DOCUMENT_UID,
  IDV_SUBMISSION_UID,
  DOCUMENT_TYPE,
  DOCUMENT_ID,
  CREATE_DT,
  CREATE_USER_ID,
  CREATE_FUNCTION_NAME,
  UPDATE_DT,
  UPDATE_USER_ID,
  UPDATE_FUNCTION_NAME,
  INGESTION_TIMESTAMP
FROM `pcb-{env}-landing.domain_validation_verification.IDV_DOCUMENT`
QUALIFY
  ROW_NUMBER()
    OVER (
      PARTITION BY IDV_DOCUMENT_UID, IDV_SUBMISSION_UID
      ORDER BY UPDATE_DT DESC
    )
  = 1
