SELECT
    ONFIDO_CHECK_UID,
    ONFIDO_APPLICANT_UID,
    STATUS,
    RESULT,
    CREATED_AT,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    CHECK_ID,
    INGESTION_TIMESTAMP
FROM pcb-{env}-landing.domain_validation_verification.ONFIDO_CHECK
QUALIFY ROW_NUMBER() OVER (
              PARTITION BY ONFIDO_CHECK_UID, ONFIDO_APPLICANT_UID
              ORDER BY UPDATE_DT DESC
    ) = 1
