SELECT
    t1.*,
    t2.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t3.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t4.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t5.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t6.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t7.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t8.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t9.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID),
    t10.* EXCEPT (MAST_ACCOUNT_ID, REC_LOAD_TIMESTAMP, JOB_ID)
FROM
    `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_01` t1
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_02` t2
        ON t1.MAST_ACCOUNT_ID = t2.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t2.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_03` t3
        ON t1.MAST_ACCOUNT_ID = t3.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t3.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_04` t4
        ON t1.MAST_ACCOUNT_ID = t4.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t4.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_05` t5
        ON t1.MAST_ACCOUNT_ID = t5.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t5.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_06` t6
        ON t1.MAST_ACCOUNT_ID = t6.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t6.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_07` t7
        ON t1.MAST_ACCOUNT_ID = t7.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t7.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_08` t8
        ON t1.MAST_ACCOUNT_ID = t8.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t8.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_09` t9
        ON t1.MAST_ACCOUNT_ID = t9.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t9.JOB_ID
    INNER JOIN `pcb-{env}-landing.domain_scoring.SCORING_PREP_CRED_DAS_HISTORY_BASE_10` t10
        ON t1.MAST_ACCOUNT_ID = t10.MAST_ACCOUNT_ID
        AND t1.JOB_ID = t10.JOB_ID

