WITH
  LABELED_DATA AS (
  SELECT
    DNS_EVENT_ID,
    DNS_CHANNEL_ID,
    MKTG_GRP_ID,
    CONT_ID,
    DNS_END_DT,
    EMAIL_LIST_ID,
    OFFER_ID,
    URL,
    PCFTOKEN,
    UNSUB_EFF_DT,
    UNSUB_END_DT,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    REC_CHNG_ID,
    DNS_EVENT_DETAIL_ID,
    ROW_NUMBER() OVER (PARTITION BY DNS_EVENT_ID, DNS_CHANNEL_ID, MKTG_GRP_ID, DNS_EVENT_DETAIL_ID ORDER BY REC_CREATE_TMS DESC) AS REC_RANK
  FROM `pcb-{env}-landing.domain_dns.DNS_EVENT_DETAIL`) 
  SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1;