WITH LABELED_DATA AS (
SELECT
	CUST_ALERT_NOTIFICATION_UID,
	CUSTOMER_UID,
	NOTIFI_CENTRE_DELIVERY_DT,
	NOTIFICATION_REQUEST_NO,
	CREATE_DT,
	CREATE_USER_ID,
	CREATE_FUNCTION_NAME,
	UPDATE_DT,
	UPDATE_USER_ID,
	UPDATE_FUNCTION_NAME,
	CMS_NOTIFICATION_TEMPLATE_NO,
	NOTIFICATION_CATEGORY_CD,
	ROW_NUMBER() OVER (PARTITION BY CUST_ALERT_NOTIFICATION_UID ORDER BY UPDATE_DT DESC) AS REC_RANK
FROM
	`pcb-{env}-landing.domain_communication.CUST_ALERT_NOTIFICATION`)
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK = 1