WITH
  LABELED_DATA AS (
  SELECT
	INDEX_NUM,
	CUSTOMER_REF_ID,
	ACCOUNT_REF_ID,
	CARD_NUM,
	STATUS,
	CODE_PCB_MATCH,
	CODE_PCB_GEN,
	CODE_SAP_GEN,
	CODE_SAP_MERGE,
	REC_CREATE_TMS,
	REC_CHNG_ID,
	REC_CHNG_TMS,
	PCF_CUST_ID,
	VICTIM_PCF_CUST_ID,
	MESSAGE_ID,
	LYLTY_ACTION_CODE,
	ROW_NUMBER() OVER (PARTITION BY INDEX_NUM ORDER BY REC_CHNG_TMS DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_loyalty.LYLTY_QUE` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1