SELECT
    CARD_NUMBER,
    EVENT_BODY,
    metadata.USERVICE_TRACEABILITY_ID,
    INGESTION_TIMESTAMP
FROM `pcb-{env}-landing.domain_card_management.INSTANT_ISSUANCE_CUSTOMER_INFO_FOR_REQUESTED_CARD`