WITH
  LABELED_DATA AS (
  SELECT
  USER_ID,
  SOURCE_ORG_ID,
  SOURCE_ID,
  SOURCE_DT,
  REC_CREATE_TMS,
  REC_CHNG_TMS,
  REC_CHNG_ID,
  EVIDENCE_ID,
  EVENT_TYPE_ID,
  EVENT_DT,
  DNS_EVENT_ID,
  DNS_ACCT_ID,
  ROW_NUMBER() OVER (PARTITION BY DNS_EVENT_ID ORDER BY REC_CHNG_TMS DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_dns.DNS_EVENT` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1