WITH
  LABELED_DATA AS (
  SELECT
    FUNDSMOVE_SCHEDULE_UID,
    START_DATE,
    FIRST_OCCURS_ON,
    LAST_OCCURS_ON,
    END_DATE,
    DAY_OF_WEEK,
    DAY_OF_MONTH,
    FREQUENCY,
    SAME_DAY_IND,
    CANCELLED_ON,
    CANCELLED_REASON_CD,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    ROW_NUMBER() OVER (PARTITION BY FUNDSMOVE_SCHEDULE_UID ORDER BY UPDATE_DT DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_payments.FUNDSMOVE_SCHEDULE` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1