WITH
  LABELED_DATA AS (
  SELECT
    RECORD_TYPE, 
    INDEX_NUM, 
    CARD_NUMBER, 
    CARD_BIN, 
    CARD_LAST4, 
    FUEL_TYPE, 
    FUEL_NAME, 
    LITERS_PURCHASED, 
    NAME_ON_CARD, 
    CARD_EXPIRY_DATE, 
    TRANSACTION_DATE, 
    TRANSACTION_CODE, 
    TRANSACTION_AMOUNT, 
    MERCHANT_NUMBER, 
    MERCHANT_NAME, 
    MERCHANT_CATEGORY_CODE, 
    MERCHANT_COUNTRY_CODE, 
    TRANSACTION_REF_NUMBER, 
    LOYALTY_REF_NUM, 
    PROMO_CODE, 
    MERCHANT_ID, 
    REC_LOAD_TIMESTAMP, 
    SOURCE_FILENAME,
    ROW_NUMBER() OVER (
      PARTITION BY CARD_NUMBER, TRANSACTION_DATE, TRANSACTION_AMOUNT
    ) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_loyalty.ESSO_FUEL_TRANSACTIONS`
)
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK = 1
