WITH
  LABELED_DATA AS (
SELECT
  ACCOUNT_REF_ID,
  CLOSED_DATE,
  CUSTOMER_REF_ID,
  LOB_NUM,
  OPEN_DATE,
  PCF_CUST_ID,
  PCF_PROD_KEY,
  PCF_SOURCE_CD,
  PRD_NUM,
  PRODUCT_REF_ID,
  REC_CHNG_ID,
  REC_CHNG_TMS,
  REC_CREATE_TMS,
  REL_TYPE,
  STATUS_CD,
  ROW_NUMBER() OVER (PARTITION BY PCF_PROD_KEY ORDER BY REC_CREATE_TMS DESC) AS REC_RANK
FROM `pcb-{env}-landing.domain_loyalty.PCF_PRODUCT`)
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1;