WITH LABELED_DATA AS (
  SELECT
    OFFER_ID,
    CHANNEL,
    MEDIA_REFERENCE,
    LANG,
    TEMPLATE_CODE,
    PRESENTATION_POINT,
    OVERRIDE_POINT,
    REALTIME_FULFILLMENT,
    AGENT_SKILL_SET,
    DNIS_FOR_OFFER,
    ALLOW_CALL_MORNING,
    ALLOW_CALL_AFTERNOON,
    ALLOW_CALL_EVENING,
    ALLOW_CALL_NIGHT,
    ALLOW_CALL_FULLDAY,
    VENDOR_OFFER_CODE,
    REC_CREATE_TMS,
    REC_CHNG_ID,
    REC_CHNG_TMS,
    ST_CD,
    ST_DT,
    AGENT_FULFILLMENT,
    ROW_NUMBER() OVER (PARTITION BY OFFER_ID,CHANNEL  ORDER BY REC_CREATE_TMS DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_marketing.CHANNEL`
)
SELECT
*
EXCEPT(REC_RANK)
FROM
  LABELED_DATA
WHERE
  REC_RANK = 1;