SELECT
      IDV_SUBMISSION_UID,
      IDV_REQUEST_UID,
      IDV_SUBMISSION_TYPE,
      SUBMISSION_DT,
      COMPLETION_DT,
      TSYS_REFERENCE_NUMBER,
      STATUS,
      CREATE_DT,
      CREATE_USER_ID,
      CREATE_FUNCTION_NAME,
      UPDATE_DT,
      UPDATE_USER_ID,
      UPDATE_FUNCTION_NAME,
      INGESTION_TIMESTAMP
FROM pcb-{env}-landing.domain_validation_verification.IDV_SUBMISSION
QUALIFY ROW_NUMBER() OVER (
              PARTITION BY IDV_SUBMISSION_UID, IDV_REQUEST_UID
              ORDER BY UPDATE_DT DESC
    ) = 1
