WITH
  LABELED_DATA AS (
  SELECT
    INDEX_NUM,
    CUSTOMER_REF_ID,
    ACCOUNT_REF_ID,
    CARD_NUMBER,
    CARD_BIN,
    CARD_LAST4,
    SOURCE_CD,
    NAME_ON_CARD,
    TRANSACTION_DATE,
    TRANSACTION_CODE,
    TRANSACTION_AMOUNT,
    POST_DATE,
    MERCHANT_NAME,
    MERCHANT_NUMBER,
    MERCHANT_CATEGORY_CODE,
    MERCHANT_COUNTRY_CODE,
    TRANSACTION_REF_NUMBER,
    LOYALTY_REF_NUM,
    PROMO_CODE,
    INTERFACE_ID,
    PROCESS_FLAG,
    PROCESS_DT,
    REC_CREATE_TMS,
    REC_LOAD_TMS,
    REC_CHNG_ID,
    REC_CHNG_TMS,
    PCF_PRD,
    MERCHANT_ID,
    PROCESS_NUM,
    STR_NUM,
    TRANS_REF_ID,
    BKUP_PROCESS_FLAG,
    AT31_MERCHANT_CATEGORY_CODE,
    ROW_NUMBER() OVER (PARTITION BY INDEX_NUM ORDER BY PROCESS_DT DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_loyalty.POINTS_STAGING` )
SELECT
  * EXCEPT(REC_RANK)
FROM
  LABELED_DATA
WHERE
  REC_RANK=1