WITH
  LABELED_DATA AS (
  SELECT
    EMAIL_CONTACT_HISTORY_UID,
    CONTACT_UID,
    EMAIL_ADDRESS,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    ACTION,
    ACTION_DT,
    MESSAGE_ID,
    EMAIL_VERIFIED_IND,
    ROW_NUMBER() OVER (PARTITION BY EMAIL_CONTACT_HISTORY_UID ORDER BY ACTION_DT DESC) AS REC_RANK
  FROM
    `pcb-{env}-landing.domain_customer_management.EMAIL_CONTACT_HISTORY` )
SELECT * EXCEPT(REC_RANK) FROM LABELED_DATA WHERE REC_RANK=1