SELECT * EXCEPT (METADATA)
FROM `pcb-{env}-landing.domain_customer_acquisition.RE_IDV_REQUIRED_CUSTOMER`
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTOMER_UID ORDER BY STATUS_CHANGE_TIMESTAMP DESC)=1