UPDATE pcb-{env}-landing.domain_account_management.PC_DOWNLOAD
SET
     MIN_DUE = SAFE_DIVIDE(MIN_DUE, 100),
     BALANCE_CURRENT = SAFE_DIVIDE(BALANCE_CURRENT, 100)
WHERE DATE(FILE_CREATE_DT) < '2025-09-17'