INSERT INTO
  pcb-{env}-landing.domain_account_management.EVENTS
SELECT
  EV3_EL01_TYPE_EVENT,
  EV3_EL01_CLIENT_NUM,
  EV3_AM00_ACCOUNT_ID,
  EV3_EL01_JULIAN_DATE,
  EV3_EL01_TIME_EVNT_UNPCKD,
  EV3_EL01_CICS_TRANS_CODE,
  EV3_EL01_OPERATOR_ID,
  EV3_EL01_CUSTOMER_ID,
  EV3_EL01_ACCOUNT_NUMBER,
  EV3_EL01_TRACKING_NUM,
  EV3_EL01_TSYS_PROD_CODE,
  EV3_EL01_CLIENT_PROD_CODE,
  EV3_EL01_PROVIDER_ID,
  EV3_EL01_CUST_TYPE,
  EV3_EL01_TIME_EVENT,
  EV3_AM00_APP_SUFFIX,
  RANK() OVER(ORDER BY EV3_EL01_TYPE_EVENT, FILE_RECORD_NBR) AS FILE_RECORD_NBR,
  EV3_EVENT_FIELD_NUM,
  EV3_EVENT_OLD_DATA,
  EV3_EVENT_NEW_DATA,
  FILE_CREATE_DT,
  REC_LOAD_TIMESTAMP
FROM
  pcb-{env}-landing.domain_account_management.EVENTS_BACKUP;
