CREATE OR REPLACE TABLE `pcb-{env}-processing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM3B_DEDUP` 
OPTIONS(
  expiration_timestamp = TIMESTAMP_ADD(
    TIMESTAMP(CURRENT_DATETIME('America/Toronto')), 
    INTERVAL 6 HOUR
    )
)
AS
with dedup_3b_jul as (
SELECT
MAST_ACCOUNT_ID,
MAST_REC_TYPE,
AM00_CLIENT_NUM,
AM00_APPLICATION_NUM,
AM00_APPLICATION_SUFFIX,
AM0A_ACCOUNT_NUM,
AM3B_SEGMENT_LENGTH,
AM3B_SECURITY_SEGMENT_TYPE,
AM3B_PHONE_POLICE_LENGTH,
AM3B_PHONE_REPORTED_BY_LENGTH,
AM3B_OPERATOR_ID,
AM3B_REPORTED_BY_NAME,
AM3B_CITY_POLICE,
AM3B_STATE_PROV_CODE_POLICE,
AM3B_CHECKS_MISSING,
AM3B_LOCATION_REPORTED_LST_USE,
AM3B_AUTO_MANUAL_DELETE,
AM3B_TAKEN_BY_TSYS,
AM3B_POLICE_CASE_NUM,
AM3B_OPERATOR_ID_DELETE,
AM3B_PHONE_REPORTED_BY,
AM3B_PHONE_POLICE,
AM3B_DATE_SECURITY_RPT_TAKEN,
AM3B_TIME_SECURITY_RPT_TAKEN,
AM3B_DATE_REPORTED_LAST_USED,
AM3B_TIME_REPORTED_LAST_USED,
AM3B_DATE_SECURITY_RPT_ENTERED,
AM3B_TIME_SECURITY_RPT_ENTERED,
AM3B_DATE_DISCOV_MISSING,
AM3B_TIME_DISCOV_MISSING,
AM3B_DATE_REPORT_DELETE,
AM3B_AMT_REPORTED_LAST_USED,
FILE_CREATE_DT,
REC_LOAD_TIMESTAMP,
ROW_NUMBER() OVER(PARTITION BY MAST_ACCOUNT_ID, AM00_APPLICATION_SUFFIX, AM0A_ACCOUNT_NUM, AM3B_TIME_SECURITY_RPT_ENTERED, AM3B_SECURITY_SEGMENT_TYPE) as rn
FROM 
`pcb-{env}-landing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM3B`
WHERE FILE_CREATE_DT = '2025-07-31'
),
dedup_3b_aug as (
SELECT
MAST_ACCOUNT_ID,
MAST_REC_TYPE,
AM00_CLIENT_NUM,
AM00_APPLICATION_NUM,
AM00_APPLICATION_SUFFIX,
AM0A_ACCOUNT_NUM,
AM3B_SEGMENT_LENGTH,
AM3B_SECURITY_SEGMENT_TYPE,
AM3B_PHONE_POLICE_LENGTH,
AM3B_PHONE_REPORTED_BY_LENGTH,
AM3B_OPERATOR_ID,
AM3B_REPORTED_BY_NAME,
AM3B_CITY_POLICE,
AM3B_STATE_PROV_CODE_POLICE,
AM3B_CHECKS_MISSING,
AM3B_LOCATION_REPORTED_LST_USE,
AM3B_AUTO_MANUAL_DELETE,
AM3B_TAKEN_BY_TSYS,
AM3B_POLICE_CASE_NUM,
AM3B_OPERATOR_ID_DELETE,
AM3B_PHONE_REPORTED_BY,
AM3B_PHONE_POLICE,
AM3B_DATE_SECURITY_RPT_TAKEN,
AM3B_TIME_SECURITY_RPT_TAKEN,
AM3B_DATE_REPORTED_LAST_USED,
AM3B_TIME_REPORTED_LAST_USED,
AM3B_DATE_SECURITY_RPT_ENTERED,
AM3B_TIME_SECURITY_RPT_ENTERED,
AM3B_DATE_DISCOV_MISSING,
AM3B_TIME_DISCOV_MISSING,
AM3B_DATE_REPORT_DELETE,
AM3B_AMT_REPORTED_LAST_USED,
FILE_CREATE_DT,
REC_LOAD_TIMESTAMP,
ROW_NUMBER() OVER(PARTITION BY MAST_ACCOUNT_ID, AM00_APPLICATION_SUFFIX, AM0A_ACCOUNT_NUM, AM3B_TIME_SECURITY_RPT_ENTERED, AM3B_SECURITY_SEGMENT_TYPE) as rn
FROM 
`pcb-{env}-landing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM3B`
WHERE FILE_CREATE_DT = '2025-08-29'
),
dedup_3b_sep as (
SELECT
MAST_ACCOUNT_ID,
MAST_REC_TYPE,
AM00_CLIENT_NUM,
AM00_APPLICATION_NUM,
AM00_APPLICATION_SUFFIX,
AM0A_ACCOUNT_NUM,
AM3B_SEGMENT_LENGTH,
AM3B_SECURITY_SEGMENT_TYPE,
AM3B_PHONE_POLICE_LENGTH,
AM3B_PHONE_REPORTED_BY_LENGTH,
AM3B_OPERATOR_ID,
AM3B_REPORTED_BY_NAME,
AM3B_CITY_POLICE,
AM3B_STATE_PROV_CODE_POLICE,
AM3B_CHECKS_MISSING,
AM3B_LOCATION_REPORTED_LST_USE,
AM3B_AUTO_MANUAL_DELETE,
AM3B_TAKEN_BY_TSYS,
AM3B_POLICE_CASE_NUM,
AM3B_OPERATOR_ID_DELETE,
AM3B_PHONE_REPORTED_BY,
AM3B_PHONE_POLICE,
AM3B_DATE_SECURITY_RPT_TAKEN,
AM3B_TIME_SECURITY_RPT_TAKEN,
AM3B_DATE_REPORTED_LAST_USED,
AM3B_TIME_REPORTED_LAST_USED,
AM3B_DATE_SECURITY_RPT_ENTERED,
AM3B_TIME_SECURITY_RPT_ENTERED,
AM3B_DATE_DISCOV_MISSING,
AM3B_TIME_DISCOV_MISSING,
AM3B_DATE_REPORT_DELETE,
AM3B_AMT_REPORTED_LAST_USED,
FILE_CREATE_DT,
REC_LOAD_TIMESTAMP,
ROW_NUMBER() OVER(PARTITION BY MAST_ACCOUNT_ID, AM00_APPLICATION_SUFFIX, AM0A_ACCOUNT_NUM, AM3B_TIME_SECURITY_RPT_ENTERED, AM3B_SECURITY_SEGMENT_TYPE) as rn
FROM 
`pcb-{env}-landing.domain_account_management.TSYS_PCB_MC_ACCTMASTER_MONTHLY_AM3B`
WHERE FILE_CREATE_DT = '2025-09-29'
)
SELECT *EXCEPT(rn)
FROM
dedup_3b_jul WHERE rn = 1
UNION ALL
SELECT *EXCEPT(rn) 
FROM
dedup_3b_aug WHERE rn = 1
UNION ALL
SELECT *EXCEPT(rn)
FROM
dedup_3b_sep WHERE rn = 1