-- Backfill missing ADM_INST_CARD_INFO records from DB563
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_customer_acquisition.ADM_INST_CARD_INFO` (
    PC_MC_CUST_APPL_ID,
    APA_APP_NUM,
    CARD_CVC,
    CARD_PIN_NM,
    TSYS_ACCT_NUM,
    CARD_EXP_DT,
    CREDIT_LT_AMT,
    MAGSTRIP_DATA,
    REC_CREATE_TMS,
    REC_CHNG_TMS,
    CUST_ID,
    CUST_TYPE,
    ACCOUNT_ID,
    REC_CHNG_ID,
    RECORD_CREATE_TMS,
    RECORD_CHNG_TMS,
    SEQ_ID,
    CUST_SER_ID
)
SELECT
    backfill_data.PC_MC_CUST_APPL_ID,
    backfill_data.APA_APP_NUM,
    backfill_data.CARD_CVC,
    backfill_data.CARD_PIN_NM,
    backfill_data.TSYS_ACCT_NUM,
    backfill_data.CARD_EXP_DT,
    backfill_data.CREDIT_LT_AMT,
    backfill_data.MAGSTRIP_DATA,
    backfill_data.REC_CREATE_TMS,
    backfill_data.REC_CHNG_TMS,
    backfill_data.CUST_ID,
    backfill_data.CUST_TYPE,
    backfill_data.ACCOUNT_ID,
    backfill_data.REC_CHNG_ID,
    backfill_data.RECORD_CREATE_TMS,
    backfill_data.RECORD_CHNG_TMS,
    backfill_data.SEQ_ID,
    backfill_data.CUST_SER_ID
FROM
    `pcb-{env}-processing.domain_customer_acquisition.ADM_INST_CARD_INFO_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_customer_acquisition.ADM_INST_CARD_INFO` existing_data
    ON backfill_data.APA_APP_NUM = existing_data.APA_APP_NUM
    AND backfill_data.CUST_ID = existing_data.CUST_ID
WHERE
    existing_data.APA_APP_NUM IS NULL;  -- Only insert missing records