-- Backfill missing ONFIDO_CHECK records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_validation_verification.ONFIDO_CHECK` (
    ONFIDO_CHECK_UID,
    ONFIDO_APPLICANT_UID,
    STATUS,
    RESULT,
    CREATED_AT,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    CHECK_ID
)
SELECT
    backfill_data.ONFIDO_CHECK_UID,
    backfill_data.ONFIDO_APPLICANT_UID,
    backfill_data.STATUS,
    backfill_data.RESULT,
    backfill_data.CREATED_AT,
    backfill_data.CREATE_DT,
    backfill_data.CREATE_USER_ID,
    backfill_data.CREATE_FUNCTION_NAME,
    backfill_data.UPDATE_DT,
    backfill_data.UPDATE_USER_ID,
    backfill_data.UPDATE_FUNCTION_NAME,
    backfill_data.CHECK_ID
FROM
    `pcb-{env}-processing.domain_validation_verification.ONFIDO_CHECK_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_validation_verification.ONFIDO_CHECK` existing_data
    ON backfill_data.ONFIDO_CHECK_UID = existing_data.ONFIDO_CHECK_UID
    AND backfill_data.ONFIDO_APPLICANT_UID = existing_data.ONFIDO_APPLICANT_UID
WHERE
    existing_data.ONFIDO_CHECK_UID IS NULL;  -- Only insert missing records