INSERT INTO pcb-{env}-landing.domain_customer_acquisition.TRANSUNION_PCMCEDA_IDENTIFICATION
SELECT
  'D' AS RECORD_TYPE,
  EXTERNAL_ID AS EXTERNAL_APPLICATION_ID,
  APP AS APPLICATION_ID,
  SCORE,
  DECISION,
  QDT AS APPLICATION_CREATED,
  ADT AS APPLICATION_GENERATED,
  SCORE_FLAG AS EXAM_FLAG,
  NO_SCORE_FLAG AS EXAM_STATUS,
  VERSION AS SSID_VERSION,
  PROCESS AS SSID,
  LAST_NAME,
  FIRST_NAME,
  DOB AS DATE_OF_BIRTH,
  PHONE AS PHONE_NUMBER,
  NUM_QUESTIONS AS NUMBER_OF_QUESTIONS,
  QID1 AS QUESTION_1_ID,
  TXT1 AS QUESTION_1_TEXT,
  PF1 AS QUESTION_1_STATUS,
  QID2 AS QUESTION_2_ID,
  TXT2 AS QUESTION_2_TEXT,
  PF2 AS QUESTION_2_STATUS,
  QID3 AS QUESTION_3_ID,
  TXT3 AS QUESTION_3_TEXT,
  PF3 AS QUESTION_3_STATUS,
  QID4 AS QUESTION_4_ID,
  TXT4 AS QUESTION_4_TEXT,
  PF4 AS QUESTION_4_STATUS,
  'HISTORY' AS SOURCE_FILENAME,
  CURRENT_TIMESTAMP() AS REC_LOAD_TIMESTAMP
FROM
  pcb-{env}-landing.domain_customer_acquisition.PERM_IDENT AS A
  WHERE NOT EXISTS (
  SELECT
    1
  FROM
    pcb-{env}-landing.domain_customer_acquisition.TRANSUNION_PCMCEDA_IDENTIFICATION B
  WHERE
    B.EXTERNAL_APPLICATION_ID = A.EXTERNAL_ID)