-- Backfill missing IDV_DOCUMENT records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_validation_verification.IDV_DOCUMENT` (
    IDV_DOCUMENT_UID,
    IDV_SUBMISSION_UID,
    DOCUMENT_TYPE,
    DOCUMENT_ID,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME
)
SELECT
    backfill_data.IDV_DOCUMENT_UID,
    backfill_data.IDV_SUBMISSION_UID,
    backfill_data.DOCUMENT_TYPE,
    backfill_data.DOCUMENT_ID,
    backfill_data.CREATE_DT,
    backfill_data.CREATE_USER_ID,
    backfill_data.CREATE_FUNCTION_NAME,
    backfill_data.UPDATE_DT,
    backfill_data.UPDATE_USER_ID,
    backfill_data.UPDATE_FUNCTION_NAME
FROM
    `pcb-{env}-processing.domain_validation_verification.IDV_DOCUMENT_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_validation_verification.IDV_DOCUMENT` existing_data
    ON backfill_data.IDV_DOCUMENT_UID = existing_data.IDV_DOCUMENT_UID
    AND backfill_data.IDV_SUBMISSION_UID = existing_data.IDV_SUBMISSION_UID
WHERE
    existing_data.IDV_DOCUMENT_UID IS NULL;  -- Only insert missing records