-- Backfill missing APPLICANT_PERSONAL_IDENTIFIER records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_validation_verification.APPLICANT_PERSONAL_IDENTIFIER` (
    APPLICANT_IDENTIFIER_UID,
    APPLICANT_IDENTIFIER_NO,
    CUSTOMER_NO,
    APPLICANT_IDENTIFIER_TYPE,
    APPLICANT_IDENTIFIER_VALUE,
    JURISDICTION,
    NATIONALITY,
    GIVEN_NAME,
    MIDDLE_NAME,
    LAST_NAME,
    GENDER,
    ISSUE_DATE,
    DATE_OF_BIRTH,
    EXPIRY_DATE,
    DATA_ENTRY_MODE,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME
)
SELECT
    backfill_data.APPLICANT_IDENTIFIER_UID,
    backfill_data.APPLICANT_IDENTIFIER_NO,
    backfill_data.CUSTOMER_NO,
    backfill_data.APPLICANT_IDENTIFIER_TYPE,
    backfill_data.APPLICANT_IDENTIFIER_VALUE,
    backfill_data.JURISDICTION,
    backfill_data.NATIONALITY,
    backfill_data.GIVEN_NAME,
    backfill_data.MIDDLE_NAME,
    backfill_data.LAST_NAME,
    backfill_data.GENDER,
    backfill_data.ISSUE_DATE,
    backfill_data.DATE_OF_BIRTH,
    backfill_data.EXPIRY_DATE,
    backfill_data.DATA_ENTRY_MODE,
    backfill_data.CREATE_DT,
    backfill_data.CREATE_USER_ID,
    backfill_data.CREATE_FUNCTION_NAME,
    backfill_data.UPDATE_DT,
    backfill_data.UPDATE_USER_ID,
    backfill_data.UPDATE_FUNCTION_NAME
FROM
    `pcb-{env}-processing.domain_validation_verification.APPLICANT_PERSONAL_IDENTIFIER_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_validation_verification.APPLICANT_PERSONAL_IDENTIFIER` existing_data
    ON backfill_data.APPLICANT_IDENTIFIER_UID = existing_data.APPLICANT_IDENTIFIER_UID
    AND backfill_data.APPLICANT_IDENTIFIER_NO = existing_data.APPLICANT_IDENTIFIER_NO
WHERE
    existing_data.APPLICANT_IDENTIFIER_UID IS NULL;  -- Only insert missing records