-- Backfill missing IDV_SUBMISSION records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_validation_verification.IDV_SUBMISSION` (
    IDV_SUBMISSION_UID,
    IDV_REQUEST_UID,
    IDV_SUBMISSION_TYPE,
    SUBMISSION_DT,
    COMPLETION_DT,
    TSYS_REFERENCE_NUMBER,
    STATUS,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME
)
SELECT
    backfill_data.IDV_SUBMISSION_UID,
    backfill_data.IDV_REQUEST_UID,
    backfill_data.IDV_SUBMISSION_TYPE,
    backfill_data.SUBMISSION_DT,
    backfill_data.COMPLETION_DT,
    backfill_data.TSYS_REFERENCE_NUMBER,
    backfill_data.STATUS,
    backfill_data.CREATE_DT,
    backfill_data.CREATE_USER_ID,
    backfill_data.CREATE_FUNCTION_NAME,
    backfill_data.UPDATE_DT,
    backfill_data.UPDATE_USER_ID,
    backfill_data.UPDATE_FUNCTION_NAME
FROM
    `pcb-{env}-processing.domain_validation_verification.IDV_SUBMISSION_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_validation_verification.IDV_SUBMISSION` existing_data
    ON backfill_data.IDV_SUBMISSION_UID = existing_data.IDV_SUBMISSION_UID
    AND backfill_data.IDV_REQUEST_UID = existing_data.IDV_REQUEST_UID
WHERE
    existing_data.IDV_SUBMISSION_UID IS NULL;  -- Only insert missing records