UPDATE
  pcb-prod-landing.domain_customer_acquisition.APPLICATION_SUBMISSION_PAYLOAD AS A
SET
  A.interceptorId = CAST(B.INTERCEPTOR_ID AS STRING)
FROM (
  SELECT
    DISTINCT ASP.AGENTID,
    IA.PLATFORM_USER_UID AS INTERCEPTOR_ID
  FROM
    pcb-prod-landing.domain_customer_acquisition.APPLICATION_SUBMISSION_PAYLOAD AS ASP
  LEFT JOIN
    pcb-prod-curated.domain_customer_service.INTERCEPTOR_AGENT AS IA
  ON
    IA.INTERCEPTOR_AGENT_NO = ASP.AGENTID
  WHERE
    ASP.AGENTID IS NOT NULL
    AND IA.PLATFORM_USER_UID IS NOT NULL ) AS B
WHERE
  A.AGENTID = B.AGENTID;