UPDATE pcb-{env}-landing.domain_customer_acquisition.APPLICATION_PRODUCT
SET CURRENT_STATUS = 'EXPIRED',
UPDATE_DT = CURRENT_DATETIME(),
UPDATE_FUNCTION_NAME = 'PCGS_5802_mark_product_exprired',
UPDATE_USER_ID = 'PCGS_5802_mark_product_exprired'
WHERE CURRENT_STATUS != 'EXPIRED'
AND APPLICATION_PRODUCT_UID in (6114836, 6114837);