-- Backfill missing IDV_EVENT records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_validation_verification.IDV_EVENT` (
    IDV_REQUEST_EVT_UID,
	EVENT_TYPE,
	OWNER_TYPE,
	OWNER_ID,
	OCCURRED_ON,
	EVENT_PAYLOAD,
	CREATE_DT,
	CREATE_USER_ID,
	CREATE_FUNCTION_NAME,
	UPDATE_DT,
	UPDATE_USER_ID,
	UPDATE_FUNCTION_NAME
)
SELECT
    backfill_data.IDV_REQUEST_EVT_UID,
    backfill_data.EVENT_TYPE,
    backfill_data.OWNER_TYPE,
    backfill_data.OWNER_ID,
    backfill_data.OCCURRED_ON,
    backfill_data.EVENT_PAYLOAD,
    backfill_data.CREATE_DT,
    backfill_data.CREATE_USER_ID,
    backfill_data.CREATE_FUNCTION_NAME,
    backfill_data.UPDATE_DT,
    backfill_data.UPDATE_USER_ID,
    backfill_data.UPDATE_FUNCTION_NAME
FROM
    `pcb-{env}-processing.domain_validation_verification.IDV_EVENT_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_validation_verification.IDV_EVENT` existing_data
    ON backfill_data.IDV_REQUEST_EVT_UID = existing_data.IDV_REQUEST_EVT_UID
WHERE
    existing_data.IDV_REQUEST_EVT_UID IS NULL;  -- Only insert missing records