UPDATE pcb-{env}-landing.domain_customer_acquisition.APPLICATION_PRODUCT
SET CURRENT_STATUS = 'EXPIRED',
UPDATE_DT = CURRENT_DATETIME(),
UPDATE_FUNCTION_NAME = 'PCGS_6007_mark_product_exprired',
UPDATE_USER_ID = 'PCGS_6007_mark_product_exprired'
WHERE CURRENT_STATUS != 'EXPIRED'
AND APPLICATION_PRODUCT_UID = 6108516;