-- Backfill missing ONFIDO_APPLICANT records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_validation_verification.ONFIDO_APPLICANT` (
    ONFIDO_APPLICANT_UID,
    IDV_REQUEST_UID,
    APPLICANT_ID,
    CREATED_AT,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME
)
SELECT
    backfill_data.ONFIDO_APPLICANT_UID,
    backfill_data.IDV_REQUEST_UID,
    backfill_data.APPLICANT_ID,
    backfill_data.CREATED_AT,
    backfill_data.CREATE_DT,
    backfill_data.CREATE_USER_ID,
    backfill_data.CREATE_FUNCTION_NAME,
    backfill_data.UPDATE_DT,
    backfill_data.UPDATE_USER_ID,
    backfill_data.UPDATE_FUNCTION_NAME
FROM
    `pcb-{env}-processing.domain_validation_verification.ONFIDO_APPLICANT_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_validation_verification.ONFIDO_APPLICANT` existing_data
    ON backfill_data.ONFIDO_APPLICANT_UID = existing_data.ONFIDO_APPLICANT_UID
    AND backfill_data.IDV_REQUEST_UID = existing_data.IDV_REQUEST_UID
WHERE
    existing_data.ONFIDO_APPLICANT_UID IS NULL;  -- Only insert missing records