-- Backfill missing APPLICATION_PRODUCT records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only update records that NULL values in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

UPDATE
  `pcb-{env}-landing.domain_customer_acquisition.APPLICATION_PRODUCT` AS AP
SET
  AP.APPLICATION_SUBMISSION_UID = AP_BACKFILL.APPLICATION_SUBMISSION_UID,
  AP.CREATE_DT = AP_BACKFILL.CREATE_DT
FROM
  `pcb-{env}-processing.domain_customer_acquisition.APPLICATION_PRODUCT_BACKFILL` AS AP_BACKFILL
WHERE
  AP.APPLICATION_PRODUCT_UID = AP_BACKFILL.APPLICATION_PRODUCT_UID
  AND AP.APPLICATION_SUBMISSION_UID IS NULL;