-- Backfill missing IDV_REQUEST records from CockroachDB
-- Load data from Processing Zone temp table to Landing Zone
-- Only inserts records that don't already exist in Landing (based on composite key)
-- METADATA will be NULL (not specified), INGESTION_TIMESTAMP will be auto-generated by table default

INSERT INTO `pcb-{env}-landing.domain_validation_verification.IDV_REQUEST` (
    IDV_REQUEST_UID,
    IDV_REQUEST_NO,
    REQUEST_DT,
    REQUESTOR_TYPE,
    REQUESTOR_NO,
    ALERT_NO,
    DIGITAL_IDV_ELIGIBLE,
    FIRST_NAME,
    LAST_NAME,
    DATE_OF_BIRTH,
    EMAIL,
    CREATE_DT,
    CREATE_USER_ID,
    CREATE_FUNCTION_NAME,
    UPDATE_DT,
    UPDATE_USER_ID,
    UPDATE_FUNCTION_NAME,
    LANGUAGE,
    CORRESPONDENCE_SENT_DT
)
SELECT
    backfill_data.IDV_REQUEST_UID,
    backfill_data.IDV_REQUEST_NO,
    backfill_data.REQUEST_DT,
    backfill_data.REQUESTOR_TYPE,
    backfill_data.REQUESTOR_NO,
    backfill_data.ALERT_NO,
    backfill_data.DIGITAL_IDV_ELIGIBLE,
    backfill_data.FIRST_NAME,
    backfill_data.LAST_NAME,
    backfill_data.DATE_OF_BIRTH,
    backfill_data.EMAIL,
    backfill_data.CREATE_DT,
    backfill_data.CREATE_USER_ID,
    backfill_data.CREATE_FUNCTION_NAME,
    backfill_data.UPDATE_DT,
    backfill_data.UPDATE_USER_ID,
    backfill_data.UPDATE_FUNCTION_NAME,
    backfill_data.LANGUAGE,
    backfill_data.CORRESPONDENCE_SENT_DT
FROM
    `pcb-{env}-processing.domain_validation_verification.IDV_REQUEST_BACKFILL` backfill_data
LEFT JOIN
    `pcb-{env}-landing.domain_validation_verification.IDV_REQUEST` existing_data
    ON backfill_data.IDV_REQUEST_UID = existing_data.IDV_REQUEST_UID
    AND backfill_data.IDV_REQUEST_NO = existing_data.IDV_REQUEST_NO
WHERE
    existing_data.IDV_REQUEST_UID IS NULL;  -- Only insert missing records