INSERT INTO
  pcb-{env}-landing.domain_ledger.GENERALLEDGER
SELECT SEQUENCE_NUMBER,
       RECORD_INDICATOR,
       GL_TABLE_NUMBER,
       GL_TABLE_BANK_NUMBER,
       GL_KEY_ID,
       GL_KEY_DESCRIPTION,
       COST_RESPONSIBILITY_CENTER,
       GL_ACCOUNT_NUMBER,
       NUMBER_OF_TRANSACTIONS,
       TRANSACTION_AMOUNT,
       TRANSACTION_TYPE,
       TRANSACTION_CURRENCY,
       BANK_CORRELATION_VALUE,
       PARSE_DATETIME('%m%d%Y', CURRENT_PROCESSING_DATE) AS CURRENT_PROCESSING_DATE,
       TOTAL_IDENTIFIER,
       FILE_CREATE_DT,
       REC_LOAD_TIMESTAMP
FROM
  pcb-{env}-landing.domain_payments.TS2_GL_DETL
WHERE
  FILE_CREATE_DT > (SELECT MAX(FILE_CREATE_DT) FROM pcb-{env}-landing.domain_ledger.GENERALLEDGER );
