INSERT INTO `pcb-{env}-landing.domain_account_management.TOKEN_NOTIFY` (
  ACCT_NBR, TKX_DATE, TKX_TIME, TKX_NAME, EMAIL_ADDR1, EMAIL_ADDR2,
  ADDR1, ADDR2, CITY, STATE_PROV, POSTAL_CODE, COUNTRY_CODE, COUNTY_NAME,
  TOKEN, TOKEN_ASSURE_LVL, TOKEN_REQUEST_ID, TOKEN_MSG_TYPE, NBR_ACT_ATTEMPTS,
  TOKEN_EXP_DATE, TOKEN_EVT_RSN_CODE, TOKEN_EVT_STATUS, TOKEN_TRANS_IND,
  PROVIDER_ID1, PROVIDER_ID2, PROVIDER_ID3, ACCT_ID, STMT_HOLD_CODE,
  LANGUAGE_CODE, RETURN_MAIL_STATUS, REC_CHNG_TMS, PROCESS_NUM, REC_LOAD_TIMESTAMP,
  FILE_CREATE_DT
)
SELECT
  ACCOUNT_NUMBER AS ACCT_NBR,
  SAFE_CAST(DATE AS NUMERIC) AS TKX_DATE,
  `TIME` AS TKX_TIME,
  CARDHOLDER_NAME AS TKX_NAME,
  EMAIL_ADDR1,
  EMAIL_ADDR2,
  ADDRESS_LINE1 AS ADDR1,
  ADDRESS_LINE2 AS ADDR2,
  CITY,
  STATE_PROVINCE_CODE AS STATE_PROV,
  POSTAL_CODE,
  COUNTRY_CODE,
  COUNTY_NAME,
  TOKEN,
  TOKEN_ASSURANCE_LEVEL AS TOKEN_ASSURE_LVL,
  TOKEN_REQUEST_ID,
  TOKEN_MESSAGE_TYPE AS TOKEN_MSG_TYPE,
  SAFE_CAST(NUMBER_OF_ACTIVATION_ATTEMPTS AS NUMERIC) AS NBR_ACT_ATTEMPTS,
  TOKEN_EXPIRATION_DATE AS TOKEN_EXP_DATE,
  TOKEN_EVENT_REASON_CODE AS TOKEN_EVT_RSN_CODE,
  TOKEN_EVENT_STATUS AS TOKEN_EVT_STATUS,
  TOKEN_TRANSACTION_INDICATOR AS TOKEN_TRANS_IND,
  PROVIDER_ID1,
  PROVIDER_ID2,
  PROVIDER_ID3,
  SAFE_CAST(ACCOUNT_ID AS NUMERIC) AS ACCT_ID,
  SAFE_CAST(STATEMENT_HOLD_CODE AS NUMERIC) AS STMT_HOLD_CODE,
  LANGUAGE_PREFERENCE AS LANGUAGE_CODE,
  RETURN_MAIL_STATUS,
  REC_LOAD_TIMESTAMP AS REC_CHNG_TMS,
  CAST(FORMAT_DATE('%y%m%d', CURRENT_DATE('America/Toronto')) AS NUMERIC) AS PROCESS_NUM,
  REC_LOAD_TIMESTAMP,
  FILE_CREATE_DT
FROM `pcb-{env}-landing.domain_payments.TS2_TOKEN_NOTIFY_DETL`
WHERE
  FILE_CREATE_DT > (
    SELECT COALESCE(MAX(FILE_CREATE_DT))
    FROM `pcb-{env}-landing.domain_account_management.TOKEN_NOTIFY`
  );