loyalty_profile_remaining_segment_kafka_writer:
  default_args:
    owner: "team-convergence-alerts"
    capability: "Loyalty"
    severity: "P2"
    sub_capability: "Rewards/Loyalty"
    business_impact: "This will impact any Loblaw partner using PAR for awarding points. Customer wallet associated to PAR value will not be retrieved and points will not be awarded to the customer."
    customer_impact: "Customer will miss earning PC points and offers."
  file_uris:
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/sync_loyalty_profile/application.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/sync_loyalty_profile/schema_mapping.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/sync_loyalty_profile/sync_loyalty_profile_key.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/sync_loyalty_profile/sync_loyalty_profile_value.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/sync_loyalty_profile/customer_identifier_file_schema.avsc
  application_config: application.yaml
  args:
    pcb.file.kafka.connector.avro.key.schema.path: sync_loyalty_profile_key.avsc
    pcb.file.kafka.connector.avro.value.schema.path: sync_loyalty_profile_value.avsc
    pcb.file.kafka.connector.file.kafka.schema.mapping.path: schema_mapping.yaml
    pcb.file.kafka.connector.file.type: PARQUET
    pcb.file.kafka.connector.file.path:
      file_source_bigquery: true
    pcb.file.kafka.connector.kafka.key: customerId
    pcb.file.kafka.connector.kafka.key.part.of.dataset: true
    pcb.file.kafka.connector.schema.file.path: customer_identifier_file_schema.avsc
  dag:
    kafka_writer_task: kafka_writer_loyalty_profile
    read_pause_deploy_config: True
    tags: ["Loyalty"]
    job_size: extra_small
    dataproc_cluster_name: sync-loyalty-profile
  bigquery:
    project_id: pcb-{env}-processing
    dataset_id: domain_customer_management
    table_id: loyalty_profile_remaining_segment_{current_date}
    query_file: loyalty_processing/par/loyalty_profile_remaining_segment.sql
  gcs:
    bucket: pcb-{env}-staging-extract
    folder_name: sync-loyalty-profile
    file_name: loyalty-profile-remaining-segment