mobile_token_initial_segment_part_1_kafka_writer:
  default_args:
    owner: "team-convergence-alerts"
    capability: "Loyalty"
    severity: "P3"
    sub_capability: "Rewards/Loyalty"
    business_impact: "New mobile tokens will not be onboarded in Eagle Eye and customer will miss the earning points for mobile wallet."
    customer_impact: "If Customers wallet was part of the batch authlog file that failed, Customer will miss earning PC points and offers when using there apple/google wallet."
  file_uris:
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/mobile_token/application.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/mobile_token/schema_mapping.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/mobile_token/mobile_token_key.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/mobile_token/mobile_token_value.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/loyalty/mobile_token/mobile_token_file_schema.avsc
  application_config: application.yaml
  args:
    pcb.file.kafka.connector.avro.key.schema.path: mobile_token_key.avsc
    pcb.file.kafka.connector.avro.value.schema.path: mobile_token_value.avsc
    pcb.file.kafka.connector.file.kafka.schema.mapping.path: schema_mapping.yaml
    pcb.file.kafka.connector.file.type: PARQUET
    pcb.file.kafka.connector.file.path:
      file_source_bigquery: true
    pcb.file.kafka.connector.kafka.key: customerUid
    pcb.file.kafka.connector.kafka.key.part.of.dataset: true
    pcb.file.kafka.connector.schema.file.path: mobile_token_file_schema.avsc
  dag:
    kafka_writer_task: kafka_writer_mobile_token_initial_segment_part_1
    read_pause_deploy_config: True
    tags: ["Loyalty"]
    job_size: extra_small
    dataproc_cluster_name: mobile-token
  bigquery:
    query_file: loyalty_processing/mobile_token/initial_segment_part_1.sql
  gcs:
    bucket: pcb-{env}-staging-extract
    folder_name: mobile-token
    file_name: mobile-token-initial-segment-part-1