rl3_statement_with_parameters_kafka_writer:
  default_args:
    owner: "team-digital-adoption-alerts"
    capability: "account-management"
    sub_capability: "data-movement"
    business_impact: "This dag loads RL3 events into a kafka topic: dp-core-statement-ready-inbound."
    customer_impact: "In the event of a failure, new RL3 statements will not be available for customers."
    severity: "P3"
    params: {
      "sbmt_ref_id": ,
      "ids":
    }
  file_uris:
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/digital-adoption/rl3_statement/application.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/digital-adoption/rl3_statement/schema_mapping.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/digital-adoption/rl3_statement/rl3_statement_key.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/digital-adoption/rl3_statement/rl3_statement_value.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/digital-adoption/rl3_statement/rl3_statement_file_schema.avsc
  application_config: application.yaml
  args:
    pcb.file.kafka.connector.avro.key.schema.path: rl3_statement_key.avsc
    pcb.file.kafka.connector.avro.value.schema.path: rl3_statement_value.avsc
    pcb.file.kafka.connector.file.kafka.schema.mapping.path: schema_mapping.yaml
    pcb.file.kafka.connector.file.type: PARQUET
    pcb.file.kafka.connector.file.path:
      file_source_bigquery: true
    pcb.file.kafka.connector.kafka.key: statementId
    pcb.file.kafka.connector.kafka.key.part.of.dataset: true
    pcb.file.kafka.connector.schema.file.path: rl3_statement_file_schema.avsc
  dag:
    kafka_writer_task: kafka_writer_rl3_statement
    read_pause_deploy_config: false
    tags: [ "team-digital-adoption-alerts" , "P3" ]
    job_size: extra_small
    dataproc_cluster_name: rl3-statement-with-parameters
    skip_kafka_writer_if_empty: true
  bigquery:
    project_id: pcb-{env}-processing
    dataset_id: domain_tax_slips
    table_id: rl3_statement_{current_date}
    query_file: digital_adoption_tax_statements/sql/rl3_statement_with_parameters_kafka.sql
    replacements:
      "{sbmt_ref_id}": "{{ dag_run.conf.get('sbmt_ref_id') }}"
      "{ids}": "{{ dag_run.conf.get('ids') }}"
  gcs:
    bucket: pcb-{env}-staging-extract
    folder_name: rl3_statement
    file_name: rl3_statement