tokenized_consent_bq_to_kafka:
  default_args:
    owner: "team-ogres-alerts"
    capability: "legal-compliance"
    severity: "P2"
    sub_capability: "consent"
    business_impact: 'This will impact the compliance'
    customer_impact: 'none'
  file_uris:
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/tokenized-consent/application.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/tokenized-consent/schema_mapping.yaml
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/tokenized-consent/tokenized_consent_key.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/tokenized-consent/tokenized_consent_value.avsc
    - gs://pcb-{env}-staging-artifacts/resources/file-kafka-connector/tokenized-consent/tokenized_consent_file_schema.avsc
  application_config: application.yaml
  args:
    pcb.file.kafka.connector.avro.key.schema.path: tokenized_consent_key.avsc
    pcb.file.kafka.connector.avro.value.schema.path: tokenized_consent_value.avsc
    pcb.file.kafka.connector.file.kafka.schema.mapping.path: schema_mapping.yaml
    pcb.file.kafka.connector.auto.register.schemas: true
    pcb.file.kafka.connector.file.type: PARQUET
    pcb.file.kafka.connector.file.path:
      file_source_bigquery: true
    pcb.file.kafka.connector.kafka.key: es5Token
    pcb.file.kafka.connector.kafka.key.part.of.dataset: true
    pcb.file.kafka.connector.schema.file.path: tokenized_consent_file_schema.avsc
  dag:
    kafka_writer_task: kafka_writer_tokenized_consent_task
    read_pause_deploy_config: True
    job_size: small
