-- ============================================================================
-- Index4 T0040: Insert Unnested Comparison Table (CRI v3 vs v4)
-- ============================================================================
-- Single source: OUTPUT_INDEX4_T0040_LATEST (all input + output fields in OUTPUTS).
-- Pivot OUTPUT_NAME/OUTPUT_VALUE into wide columns (same approach as all_score_trs_t0090_unnested).
-- No dependency on INPUT_INDEX4_T0040_FEATURES_LATEST; record count = OUTPUT_INDEX4_T0040_LATEST.
-- ============================================================================

INSERT INTO `pcb-{env}-landing.domain_scoring.OUTPUT_INDEX4_T0040_UNNESTED_COMPARISON`
(
  MAST_ACCOUNT_ID,
  TOB,
  NUM_DEROG_PUB_T0,
  CURR_PD,
  BC62_T0,
  AM00_TRIAD_SCORE_ALIGNED_T0,
  AM00_CASH_AVAILABLE_T0,
  AM02_AMT_FCHG_PAID_LTD_T0,
  AM02_NUM_PAYMENTS_LTD_T0,
  AF_ALL_AGE_RECENT_T0,
  RE_ALL_AGE_OLDEST_T0,
  RE_ALL_AGE_RECENT_T0,
  MG_OP_TOT_BAL_T0,
  AL_NUM_INQ_6MO_T0,
  AM_NUM_30P_DEL_12MO_T0,
  MONTHS_SINCE_LAST_INTEREST_CHARGE,
  PAYMENT_PROP_CHANGE_12M,
  PAYMENT_PROP_CHANGE_6M,
  RE_OP_TOT_UTL_VARIANCE_12M,
  RE_OP_TOT_UTL_VARIANCE_6M,
  RE_OP_TOT_UTL_A3M,
  AL_OP_TOT_BAL_Qtr,
  AM02_AMT_PAYMENTS_LTD_SL3M,
  AL_NUM_INQ_24MO_A6M,
  AL_NUM_INQ_24MO_2Qtr,
  AL_OP_TOT_BAL_2Qtr,
  AREA_RISK_CATEGORY,
  PRODUCT_HIERARCHY_RANK,
  PROP_CLEAN_LIVE,
  PROP_TXNS_RISK_CAT_1,
  PROP_SALES_RISK_CAT_1,
  TOTAL_DIST_MCCS,
  V1_MCH0_SALESSHR_CAT5_6M,
  P6_TOT_DOLLAR_COLLECT,
  P6_TXNS_CREDIT,
  CRI_V3_RISK_INDEX,
  CRI_V4_SCORE,
  CRI_V4_RISK_INDEX,
  GENERATED_RANDOM_ID,
  FINAL_INDEX_ALLOCATION,
  SCORE_RUN_COUNTER,
  REC_LOAD_TIMESTAMP,
  JOB_ID
)

WITH
  -- ==========================================================================
  -- STEP 1: Single source – OUTPUT_INDEX4_T0040_LATEST (pivot OUTPUTS to wide)
  -- ==========================================================================
  output_with_row_id AS (
    SELECT
      ROW_NUMBER() OVER () AS source_row_id,
      r.EXECUTION_ID,
      r.REC_LOAD_TIMESTAMP,
      r.JOB_ID,
      r.OUTPUTS
    FROM
      `pcb-{env}-curated.domain_scoring.OUTPUT_INDEX4_T0040_LATEST` AS r
  ),

  index4_pivoted AS (
    SELECT
      ANY_VALUE(r.REC_LOAD_TIMESTAMP) AS REC_LOAD_TIMESTAMP,
      ANY_VALUE(r.JOB_ID) AS JOB_ID,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'MAST_ACCOUNT_ID' THEN o.OUTPUT_VALUE END) AS MAST_ACCOUNT_ID,
      -- PMML input features (35 fields) + CRI_V4 from OUTPUTS
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'TOB' THEN o.OUTPUT_VALUE END) AS TOB,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'NUM_DEROG_PUB_T0' THEN o.OUTPUT_VALUE END) AS NUM_DEROG_PUB_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'CURR_PD' THEN o.OUTPUT_VALUE END) AS CURR_PD,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'BC62_T0' THEN o.OUTPUT_VALUE END) AS BC62_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AM00_TRIAD_SCORE_ALIGNED_T0' THEN o.OUTPUT_VALUE END) AS AM00_TRIAD_SCORE_ALIGNED_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AM00_CASH_AVAILABLE_T0' THEN o.OUTPUT_VALUE END) AS AM00_CASH_AVAILABLE_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AM02_AMT_FCHG_PAID_LTD_T0' THEN o.OUTPUT_VALUE END) AS AM02_AMT_FCHG_PAID_LTD_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AM02_NUM_PAYMENTS_LTD_T0' THEN o.OUTPUT_VALUE END) AS AM02_NUM_PAYMENTS_LTD_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AF_ALL_AGE_RECENT_T0' THEN o.OUTPUT_VALUE END) AS AF_ALL_AGE_RECENT_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'RE_ALL_AGE_OLDEST_T0' THEN o.OUTPUT_VALUE END) AS RE_ALL_AGE_OLDEST_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'RE_ALL_AGE_RECENT_T0' THEN o.OUTPUT_VALUE END) AS RE_ALL_AGE_RECENT_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'MG_OP_TOT_BAL_T0' THEN o.OUTPUT_VALUE END) AS MG_OP_TOT_BAL_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AL_NUM_INQ_6MO_T0' THEN o.OUTPUT_VALUE END) AS AL_NUM_INQ_6MO_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AM_NUM_30P_DEL_12MO_T0' THEN o.OUTPUT_VALUE END) AS AM_NUM_30P_DEL_12MO_T0,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'MONTHS_SINCE_LAST_INTEREST_CHARGE' THEN o.OUTPUT_VALUE END) AS MONTHS_SINCE_LAST_INTEREST_CHARGE,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'PAYMENT_PROP_CHANGE_12M' THEN o.OUTPUT_VALUE END) AS PAYMENT_PROP_CHANGE_12M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'PAYMENT_PROP_CHANGE_6M' THEN o.OUTPUT_VALUE END) AS PAYMENT_PROP_CHANGE_6M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'RE_OP_TOT_UTL_VARIANCE_12M' THEN o.OUTPUT_VALUE END) AS RE_OP_TOT_UTL_VARIANCE_12M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'RE_OP_TOT_UTL_VARIANCE_6M' THEN o.OUTPUT_VALUE END) AS RE_OP_TOT_UTL_VARIANCE_6M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'RE_OP_TOT_UTL_A3M' THEN o.OUTPUT_VALUE END) AS RE_OP_TOT_UTL_A3M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AL_OP_TOT_BAL_Qtr' THEN o.OUTPUT_VALUE END) AS AL_OP_TOT_BAL_Qtr,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AM02_AMT_PAYMENTS_LTD_SL3M' THEN o.OUTPUT_VALUE END) AS AM02_AMT_PAYMENTS_LTD_SL3M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AL_NUM_INQ_24MO_A6M' THEN o.OUTPUT_VALUE END) AS AL_NUM_INQ_24MO_A6M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AL_NUM_INQ_24MO_2Qtr' THEN o.OUTPUT_VALUE END) AS AL_NUM_INQ_24MO_2Qtr,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AL_OP_TOT_BAL_2Qtr' THEN o.OUTPUT_VALUE END) AS AL_OP_TOT_BAL_2Qtr,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'AREA_RISK_CATEGORY' THEN o.OUTPUT_VALUE END) AS AREA_RISK_CATEGORY,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'PRODUCT_HIERARCHY_RANK' THEN o.OUTPUT_VALUE END) AS PRODUCT_HIERARCHY_RANK,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'PROP_CLEAN_LIVE' THEN o.OUTPUT_VALUE END) AS PROP_CLEAN_LIVE,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'PROP_TXNS_RISK_CAT_1' THEN o.OUTPUT_VALUE END) AS PROP_TXNS_RISK_CAT_1,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'PROP_SALES_RISK_CAT_1' THEN o.OUTPUT_VALUE END) AS PROP_SALES_RISK_CAT_1,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'TOTAL_DIST_MCCS' THEN o.OUTPUT_VALUE END) AS TOTAL_DIST_MCCS,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'V1_MCH0_SALESSHR_CAT5_6M' THEN o.OUTPUT_VALUE END) AS V1_MCH0_SALESSHR_CAT5_6M,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'P6_TOT_DOLLAR_COLLECT' THEN o.OUTPUT_VALUE END) AS P6_TOT_DOLLAR_COLLECT,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'P6_TXNS_CREDIT' THEN o.OUTPUT_VALUE END) AS P6_TXNS_CREDIT,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'CRI_V4' THEN o.OUTPUT_VALUE END) AS CRI_V4_SCORE,
      MAX(CASE WHEN UPPER(o.OUTPUT_NAME) = 'SCORE_RUN_COUNTER' THEN o.OUTPUT_VALUE END) AS SCORE_RUN_COUNTER
    FROM output_with_row_id r
    CROSS JOIN UNNEST(r.OUTPUTS) AS o
    GROUP BY r.source_row_id
  ),

  -- ==========================================================================
  -- STEP 2: Calculate CRI_V4_RISK_INDEX from CRI_V4_SCORE (15 risk bands)
  -- ==========================================================================
  v4_with_index AS (
    SELECT DISTINCT
      MAST_ACCOUNT_ID,
      REC_LOAD_TIMESTAMP,
      JOB_ID,
      TOB,
      NUM_DEROG_PUB_T0,
      CURR_PD,
      BC62_T0,
      AM00_TRIAD_SCORE_ALIGNED_T0,
      AM00_CASH_AVAILABLE_T0,
      AM02_AMT_FCHG_PAID_LTD_T0,
      AM02_NUM_PAYMENTS_LTD_T0,
      AF_ALL_AGE_RECENT_T0,
      RE_ALL_AGE_OLDEST_T0,
      RE_ALL_AGE_RECENT_T0,
      MG_OP_TOT_BAL_T0,
      AL_NUM_INQ_6MO_T0,
      AM_NUM_30P_DEL_12MO_T0,
      MONTHS_SINCE_LAST_INTEREST_CHARGE,
      PAYMENT_PROP_CHANGE_12M,
      PAYMENT_PROP_CHANGE_6M,
      RE_OP_TOT_UTL_VARIANCE_12M,
      RE_OP_TOT_UTL_VARIANCE_6M,
      RE_OP_TOT_UTL_A3M,
      AL_OP_TOT_BAL_Qtr,
      AM02_AMT_PAYMENTS_LTD_SL3M,
      AL_NUM_INQ_24MO_A6M,
      AL_NUM_INQ_24MO_2Qtr,
      AL_OP_TOT_BAL_2Qtr,
      AREA_RISK_CATEGORY,
      PRODUCT_HIERARCHY_RANK,
      PROP_CLEAN_LIVE,
      PROP_TXNS_RISK_CAT_1,
      PROP_SALES_RISK_CAT_1,
      TOTAL_DIST_MCCS,
      V1_MCH0_SALESSHR_CAT5_6M,
      P6_TOT_DOLLAR_COLLECT,
      P6_TXNS_CREDIT,
      CRI_V4_SCORE,
      SCORE_RUN_COUNTER,
      CASE
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 0 AND 490 THEN '15'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 491 AND 545 THEN '14'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 546 AND 565 THEN '13'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 566 AND 590 THEN '12'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 591 AND 605 THEN '11'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 606 AND 615 THEN '10'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 616 AND 630 THEN '9'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 631 AND 640 THEN '8'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 641 AND 655 THEN '7'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 656 AND 665 THEN '6'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 666 AND 675 THEN '5'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 676 AND 685 THEN '4'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 686 AND 695 THEN '3'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 696 AND 720 THEN '2'
        WHEN SAFE_CAST(CRI_V4_SCORE AS FLOAT64) BETWEEN 721 AND 999 THEN '1'
        ELSE NULL
      END AS CRI_V4_RISK_INDEX
    FROM index4_pivoted
  ),

  -- ==========================================================================
  -- STEP 3: Get CRI_v3 scores from CREDSCORE_T0030 (legacy scoring)
  -- ==========================================================================
  cri_v3_raw AS (
    SELECT DISTINCT
      TRIM(ACCOUNT_NUMBER) AS ACCOUNT_NUMBER,
      SCORE_RAW AS CRI_v3
    FROM (
      SELECT DISTINCT
        ACCOUNT_NUMBER,
        SCORE_RAW,
        ROW_NUMBER() OVER (
          PARTITION BY ACCOUNT_NUMBER
          ORDER BY FILE_CREATE_DT DESC, REC_LOAD_TIMESTAMP DESC
        ) AS RN
      FROM `pcb-{env}-curated.domain_scoring.CREDSCORE_T0030`
      WHERE FILE_CREATE_DT <= (SELECT MAX(FILE_CREATE_DT) FROM `pcb-{env}-curated.domain_scoring.CREDSCORE_T0030`)
    )
    WHERE RN = 1
  ),

  -- ==========================================================================
  -- STEP 4: Map CRI_v3 ACCOUNT_NUMBER to MAST_ACCOUNT_ID via PCMC_DATA_DEPOT
  -- ==========================================================================
  cri_v3_mapped AS (
    SELECT DISTINCT
      dd.MAST_ACCOUNT_ID,
      v3.CRI_v3 AS CRI_V3_RISK_INDEX
    FROM cri_v3_raw v3
    INNER JOIN `pcb-{env}-curated.domain_scoring.SCORING_PREP_PCMC_DATA_DEPOT_LATEST` dd
      ON v3.ACCOUNT_NUMBER = dd.ACCOUNT_NUMBER
  ),

  -- ==========================================================================
  -- STEP 5: Get GENERATED_RANDOM_ID for A/B testing allocation (0-5999)
  -- ==========================================================================
  random_ids AS (
    SELECT DISTINCT
      MAST_ACCOUNT_ID,
      GENERATED_RANDOM_ID
    FROM `pcb-{env}-curated.domain_scoring.SCORING_PREP_ACCOUNT_IDS_RANDOMIZED_LATEST`
  ),

  -- ==========================================================================
  -- STEP 6: Join v4 data with CRI v3 and random_id (LEFT JOIN to keep all rows)
  -- ==========================================================================
  final_data AS (
    SELECT DISTINCT
      v4.MAST_ACCOUNT_ID,
      v4.REC_LOAD_TIMESTAMP,
      v4.TOB,
      v4.NUM_DEROG_PUB_T0,
      v4.CURR_PD,
      v4.BC62_T0,
      v4.AM00_TRIAD_SCORE_ALIGNED_T0,
      v4.AM00_CASH_AVAILABLE_T0,
      v4.AM02_AMT_FCHG_PAID_LTD_T0,
      v4.AM02_NUM_PAYMENTS_LTD_T0,
      v4.AF_ALL_AGE_RECENT_T0,
      v4.RE_ALL_AGE_OLDEST_T0,
      v4.RE_ALL_AGE_RECENT_T0,
      v4.MG_OP_TOT_BAL_T0,
      v4.AL_NUM_INQ_6MO_T0,
      v4.AM_NUM_30P_DEL_12MO_T0,
      v4.MONTHS_SINCE_LAST_INTEREST_CHARGE,
      v4.PAYMENT_PROP_CHANGE_12M,
      v4.PAYMENT_PROP_CHANGE_6M,
      v4.RE_OP_TOT_UTL_VARIANCE_12M,
      v4.RE_OP_TOT_UTL_VARIANCE_6M,
      v4.RE_OP_TOT_UTL_A3M,
      v4.AL_OP_TOT_BAL_Qtr,
      v4.AM02_AMT_PAYMENTS_LTD_SL3M,
      v4.AL_NUM_INQ_24MO_A6M,
      v4.AL_NUM_INQ_24MO_2Qtr,
      v4.AL_OP_TOT_BAL_2Qtr,
      v4.AREA_RISK_CATEGORY,
      v4.PRODUCT_HIERARCHY_RANK,
      v4.PROP_CLEAN_LIVE,
      v4.PROP_TXNS_RISK_CAT_1,
      v4.PROP_SALES_RISK_CAT_1,
      v4.TOTAL_DIST_MCCS,
      v4.V1_MCH0_SALESSHR_CAT5_6M,
      v4.P6_TOT_DOLLAR_COLLECT,
      v4.P6_TXNS_CREDIT,
      SAFE_CAST(v3.CRI_V3_RISK_INDEX AS STRING) AS CRI_V3_RISK_INDEX,
      v4.CRI_V4_SCORE,
      v4.SCORE_RUN_COUNTER,
      v4.CRI_V4_RISK_INDEX,
      rand.GENERATED_RANDOM_ID,
      CASE
        WHEN SAFE_CAST(rand.GENERATED_RANDOM_ID AS INT64) <= 999 THEN v4.CRI_V4_RISK_INDEX
        ELSE SAFE_CAST(v3.CRI_V3_RISK_INDEX AS STRING)
      END AS FINAL_INDEX_ALLOCATION
    FROM v4_with_index v4
    LEFT JOIN cri_v3_mapped v3 ON v4.MAST_ACCOUNT_ID = v3.MAST_ACCOUNT_ID
    LEFT JOIN random_ids rand ON v4.MAST_ACCOUNT_ID = rand.MAST_ACCOUNT_ID
  )

-- ==========================================================================
-- Final SELECT: Insert into target table with audit fields
-- ==========================================================================
SELECT DISTINCT
  MAST_ACCOUNT_ID,
  TOB,
  NUM_DEROG_PUB_T0,
  CURR_PD,
  BC62_T0,
  AM00_TRIAD_SCORE_ALIGNED_T0,
  AM00_CASH_AVAILABLE_T0,
  AM02_AMT_FCHG_PAID_LTD_T0,
  AM02_NUM_PAYMENTS_LTD_T0,
  AF_ALL_AGE_RECENT_T0,
  RE_ALL_AGE_OLDEST_T0,
  RE_ALL_AGE_RECENT_T0,
  MG_OP_TOT_BAL_T0,
  AL_NUM_INQ_6MO_T0,
  AM_NUM_30P_DEL_12MO_T0,
  MONTHS_SINCE_LAST_INTEREST_CHARGE,
  PAYMENT_PROP_CHANGE_12M,
  PAYMENT_PROP_CHANGE_6M,
  RE_OP_TOT_UTL_VARIANCE_12M,
  RE_OP_TOT_UTL_VARIANCE_6M,
  RE_OP_TOT_UTL_A3M,
  AL_OP_TOT_BAL_Qtr,
  AM02_AMT_PAYMENTS_LTD_SL3M,
  AL_NUM_INQ_24MO_A6M,
  AL_NUM_INQ_24MO_2Qtr,
  AL_OP_TOT_BAL_2Qtr,
  AREA_RISK_CATEGORY,
  PRODUCT_HIERARCHY_RANK,
  PROP_CLEAN_LIVE,
  PROP_TXNS_RISK_CAT_1,
  PROP_SALES_RISK_CAT_1,
  TOTAL_DIST_MCCS,
  V1_MCH0_SALESSHR_CAT5_6M,
  P6_TOT_DOLLAR_COLLECT,
  P6_TXNS_CREDIT,
  CRI_V3_RISK_INDEX,
  CAST(CAST(CAST(CRI_V4_SCORE AS FLOAT64) AS INT64) AS STRING) AS CRI_V4_SCORE,
  CRI_V4_RISK_INDEX,
  GENERATED_RANDOM_ID,
  FINAL_INDEX_ALLOCATION,
  SCORE_RUN_COUNTER,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM final_data;
