-- PDSB-6819-N125K
UPDATE `pcb-{env}-landing.domain_loyalty.PC_TARGETED_OFFER`
SET offerTriggers =
[                                                                           -- offerTriggers
    STRUCT
    <
      offerTriggerId INT64,
      triggerDescription STRING,
      offerTriggerType STRING,
      triggerType STRING,
      categoryCode STRING,
      noFpPts BOOL,
      merchantGroups STRING,
      fulfillmentPeriodDays INT64,
      minAmount STRING,
      pointsAwarded INT64,
      percentRewarded STRING,
      targetTransactionCount INT64,
      targetTotalAmount STRING,
      maxTotalAmount STRING,
      maxTransactionCount INT64,
      numberOfPeriods INT64,
      campaignId INT64,
      createTimestamp TIMESTAMP,
      createUserId STRING,
      updateTimestamp TIMESTAMP,
      updateUserId STRING,
      eventType STRING
    >
    (
      39,
      'PDSB-6819',
      'FTP',
      'IWE_SP3M',
      'IWE_SP3M',
      FALSE,
      NULL,
      NULL,
      NULL,
      80000,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '2025-06-11 15:50:41.001615+00',
      'sysUser',
      NULL,
      NULL,
      'ADD'
    ),
    STRUCT
    <
      offerTriggerId INT64,
      triggerDescription STRING,
      offerTriggerType STRING,
      triggerType STRING,
      categoryCode STRING,
      noFpPts BOOL,
      merchantGroups STRING,
      fulfillmentPeriodDays INT64,
      minAmount STRING,
      pointsAwarded INT64,
      percentRewarded STRING,
      targetTransactionCount INT64,
      targetTotalAmount STRING,
      maxTotalAmount STRING,
      maxTransactionCount INT64,
      numberOfPeriods INT64,
      campaignId INT64,
      createTimestamp TIMESTAMP,
      createUserId STRING,
      updateTimestamp TIMESTAMP,
      updateUserId STRING,
      eventType STRING
    >
    (
      40,
      'PDSB-6819',
      'FTP',
      'IWE_SPAF3M',
      'IWE_SPAF3M',
      TRUE,
      NULL,
      NULL,
      NULL,
      45000,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '2025-06-11 15:50:41.001615+00',
      'sysUser',
      NULL,
      NULL,
      'ADD'
    )
  ]
WHERE offerCode = 'PDSB-6819-N125K';

-- PDSB-6483-N150K
UPDATE `pcb-{env}-landing.domain_loyalty.PC_TARGETED_OFFER`
SET offerTriggers =
[                                                                           -- offerTriggers
    STRUCT
    <
      offerTriggerId INT64,
      triggerDescription STRING,
      offerTriggerType STRING,
      triggerType STRING,
      categoryCode STRING,
      noFpPts BOOL,
      merchantGroups STRING,
      fulfillmentPeriodDays INT64,
      minAmount STRING,
      pointsAwarded INT64,
      percentRewarded STRING,
      targetTransactionCount INT64,
      targetTotalAmount STRING,
      maxTotalAmount STRING,
      maxTransactionCount INT64,
      numberOfPeriods INT64,
      campaignId INT64,
      createTimestamp TIMESTAMP,
      createUserId STRING,
      updateTimestamp TIMESTAMP,
      updateUserId STRING,
      eventType STRING
    >
    (
      43,
      'PDSB-6483',
      'FTP',
      'IWE_SP3M',
      'IWE_SP3M',
      FALSE,
      NULL,
      NULL,
      NULL,
      75000,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '2025-06-11 15:50:41.001615+00',
      'sysUser',
      NULL,
      NULL,
      'ADD'
    ),
    STRUCT
    <
      offerTriggerId INT64,
      triggerDescription STRING,
      offerTriggerType STRING,
      triggerType STRING,
      categoryCode STRING,
      noFpPts BOOL,
      merchantGroups STRING,
      fulfillmentPeriodDays INT64,
      minAmount STRING,
      pointsAwarded INT64,
      percentRewarded STRING,
      targetTransactionCount INT64,
      targetTotalAmount STRING,
      maxTotalAmount STRING,
      maxTransactionCount INT64,
      numberOfPeriods INT64,
      campaignId INT64,
      createTimestamp TIMESTAMP,
      createUserId STRING,
      updateTimestamp TIMESTAMP,
      updateUserId STRING,
      eventType STRING
    >
    (
      44,
      'PDSB-6483',
      'FTP',
      'IWE_SPAF3M',
      'IWE_SPAF3M',
      TRUE,
      NULL,
      NULL,
      NULL,
      60000,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '2025-06-11 15:50:41.001615+00',
      'sysUser',
      NULL,
      NULL,
      'ADD'
    ),
    STRUCT
    <
      offerTriggerId INT64,
      triggerDescription STRING,
      offerTriggerType STRING,
      triggerType STRING,
      categoryCode STRING,
      noFpPts BOOL,
      merchantGroups STRING,
      fulfillmentPeriodDays INT64,
      minAmount STRING,
      pointsAwarded INT64,
      percentRewarded STRING,
      targetTransactionCount INT64,
      targetTotalAmount STRING,
      maxTotalAmount STRING,
      maxTransactionCount INT64,
      numberOfPeriods INT64,
      campaignId INT64,
      createTimestamp TIMESTAMP,
      createUserId STRING,
      updateTimestamp TIMESTAMP,
      updateUserId STRING,
      eventType STRING
    >
    (
      45,
      'PDSB-6483',
      'FTP',
      'IWE_MW2M',
      'IWE_MW2M',
      TRUE,
      NULL,
      NULL,
      NULL,
      15000,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '2025-06-11 15:50:41.001615+00',
      'sysUser',
      NULL,
      NULL,
      'ADD'
    )
  ]
WHERE offerCode = 'PDSB-6483-N150K';

-- PDSB-6485-N100K
UPDATE `pcb-{env}-landing.domain_loyalty.PC_TARGETED_OFFER`
SET offerTriggers =
[                                                                           -- offerTriggers
    STRUCT
    <
      offerTriggerId INT64,
      triggerDescription STRING,
      offerTriggerType STRING,
      triggerType STRING,
      categoryCode STRING,
      noFpPts BOOL,
      merchantGroups STRING,
      fulfillmentPeriodDays INT64,
      minAmount STRING,
      pointsAwarded INT64,
      percentRewarded STRING,
      targetTransactionCount INT64,
      targetTotalAmount STRING,
      maxTotalAmount STRING,
      maxTransactionCount INT64,
      numberOfPeriods INT64,
      campaignId INT64,
      createTimestamp TIMESTAMP,
      createUserId STRING,
      updateTimestamp TIMESTAMP,
      updateUserId STRING,
      eventType STRING
    >
    (
      20,
      'PDSB-6485',
      'FTP',
      'IWE_SP3M',
      'IWE_SP3M',
      TRUE,
      NULL,
      NULL,
      NULL,
      70000,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '2025-05-26 18:51:17.133389+00',
      'sysUser',
      NULL,
      NULL,
      'ADD'
    ),
    STRUCT
    <
      offerTriggerId INT64,
      triggerDescription STRING,
      offerTriggerType STRING,
      triggerType STRING,
      categoryCode STRING,
      noFpPts BOOL,
      merchantGroups STRING,
      fulfillmentPeriodDays INT64,
      minAmount STRING,
      pointsAwarded INT64,
      percentRewarded STRING,
      targetTransactionCount INT64,
      targetTotalAmount STRING,
      maxTotalAmount STRING,
      maxTransactionCount INT64,
      numberOfPeriods INT64,
      campaignId INT64,
      createTimestamp TIMESTAMP,
      createUserId STRING,
      updateTimestamp TIMESTAMP,
      updateUserId STRING,
      eventType STRING
    >
    (
      21,
      'PDSB-6485',
      'FTP',
      'IWE_SPAF3M',
      'IWE_SPAF3M',
      TRUE,
      NULL,
      NULL,
      NULL,
      30000,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      NULL,
      '2025-05-26 18:51:17.133389+00',
      'sysUser',
      NULL,
      NULL,
      'ADD'
    )
  ]
WHERE offerCode = 'PDSB-6485-N100K';