INSERT INTO
  `pcb-{env}-curated.cots_cdic.PCMA_CDIC_0130`
WITH
  pcma_cdic_0500_latest_load AS (
  SELECT
    MAX(pcma_cdic_0500.REC_LOAD_TIMESTAMP) AS LATEST_REC_LOAD_TIMESTAMP
  FROM
    `pcb-{env}-curated.cots_cdic.PCMA_CDIC_0500` AS pcma_cdic_0500 ),
  unique_accounts AS (
  SELECT
    pcma_cdic_0500.ACCOUNT_UNIQUE_ID,
    COUNTIF(pcma_cdic_0500.PRIMARY_ACCOUNT_HOLDER_FLAG = 'N') AS JOINT_ACC
  FROM
    `pcb-{env}-curated.cots_cdic.PCMA_CDIC_0500` AS pcma_cdic_0500
  INNER JOIN
    pcma_cdic_0500_latest_load AS pcma_cdic_0500_ll
  ON
    pcma_cdic_0500.REC_LOAD_TIMESTAMP = pcma_cdic_0500_ll.LATEST_REC_LOAD_TIMESTAMP
  GROUP BY
    pcma_cdic_0500.ACCOUNT_UNIQUE_ID ),
  hold_status_code AS (
  SELECT
    ua.ACCOUNT_UNIQUE_ID,
    CASE
      WHEN pcma_cdic_0700.ACCOUNT_UNIQUE_ID IS NULL THEN 1
      WHEN pcma_cdic_0700.ACCOUNT_UNIQUE_ID IS NOT NULL THEN
    CASE
      WHEN CAST(pcma_cdic_0700.HOLD_AMOUNT AS FLOAT64) > 0 THEN 3
      WHEN CAST(pcma_cdic_0700.HOLD_AMOUNT AS FLOAT64) = 0 THEN 1
      WHEN CAST(pcma_cdic_0700.HOLD_AMOUNT AS FLOAT64) = -1 THEN 1
      WHEN CAST(pcma_cdic_0700.HOLD_AMOUNT AS FLOAT64) = -2 THEN 2
  END
  END AS CDIC_HOLD_STATUS_CODE
  FROM
    unique_accounts AS ua
  LEFT JOIN
    `pcb-{env}-curated.cots_cdic.PCMA_CDIC_0700` AS pcma_cdic_0700
  ON
    ua.ACCOUNT_UNIQUE_ID = pcma_cdic_0700.ACCOUNT_UNIQUE_ID ),
  pcma_cdic_0130 AS (
  SELECT
    ua.ACCOUNT_UNIQUE_ID,
    ac.MAST_ACCOUNT_ID,
    ac.ACCOUNT_UID,
    ac.PRODUCT_UID,
    CASE LOWER(prd.TYPE)
      WHEN 'individual' THEN '7'
      WHEN 'joint' THEN '9'
      WHEN 'goal' THEN '8'
      WHEN 'additional' THEN '10'
  END
    AS ACCOUNT_TYPE_CODE,
    CASE ua.JOINT_ACC
      WHEN 0 THEN 2
      ELSE 3
  END
    AS INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE,
    CASE
      WHEN am02.AM02_BALANCE_CURRENT IS NULL THEN 0.0
      ELSE am02.AM02_BALANCE_CURRENT * -1
  END
    AS AM02_BALANCE_CURRENT,
    CASE
      WHEN am02.AM02_BALANCE_CURRENT IS NULL THEN 0.0
      ELSE (am02.AM02_BALANCE_CURRENT * -1) - am00.AM00_AMT_AUTHORIZATIONS_OUT + am00.AM00_AUTH_PAYMENT_AMT + AM00_LIMIT_CREDIT
  END
    AS ACCESSIBLE_BALANCE,
    CASE
      WHEN (am00.AM00_BANKRUPTCY_TYPE IS NULL OR am00.AM00_BANKRUPTCY_TYPE = 0) AND (am00.AM00_STATC_CLOSED IS NULL OR am00.AM00_STATC_CLOSED = '') AND (am00.AM00_STATC_CHARGEOFF IS NULL OR am00.AM00_STATC_CHARGEOFF = '') AND (am00.AM00_BLOCKED_CARDS_CNT IS NULL OR am00.AM00_BLOCKED_CARDS_CNT = 0) AND (am00.AM00_STATC_SECURITY_FRAUD IS NULL OR am00.AM00_STATC_SECURITY_FRAUD = '') AND (am00.AM00_STATF_CHGOFF_LAG IS NULL OR am00.AM00_STATF_CHGOFF_LAG = '') THEN '11'
      ELSE CASE
      WHEN (am00.AM00_STATF_INACTIVE IS NULL OR TRIM(am00.AM00_STATF_INACTIVE) = '') THEN '12'
      ELSE '13'
  END
  END AS ACCOUNT_STATUS_CODE,
    CASE ua.JOINT_ACC
      WHEN 0 THEN 'N'
      ELSE 'Y'
  END
    AS JOINT_ACCOUNT_FLAG,
    CDIC_HOLD_STATUS_CODE
  FROM
    unique_accounts AS ua
  INNER JOIN
    `pcb-{env}-curated.domain_account_management.ACCOUNT` AS ac
  ON
    CAST(ua.ACCOUNT_UNIQUE_ID AS INT) = CAST(ac.MAST_ACCOUNT_ID AS INT)
  INNER JOIN
    `pcb-{env}-curated.domain_account_management.PRODUCT` AS prd
  ON
    ac.PRODUCT_UID = prd.PRODUCT_UID
    AND LOWER(prd.TYPE) IN ('individual',
      'joint',
      'goal',
      'additional')
  INNER JOIN
    hold_status_code AS hsd
  ON
    ua.ACCOUNT_UNIQUE_ID = hsd.Account_Unique_ID
  LEFT JOIN
    `pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM02_REC` AS am02
  ON
    CAST(ua.ACCOUNT_UNIQUE_ID AS INT) = CAST(am02.MAST_ACCOUNT_ID AS INT)
    AND am02.AM00_APPLICATION_SUFFIX = 0
  LEFT JOIN
    `pcb-{env}-curated.domain_account_management.TSYS_PCB_MC_ACCTMASTER_DAILY_AM00_REC` AS am00
  ON
    CAST(ua.ACCOUNT_UNIQUE_ID AS INT) = CAST(am00.MAST_ACCOUNT_ID AS INT)
    AND am00.MAST_ACCOUNT_SUFFIX = 0 ),
  pcma_cdic_0233_latest_load AS (
  SELECT
    MAX(pcma_cdic_0233.REC_LOAD_TIMESTAMP) AS LATEST_REC_LOAD_TIMESTAMP
  FROM
    `pcb-{env}-curated.cots_cdic.PCMA_CDIC_0233` AS pcma_cdic_0233 )
SELECT
  t_0130.ACCOUNT_UNIQUE_ID,
  t_0130.ACCOUNT_UNIQUE_ID AS ACCOUNT_NUMBER,
  '1' AS ACCOUNT_BRANCH,
  CAST(t_0130.PRODUCT_UID AS STRING) AS PRODUCT_CODE,
  '1' AS REGISTERED_PLAN_TYPE_CODE,
  '' AS REGISTERED_PLAN_NUMBER,
  (
  SELECT
    pcma_cdic_0233.CURRENCY_CODE
  FROM
    `pcb-{env}-curated.cots_cdic.PCMA_CDIC_0233` AS pcma_cdic_0233
  INNER JOIN
    pcma_cdic_0233_latest_load AS pcma_cdic_0233_ll
  ON
    pcma_cdic_0233.REC_LOAD_TIMESTAMP = pcma_cdic_0233_ll.LATEST_REC_LOAD_TIMESTAMP
  WHERE
    MI_CURRENCY_CODE = 'CAD') AS CURRENCY_CODE,
  CAST(t_0130.INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE AS STRING) AS INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE,
  FORMAT('%.2f', t_0130.AM02_BALANCE_CURRENT) AS ACCOUNT_BALANCE,
  FORMAT('%.2f', t_0130.ACCESSIBLE_BALANCE) AS ACCESSIBLE_BALANCE,
  '' AS MATURITY_DATE,
  t_0130.ACCOUNT_STATUS_CODE,
  '1' AS TRUST_ACCOUNT_TYPE_CODE,
  CAST(t_0130.CDIC_HOLD_STATUS_CODE AS STRING) AS CDIC_HOLD_STATUS_CODE,
  t_0130.JOINT_ACCOUNT_FLAG,
  '1' AS CLEARING_ACCOUNT_CODE,
  t_0130.ACCOUNT_TYPE_CODE,
  '' AS MI_ISSUED_REGISTERED_ACCOUNT_FLAG,
  'N' AS MI_RELATED_DEPOSIT_FLAG,
  CURRENT_DATETIME('America/Toronto') AS REC_LOAD_TIMESTAMP,
  '{dag_id}' AS JOB_ID
FROM
  pcma_cdic_0130 AS t_0130;
